packaging/datadog-agent/source/install_agent.sh
@miketheman could use your opinion on the wording of the error message :thought_balloon: ?
=> Fix #1133. Detailed error for APT failure

checks.d/activemq_xml.py, conf.d/activemq_xml.yaml.example, tests/test_activemq_xml.py
Also add safeguards in case of crazy amount of queues/topics/subscribers
=> Refactor activemq_xml check

checks.d/network.py
[leo@datadoghq.com: Rebased to pass CI, cosmetic changes]
Few mods of #1141 to merge it for 5.2.
=> [netowrk] freebsd: '-W' in netstat for full names

checks.d/postgres.py
=> Change postgres deadlocks from gauge to rate

checks.d/teamcity.py, conf.d/teamcity.yaml.example, tests/test_teamcity.py
Rebased, improved a little more the PR to fit the current agent codebase.
Also added a test to test the logic of the check : get only newer builds after the agent start. The responses saved in mocks came from a real TeamCity server at one point though.
Supersedes #1171
=> [teamcity] new check

agent.py, checks/system/unix.py, config.py, daemon.py, dogstatsd.py, tests/test_autorestart.py
=> Fix autorestart feature (and test) and fix pid bug

conf.d/redisdb.yaml.example
Fix #1316 with some extra cleanup.
=> Clean and add options in redis.yaml.example

checks.d/snmp.py, tests/test_snmp.py
* Add Integer and Integer32 type support
* Change the SNMP get command logic to solve the 'Missing OID' issue
* Some PEP8 code cleaning
=> SNMP new types support + bug fix

checks.d/etcd.py
Use a tag to mark leader and followers instead of a gauge.
Add two captured metrics.
=> [etcd] Use a tag to mark leader/follower

aggregator.py, dogstatsd.py, tests/test_dogstatsd.py
Add service checks to the dogstatsd server. See also: https://github.com/DataDog/dogstatsd-python/pull/24
=> Dogstatsd service checks

agent.py
=> [dev] Print service checks when you run the `dd-agent check` command.

checks.d/rabbitmq.py
ref https://github.com/DataDog/dd-agent/issues/1323
=> Add consumer_utilization to RabbitMQ

checks.d/ssh_check.py, tests/test_ssh_check.py
=> Add tags to identify a proper instance in the ssh check

win32/agent.py
=> Fix autorestart option for windows agent (which broke everything else)

checks/system/win32.py
Emit warning when not able to fetch disk latency metrics.
=> [windows] Catch psutil RuntimeError (which was blocking all checks)

ddagent.py, dogstatsd.py, emitter.py, tests/test_transaction.py
Also add headers about the version of the agent and of the forwarder
Note that this test will fail until the new endpoints are created and properly configured.
=> [core] Move to versioned endpoints for the agent

checks/collector.py, checks/system/unix.py, tests/test_system.py
It was requested by a customer
* Only works on linux so far
* Also update outdated syntax of some other system checks
=> [System/Linux] Add uptime metric

dogstatsd.py
No event were sent by dogstatsd to the forwarder.
=> [dogstatsd] Fix event transmission to the forwarder

conf.d/postfix.yaml.example
=> [postfix] Add Amazon Linux to list of distros with special config

checks.d/snmp.py, conf.d/snmp.yaml.example
=> [snmp] add timeout and retries options in config

conf.d/activemq.yaml.example, conf.d/activemq_58.yaml.example, conf.d/cassandra.yaml.example, conf.d/jmx.yaml.example, conf.d/solr.yaml.example, conf.d/tomcat.yaml.example, jmxfetch.py, tests/common.py, tests/test_java_jmx.py
=> [jmx] default heap size options

checks.d/process.py, ci/etcd.rb, conf.d/process.yaml.example, tests/common.py, tests/test_etcd.py, tests/test_process.py
Supersedes #1336.
Refactoring the test suite to use the new common `AgentCheckTest` interface.
+ some improvements in that class, mainly coverage reports.
=> [process] tags per instance + test suite refactoring

daemon.py
And thus add the ability to be restarted properly after a SIGKILL (since
the pid in the pidfile is now tested)
=> [core] Fix pidfile bug for 5.2.2

win32/agent.py
- check memory consumption of all processes
- check whether the agent is blocked on a check or not
=> [windows] add a basic "Watchdog"

checks.d/jenkins.py
Starting from v1.597, the build folder names are not named with a timestamp anymore but with an ID. We have to get the timestamp from the `build.xml` file and to use the folder name to guess the build number.
=> [Jenkins] supporting the new folder naming convention

agent.py, config.py, ddagent.py, jmxfetch.py, packaging/datadog-agent/source/supervisord.conf, packaging/supervisor.conf, supervisord.dev.conf, tests/test_cassandra_jmx.py, tests/test_java_jmx.py, tests/test_solr.py, tests/test_tomcat.py, win32/agent.py
=> [jmx][supervisor] JMXFetch standalone

checks.d/jenkins.py
=> Fix timestamp comparison error.

ci/fluentd.rb
ci/fluentd.rb invokes a fluentd process, but doesn't kill it at cleanup time. This change fixes it.
=> Kill a fluentd process at test cleanup time.

agent.py
=> [jmx] removes legacy code

packaging/centos/datadog-agent.init, packaging/debian/datadog-agent.init
=> [jmx][core] jmx may not run at agent start

tests/test_flare.py, utils/flare.py
And some pep8 cleaning.
Also setting TIMEOUT to 60s (in case of huge files).
=> [flare] fix test_endpoints (wrong error msg)

checks.d/process.py, tests/test_process.py
=> [process] clean check & test

ddagent.py, tests/test_transaction.py
Hander service check endpoint in the Forwarder.
=> [core] handle /check_run in the forwarder

tests/test_supervisord.py
I changed the error message in #1512 but didn’t change the test
accordingly.
This fixes that issue.
=> [Supervisord] Fix expected error message

checks.d/process.py
Use `_is_affirmative` util.
See commit 0e862f5f7f16f5fc1466f4b8ebff1b4e44cac64e
@degemer assigning you this one for review, feel free to merge.
=> [process] fix config booleans parsing

CHANGELOG.md
Diff: https://github.com/DataDog/dd-agent/compare/8bc0219ab6efd0a79f1cb39badb57497b50ed639...master
=> [changelog] update for 5.3

.pylintrc, Rakefile, checks.d/php_fpm.py, ci/default.rb, tests/common.py, tests/test_java_jmx.py, tests/test_lighttpd.py
See commit messages for details but overall:
1. call pylint correctly
2. fix the lint errors we didn't catch before.
=> Fix some pylint issues in the CI.

checks.d/redisdb.py, tests/test_redis.py
(wrong variable name was used).
=> [redisdb] "Variable referenced before assignment" error solved

utils/flare.py
See c7cb52d88d7f5587f0afd6f2a4d28c871f86d6aa
=> [flare] collect default checks conf files

jmxfetch.py
=> [jmx] typo

checks/check_status.py, config.py, jmxfetch.py
=> [jmx] fix bad status path and encoding issues on Windows :bug:

CHANGELOG.md, checks/check_status.py, config.py, jmxfetch.py, packaging/datadog-agent/source/supervisord.conf, packaging/supervisor.conf, supervisord.dev.conf, win32/agent.py
* [Windows] Fix JMXFetch bootloop issue when no JMX integration config is found
* [Linux][OSX] Better management of unexpected exit codes ( != 0)
* [Linux][OSX] [Windows] Limit JMXFetch attempts of restarts to 3
* [Linux][OSX][Windows] Fill a status when JMXFetch could not be launched
=> [jmxfetch] fix windows bootloop :bug:

CONTRIBUTING.md, README.md, tests/README.md
Based on dd-agent wiki. Add some more content to tests/README.md.
This is only a first version, let's see what we can do with it.
cc @technovangelist 
Fix https://github.com/DataDog/dd-agent/issues/1495
=> [doc] add a CONTRIBUTING.md :memo:

CHANGELOG.md
=> [changelog] update for 5.3.2 release

utils/flare.py
Also:
- check if files are readable before trying to add them to the
tarfile.
- remove whitespaces from input before checking for yes/no.
=> [flare] add stderr of commands

tests/core/test_transaction.py
We recently introduced an early stage validation of the api key in our intake pipeline
Using this api key will fix the test
=> [Test] Fix endpoint testing

packaging/datadog-agent/source/install_agent.sh
Before that, if the forwarder was not in a ready state at the first
try, the installation script would fail directly without trying a few
more times as we used a trap on error and set -e.
This commit clears the trap and use set +e to allow a few failures for
the status verification.
=> [Script] Fix package installation validation

packaging/datadog-agent/source/install_agent.sh
Edit of this PR (https://github.com/DataDog/dd-agent/pull/1597) from an external contributor.
The script uses long option names so that it's easy to understand. Since the script is not only used by our one line installation command, I added a "usage" description displayed when the program is called with the --help option or with a wrong option.
=> [install script] add DD_INSTALL_ONLY option

checks.d/etcd.py, tests/checks/integration/test_etcd.py
With a mock test that does not require to stand up a full etcd cluster.
=> Add etcd latency metrics

checks/check_status.py
From now on, the collector will also fetch the number of service checks
for the JMX checks from the {tmpdir}/jmx_status.yaml file.
=> [jmx-sc] Added service count to JMX status check

checks.d/http_check.py, checks.d/tcp_check.py, tests/checks/common.py, tests/checks/integration/test_http_check.py, tests/core/test_service_checks.py
And get rid of legacy ch…eck names
The old check names are currently transformed in the backend
cc: @conorbranagan
=> [HTTP/TCP Check] Add support for custom tags 

aggregator.py
=> Revert "Fix displayed metric type for Rate"

config.py, dogstatsd.py, emitter.py, tests/core/test_common.py, tests/core/test_dogstatsd.py, utils/proxy.py
Fix #1594
Also:
* simplify the proxy parsing
* Move the code in a new utils module
=> [Core] Proxy, fix the way we set the no proxy environment setting

checks.d/ntp.py, checks/check_status.py, tests/core/test_common.py, utils/ntp.py
=> [Core] Status page uses ntp settings defined in ntp check

checks/collector.py, checks/system/unix.py, config.py, jmxfetch.py, util.py, utils/subprocess_output.py
Adding more logging inside system checks to help future investigations.
Fix #1286.
=> [core] subprocess debug log messages

win32/agent.py
Drop the global count of restarts in favor of a timeframe based one.
=> [windows] record restarts on a specific timeframe

checks.d/haproxy.py
Introduced by 6aacd3f41c2dce2a6b75fb6d1a66498353f5e887
=> [haproxy] fix hostname not found error

conf.d/system_swap.yaml.example
This example file was previously missing
=> [system_swap] add example conf file

checks/collector.py
We now have a checks.d check for this.
=> [core] remove old call to windows disk check

checks.d/disk.py, tests/checks/integration/test_disk.py, tests/checks/mock/test_disk.py
And remove them for Linux, as it wasn't in the previous check.
=> [disk] fix system.disk.*_time_pct for Windows

CHANGELOG.md, config.py
=> [changelog] close 5.4.0 release

win32/agent.py
The developer mode profiler was not being enabled correctly in the Windows agent. This fixes that
=> [win32] fix developer mode configuration

conf.d/win32_event_log.yaml.example
Linked to https://github.com/DataDog/documentation/pull/442 and https://github.com/DataDog/dogweb/pull/8622
Closes https://github.com/DataDog/dd-agent/issues/1439
=> [event_viewer] Improve comments in example configuration

packaging/osx/install.sh
Add the install script before the changes, #1361 will need a rebase.
=> [packaging][osx] add install script

checks.d/postgres.py, conf.d/postgres.yaml.example
We need the ability to connect to Postgres with SSL.
This PR adds this config param via the yaml config file.
=> Add ability to connect to postgres with SSL

.travis.yml
=> [ci/travis] cache gems with bundle

checks.d/docker.py
On Kubernetes, container files are directly at the top level of cgroups,
instead of being in a directory (`docker` or `lxc`).
Fixes https://github.com/DataDog/dd-agent/issues/1748.
=> [docker] Kubernetes support (new cgroups path)

utils/flare.py
The permissions are collected in a files_permissions.log file.
All the files are added to the tar through an `_add_tar_file` method.
The generated `files_permissions.log` file looks like the following:
```
File path                                          | mode  | owner      | group
/var/log/datadog/collector.log                     | 0644  | dd-agent   | nogroup
/var/log/datadog/forwarder.log                     | 0644  | dd-agent   | nogroup
/var/log/datadog/dogstatsd.log                     | 0644  | dd-agent   | nogroup
/var/log/datadog/jmxfetch.log                      | 0644  | dd-agent   | nogroup
/var/log/datadog/supervisord.log                   | 0644  | dd-agent   | root
/etc/dd-agent/datadog.conf                         | 0644  | dd-agent   | root …
```
=> [flare] Log permissions on collected files

checks.d/process.py
=> [checks.d][process] correctly handle disappearing pids

requirements-test.txt, tox.ini
=> [flake8] disable import order checks

CONTRIBUTING.md, README.md, tests/README.md
Add Appveyor doc (appveyor.yml, how to add a flavor), and description of the
tests directory split.
=> [doc] Appveyor & tests directory split

utils/flare.py, win32/gui.py
Add a Windows flare function inside the GUI, using only popups (because it's
the easiest way to do this).
=> [windows] add flare function

datadog.conf.example
I realized today that we didn't document this. This PR is supposed to fill that gap.
[skip ci]
=> Document the dd_check tags feature and config flag

checks.d/couchbase.py
=> [couchbase] Fix service check tags

conf.d/consul.yaml.example
=> [consul] Add documentation to example yaml

tests/checks/integration/test_http_check.py, tests/checks/integration/test_tcp_check.py
Fix flaky tests and enhance content exception messages.
=> [network] fix flaky tests + better exception log

checks.d/docker.py
Docker 1.8 adds cgroup bind mount by default ( See
https://github.com/docker/docker/blob/v1.8.0/CHANGELOG.md#runtime )
Which confuses the docker check when running in a container. This is a
tiny fix to make the docker check prefers mountpoint starting with
“/host”.
Also, use "with" syntax to open files.
=> [docker] Add support for Docker 1.8

CHANGELOG.md
=> [changelog] add 5.4.5 & update 5.5.0 changes

checks.d/wmi_check.py, conf.d/wmi_check.yaml.example, tests/checks/mock/test_wmi_check.py
Collect WMI metrics from the specified namespace.
=> [wmi] `namespace` support

conf.d/mongo.yaml.example
Ref: https://app.datadoghq.com/account/settings#integrations/mongodb
=> [docs] Update mongo yaml with URI matching integration docs

conf.d/wmi_check.yaml.example
It's possible with the wmi_check to target a remote host,
it was just not documented
[skip ci]
=> [wmi] Document host statement in wmi_check.yaml

checks/system/unix.py
Rebased https://github.com/DataDog/dd-agent/pull/1656 on current master
Thanks to @rhormaza for contributing!
=> Account for %guest cpu time

CHANGELOG.md
=> [changelog] update 5.5.0

checks.d/jenkins.py, conf.d/jenkins.yaml.example
We are deprecating the Jenkins check, in favor of our new Jenkins plugin.
=> [jenkins] Deprecating Jenkins check

CHANGELOG.md
=> [changelog] 5.4.6 + 5.5.0 update

packaging/datadog-agent/source/agent
=> [source install] Fix path to sock and pid files

checks/system/unix.py
=> [darwin][iostat] Fix bad conversion

CHANGELOG.md, checks.d/jenkins.py, conf.d/jenkins.yaml.example
Postpone Jenkins AgentCheck deprecation until Datadog Jenkins plugin is considered ready.
=> [jenkins] postpone Jenkins check deprecation

CHANGELOG.md
=> [changelog] update 5.5.0 changelog

tests/checks/mock/test_sysstat.py
Fix tests associated with #1912.
=> [unix][tests] fix bad conversion in tests

checks.d/docker_daemon.py, conf.d/docker.yaml.example, conf.d/docker_daemon.yaml.example, tests/checks/integration/test_docker_daemon.py
See comments on https://github.com/DataDog/dd-agent/pull/1908
=> [docker] A few improvements as per PR review

CHANGELOG.md, packaging/datadog-agent/source/setup_agent.sh
=> [packaging] 5.5.0 release

win32/gui.py
I just saw your remark on the PR that's already merged @yannmh . Here's a fix ;-)
=> [windows] Stop checking the Platform 2ce in a row

checks.d/docker_daemon.py
- cpuacct field may appear as follows: cpuacct, cpu,cpuacct, or
cpuacct,cpu. Deal with each.
- Use a regex to find the container id rather than using split.
Fixes #1937
=> Fix docker_daemon.py integration

checks.d/http_check.py, tests/checks/integration/test_http_check.py
Re-formatted commit message from #1923 to respect guidelines, and updated the test.
Thanks to @dmulter for contributing!
=> [http] Fix SSL cert check when specifying a port in the URL

CHANGELOG.md
=> [changelog] 5.5.1

CHANGELOG.md
Cluster
Broken link for wiki page to send logs to support
=> [Changelog] Fixing 2 typos in Agent 5.5.0 release note

checks.d/docker_daemon.py
=> Create a container_name extractor to always extract the real container name

checks.d/openstack.py
Hi @talwai, here's the update I was talking about for the Aggregate & Availability Zone I emailed you about yesterday.
This will allow us to map the aggregate and AZ info onto the hypervisor as a tag. Depending on the permissions granted to the user account doing the checks, the api call for the aggregates may fail. The check will gracefully ignore the aggregate & az tags if that is the case.
Need to update the nova policy.json to allow the role access to this api call.
```
"compute_extension:aggregates": "rule:admin_api or role:datadog_monitoring",
"compute_extension:v3:os-aggregates:index": "rule:admin_api or role:datadog_monitoring",
"compute_extension:v3:os-aggregates:show": "rule:admin_api or role:datadog_monitoring",
```
/cc @marktward
=> [checks.d][openstack] Try to get the list of aggregates and the associated hypervisors. 

checks.d/mcache.py, tests/checks/integration/test_mcache.py
Memcached Wiki https://code.google.com/p/memcached/wiki/Timeouts
recommends consulting this counter when troubleshooting timeouts.
[closes #1977]
=> [mcache] report `listen_disabled_num`

checks.d/nginx.py
=> [nginx] Log exception message

checks.d/couchbase.py
Trims down the number of metrics retrieved per bucket from ~250 to ~90.
Very simple approach for now. I've selected the metrics based on the little information that is available in the docs (http://developer.couchbase.com/documentation/server/4.0/monitoring/monitoring-rest.html), and on the metrics that are currently being used on monitors/screenboards/dashboards.
We could also limit the number of buckets on which stats are collected (and allow listing these buckets in the yaml file), but given that this check is not used that much I'm not sure it's worth it.
=> [couchbase] Only send selected bucket-level metrics

CHANGELOG.md, packaging/datadog-agent/source/setup_agent.sh
=> [packaging] Release 5.5.2

checks.d/http_check.py, tests/checks/integration/test_http_check.py
=> [http_check] revert weak SSL/TLS ciphers support

CHANGELOG.md
=> [changelog] 5.6.0

packaging/datadog-agent/source/setup_agent.sh
=> [packaging] source install `5.5.2`→`5.6.0 `

config.py
=> [packaging] 5.7.0 nightlies

CHANGELOG.md
+ mention that 5.6.0 is Unix only
=> [changelog] 5.6.1

packaging/datadog-agent/source/setup_agent.sh
=> [packaging] 5.6.1 source install

CHANGELOG.md
=> [changelog] 5.6.2

CHANGELOG.md, packaging/datadog-agent/source/setup_agent.sh
=> [packaging] Release 5.6.2

CHANGELOG.md
=> [changelog] 5.6.3

utils/dockerutil.py
=> [docker] Add one more cgroup location. Fix #2137

conf.d/tomcat.yaml.example
=> [tomcat][skip ci] Fix bad documentation

requirements-opt.txt
Upgrade `pymongo` 3p module from `2.8` to `3.2`.
**Related PR**
https://github.com/DataDog/omnibus-software/pull/30
=> [deps] `pymongo==2.8`→`pymongo==3.2`

checks.d/zk.py, tests/checks/integration/test_zk.py
=> Revert "[zk] new `zookeeper.bytes_received/sent*` rates "

config.py
+ use the Platform helpers to determine the OS family
Fixes #1956
=> [freebsd][logging] Use correct file for syslog

tests/core/test_win32.py, tests/core/test_win32_agent.py, win32/agent.py
Re-set collector heartbeat on WatchDog restarts.
=> [windows] restore heartbeat on watchdog restarts

checks.d/consul.py, checks.d/docker_daemon.py, checks.d/mesos_master.py, checks.d/mesos_slave.py, checks.d/mysql.py, checks.d/nagios.py, checks.d/redisdb.py, checks.d/ssh_check.py, checks.d/vsphere.py, checks/collector.py, checks/datadog.py, checks/libs/wmi/sampler.py, config.py, daemon.py, ddagent.py, graphite.py, tests/checks/mock/test_cacti.py, tests/checks/mock/test_ganglia.py, tests/core/test_datadog.py, tests/core/test_watchdog.py, tests/core/test_wmi.py, tox.ini, util.py, utils/flare.py, utils/platform.py, win32/gui.py
=> [flake8] Fix F841

datadog.conf.example
=> [datadog.conf] Update link to dogstatsd guide [skip ci]

checks.d/docker_daemon.py
=> [docker_daemon] Ignore case when container are excluded

checks.d/postgres.py, conf.d/postgres.yaml.example
Disabled by default
Based on #1941
=> [postgres] Measure user functions

checks.d/docker_daemon.py
=> [docker daemon] Pass tags to events as well

checks.d/mesos_slave.py, conf.d/mesos_slave.yaml.example
=> [mesos_slave] Allow to configure mesos master port

util.py
AWS EC2 custom tags collection should be using proxy settings.
=> [util] use proxy settings for EC2 tag collection

checks.d/http_check.py
=> [http check] Improve message when using default http code

ci/etcd.rb
=> Remove etcd flake

packaging/datadog-agent/source/setup_agent.sh
Changed by https://github.com/pypa/pip/pull/3396
Fixes #2217
=> [source] Fix URL of get-pip script

checks.d/yarn.py
@yannmh @remh That was happening because some metrics were not available with my version of Hadoop.
=> [yarn] Fix index error in the YARN check

packaging/datadog-agent/smartos/dd-agent, packaging/datadog-agent/source/agent, packaging/datadog-agent/source/info, packaging/datadog-agent/source/supervisor.conf, utils/flare.py, utils/pip-allow-failures.sh
Applies the changes of #1504 to the files other than `setup_agent.sh`
Should be merged before the 5.7.0 release.
=> [source] Revamp our source install script (part 1)

packaging/datadog-agent/source/install_agent.sh
Based on and supersedes #2067
Thanks @lowl4tency for contributing!
=> [install script] Add custom provided hostname to dd-agent config

checks.d/dns_check.py, conf.d/dns_check.yaml.example, requirements.txt, tests/checks/mock/test_dns_check.py
fixes #2052 
linked to https://github.com/DataDog/omnibus-software/pull/38 and https://github.com/DataDog/dd-agent-omnibus/pull/63
=> [DNS check] First pass at DNS check

checks/collector.py, checks/system/common.py
Enable uptime metric collection on Windows system check.
=> [windows][system] enable uptime collection

CHANGELOG.md
Will need to be updated with the PRs that get merged from now on.
=> [changelog] 5.7.0

checks.d/wmi_check.py, checks/wmi_check.py, tests/checks/mock/test_wmi_check.py, tests/core/test_wmi.py
Append `tag_by` property to the list of properties to collect.
=> [wmi] add `tag_by` to the properties to collect

checks/collector.py
=> [gohai] Log unexpected OSError exceptions instead of re-raising

CHANGELOG.md
**[WIP]**
Let's merge this once the release is ready and all the fixes are in.
=> [changelog] Updated 5.7.0

checks.d/hdfs_datanode.py, checks.d/hdfs_namenode.py, checks.d/mapreduce.py, checks.d/mysql.py, checks.d/yarn.py, config.py
Only fixed the errors that looked justified.
=> [pylint] Fix errors found with pylint

checks.d/mysql.py, tests/checks/integration/test_mysql.py
=> [mysql] Fix check failure when no tag is provided

config.py
=> [packaging] 5.8.0 nightlies

CHANGELOG.md, packaging/datadog-agent/source/setup_agent.sh
=> [packaging] Release 5.7.1

packaging/datadog-agent/source/install_agent.sh, packaging/datadog-agent/source/setup_agent.sh
=> [docs] Document install scripts

jmxfetch.py
Related to https://github.com/DataDog/jmxfetch/pull/85
=> [jmxfetch] Pass value of `bind_host` to JMXFetch command

conf.d/varnish.yaml.example
Was already documented on the web UI, add it to the yaml example file.
Fixes #2360
[skip ci]
=> [varnish] Document varnish group requirement

CHANGELOG.md
=> [changelog] 5.7.3

checks.d/snmp.py, checks/network_checks.py, tests/checks/integration/test_snmp.py
The cmd_generator was a per check instance, unfortunately it is not thread-safe. To address the issue we simply create a `cmd_generator` per instance (we also cache them to avoid too much overhead impact due to the change).
=> [snmp] fixing thread-safety issues with pysnmp cmd_generator

CHANGELOG.md, packaging/datadog-agent/source/setup_agent.sh
=> [packaging] Release 5.7.3

checks.d/process.py, tests/checks/integration/test_process.py
(would allow us to monitor that the agent doesn't have a handle leak)
=> [process][win32] Add metric on opened handles

conf.d/directory.yaml.example
=> [directory] The check actually works on windows

conf.d/kafka.yaml.example
Same as #2371 but with squashed commits
=> [kafka] updates to yaml file

tests/core/test_service_discovery.py
updating the auto-config for consul broke the test, this fixes it.
=> Fix get_auto_config test

conf.d/mcache.yaml.example
=> document memcache usage for listening ot unix socket

checks.d/riak.py
Adds metrics related to Riak Search that are exposed through Riak's HTTP API via the `/stats` endpoint
=> [riak] added search metrics

CHANGELOG.md
=> [changelog] 5.7.4

conf.d/kafka.yaml.example
=> [kafka] Remove duplicate metric

CHANGELOG.md
=> [changelog] 5.7.4 update

packaging/datadog-agent/source/setup_agent.sh
=> [packaging] Release 5.7.4

CHANGELOG.md
=> [packaging][5.7.4] Release date in changelog

checks/check_status.py, setup.py
There was a regression in the windows build. Honestly, I think that I caused it. 
This PR will fix it.
=> [core] fixes regression in windows build process

Rakefile
=> [dev-env] Pin setuptools version in rake setup_env cmd

checks.d/rabbitmq.py, conf.d/rabbitmq.yaml.example, tests/checks/integration/test_rabbitmq.py
Based on #2259 by @rhwlo 
My only modification was to fix a minor linting issue.
Thanks again @rhwlo!
=> [rabbitmq] add a way to tag multiple queues in the same "family"

checks.d/windows_service.py
WMI queries are not sensitive to case when fetching services status.
So you could have a conf.d with a different case for the service name.
But as we were comparing names with the actual case here:
https://github.com/DataDog/dd-agent/blob/5.7.4/checks.d/windows_service.py#L71
It would result in a bad logic.
This fixes it by having a simpler logic.
=> [windows services] Be more resilient to case

checks.d/kong.py, tests/checks/integration/test_kong.py
Instead of creating one metric per table.
=> [kong] tag metric by table/collection

checks.d/process.py, tests/checks/integration/test_process.py
Mostly from PR #2363.
I fixed the failing test and rebased against master.
=> [checks] [process] add pagefault stats

CHANGELOG.md
=> [changelog] 5.8.0

CHANGELOG.md
=> [changelog] update 5.8.0

checks.d/docker_daemon.py, conf.d/docker_daemon.yaml.example
=> [docker daemon] Add the possibility to tag by container id

CHANGELOG.md
=> [changelog] update `5.8.0` changelog

CHANGELOG.md
=> [changelog] update 5.8.0 changelog

packaging/datadog-agent/source/setup_agent.sh
=> updates version in the installer

CHANGELOG.md
=> [changelog] release 5.8.0

CHANGELOG.md
=> [5.8.1] changelog

config.py, tests/core/test_config.py
This fixes a bug in parsing the windows configuration location.
=> [core] fixes windows conf

util.py
This reverts commit dab517f9ef4bb6a989b7cc5033767132c844f45d.
=> Revert "Fix get_hostname for windows ec2 instances"

CHANGELOG.md
=> [changelog] release 5.8.2

config.py
=> [packaging] 5.9.0 nightlies

checks.d/mongo.py, checks.d/tokumx.py, checks/__init__.py, checks/collector.py
Legacy, they are not used anymore.
=> [core] remove events & resources api_key

Rakefile
Same as commit 34958887b, but for the `setup_env` rake command
=> [dev-env] DL ez_setup from preferred URL

conf.d/wmi_check.yaml.example
Recommended by customer see ticket https://datadog.zendesk.com/agent/tickets/54475
=> [wmi_check] Example syntax using a wildcard

checks.d/http_check.py
Previously SNI wasn't supported for the cert_expiration part of the check,
because we were not passing the hostname to wrap_socket.
It can only be done with a SSLContext. The code is taken from the Python docs
and should act exactly the same as before.
Doc: https://docs.python.org/2.7/library/ssl.html#ssl.SSLContext.wrap_socket
============ Previous Description ============
In order to get the certificate, `ssl_` is now used.
This was done to fix a sneaky bug which seems to only happen with some hosts
and not others. (only thing in common these hosts had was that they were
running Apache and returning a 401 for the queried URL)
`server_hostname` argument is needed, as this fix doesn't work otherwise.
According to the doc, it is set when the shipped OpenSSL version is
SNI-compatible.
=> [http_check] SNI support for cert_expiration

ci/common.rb
Move away travis cache to another S3 bucket
=> [CI] change target S3 bucket for travis cache

conf.d/mongo.yaml.example
Just adding more info about the `ssl_cert_reqs` config
Cheers
=> [mongo][doc] Add more info about ssl_cert_reqs config

ci/kong.rb, ci/resources/kong/kong_install.sh
=> [ci] only install kong when it's not already there

checks/system/unix.py, tests/checks/mock/test_sysstat.py
=> [iostat] Fix regex to match devices with a - in them

tests/checks/integration/test_ssh_check.py
Fixes integration test that was failing b/c `smashthestack.org` was deprecated.
=> [ssh][testing] updated domain name to netgarage.org

ci/elasticsearch.rb
The previous task only attempted to re-download the package if the ES dir did not exist but if the download failed the cache remained dirty and the build stuck.
Now it checks for the ES bin, if not found cleans up the ES dir and download the package.
=> [ES][testing] fix es integration tests

utils/flare.py
Otherwise the file is closed only when the file object is garbage-
collected.
Fixes flare tests errors on Windows.
=> [flare] Close the tar file cleanly once upload is done

conf.d/agent_metrics.yaml.default, conf.d/disk.yaml.default, conf.d/network.yaml.default, conf.d/ntp.yaml.default
To remind users not to edit these files directly.
=> [doc] Add disclaimer on `yaml.default` files

CHANGELOG.md
=> [changelog] lint 🎨

agent.py
Reloading configurations and checks during collection runs exposes us
to race conditions, pain and unhappiness (for instance, thread leaks
from `NetworkCheck`s).
To fix that, we reload configurations synchronously before collections
runs. The SIGHUP signal handler sets a flag to let the collector know
that it needs to reload configurations before the next run, and that's
all the signal handler does.
=> [core][collector] Use flag to signal config reload

tests/checks/integration/test_http_check.py
`http://www.inter-locale.com` has been down for a while now, changed it.
=> use a more reliable external resource

checks.d/mongo.py
=> [mongo] Fix case where optimeDate is not available

checks.d/process.py, tests/checks/integration/test_process.py
Add new metrics to test_process.py
=> [process] Add metrics for avg, max, and min run times for processes

config.py, datadog.conf.example, packaging/datadog-agent/source/install_agent.sh, packaging/datadog-agent/win32/install_files/datadog_win32.conf, packaging/datadog-agent/win32/wix/agent.wxs
=> [config] clean defaults

packaging/datadog-agent/source/install_agent.sh
Since the config file is not the good one yet.
This needs to be reverted once 5.9 is out.
=> [packaging] revert to old hostname sed

checks.d/mongo.py
The previous Pull Request for the Mongo Collections Check, #2739, has a small bug in it. I had forgotten to take out something after I stopped making the collection name an array and made it a string.
=> [mongo] Fixes a mistake in the Mongo Collections Check

ci/common.rb
Only tries to skip tests for Travis PR.
And a smarter commit comparison.
Don't skip tests on master.
=> [ci] only skip tests for Travis PR

config.py, datadog.conf.example, tests/core/fixtures/config/multiple_apikeys.conf, tests/core/fixtures/config/multiple_endpoints.conf, tests/core/fixtures/config/multiple_endpoints_bad.conf, tests/core/fixtures/flare/apikey.conf, tests/core/fixtures/flare/apikeys.conf, tests/core/test_flare.py, utils/flare.py
Change multiple endpoints config.
Clearer config.
The previous configuration was done this way because of legacy
issues/conflicts that have been fixed since.
=> [core] easier config for multiple endpoints

tests/core/test_flare.py
No need to keep the CI broken.
It's being worked on.
=> [ci] we know, flare is broken

checks.d/http_check.py, conf.d/http_check.yaml.example, tests/checks/integration/test_http_check.py
https://trello.com/c/WcJegyCV/960-support-post-method-for-http-check
=> [http_check] add ability to use post method

tests/core/test_flare.py
=> [tests] fix KeyError when no FLARE_BROKEN

config.py, tests/core/test_flare.py
=> Revert "[flare] use specific URL"

utils/dockerutil.py
This PR fixes a problem that raises as a product of #2724. There are two approaches to this problem. One is what we're doing here, the other is to modify https://github.com/DataDog/dd-agent/blob/master/checks.d/docker_daemon.py#L73 such that the `cgroup` is set to `cpuacct` instead of `cpu`. 
The second approach is a simple one word change and it actually matches the behavior I have seen with Xenial and CentOS7 (still untested on other distros). However #2724 does come from a contributor PR and it also happens to be undeniable that `cpu` is a _legit_ cgroup. So I'm unsure about what may happen in other distributions or with people that run custom cgroups.
I have found the `cpu.stat` file to be available in the `cpuacct` (or `cpu,cpuacct` cgroup stats). I'd love to hear any feedback …
=> [dockerutil] cpu stats might not always fall into the expected "subsystem" match

utils/cloud_metadata.py
To keep the same behavior as before we need to make sure not to put bad
data in the metadata if the metadata endpoint returns a non 2xx
response code (that was already the case with urllib)
This fixes a bug that was introduced with https://github.com/DataDog/dd-agent/pull/2822
Confirmed that it fixed the issue i saw on Google Compute nodes.
=> [cloud metadata] Fail on non 2xx responses

packaging/datadog-agent/source/install_agent.sh
=> Revert "[packaging] revert to old hostname sed"

config.py
=> [packaging] 5.10.0 nightlies

config.py
This PR bumps the config version.
Bumping version for bugfix release.
=> [config] bumping version to 5.9.1.

requirements.txt
Was upgraded in https://github.com/DataDog/omnibus-software/pull/75, let's do it here too.
=> [requests] Upgrade to `2.6.2`

appveyor.yml, tests/checks/integration/test_sqlserver.py
Until we figure out a way to test against multiple sqlserver instances
on AppVeyor
=> [appveyor][sqlserver] Disable tests on multiple instances

ci/activemq.rb
If something goes wrong during the installation process, some folders hang around and Travis starts failing
A strong motivation
=> [CI] cleanup dirty states for activemq

ci/redis.rb
Try to handle dirty states between CI runs for redis
Tests are failing
=> [CI][redis] handle dirty states from redis install

checks.d/kubernetes.py
A very simple pull request to fix bug #2886.
=> [kubernetes] fix kubelet health check request

CHANGELOG.md
Update Jenkins notes to make sure people know it's still supported.
=> Updated Jenkins notes

checks.d/ceph.py, tests/checks/fixtures/ceph/warn.json, tests/checks/mock/test_ceph.py
Rebased version of #2718. Thanks @ccocsas!
Will merge once the CI is 💚
=> [ceph] overall_status HEALTH_WARNING not handled [rebased PR]

checks.d/haproxy.py, tests/checks/mock/test_haproxy.py
#2649 added custom tags to haproxy. This Pull Request adds a test to ensure that they work.
=> [haproxy] adds a test for custom tags

checks/check_status.py
Display api key status in the info page
Feature request
=> [status] Display api key status in the info page

checks.d/pgbouncer.py
This fixes the service check messages and tags to support SSL which was introduced with #2885
=> [pgbouncer] SSL support. Fix service check messages and tags

checks.d/fluentd.py
Supersedes https://github.com/DataDog/dd-agent/pull/2839. Thanks @mattrobenolt.
=> [fluentd] add collection timeout

checks.d/openstack.py
Fixes missing verify=self._ssl_verify in two calls to _make_request_with_auth_fallback
We use self-signed certs. 'info' was reporting CERTIFICATE_VERIFY_FAILED errors when trying to get project stats even with 'ssl_verify: false' in conf.d/openstack.yml
The call at line 661 (in function get_stats_for_single_project) fixed my immediate issue. I modified the call at line 846 (in function get_scoped_project) because that was the only other call not having the verify parameter.
=> [openstack] Missing verify=self._ssl_verify in two calls to _make_request_with_auth_fallback

requirements-opt.txt
Adds `protobuf` dep to `requirements-opt.txt`
New dep required by #2890
=> [kubernetes] Add `protobuf` dep to `requirements-opt.txt`

checks.d/docker_daemon.py
Fix the case of empty event creation
Issue was identified during QA session on RC1
=> [docker] fix empty docker events

checks.d/pgbouncer.py, tests/checks/integration/test_pgbouncer.py
Fix typo, add test
check was failing when using db url in config file
=> [pg_bouncer] fixed urlparse call, added basic test to trigger db url parsing

CHANGELOG.md, packaging/datadog-agent/source/setup_agent.sh
=> [packaging][source] Bump to 5.10.0

config.py
=> [packaging] 5.11.0 nightlies

ci/common.rb
A brief description of the change being made with this pull request.
=> [ci] let's debug these issues

ci/common.rb, tests/checks/integration/test_mongo.py
Fix the check name detection when only tests files are modified.
Fixing a broken feature.
=> [ci] fix check name detection of test files

checks/check_status.py
Silence requests exception.
We don't want to display errors on the info page when it's only
a requests exception
=> [status] Silence requests exception

transaction.py
[forwarder] stop flushing after 10s (so that new payloads can be sent).
Very long running flushes which delay the metrics.
=> [forwarder] stop flushing after 10s

ci/default.rb
Reduce the maximum number of arguments given to pylint.
With high number of arguments pylint raise false error.
=> Reduce the maximum amount of argument to pylint.

packaging/datadog-agent/source/install_agent.sh
=> Revert to https for the APT repo

packaging/datadog-agent/source/install_agent.sh
Adds the new GPG key to the install script.
=> [core] New GPG key

checks.d/elastic.py
=> [elastic] Fix grammar and casing in exception text

checks.d/process.py
Fixes #3049 
Wanted to fix #3049
=> [process] trap psutil.NoSuchProcess exception

checks.d/mesos_slave.py, tests/checks/fixtures/mesos_master/state.json, tests/checks/fixtures/mesos_slave/state.json, tests/checks/mock/test_mesos_master.py, tests/checks/mock/test_mesos_slave.py
Revamp testing for mesos checks
Make mesos_slave check more resilient
Moving checks to the integration SDK made me realize the mesos tests had several issues
mesos_master and mesos_slave tests now run with other mocked tests.
=> [mesos] revamp tests

conf.d/docker_daemon.yaml.example
Better document container exclusion
Some support tickets suggest this wasn't clear enough.
=> [docker] Better document container exclusion

checks/collector.py
Gohai has usually useless logs which can be quite anxiogenic. Let's fix
the symptom.
=> [gohai] switch log to debug

tests/checks/common.py
Fixes JSON loading of fixtures if called from the SDK.
Left this one out with the previous PR.
=> [tests][common][sdk] use sdk_dir to load json as well.

checks.d/linux_proc_extras.py
I made a few changes to linux_proc_extras when I moved it to the sdk. It makes it easier to test. Since this is still the source of truth, we have to backport it here.
=> [linux_proc_extras] backport linux_proc_extras changes from the sdk

checks.d/mysql.py
This adds support for yet another format for innodb aio reads and writes metrics
Support ticket for a customer running mysql 5.5.50
Works with the customer
=> [mysql] Yet another format for innodb aio reads and writes

checks.d/sqlserver.py
In the event where the SQLserver is down during the check instantiation (__init__), we would not be able to retrieve the list of metrics to collect, and we'd never be able to recover from that even if the SQLserver does eventually become available. This PR addresses that. It also adds context managers for connections and cursors.
A customer stumbled on the bug.
=> [sqlserver] collect metric list in check if not previously cached.

.github/ISSUE_TEMPLATE.md
This is the new issue template:
**Output of the [info page](https://help.datadoghq.com/hc/en-us/articles/203764635-Agent-Status-and-Information) **
```
(paste your output here)
```
**Additional environment details (Operating System, Cloud provider, etc):**
**Steps to reproduce the issue:**
1.
2.
3.
**Describe the results you received:**
**Describe the results you expected:**
**Additional information you deem important (e.g. issue happens only occasionally):**
=> updates issue template for the sdk

checks.d/php_fpm.py
Resolving merge conflicts for #3074 and merging for SDK transition.
See #3074
=> [php-fpm] add http_host tag

tests/checks/integration/test_dns_check.py
To make assertions on metrics, we need to manually set `self.metrics` once the check has actually finished running (i.e. after the `wait_for_async` call), since the check runs asynchronously.
We should probably find a way to generalize this approach to all `NetworkCheck`s (in `tests.checks.common`) instead of doing this manually in the tests of every `NetworkCheck`.
Ready to port this to `integrations-core` as soon as it's merged here.
=> [dns_check][ci] Bring back assertions on metrics

checks.d/riak.py, conf.d/riak.yaml.example
Thanks to the work from @hamano in #2389 this PR allows to enable Riak security.
=> Hamano riak security

CONTRIBUTING.md
Adds mention of our new office hours to the dd-agent repo.
We want contributors to join us at office hours.
=> add mention of office hours

ci/rabbitmq.rb, requirements-test.txt, tests/checks/mock/test_kubernetes.py
This PR will update the test requirements. These do not affect releases but our CI, local testing. Aiming to unify versions across the core and SDK repositories.
Discrepancies with the SDK repos.
=> [test] bump requirements to match integrations repos.

checks.d/mysql.py
The `performance_schema.threads` table is not available on MySQL <
`5.6.0`. As a result, retrieving the slaves' statuses triggers the
following error:
```
ProgrammingError: (1146, u"Table 'performance_schema.threads' doesn't
exist")
```
This is a regression introduced by
https://github.com/DataDog/dd-agent/pull/2603
=> [mysql] use `information_schema` when < 5.6.0

conf.d/docker_daemon.yaml.example, utils/dockerutil.py
Mention that default exclusion doesn't apply if a custom one is set.
Saw some confusion about this.
=> [docker] clarify exclusion mechanism

utils/service_discovery/sd_docker_backend.py
When service discovery is enabled and we're running in kubernetes, find the namespace, replica set and daemon set (when available) and add them as tags to all metrics.
Someone asked it to me, but I can't remember who :thinking: 
The replica set tag is open to discussion. Of course it's useful as is, but a later version will also add the deployment as a tag, and in the case of deployments, replica set is not stable. The deployment name is stable but it churns through replica sets at each …
=> [service_disco] add replica_set, daemon_set & namespace tags for k8s

packaging/osx/install.sh
=> [mac os agent] Switch to google cloud storage

packaging/osx/install.sh
=> Revert "[mac os agent] Switch to google cloud storage"

checks/network_checks.py
Use a global counter for the pool size.
This way our assertion on the max number of threads will be accurate.
See #3080 for details
=> [network checks] 

tests/core/test_service_discovery.py, utils/service_discovery/abstract_config_store.py, utils/service_discovery/sd_docker_backend.py
the constant is not defined in the dockerutil class anymore. Import it correctly. Also tag with the right label.
Spotted by @sjenriquez during QA
=> fix service discovery swarm tagging

CHANGELOG.md
=> Changelog 5.12.0

datadog.conf.example
As it is not officially supported.
To future readers: please contact our support if you'd like to use something similar.
=> [conf] remove multiple endpoints

CHANGELOG.md
A small update for Windows omnibus, a bit of cleaning.
I think we should develop the "per user" to "per machine" part, make it its own part `###`, with a short explanation and a link to the official doc.
=> [changelog] windows update

requirements.txt
Fixes an outdated warning message
=> Fixed warning message in requirements file

CHANGELOG.md
=> [changelog] Add release date for 5.12.1 + link to windows upgrade docs

utils/dockerutil.py
See sister PR https://github.com/DataDog/integrations-core/pull/277
=> [docker] network tagging

requirements-opt.txt
Only keep the core agent optional requirements.
=> remove all checks.d optionals requirements

packaging/datadog-agent/source/setup_agent.sh
We need to bump the source install for the release
=> bumps source install version to 5.12.2

packaging/datadog-agent/source/setup_agent.sh
=> [packaging] Bump source install to 5.12.3

requirements.txt
=> Remove checks deps in reqs.txt

utils/service_discovery/sd_docker_backend.py
Fixes a bug in the logging if the kubelet is not found.
Found issue while testing.
=> [sd][docker] no self log attribute, use global.

conf.d/jmx.yaml.example, jmxfetch.py
Add warnings about a breaking change coming with agent 6 regarding the config of jmx checks
=> Add warnings of breaking change coming with agent 6

utils/kubernetes/kube_state_processor.py
Add more kube-state-metrics
Requested by the community
See https://github.com/DataDog/integrations-core/pull/343
=> Add more kube-state-metrics

.travis.yml
=> [slack] removing potentially compromised token.

.travis.yml, Gemfile, checks/__init__.py, tests/core/test_proxy.py, utils/proxy.py
Adds a couple of helper utility functions to avoid having code duplication in several places (dd-agent, checks that wish to disable the proxy config, etc).
While adding the `skip_proxy` feature to rabbitMQ: https://github.com/DataDog/integrations-core/pull/407, it made plently of sense to add the common code to a util package.
Merge before the sister PR.
Also sneaks in some fixes to Travis. CI was broken.
=> [utils][proxy] adding a utility function to deal with proxy configs+skipping

packaging/datadog-agent/source/setup_agent.sh
=> [source install] Fix typo in message

utils/orchestrator/__init__.py, utils/orchestrator/ecsutil.py, utils/service_discovery/sd_docker_backend.py
Add image tags and ecs tags to auto-discovered checks.
@xvello pointed out we didn't have these tags, it was clearly an oversight from us.
=> [AD] add image and ecs tags to auto-discovery

utils/kubernetes/kube_state_processor.py
https://github.com/DataDog/dd-agent/pull/3309 add support for more metrics, but kept this one commented out while waiting for the k-s-m release. 0.5.0 was released with support for this metric
s/ressourcequota/limitrange/ for the tag
=> activate limitrange in k_state_processor

utils/kubernetes/kube_state_processor.py
Reverts DataDog/dd-agent#3319 (see https://github.com/DataDog/dd-agent/pull/3319#issuecomment-305175858 for explanation)
=> Revert "[kubernetes_state] Record pod phase"

checks/prometheus_check.py, tests/core/test_prometheus.py
Fix tags getting appended once for each metric
=> [prometheus] Fix tags getting appended once for each metric

utils/orchestrator/ecsutil.py
=> fix ecsutil gateway fetching if ecs-agent is using host network

CHANGELOG.md
=> [changelog] 5.14.0

packaging/datadog-agent/source/setup_agent.sh
Update agent version to 5.14.0
=> [source install] Update agent version to 5.14.0

config.py
=> [packaging] 5.15.0 nightlies

utils/service_discovery/etcd_config_store.py
- if a port is configured, only try this one
- else, try on 4001 then 2379
If connection fails, raise a ValueError that is caught in sd_docker_backend
This allows a smooth update path to users that upgrade to new versions of etcd and didn't configure their etcd port for SD
Tested manually with:
- an invalid host (both ports fails, exception raised)
- no conf and a server listening only on 2379 (4001 will fail, 2379 will succeed)
- port 2379 configured (only this one is tried)
=> try both 4001 and 2379 etcd ports in SD if not configured

packaging/centos/datadog-agent.init
Make sure that the agent start the last and stop first.
This allows time to other software that we might depend on to start.
see: #3367
=> Make sure we start the last and stop first.

utils/kubernetes/kubeutil.py
This PR adds a constant used in https://github.com/DataDog/integrations-core/pull/509
=> constant for container name label

utils/service_discovery/sd_docker_backend.py
Add the kubernetes container name to auto discovery's additional tags.
Inspired by #3365 
=> [kubernetes] add kubernetes container name

utils/cloud_metadata.py
Remove getpass import to unblock CI.
Had a CI failure on https://travis-ci.org/DataDog/dd-agent/jobs/251965080
=> Remove unused import (it made flake8 sad)

config.py, packaging/centos/datadog-agent.init, packaging/debian/datadog-agent.init, packaging/supervisor.conf, packaging/suse/datadog-agent.init, utils/flare.py
=> Revert "pkg: Add process-agent to supervisor and flares"

packaging/datadog-agent/source/setup_agent.sh
Bump source install version to 5.15.0
=> Bump source install version to 5.15.0

config.py
Bump version for nightlies builds to 5.16.0
=> Bump version for nightlies builds

CHANGELOG.md
Updated changelog with `5.16.0` changes.
=> [changelog] updates for 5.16.0

utils/dockerutil.py
This is the name of k8s pause containers in Origin
=> [docker] Add openshift/origin-pod to default docker ignore list

utils/service_discovery/sd_docker_backend.py
If KubeUtil can't be setup it's set to None, calls that don't check for that will fail. This PR updates these calls.
Stumbled on that one during testing of something else. That's one less traceback in the logs.
=> [AD] avoid calling kubeutil if it's not initialized

utils/dockerutil.py
Docker-less host display this log line in `collector.log`:
```2017-08-11 09:15:42 UTC | WARNING | dd.collector | utils.dockerutil(dockerutil.py:94) | Error while detecting orchestrator: Error while fetching server API version: ('Connection aborted.', error(2, 'No such file or directory'))```
This PR detects whether the integration configuration `docker_daemon.yaml` is absent, and changes the `warning` to `debug`.
=> downgrade docker warning message to debug on dockerless host

packaging/datadog-agent.service, packaging/start_agent.sh
Honor sysconfig settings when launching with systemd service.
Not working in the mentioned scenario: https://github.com/DataDog/dd-agent/pull/3301
=> [systemd] apply sysconfig settings on launch too.

CHANGELOG.md
=> [changelog] 5.17.0

datadog.conf.example
Provides a consistent place to visualize all of the Datadog APM based config options with the currently available Infrastructure options. 
Pulls the list from the Trace Agent README - https://github.com/DataDog/datadog-trace-agent/blob/97721707a8b3c624864e8e49574c18dbbdb2e321/config/README.md
Consistency with providing a single place for customers to visualize available config options and settings.
=> Update datadog.conf.example to reflect APM options

CHANGELOG.md
=> [changelog] 5.17.1

CHANGELOG.md, packaging/datadog-agent/source/setup_agent.sh
* Source install version
* Changelog release date
=> [packaging] Release 5.17.1

requirements.txt
=> [supervisor] supervisor bump to 3.3.3

CHANGELOG.md, packaging/datadog-agent/source/setup_agent.sh
* Source install version
* Changelog release date
=> [packaging] Release 5.17.2

config.py
Bumps jmxfetch version to 0.17.0.
JMXFetch relese
=> [config] bump to new jmxfetch 0.17.0

tests/core/fixtures/prometheus/metrics.txt, tests/core/test_prometheus.py
Adds unit tests
Increasing coverage + testing new feature
=> Adding tests for type overrides in Prometheus check

utils/dockerutil.py
Fix the image name when it contains `sha256`
ugly container image tags
tied to https://github.com/DataDog/integrations-core/pull/770
=> Fix image lookup

checks/system/unix.py
A brief description of the change being made with this pull request.
=> Added Percentage Free Memory Stats

datadog.conf.example
Update knowledge base link for GKE.
Previous link returned a 404.
=> update link to gce knowledge base

CHANGELOG.md
Changes on AD and container tagging
[skip ci]
=> [changelog] Update 5.19.0 changelog

packaging/datadog-agent/source/setup_agent.sh
Fixes syntax error.
Instalation script broke in the middle of my work after last commit.
=> Syntax error fix

.travis.yml, checks/libs/win/__init__.py, checks/libs/win/pdhbasecheck.py, checks/libs/win/winpdh.py, checks/libs/win/winpdh_stub.py, tests/core/test_dogstatsd.py
Fixes the CI, bad code we had stubbing WinPDHCounter
Remove sadness from the world.
=> [win] fixing flakes, stubbing WinPDHCounter

config.py
=> Bump version to 5.20.1

config.py
=> [config] bumping to 5.21.0

CHANGELOG.md
=> Update changelog for 5.20.1

config.py
Bump agent version to `5.20.2`
=> Bump agent version to 5.20.2

checks/libs/win/pdhbasecheck.py, checks/libs/win/winpdh.py
Allows pdh checks to work on a remote machine
adds generic handling of additional metrics not specified in the check itself.
fixes tagging to correct separator.
equivalent of https://github.com/DataDog/datadog-agent/pull/918
=> update base libraries for PDH based checks 

requirements-opt.txt, tests/core/test_prometheus.py
bumps `protobuf` to the latest version - `3.5.1`
=> [protobuf] bumping to 3.5.1

checks/prometheus_check.py, requirements.txt, tests/core/test_prometheus.py
This reverts commit 05c50c640cc26924b1e6d762700c24818a88f6b1 for the 5.21.0 from #3617
=> Revert "Fix prometheus check summary and histogram

utils/dockerutil.py
Fix #3082
user request
this PR is tied to ... - they should be tested together
=> add flag to image_name_extractor to return short image name

datadog.conf.example
Add process_agent_enabled to example datadog.conf
Close #3615
=> Add process_agent_enabled to example datadog.conf

packaging/datadog-agent/source/setup_agent.sh
Bump source install to latest release: `5.21.0`
=> [source install] bump version to 5.21.0

config.py
bumping config to next minor for nightlies: `5.22.0`
=> [config] bumping to next minor

utils/proxy.py
=> fix no proxy

checks/__init__.py
See https://github.com/DataDog/integrations-core/pull/1057
=> deprecate no_proxy config option

packaging/datadog-agent/source/setup_agent.sh
This updates the setup script to use wheels.
Outdated
=> update for wheels

packaging/datadog-agent/source/setup_agent.sh
This better supports checks with multiple files.
=> [setup_agent.sh] install integrations as wheels

CHANGELOG.md, packaging/datadog-agent/source/setup_agent.sh
Update CHANGELOG.md and the default version of the install script for the release of 5.22.0
=> Release 5.22.0

packaging/datadog-agent/source/setup_agent.sh
Alpine doesn't expand wildcards when quoted.
=> [setup_agent.sh] fix wildcards

CHANGELOG.md
We're moving the rotation to the next day
=> [changelog] Update to APT key rotation date

checks/libs/win/pdhbasecheck.py
Fix tag initialization when reading `tags` list from check config yaml
customer report.
=> [pdh] fix tagging

util.py, utils/configcheck.py
=> Avoid failing the configcheck command if the instances is empty

requirements.txt
Part of
https://github.com/DataDog/integrations-core/pull/1264
https://github.com/DataDog/integrations-extras/pull/125
=> upgrade requests dependency

.gitignore, utils/service_discovery/abstract_config_store.py, utils/service_discovery/etcd_config_store.py
Part of:
https://github.com/DataDog/integrations-core/pull/1264
https://github.com/DataDog/integrations-extras/pull/125
https://github.com/DataDog/dd-agent/pull/3706
https://github.com/DataDog/integrations-core/pull/1266
=> fix requests imports

config.py
Bump JMXFetch version to 0.19.0
=> Bump JMXFetch version to 0.19.0

checks/libs/win/winpdh.py
Customer report; should work outside of us
=> [Windows] fix pdh counters on localized versions of windows

utils/flare.py
Collects useful system information on the state of windows performance counters within a flare
Asking the customer to always do this when troubleshooting, may as well just include this in a flare.
=> [windows] add pdh data to flare

config.py
=> [jmxfetch] bump to 0.20.0

CHANGELOG.md
=> [changelog] Add entry for 5.24.0

packaging/datadog-agent/source/setup_agent.sh
5.24.0 release for source install
=> [source install] 5.24.0

CHANGELOG.md
=> changelog 5.25.2

packaging/datadog-agent/source/setup_agent.sh
=> bump source install to 5.25.2

checks/collector.py
re-instantiates the dogstream every 10 runs (approx. every 2 minutes)
Fixes issue #3700
=> Fixes issue #3700

packaging/datadog-agent/source/setup_agent.sh
Bump version of the source install.
=> Bump version of the source install

packaging/datadog-agent/source/install_agent.sh
Found a bug in the rpm version of the install script!
=> fix install script for yum

checks/check_status.py
Fix proxy formatting when user or password aren't set
=> Fix proxy formating when user or password aren't set

CHANGELOG.md, packaging/datadog-agent/source/setup_agent.sh
* [changelog] 5.27.2
* [changelog] Normalize date format to YYYY-MM-DD
* [packaging] Source install 5.27.2
5.27.2 release + normalize all dates
=> 5.27.2 changelog + source install

config.py
=> bump jmxfetch to 0.21.0

packaging/datadog-agent/source/setup_agent.sh
=> bump source install to 5.28.1

CHANGELOG.md
Will cherry-pick on `5.29.x` after this is merged.
=> 5.29.0 changelog

requirements.txt
Bump Kazoo to match https://github.com/DataDog/integrations-core/pull/2766
Keep Agent 5 aligned with 6+
=> Bump kazoo to 2.6.0

CHANGELOG.md
Mentions known issue of `disk`  in 5.30.
I said this would be reverted in 5.31, @masci please confirm this is indeed the plan :)
=> [changelog] Add mention of disk check issue in 5.30

config.py
Upgrades JMXFetch to 0.24.0
See https://github.com/DataDog/omnibus-software/pull/278
=> [jmxfetch] Upgrade to 0.24.0

config.py
Bump JMXFetch to 0.24.1
Depends on https://github.com/DataDog/omnibus-software/pull/284
=> Bump JMXFetch to 0.24.1

checks/collector.py, config.py
Add telemetry to the linter but don't display warnings in the status page for now
=> Add telemetry to the python3 linter and but display warnings in the status page for now

config.py
Removing log line about py3 validation
=> Removing log line about py3 validation

config.py
Related: https://github.com/DataDog/omnibus-software/pull/287
=> [jmxfetch] Update to 0.25.0

config.py
Bumps the version of jmxfetch.
Bugfix JMXFetch release
=> [jmxfetch] 0.26.1 released

requirements-opt.txt, requirements.txt
DataDog/integrations-core#3274
DataDog/integrations-core#3272
=> Upgrade requests & protobuf

.travis.yml, appveyor.yml
Runs CI on/against `agent-v5` branches.
`agent-v5` is now the default branch of the repo
=> [ci] Run on/against agent-v5 branch

CHANGELOG.md
Changelog for the 5.32.2 release.
=> [release] Add 5.32.2 CHANGELOG entry.

config.py
Bump config.py to the future version.
=> Bump config.py to the future version.

requirements.txt
Upgrades urlllib3 to 1.24.3
See https://github.com/DataDog/dd-agent/pull/3837
=> Upgrade urllib3 to 1.24.3

CHANGELOG.md
Update CHANGELOG.md for 5.32.3
Release of 5.32.3
=> Update CHANGELOG.md for 5.32.3

config.py
Related to https://github.com/DataDog/omnibus-software/pull/325
=> [jmxfetch] Bump to 0.26.2

config.py
=> Bump agent version to 5.32.4

CHANGELOG.md, config.py
Bump AGENT_VERSION and update changelog.
=> Release 5.32.5

CHANGELOG.md
=> Add changelog for 5.32.6

config.py
=> Bump to 5.32.7

CHANGELOG.md
=> 5.32.7 changelog

CHANGELOG.md
This PR updates the changelog ahead of the 5.23.8 release.
upcoming 5.32.8 promotion.
=> [changelog] 5.32.8 changes.

config.py
Update nightly version after 5.32.8 release.
This was missed after the 5.32.8 release.
Let's check the build pipeline works after merging this to master
=> 5.32.9 nightlies

packaging/datadog-agent/source/install_agent.sh
* [RH, Debian] By default, get keys from keys.datadoghq.com
* [Debian] Always add the DATADOG_APT_KEY_CURRENT.public key (contains key used to sign current repodata)
* [Debian] Add 'signed-by' option to all sources list lines
* [Debian] On Debian >= 9 and Ubuntu >= 16, only add keys to /usr/share/keyrings/datadog-archive-keyring.gpg
* [Debian] On older systems, also add the same keyring to /etc/apt/trusted.gpg.d
=> Improvements for GPG keys management in install script

.github/ISSUE_TEMPLATE.md
This should help folks filing issues here by accident to find the right place.
=> Note that this repo is probably not the one you want

packaging/datadog-agent/source/install_agent.sh
Stops adding old RPM GPG key 4172A230
=> Stop adding old RPM GPG key 4172A230

CHANGELOG.md
=> [changelog] 5.32.9
