DataDog/dd-agent

- checks.d/postgres.py
- tests/test_postgresql.py
We were incorrectly only sending an OK status when a connection was
first established. This means any monitors on this check would be in
a NODATA state after the first run of the check.
Now we'll send an OK once we have a working connection, even if the
connection had to be reset.
Also adds a message to the service check :)
> [postgres] Always sent OK status, even with cached connection.

- checks.d/couch.py
- checks.d/couchbase.py
- checks.d/kyototycoon.py
`e.reason` is an error type and not simply a string describing the
reason. This was causing errors in the HTTP emitter because these
error types aren't serializable.
> Make sure all service check messages are strings.

- checks.d/postgres.py
We are using Postgres 9.1.9 and I see a lot of errors in collector,log like this:
2014-12-22 18:33:47 UTC | WARNING | dd.collector | checks.postgres(postgres.py:277) | Not all metrics may be available: ('ERROR', '42703', 'column "checkpoint_write_time" does not exist')
The problem is that  postgres 9.2 columns of a pg_stat_bgwriter view are hardcoded in postgres.py
The columns checkpoint_write_time, checkpoint_sync_time, buffers_backend_fsync are missing in version 9.1
After a BGW_METRICS query failed, all the following queries fail, too. 
The proposed fix makes the BGW_METRICS Postgres version aware. This may not be the most elegant solution, but I tried to make as fewer changes as possible, and do everything in the spirit of the existing code.
After I applied this fix, I have …
> [postgres] Made BGW_METRICS version dependent

- checks.d/network.py
Not sure if the comment is still relevant.
At least the current feature is broken and the code guarantees it stays broken.
> [network] Really skip excluded_interfaces

- checks.d/docker.py
- conf.d/docker.yaml.example
Some improvements around Docker containers filtering.
* Filters also apply to events. Fix #1234
* Performance improvements around filtering and regex
* Fix the logic of our rules: what we were explaining in the documentation (the docker.yaml.example) wasn't matching the real behavior. Fix the code to make it matches.
* Clarify the explanations in the example config.
> [docker] Filter events

- checks.d/elastic.py
- tests/test_elastic.py
When using an external Elasticsearch cluster, we should tag the
hostname by the node's given hostname in the stats output. Otherwise
we end up using only the last node's values because each subsequent
gauge metric will stomp on the one before it.
The test is updated to make sure the hostname given in the stats
(which should be the FQDN) matches what we output at the end.
Finally, this change also splits the cluster health metrics into a
seperate dict. This has two benefits: (a) it will clean up a lot of
debugging logging and extra work for `_process_health_data` and
(b) makes it easy to check against just the stats metrics for tests.
> [elasticsearch] Fix host tagging for external clusters.

- checks/system/unix.py
subprocess.PIPE is limited in size because the data is buffered in
memory. When running the Agent on a host that has many containers,
the number of mountpoints can be very large. Because of this buffer limit,
the shell call can hang for these huge outputs.
To workaround this, we will write the output to a temporary file and
read it from there.
This is a "quick" fix for a specific case and there might be a better
general approach. But either way, we will still need to handle the
case of large outputs from our subprocess commands otherwise the
whole Agent collector simply hangs.
refs:
- http://thraxil.org/users/anders/posts/2008/03/13/Subprocess-Hanging-PIPE-is-your-enemy/
- https://datadog.desk.com/agent/case/17823
cc @remh @LeoCavaille
> Use a temporary file for df output to avoid PIPE limits.

- checks.d/snmp.py
- conf.d/snmp.yaml.example
- tests/test_snmp.py
Adds a configuration option to walk non-increasing OIDs.  Fixes #1231.
> [snmp] configuration option to ignore non-increasing OIDs

- checks.d/marathon.py
After working on the just-merged etcd plugin for #1235 I wanted to take a look at the Marathon plugin. Looks like the key problem I saw was already fixed in #1240. While I was here I:
* Refactored some of the magic numbers and arrays up into class variables
* Removed unnecessary includes
* Switched to the service check API
* Added the "disk" attribute from the metrics
I appreciate you taking the time to look at this. If I can do anything to help a merge, let me know!
> [marathon] service checks and improvements

- conf.d/postfix.yaml.example
Various CentOS/Redhat flavours require a tty to be allocated when using sudo. Document how to by-pass this requirement per user.
> [postfix] Document requiretty requirement on Redhat/Centos for using sudo.

- aggregator.py
- config.py
- datadog.conf.example
- dogstatsd.py
- tests/performance/benchmark_aggregator.py
- tests/test_dogstatsd.py
Fixes #1256. We should always consider that dogstatsd
receives a utf-8 encoded string through its socket,
but still support unicode python strings in case we
submit things programatically (e.g. useful for tests)
> [dogstatsd] handle properly utf8 packets

- conf.d/docker.yaml.example
- conf.d/http_check.yaml.example
- conf.d/tcp_check.yaml.example
* Restore the proper docker.yaml.example "new_tag_names" option (got commened on 36781988)
* Fix #1317
> Discourage legacy options for Docker and network checks

- conf.d/cassandra.yaml.example
- sort cassandra config attributes
- add cassandra monitoring attributes for recent latency
See:
http://wiki.apache.org/cassandra/JmxInterface#org.apache.cassandra.service.StorageProxy.Attributes.RecentRangeLatencyMicros
http://wiki.apache.org/cassandra/JmxInterface#org.apache.cassandra.service.StorageProxy.Attributes.RecentReadLatencyMicros
http://wiki.apache.org/cassandra/JmxInterface#org.apache.cassandra.service.StorageProxy.Attributes.RecentWriteLatencyMicros
> Update cassandra config

- checks.d/docker.py
- conf.d/docker.yaml.example
- tests/common.py
- tests/test_docker.py
Fixes #1342.
We should always cast boolean options from the config with
the `_is_affirmative` tool, otherwise you're exposed to
oddities like bool('false') == True.
This introduces a new option `collect_images_stats` that is
enabled by default and skips the collection of metrics
`docker.images.available` and `docker.images.intermediate` that
sometimes is very slow through docker API if you have a lot of
intermediate layer images.
> [docker] fix config bools, skip image stats option

- conf.d/mongo.yaml.example
If you follow the mongo.yml example, you end up with a series of messages cluttering the logs rather noisily:
```
Feb  3 22:00:51 my-awesome-host dd.collector[16860]: INFO (mongo.py:183): No MongoDB database found in URI. Defaulting to admin.
```
Updating the example file would go a long way towards making this explicit, although it could be a better change to silence (or change the level to DEBUG) of the message above.
> Update mongo.yml.example to add database

- config.py
In python bool is a subclass of int, so when we parse
something from the config, being an int like 0/1 or a
"true" boolean isinstance(s, int) does the job. For
additional security we cast it again as a bool.
This was the intentional behavior from the start...
> [config] fix integer to boolean casting helper

- packaging/datadog-agent/source/install_agent.sh
Try `lsb_release` command to determine the Linux distribution and 
- If failing try `/etc/issue` should contain the release information
- If still failing, rely on the `/etc/*-release` files
More info:
http://unix.stackexchange.com/questions/92199/how-can-i-reliably-get-the-operating-systems-name
Also see:
https://github.com/DataDog/dd-agent-omnibus/pull/8
> Determine the Linux distribution logic

- checks.d/win32_event_log.py
Event log datetime standard is `yyyymmddHHMMSS.mmmmmmsUUU` (see https://msdn.microsoft.com/en-us/library/aa387237%28v=vs.85%29.aspx), `sUUU` being the offset in minutes. (and `s` `+` or `-`).
`wmi.to_time` doesn't deal with the `s` information, so  here is a quick trick to add timezone.
> [win32_event_log] stop ignoring timezone in time conversion

- checks.d/nginx.py
Spread between “connections opened” and “connections handled” indicates
resource saturation
> Monitor 'handled' in nginx

- source-optional-requirements.txt
- source-requirements.txt
pysnmp and pysnmp-mibs require pycrypto which requires a compiler. So
the source install would fail on systems that don’t have a compiler.
> Fix source install requirements, fix #1380

- checks.d/varnish.py
When calling subprocess with an argv-like array, argv[0] needs to
be the program to execute and not a sequence of programs like
`sudo someprogram`.
Otherwise this results in:
`OSError: [Errno 2] No such file or directory` when trying to find
the `sudo someprogram` executable in the PATH.
> [varnish] fix `varnishadm` subp call with sudo

- checks.d/redisdb.py
- ci/redis.rb
- ci/resources/redis/auth.conf
- tests/test_redis.py
[redis] add new replication metrics for >= 2.8 instances
New metrics:
* `redis.replication.backlog_histlen`
shows the current replication backlog size in bytes used from the
allocated `repl-backlog-size` in the config.
* `redis.replication.master_repl_offset`  
this metric is available on masters, it shows the current offset of
the replication process on the master in bytes
* `redis.replication.slave_repl_offset`
idem for the slaves.
* `redis.replication.delay`
on masters only, measures the difference between the last offset
reported by the slave and the current replication offset, which
indicates how far your slave is behind.
This metric is tagged by `slave_ip`, `slave_port` and `slave_id`
(internal ID in the master).
Also added on Travis a replication config between the two instances we …
> [redis] new post 2.8 replication metrics

- checks.d/redisdb.py
- conf.d/redisdb.yaml.example
- tests/test_redis.py
Superseed #1330
Creates a histogram per redis command (HGET, LPUSH, etc) that is in the
slow query log.
> [Redis] Add slow log metrics

- checks.d/apache.py
- checks.d/couch.py
- checks.d/couchbase.py
- checks.d/fluentd.py
- checks.d/haproxy.py
- checks.d/http_check.py
- checks.d/kyototycoon.py
- checks.d/lighttpd.py
- checks.d/mesos.py
- checks.d/nginx.py
- checks.d/rabbitmq.py
- checks/network_checks.py
- checks/utils.py
- tests/test_haproxy.py
Fixes
* Fix #1196
* Fix #1398
Along with the self contained agent (pyopenssl etc) it will support SNI.
See https://github.com/kennethreitz/requests/issues/749 for more
information
> Switch http libraries used in checks to requests

- checks.d/marathon.py
> Properly build marathon url

- checks.d/postgres.py
- tests/test_postgresql.py
Fix #1211
When multiple instances were connecting to the same pg instance, as metrics are not tagged by instance, We were collecting the same metrics multiple times leading to the errors described here:
https://github.com/DataDog/dd-agent/issues/1211
This fixes it by not collecting common metrics across instances more than once.
> Fix bug when multiple instances were connecting to the same pg instance

- conf.d/cassandra.yaml.example
This adds a few more node-wide metrics that complete the `StorageProxy` section of Cassandra's JMX metrics.
See here for more: http://wiki.apache.org/cassandra/JmxInterface#org.apache.cassandra.service.StorageProxy
> [cassandra] Add some more StorageProxy metrics

- checks.d/snmp.py
- conf.d/snmp.yaml.example
Supersedes #1397
Fixes #1374
pysnmp requires mpModel to be set to 0 to use SNMPv1.
This parameter defaults to 1 which means SNMPv2c
See
http://pysnmp.sourceforge.net/docs/current/security-configuration.html
> Allow snmpv1

- config.py
Fixes #1414
From http://tornado.readthedocs.org/en/latest/httpclient.html:
```
`proxy_host` (string) – HTTP proxy hostname. To use proxies, proxy_host and proxy_port must be set; proxy_username and proxy_pass are optional. Proxies are currently only supported with curl_httpclient.
`proxy_port` (int) – HTTP proxy port
```
> [core] Cast system settings proxy port to int

- checks.d/marathon.py
- conf.d/marathon.yaml.example
I like to protect our marathon instances behind basic authentication, so I needed this configuration option.
Launch marathon with --http_credentials "user:password" to require basic authentication, then configure your marathon.yaml with the user and password.
I tested this pull request with and without the user/password fields in marathon.yaml -- both seem to work fine.
> [marathon] add basic auth option

- .travis.yml
- checks.d/couch.py
- ci/couchdb.rb
- conf.d/couch.yaml.example
This adds the installation of couch in the CI (no need to install manually anymore).
It also limits the check to 50 DB, and adds whitelist and timeout features, both configurable in the yaml.
> Add timeout and whitelists to couchdb check, and improve the CI.

- config.py
The sample conf shows `histogram_aggregates`, but we pass the attribute
to the parsing fonction with a typo which causes confusing errors.
> [core] Fix histogram option typo

- checks.d/wmi_check.py
- conf.d/wmi_check.yaml.example
Rebased #1253 on 5.2.0 agent release.
Added a few changes:
* String cast and flatten `link_value` tags values (https://github.com/DataDog/dd-agent/compare/yann/wmi-extend-tagging?expand=1#diff-7a46560288aed829df125f0734b355f9R89)
* Cast source property link value to `int` instead of `float` (experienced issues in my tests)
Thanks a lot @rlaveycal
> [wmi] extend tagging for related class & constants

- util.py
The AWS EC2 tag discovery defaulted to us-east-1 which resulted in an instance discovery failure in other regions.  The _/var/log/datadog/collector.log_ was showing entries as in:
```
EC2ResponseError: EC2ResponseError: 400 Bad Request
<?xml version="1.0" encoding="UTF-8"?>
<Response><Errors><Error><Code>InvalidInstanceID.NotFound</Code><Message>The instance ID 'i-XXXXXXXX' does not exist</Message></Error></Errors><RequestID>deadbeef-701a-4bf9-9f29-147994aee2cc</RequestID></Response>
```
Support instance tag
discovery in all regions by querying the instance-identity document
store for the region and using `boto.ec2.connect_to_region` for the EC2 instance discovery.
*NOTE*: Apologies in advance for Python style violations...I've not used Python in a _long_ time and I'm not in a position to …
> Support EC2 tag discovery in all regions

- daemon.py
Solve all problems related to the agent receiving a SIGKILL and not cleaning its pidfile.
Check if the pid in the pidfile is valid, if it is, abort, otherwise ignore and continue its start.
With this change, even if the collector (or any other agent process) receives a SIGKILL, it will just be restarted by supervisor.
So the question is: do we want to have a _Phoenix_ agent which will always arise from its ashes (but may hide any error causing its death), or an agent which need a manual restart after a *critical* error ?
----
It was the default behaviour before 5.2 because processes started by supervisor didn't have a pidfile.
> [core] improve detection of already running agent at startup

- conf.d/kafka.yaml.example
kafka updated their bean names.
See
https://issues.apache.org/jira/browse/KAFKA-1481
This won't work on older Kafka version so we added a warning
to link back to the old Kafka sample file if needed
[leo@datadoghq.com] Rebased on master and reindented
+ added warning
Link to `beans` on a fresh install of 0.8.2 locally: http://paste.cavaille.net/?8f6a17732af85955#WNlLjIh3nzet2yjJIaQ9Z0/ufazYZTTcvG+732EzOJA=
And 0.8.1 http://paste.cavaille.net/?b937f059b8dd75e2#NWRRO0TqNDwm/ElRPXK5hDrQIOTbCKdEsfiTwjtWMJ8=
> [kafka] upgraded jmx keys for >= 0.8.2

- checks.d/postgres.py
- tests/test_postgresql.py
Improve postgresql.replication_delay, add postgresql.replication_delay_bytes and postgresql.total_tables.
> Add some metrics to the postgres check

- checks/check_status.py
Otherwise it will try to parse args that are not expected
e.g. use_simple_http_client and will log some errors.
This fixes the 
```
ddagent.py: error: no such option: --use_simple_http_client
```
error on source install.
> Do not parse args in info page

- checks.d/vsphere.py
Fix bug in retrieving open connections to vCenter instances
(previously, `server_instance` was only defined for new connections).
> Fix small bug in vSphere integration check

- checks.d/couch.py
- ci/couchdb.rb
- tests/test_couch.py
Couch test can now be run using the cache (previously it wasn't possible because
of missing environment variables)
> [tests] use AgentCheckTest for couch.py

- tests/test_http_check.py
`http_check` was already using `AgentCheckTest`, thanks to @yannmh.
> [http_check] add coverage_report

- checks.d/haproxy.py
- ci/haproxy.rb
- ci/resources/haproxy/haproxy-open.cfg
- ci/resources/haproxy/haproxy.cfg
- tests/common.py
- tests/test_haproxy.py
- PEP8 and FLAKE8 cleaning in `haproxy.py`
- use AgentCheckTest to test haproxy (rewrite old tests to have a 100%
metrics coverage)
- start/stop haproxy in `ci/haproxy.rb`, instead of inside the test
itself
- add a `run_check_twice` function inside `AgentCheckTest` to avoid code
repetition when testing rates
> [haproxy] use new test class

- checks.d/mysql.py
- Don't try to calculate `innodb_buffer_pool_pages_utilization` when `innodb_buffer_pool_pages_total == 0`
> Fix zero division bug in mysql check

- checks.d/gearmand.py
- tests/test_gearman.py
* Add proper support of multiple instances
* Add tags to service checks
* Migrate test to new test framework
> [Gearman] Improve integration

- checks.d/rabbitmq.py
- ci/rabbitmq.rb
- tests/common.py
- tests/test_rabbitmq.py
* because we checked the tags only to be non-`None` we were creating
empty tags like `rabbitmq_policy:`
* adds some helper methods in `AgentCheckTest` to assert directly a
service check by status like `assertServiceCheckCritical` without
having to import `AgentCheck` just for that in the test file
* add coverage report to ensure we cover 100% of the metrics output
add TODO instead of commenting the missing metrics, maybe we can do
that at some point but we would have to create a consumer and do some
work to get these. For instance use the `pika` python module.
* Bonus: some pep8-ing
> [rabbitmq] Improve test suite and fix tagging

- .travis.yml
- ci/common.rb
Previous command was working with a *zsh* shell but not bash,
see http://unix.stackexchange.com/a/62665
We might need to manually clear the cache.
> [dev] delete log files before caching

- checks.d/system_core.py
- tests/test_system_core.py
- util.py
\+ as usual pep8/flake8 cleanup.
> [system_core] Add AgentCheckTest mocked test

- checks.d/nginx.py
To avoid any irregularities in roll-ups / averages, etc. Also fix a
typo (“conn”=>”handled”)
> calculate dropped connections directly in the agent

- checks.d/mcache.py
- tests/common.py
- tests/test_mcache.py
- 100% metrics and service check coverage
- Add a default tag so that multi instances will work properly
- Remove monkey patch as it’s not needed anymore (See comments about
python-memcached version impacted here:
https://github.com/DataDog/dd-agent/commit/d3bbd1ff561b3b2682ae79d308876
a4910f9ff3b )
- Flake 8
Also:
- Add a helper in the AgentCheckTest class to determine if we’re
running on travis or not
- Add a helper to “reset” a check that may be useful sometimes
> [Memcache] Improve tests and bug fixes

- CHANGELOG.md
- checks.d/elastic.py
- tests/common.py
- tests/test_elastic.py
- Properly handle multiple instances
- 100% metrics and service checks coverage
- Flake8 (everything but line > 80)
- Make sure that constants are constants
- Fix #1402 
- Default version to 1.0.0 as it's more common to have an ES version >= 1.0.0
Also:
- Pretty format coverage report
- Log more info when candidates assertion is failing
> [ElasticSearch] Improve tests and bug fixes

- utils/flare.py
When unning the `flare` command, this output appear if the user has installed some modules manually in the `/opt/datadog-agent` python environment:
> 2015-03-31 23:55:36,997 | INFO | dd.collector | flare(flare.py:99) |   * pip freeze
The directory '/opt/datadog-agent/.cache/pip/log' or its parent directory is not owned by the current user and the debug log has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want the -H flag.
The directory '/opt/datadog-agent/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want the -H flag.
We cannot remove the warning about the log file (no …
> [flare] remove pip cache warning :bug:

- util.py
get_only_instances is overkill for grabbing tags.
get_only_instances requires DescribeInstances, where get_all_tags only
requires the DescribeTags permission.
> util/get_tags: use get_all_tags instead of get_only_instances

- agent.py
- packaging/centos/datadog-agent.init
- packaging/debian/datadog-agent.init
- tests/test_flare.py
- utils/flare.py
As otherwise `supervisorctl status` won't be collected.
Ask for email even to update a case, as it is now the 'id' to check if
it is the good case (ie a case open by this customer).
> [flare] Warn user if not root

- checks.d/supervisord.py
- tests/test_supervisord.py
- Send status OK when we can connect to the daemon
- Rename service check
- Use proper nose API
> Improvements to the supervisor integration

- .travis.yml
- ci/apache.rb
- ci/cassandra.rb
- ci/common.rb
- ci/couchdb.rb
- ci/default.rb
- ci/elasticsearch.rb
- ci/etcd.rb
- ci/fluentd.rb
- ci/gearman.rb
- ci/haproxy.rb
- ci/lighttpd.rb
- ci/memcache.rb
- ci/mongo.rb
- ci/mysql.rb
- ci/nginx.rb
- ci/pgbouncer.rb
- ci/phpfpm.rb
- ci/postgres.rb
- ci/rabbitmq.rb
- ci/redis.rb
- ci/skeleton.rb
- ci/snmpd.rb
- ci/ssh.rb
- ci/supervisord.rb
- ci/sysstat.rb
- ci/tomcat.rb
Some files are regenerated every time the test is launched, and so were
triggering the upload of a new cache.
This commit should fix this devious behaviour.
It also fixes the issue with pylint not found by Travis-caching the
python bin directory.
& Use the cache only internally
And not on forks, this was already done by Travis to protect our
"secure env variables", this commit just removes all calls to the cache
in this case (previously, it was called, but nothing happened).
Travis doc about "Secure variables":
http://docs.travis-ci.com/user/environment-variables/#Secure-Variables
> [tests] Clean before cache

- .travis.yml
- Rakefile
- checks.d/zk.py
- ci/resources/zookeeper/zoo.cfg
- ci/zookeeper.rb
- tests/test_zookeeper.py
> [zk] CI + tests

- dogstatsd.py
- emitter.py
- tests/test_common.py
- tests/test_dogstatsd.py
Starting with Agent 5.0.0, there should always
be a local forwarder running and all payloads
should go through it.
So we should make sure that we pass the no_proxy
environment variable that will be used by requests
See: https://github.com/kennethreitz/requests/pull/945
Fix #1514
> [Core] Do not use proxy for local connections

- checks.d/php_fpm.py
- tests/test_php_fpm.py
Otherwise it doesn't produce the expected results, with an increment the
graph will have a monotonically increasing curve whereas with a
monotonic count it will only report the difference since the last flush
which is what we want because the value given by FPM is never reset.
> [phpfpm] Use monotonic counts instead of counters

- checks.d/riak.py
Since we don't support custom tags for service_checks for now.
> [riak] remove custom tags from service_checks_tags

- .travis.yml
- Rakefile
- checks.d/varnish.py
- ci/varnish.rb
- tests/test_varnish.py
- utils/shell.py
Fixes https://github.com/DataDog/dd-agent/issues/1459
> Omit MAIN type from varnish metric names

- checks.d/pgbouncer.py
Otherwise it fails with
> UnboundLocalError: local variable 'connection' referenced before
> assignment
instead of the real connection error.
> [pgbouncer] Raise connection error instead of pass

- checks.d/docker.py
- checks.d/etcd.py
- checks.d/kyototycoon.py
- checks.d/marathon.py
- checks.d/mysql.py
- checks.d/php_fpm.py
- checks.d/redisdb.py
- checks.d/zk.py
- tests/test_etcd.py
- tests/test_php_fpm.py
- etc: do not use custom tags
- Docker: Remove custom tags
- kyototycoon: add missing tags on status OK
- Marathon: Remove python2.6 incompatible code
- Mysql: Add support for socket connection
- PHP-FPM: Remove custom tags
- Redis: Use only one set of tags
- Zookeeper: Add tags to service check
--
This will likely break the CI and i'll try to add a few tests so this is not ready to merge yet.
cc: @conorbranagan , @LeoCavaille
> [Multi] Fix service check tags

- jmxfetch.py
Save exception as a string, not a Python object
jmx_status_python.yaml
```
invalid_checks:
jmx: !!python/object/apply:__main__.InvalidJMXConfiguration [A numeric port must
be specified]
timestamp: 1429048613.553269
```
Printing agent info was raising an exception:
```
ConstructorError: while constructing a Python object
cannot find 'InvalidJMXConfiguration' in the module '__main__'
in "/tmp/jmx_status_python.yaml", line 2, column 8
```
jmx_status_python.yaml
```
invalid_checks: {jmx: A numeric port must be specified}
timestamp: 1429050253.38898
```
> [jmx] invalid_checks cast bug :bug:

- checks.d/system_swap.py
- tests/test_system_swap.py
Uses `psutil` to collect the rate of memory swapped in and swapped out. New metrics are labelled `system.swap.swapped_in` and `system.swap.swapped_out`.
Fixes #716
> [swap stats] add swap in/out check to checks.d

- .travis.yml
It seems that pip doesn't delete some artefacts when upgrading itself
and setuptools. :facepunch: 
Build failing because of transient Travis cache issues.
> [ci] fix Travis cache reupload everytime

- .travis.yml
- Gemfile
- ci/apache.rb
- ci/cassandra.rb
- ci/common.rb
- ci/couchdb.rb
- ci/elasticsearch.rb
- ci/etcd.rb
- ci/fluentd.rb
- ci/gearman.rb
- ci/go_expvar.rb
- ci/haproxy.rb
- ci/mongo.rb
- ci/pgbouncer.rb
- ci/postgres.rb
- ci/rabbitmq.rb
- ci/resources/supervisord/program_0.sh
- ci/resources/supervisord/program_1.sh
- ci/resources/supervisord/program_2.sh
- ci/skeleton.rb
- ci/supervisord.rb
- ci/tomcat.rb
- tests/checks/common.py
- tests/checks/integration/test_elastic.py
- tests/checks/integration/test_pgbouncer.py
`Wait.for` can receive either:
- a port (`Wait.for 7199`), and will return when the port is open
- an url (`Wait.for 'http://localhost:8080'`), and will return when
receiving a 2xx response code
- a file (`Wait.for '/tmp/started'`), and will return when the file
exists
It has a default timeout of 5s, which can be configured as its second
parameter: `Wait.for 'http://localhost:8080', 10`
> [ci] replace sleep_for by a function

- packaging/datadog-agent/source/install_agent.sh
- packaging/debian/datadog-agent.service
- packaging/debian/start_agent.sh
The install script has been modified (it uses updated-rc.d to restart
the agent, which will implicitly call systemd if available) and the
datadog-agent.service systemd descriptor has been added as part of the
package (so that omnibus puts it in the .deb packages).
This service declaration is basically pluging supervisord into systemd,
nothing more (as shown here
https://gist.github.com/tonyseek/ddc7e3a89f0d78e685d6 for instance)
The supervisord start call has been ut in a separate script.
It allows us to have access to the PATH (/bin/sh is called to run the
script) while keeping a one-level forking scheme thanks to exec (/bin/sh
gets replaced by supervisord that will then fork and launch the
different components of our agent. Being a direct child of systemd, the
forked processes are too).
> [systemd] Package updated to be systemd compliant

- checks.d/docker.py
Fix a bug when a Docker container has no name.
That's uncommon (since usually Docker assign at least a random name), but that's possible.
> Fix docker check when a container has no name

- checks.d/postgres.py
When polling an RDS instance the rdsadmin database should be ignored. This is an internal database used for RDS and it's not accessible to normal users and probably doesn't have any interesting information for anyone but Amazon.
This is what happens when `rdsadmin` is not ignored:
```
2015-05-02 01:08:48 UTC | WARNING | dd.collector | checks.postgres(postgres.py:419) | Not all metrics may be available: ('ERROR', '42501', 'permission denied for database rdsadmin')
2015-05-02 01:08:48 UTC | WARNING | dd.collector | checks.postgres(postgres.py:419) | Not all metrics may be available: ('ERROR', '25P02', 'current transaction is aborted, commands ignored until end of transaction block')
```
Works fine after this patch. Should not affect anyone that isn't using a table with this name for their …
> ignore rdsadmin database in postgres check to avoid permission error

- packaging/datadog-agent/osx/com.datadoghq.Agent.plist.example
- packaging/datadog-agent/source/agent
- packaging/datadog-agent/source/info
- packaging/datadog-agent/source/setup_agent.sh
- packaging/datadog-agent/source/supervisor.conf
- utils/flare.py
Previsouly logging was done using supervisor & stdout, totally different
from the package logging. There are options in the configuration to
change the log location, so let's use them instead of doing this trick!
In order to do this, this changes were made:
* remove supervisor processes logging (except `supervisor` itself)
* add a step to configure log location in the source install script
In order to clean weird conf location & others:
* move `supervisor.conf` from `supervisord/` to `agent/` with
`datadog.conf`
* update `bin/agent` to reflect this change
* remove `bin/info` as it is handled in `bin/agent` now (was probably
still here for _legacy_ reasons)
* put launchd logs in the same directory as other logs (`logs/`)
* update the source install script to reflect this change
And to fix …
> [source] log properly (package style) & cleanup

- checks.d/kafka_consumer.py
- conf.d/kafka_consumer.yaml.example
Because the default timeouts are pretty high in the kafka-python and
kazoo library (resp. 120s and 10s), we put them at a much lower
threshold (5s) for the default cases and offer a way to override in the
YAML init_config section.
Fixes #1589.
> [kafka_consumer] add timeout for zk/kafka connections

- ci/common.rb
- ci/elasticsearch.rb
- ci/supervisord.rb
Because when Travis is slow, we get a lot of false negative because the
program takes too much time to start.
For the same reason:
* increase timeout for elasticsearch to 15s
* sleep for 1s after the Wait for supervisor
> [ci] increase default wait timeout to 10s

- checks/collector.py
- config.py
- jmxfetch.py
- tests/core/test_common.py
The agent now sends one "dd_check:appname" tag to dogweb for each
running check (including the JMX checks) if the user enables the
create_dd_check_tags option. This enables slice/dice by app in the
backend. The apptags are sent at regular intervals (every ten minutes by
default)
The running JMX apps list is retrieved from the {tmp}/jmx_status.yaml
file. Indeed, these tags have to be sent from the collectors side, along
with host-tags and this file happens to be the only communication
channel between JMXFetch.jar and the agent.
A test had been added to our test suite specifically for this new
feature (checking that the apptag is sent).
> [apptags] Added apptag support to dd-agent

- checks/collector.py
From now on, everything gohai prints on its stderr (that is to say the
logs) is written to the collector.log file. It makes it easier for us to
pinpoint gohai related errors such as the "No IPV6" bug we just found.
> [gohai] Writing gohai errors to collector's log

- agent.py
**Bugfix** :bug:
`jmx` commands print a false warning, when it just ran fine.
Command outputs were ending with
```
Couldn't find any valid JMX configuration in your conf.d directory: /etc/dd-agent/conf.d
Have you enabled any JMX check ?
If you think it's not normal please get in touch with Datadog Support
```
> [jmx] fix `jmx` commands false warning :bug:

- checks.d/mesos.py
`AgentCheck.service_check` expect a string message. Otherwise it breaks the
emitter `json.dumps()`.
> [mesos] cast error message to string

- checks/__init__.py
As it might break the emitter if the message is not a string.
We cannot enforce a good use of service_checks in custom checks (and
also sometimes in our own checks,
see a874802ed52b0bdecc2340d5844795eff7c7d956)
> [core] cast service_checks message to string

- checks.d/ntp.py
- checks/check_status.py
- tests/core/test_common.py
- utils/ntp.py
Using directly pool.ntp.org is not recommended and must be avoided.
We set up our own vendor pool zone and we have the following hostnames:
```
0.datadog.pool.ntp.org
1.datadog.pool.ntp.org
2.datadog.pool.ntp.org
3.datadog.pool.ntp.org
```
> [Core+NTP] Use data dog ntp pool

- checks.d/sqlserver.py
SQL fractional values represent ratios: it should be casted as `float` (rather than `int`) otherwise information is lost behind a rounded `0` int.
Default metrics impacted:
* `Buffer cache hit ratio` aka `sqlserver.buffer.cache_hit_ratio`
More information:
http://blogs.msdn.com/b/psssql/archive/2013/09/23/interpreting-the-counter-values-from-sys-dm-os-performance-counters.aspx
cc @simnyc
> send fraction metrics as floats + cleaning

- checks.d/elastic.py
- tests/checks/integration/test_elastic.py
Adding new elasticsearch metrics
> [elasticsearch] Get information about `pending_tasks`

- tox.ini
As some of them can be named *.py and thus fail flake8.
> [flake8] ignore git files

- checks.d/wmi_check.py
As it could return an integer, for instance
```yaml
init_config:
instances:
- class: Win32_PerfFormattedData_PerfProc_Process
metrics:
- ...
filters:
- Name: appname
tag_by: IDProcess
```
cc @simnyc
> [wmi] cast `tag_by` value as a string

- checks.d/process.py
- conf.d/process.yaml.example
- tests/checks/integration/test_process.py
Refactor a bit this check, two noticeable changes:
1. on Windows especially, we get randomly some `AccessDenied` exceptions
when trying to look at some processes. Because we iterate on all the
processes at every run, it would trigger as many failures *every run*.
Once we get this error and `ignore_denied_access` is set to true, we'll
not look at it again until DEFAULT_AD_CACHE_DURATION or
`access_denied_cache_duration` in the init config.
2. instead of doing some sketchy try/catch over the code, all the
psutil-related code that actually gets metric values is wrapped into
`psutil_wrapper` which knows how to handle exceptions and known
failures.
Last remark: before we were setting some metrics to 0 even if we had no
values parsed, this is not the case anymore.
> [process] prettify & cache AccessDenied failures

- checks.d/sqlserver.py
- conf.d/sqlserver.yaml.example
Set a timeout for each SQL command (by default 5 sec), to fix #1247 .
> [sqlserver] add command timeout, 5sec default

- checks.d/disk.py
- checks/collector.py
- checks/system/unix.py
- checks/system/win32.py
- conf.d/disk.yaml.default
- config.py
- tests/checks/common.py
- tests/checks/fixtures/disk/debian-df-Tk
- tests/checks/fixtures/disk/freebsd-df-Tk
- tests/checks/integration/test_disk.py
- tests/checks/integration/test_pgbouncer.py
- tests/checks/mock/test_disk.py
- tests/checks/mock/test_sysstat.py
- utils/subprocess_output.py
This commit is the first step towards the annihilation of the old `Check`
hidden in `checks/system/{unix,win32}.py`!
It's time to launch the final assault of `Check`. `AgentCheck` shall triumph!
Add a `checks.d/disk.py` checks, which uses psutil when available to get
disk metrics (same than the previous `disk` checks), and otherwise
get the same metrics with `df`.
It has a small integration test, just to check that metrics exist, and
more precise mock tests.
This new check is enabled by default, and the old `disk` checks are
deleted.
Fix https://github.com/DataDog/dd-agent/issues/568
> [disk] AgentCheck for Disk metrics :tada:

- checks.d/sqlserver.py
We saw memory leak issues with that check. It could have been caused by
two different things:
* The fact that we are not closing cursors properly, and therefore not
freeing properly the recordsets loaded in them
* We instantiated wrongly two different cursors in the main check loop
letting one leak...
> [sqlserver] properly close cursor, avoid leaks

- checks.d/postgres.py
> [postgres] fix log 'truncating' custom metrics query

- ci/postgres.rb
Otherwise this causes psql to fail when we load data.
> [postgres/ci] delay PG init in CI

- checks.d/http_check.py
- conf.d/http_check.yaml.example
PyYaml was returning an int for the expected status code when
"http_response_status_code: 200" (for instance) was used in the yaml
config while a Regex (and therefore an string) is expected. I added a
cast to avoid that from happening again. I also added some doc to tell 
our customers about the possibility to use a Regex for this parameter.
> [http_check] Fix status type err. in service check

- checks.d/varnish.py
- tests/checks/integration/test_varnish.py
The tags were just not passed at all in that case.
Also assert the tags in the CI, to avoid that kind of problems.
> [varnish] allow tags in varnish 3 xml style parsing

- packaging/datadog-agent/source/install_agent.sh
Our one-line install script wasn't compatible with Python3... we're
executing a single line of Python there and it contains an old-style
print which was making the install script crash. I just switched to the
new print/format syntax which should be compatible with any version of
Python.
> [packaging] Fix install-script to work w/ python3

- jmxfetch.py
Remove a potential JMX status Python file left from a previous run before starting JMXFetch.
> [jmxfetch] clean jmx status python file

- checks.d/sqlserver.py
SQLServer check hangs the collector when a connection is failing.
Default timeout is set to 30s, but it is raised multiple times for the same instance: after 120s, collector is restarted by the watchdog and loops back.
Solution: cache failing connections.
> [sqlserver] fix collector hangs when a connection is failing

- jmxfetch.py
- win32/agent.py
Order JMXFetch to exit, communicating through a file. Windows only.
Requires https://github.com/DataDog/jmxfetch/pull/58
Alternative: https://github.com/DataDog/dd-agent/pull/1639
> [jmxfetch][windows] write to file to exit JMXFetch

- checks/datadog.py
- tests/core/test_datadog.py
Rebase of  #1550 to fix merge conflicts.
Extend filename globbing support to all dogstream configurations.
Thanks a lot @gtaylor !
> [dogstream] filename globing support

- checks.d/elastic.py
- checks.d/mysql.py
- checks.d/postgres.py
- checks.d/redisdb.py
- checks/__init__.py
- checks/check_status.py
- checks/collector.py
- ddagent.py
- emitter.py
- tests/checks/common.py
- tests/checks/integration/test_elastic.py
- tests/checks/integration/test_mysql.py
- tests/checks/integration/test_postgres.py
- tests/checks/integration/test_redisdb.py
- tests/core/test_common.py
- tests/core/test_metadata.py
- tests/core/test_payload.py
- tests/core/test_transaction.py
`AgentCheck.service_metadata(metadata_name, value)` replaces `AgentCheck.svc_metadata(metadata_dict)` method.
Under the hood, metadata are stored in a list, and rolled-up to a dictionnary for every instance.
Usage:
```
self.service_metadata('foo', "bar")
```
Following methods were added to `AgentCheck` interface to support service metadata collection:
```python
self.service_metadata(name, value) # Check purpose - Send metadata
self.get_service_metadata() # Collector purpose - Return a list of metadata dictionaries saved by check -if any-
```
To send metadata from an Agent Check, decorate it with `self.svc_metadata(...)` statements.
```python
def	check(...)
...
self.service_metadata('foo', "bar")
...
```
Collector payload was re-factored behind `AgentPayload` interface: it offers the same …
> [core] service metadata collection

- checks.d/disk.py
- tests/checks/mock/test_disk.py
When `device_blacklist_re` or `excluded_disk_re` were empty (let's say in
datadog.conf `device_blacklist_re: `), the disk check was failing, because all
disks were excluded.
This is fixed.
> [disk] fix empty device regex exclusion issue

- checks/__init__.py
- tests/checks/common.py
- utils/debug.py
PR #1571 introduced a bad regression: 'run_check' method was deleted
beside it is still used on Windows to debug.
> [core][windows] restore 'run_check' from 'checks'

- jmxfetch.py
When JMXFetch is disabled, its status file was still persisting and leads to a wrong `info` command output.
Remove this file at start in addition to the Python status file.
> [jmxfetch] remove 'jmx_status' yaml

- win32/agent.py
JMXFetch can take up to 15seconds to stop. If we don't wait JMXFetch to
stop and restart the agent, the 'exit_file' might be deleted before
JMXFetch has time to catch it.
This might also fix 'restart' warnings at installation upgrades.
> [jmxfetch][windows] wait JMXFetch exit to exit

- ci/elasticsearch.rb
- tests/checks/integration/test_elastic.py
Features:
* defaults to newest 1.6.0 version for CI
* use `--path.data` to override the data directory of ES, this way all
data is stored in `$VOLATILE_DIR` and we don't have to worry about it
when caching
* create a dummy index "datadog" in the `before_script` stage, this
makes the node "yellow" because by default an index asks for one
replica to be set up
* new testcase where we change the `number_of_replicas` parameter in ES
directly and make sure the state transitions from yellow to green for
the created events and service checks. Also assert the tags.
> [elastic] fixes to the CI. Proper tests of health

- checks.d/mesos_master.py
The option can be unset and no `cluster` key is returned from the
state.json endpoint.
> [mesos] do not fail if no cluster name is set

- packaging/centos/datadog-agent.init
It was hidden, it's now fixed.
Removed unused `$PIDFILE`.
> [packaging] fix CentOS bad path to supervisor pid

- CHANGELOG.md
- checks/check_status.py
- checks/collector.py
- config.py
- jmxfetch.py
- utils/jmxfiles.py
- win32/agent.py
Use '/run' for JMXFetch status & exit files instead of '/tmp/'. Move more functions to '/utils'.
> [jmxfetch] move status & exit files to '/run'

- tests/core/test_run_files.py
Add a test that checks the logic of `AgentStatus._get_pickle_path` to ensure that the `.pickle` file gets written to an internal folder
> [tests] add mocked tests for internal /run folder

- conf.d/kafka.yaml.example
Fixing indentation issue in the kafka.yaml.example file regarding kafka.net.bytes.
> Fixing indentation issue on alias kafka.net.bytes_out

- CHANGELOG.md
- checks.d/disk.py
- conf.d/disk.yaml.default
- tests/checks/mock/test_disk.py
Otherwise a lot of useless/temp partitions appear.
See https://github.com/giampaolo/psutil/blob/58711c2db81d437fdcf5b8aedf68bfd00fc089fd/psutil/_pslinux.py#L651-L653
> [disk] disable all_partitions by default

- checks.d/disk.py
- conf.d/disk.yaml.default
- tests/checks/mock/test_disk.py
The new disk check was ignoring by default tmpfs disks and some others,
breaking compatibility with the old check.
It is fixed by filtering on device name (exclusion on '' and 'none') and total
disk usage (!= 0), and setting all_partitions to True for psutil.
The new all_partitions option will send metrics from the non excluded disks
with 0 total disk usage.
> [disk] backward compatibility with old Disk check

- checks.d/etcd.py
The '/stats/leader' endpoint is only available on the leader etcd host.
On the followers, it returns a 403: it is illegitimately logged as an
exception in the agent and triggers a CRITICAL service check.
Fix #1707
> [etcd] ignore /stats/leader endpoint on followers

- checks.d/docker.py
This tag is the same as the `image` one without the tag at the end (eg. `ubuntu` instead of `ubuntu:latest`).
> [Docker] Add an image_repository tag to the docker check

- checks.d/docker.py
Some versions of the Docker `/events` API have juxtaposed JSON dictionaries in the response. We had some logic to handle the basic case, but we did not have any to account for newlines between juxtaposed dictionaries. The latter causes our parsing to break. This accounts for that by getting rid off any newlines in the response.
> [docker] strip newlines from API responses

- ci/apache.rb
- tests/core/test_common.py
- `test_min_collection_interval` in `core/test_common.py`: use `disk` check
instead of `ntp` (no network call)
- `apache`: increase timeout before start
> [ci] fix two (often) false-negative tests

- utils/pidfile.py
It was previously a relative path, it's clearer this way.
> [core] use real path for PidFile

- checks.d/rabbitmq.py
- tests/checks/integration/test_rabbitmq.py
When running a RabbitMQ cluster, the "partitions" attribute in the response of /api/nodes indicates if the cluster is in a split brain situation:
```
...
"partitions": []
...
```
The length of this array is collected as the metric "rabbitmq.node.partitions"
> Collect the number of rabbitmq partitions per node

- agent.py
- checks/check_status.py
- checks/collector.py
- jmxfetch.py
- utils/flare.py
- utils/jmx.py
- win32/agent.py
- win32/gui.py
Adds in a `jmxinfo` directory:
- 2 JMXFetch status files: `jmx_status.yaml` and `jmx_status_python.yaml`
- JMXfetch commands output: `list_matching_attributes` and `list_everything`
- `java -version` output (using the configured java path) in a `java_version.log` file
@remh One thing that may not work properly in flare is the change I've made here https://github.com/DataDog/dd-agent/compare/olivielpeau/jmx-flare?expand=1#diff-64a477c26f008c29252aad6c1499c099R271 , which basically leaves file descriptors open (`close_fds=False`) when the JMXFetch subprocess is launched from the flare command. Do you know what issues can happen when the main process leaves the file descriptors open ?
cc @degemer @yannmh
> [flare] Add JMXFetch-specific info

- checks.d/docker.py
When Docker Remote API `/events` returns invalid JSON, just default to an empty list
> [docker] catch error when parsing json response

- .travis.yml
- tests/checks/integration/test_elastic.py
- tests/checks/integration/test_http_check.py
- tests/checks/integration/test_lighttpd.py
- tests/checks/mock/test_disk.py
In order to do this:
- `elastic`: add tests for new metrics from
https://github.com/DataDog/dd-agent/pull/1507
- `http_check`: add a missing service check test (`http.can_connect` is also
collected when testing `http.ssl_cert`)
- `disk`: 100% coverage for the 5.4.2 check (full compatibility with old check)
- `lighttpd`: add two missing metrics for 100% coverage
Waiting on https://github.com/DataDog/dd-agent/pull/1730 for the coverage metadata fix.
> [ci] enable coverage tests :tada:

- datadog.conf.example
It still works right now, but is deprecated.
> [doc] deprecate old disk option in example conf

- checks.d/http_check.py
- conf.d/http_check.yaml.example
- tests/checks/integration/test_http_check.py
- tests/core/test_service_checks.py
Improves a few things:
- custom CA certificates are used in the `http.can_connect` check (in addition to the `http.ssl_cert` check)
- instance-level CA certificate files can be defined
- fixes flaky test
> [http_check] Improve SSL cert configuration & validation

- packaging/datadog-agent/source/install_agent.sh
Tested on CentOS 5 and Ubuntu 12 (needs to be run on dd-agent-testing).
> [packaging] do not fail if non-datadog repos are in a bad state

- checks.d/etcd.py
- conf.d/etcd.yaml.example
- tests/checks/integration/test_etcd.py
Supersedes #1654.
Based on @KnownSubset's work, with a few additional changes:
- remove the `ssl` parameter (using SSL or not depends on the url scheme)
- split `ssl_cert_reqs` in 2 parameters
- reformat the example config file
> [etcd] Add full SSL support

- checks.d/elastic.py
- conf.d/elastic.yaml.example
- tests/checks/integration/test_elastic.py
Add shard level metrics to Elasticsearch integration (Careful: branch has been created on top of etienne/es-pshard-metrics)
> Es shard level metrics

- checks.d/supervisord.py
- ci/resources/supervisord/supervisord.yaml
- ci/supervisord.rb
- conf.d/supervisord.yaml.example
- tests/checks/integration/test_supervisord.py
- tests/checks/mock/test_supervisord.py
From @ckrough:
Adds the ability to select processes to monitor by regex name match.
- Check will monitor processes whose names match the list of regex patterns provided in 'proc_regex'
- Check will monitor processes whose names exactly match the strings provided in 'proc_names'
- All processes matching proc_names OR proc_regex filters are monitored.
- All processes are monitored when no proc_names or proc_regex filters are defined.
- Sample configuration provides proc_regex examples
My two cents:
- Rebased on dd-agent 5.4 to solve conflicts. 
- Upgrade integration tests to use AgentCheckTest. Assess full coverage.
Original PR #1375. Thanks a lot @ckrough !
> [supervisord] selct processes by regexp name match

- checks.d/http_check.py
This fixes a bug reported by a customer where the service check wasn't set to DOWN since the exception was caught by the last, general except.
> [checks] Handle requests raised timeouts in http_check

- util.py
Thanks to @dspangen for the initial fix.
I've also added the trailing slash to the `public-keys` endpoint as it might break in the same way in the future.
> [ec2] Add trailing slash to metadata lists endpoints

- checks.d/disk.py
As it turns out psutil is actually UNDER counting disk.in_use because it is INCLUDING reserved space.
The solution, to bring this back to what df shows, is to calculate the disk usage ourselves by doing ( disk.used / (disk.used + disk.free) ), which will completely ignore the root space.
I separated 'system.disk.used' and 'system.disk.free' into different variables for readability.
Further Proof:
The calculation by psutil of disk.total is (disk.free + disk.used + <root_reserved_space>). You can prove that disk.total is including root space by adding disk.free + disk.used. The number you'll come up with is exactly <root_reserved_space> less than disk.total.
The calculation by psutil of disk.in_use is ( disk.used / disk.total ), pushing the percentage down because the disk.total includes …
> Recalculate disk.in_use to make consistent with df's Use% metric

- checks.d/redisdb.py
On AWS Elasticache, Redis config command is disabled by default. We only use it
to get the max_slow_entries (and we have a default), so now it tries to get it
from the config and catch potential errors, defaulting to
DEFAULT_MAX_SLOW_ENTRIES.
> [redis] handle exception when CONFIG disabled

- checks.d/disk.py
Currently, for our manual checks, we are just grabbing the percentage for disk in_use from the output of df. This produces a percentage with no decimal precision. To improve this precision, let's calculate the disk in_use metric ourselves based on the free and used values supplied by df. This calculation is consistent with how df calculates disk usage, but isn't rounded up.
Calculation: <disk_used> / (<disk_used> + <disk_free>)
Further Proof:
We don't calculate in_use as (<disk_used> / <disk_total>), because <disk_total> includes reserved space that is inaccessable by the user. Calculating this way would produce a misleading value that is of a lower percentage than what df shows.
> Rather than grabbing in_use from df, calculate for precision

- requirements.txt
Apparently `0.3.2` has disappeared from PyPi . 
cc @elafarge
> [deps] bump ntplib version

- checks.d/fail2ban.py
- conf.d/fail2ban.yaml.example
- tests/checks/mock/test_fail2ban.py
Add a fail2ban check, which reports stats from `fail2ban-client status <jail>`
> Fail2ban check

- checks.d/mysql.py
- ci/mysql.rb
- conf.d/mysql.yaml.example
- tests/checks/integration/test_mysql.py
Rebase of #1274 with additional logging and testing
> Add Custom MySQL query metrics

- checks/collector.py
- config.py
- datadog.conf.example
- util.py
fixes #1736 
- update the hostname to `host_metadata['instance']['hostname']` so it's unique
- drop some tags that we don't want to collect
- add `"instance_name.project_id"` as a host alias
> [GCE] Update hostname to be unique

- checks.d/consul.py
- conf.d/consul.yaml.example
- tests/checks/mock/test_consul.py
Adds a consul AgentCheck with the following metrics:
Number of Consul Agents in the Cluter
`consul.peers`: tagged by `consul_datacenter` and `mode` (`leader | follower`) 
Consul Catalog Nodes Up by Service
`consul.catalog.nodes_up`: tagged by `consul_datacenter` and `consul_service_id`
Consul Catalog Services Up by Node
`consul.catalog.services_up`: tagged by `consul_datacenter` and `consul_node_id`
This check also sends `consul.new_leader` events when a leader change is detected.
> [consul] add consul catalog check

- daemon.py
- tests/test_utils_process.py
- utils/process.py
The `Daemon` class got an additional dependency with `psutil` with this commit 21ba11a, which broke the source install.
The problem is that the core of the agent now depends on psutil, which is not installed in the install from source (because psutil needs a lot of stuff to be built). This fixes the issue by removing this hard dependency.
Cherry-picked 2 commits from https://github.com/DataDog/dd-agent/pull/1504 so that the source install can be fixed for the 5.5 release.
> Remove psutil dependency in the agent core

- checks.d/http_check.py
Per customer request:
> The `content_match` text is not picked out of the body of the email, so it’s not clear.
[Related card](https://trello.com/c/4TXcnGc8/314-copy-update-for-http-tcp-check-message)
> [http_check] Add quote to http copy for clarity

- conf.d/rabbitmq.yaml.example
- Make it clearer that the vhost parameter only applies to service checks
- Mention how to pull metrics from queues on specific vhosts
- Update to new doc format
> [rabbitmq] Update yaml config example

- CHANGELOG.md
- packaging/datadog-agent/source/setup_agent.sh
**Source Install only**
https://github.com/DataDog/dd-agent/compare/5.4.3...5.4.4
* [BUGFIX] Update `ntplib` to 0.3.3 to fix the source install. See [#1792][]
[#1792]: https://github.com/DataDog/dd-agent/issues/1792
> [packaging] source install 5.4.4

- checks.d/wmi_check.py
Discovered that when wmi_check.py is run, that depending upon the yaml configuration, it can end up pulling attributes that have a value of None, which will throw a TypeError complaining that float() cannot coerce something that is not a string nor an integer. Specifically, this issue came to light with a config that setup grabbing metrics for the `FreeSpace` and `Size` properties from the `Win32_LogicalDisk` class. This runs for all disks, including CD-ROMs, which will report nothing for either property.
The fix is to check tht the attribute retrieved by wmi_property is not None before attempting to coerce to a float.
I'll not for the record as well, in regard to the specific situation that this turned up in, that we are already collecting disk usage statistics in `checks.d/disk.py`, and …
> Checking that attribute retreived by wmi_property is not None

- checks.d/mesos.py
This generic Mesosphere check is deprecated not actively developed
anymore. It will be removed in a future version of the Datadog Agent.
Please head over to the Mesosphere master and slave specific checks.
> [mesos] `mesos` → `mesos_master` + `mesos_slave`

- checks.d/windows_service.py
Windows Service check lacks of logs, thus, it is quite difficult to
troubleshoot.
Adding `debug` level logs to fix that.
> [windows_service] add debug logs

- checks.d/rabbitmq.py
Fixing issue #1819
where exception `ValueError: list.remove(x): x not in list` is raised
any time there is a queue with an absolute name (format `vhost/queue_name`)
in the rabbitmq.yaml
> [RabbitMQ] Fix variable for absolute queue name situations

- checks.d/disk.py
- tests/checks/mock/test_disk.py
Currently the agent disk check is including the monitoring of mounted cd-rom images. This isn't good as these are read-only and already have 100% usage. This is a threat for triggers false positives.
Solution is to forcibly exclude CDROM (iso9660) filesystems from the disk check.
> Force exclusion of CDROM (iso9660) from disk check

- checks.d/mongo.py
- conf.d/mongo.yaml.example
We have one MongoDB instance that's misbehaving. It's a bit slow to connect to it because of the problems it's having and so it's difficult to tell what's wrong because we're not getting any metrics from it.
> [mongo] make timeout configurable and increase the default

- checks.d/mongo.py
Also added notes that references the deprecated metrics in latest update.
List of metrics now matches the return of db.serverStatus() found here:
http://docs.mongodb.org/manual/reference/command/serverStatus/
> [mongo] Updated metric list to match V 3.0

- checks.d/mysql.py
this helps avoid aborted connection warnings in the mysql log.
> [mysql] close connection when complete

- checks.d/snmp.py
SNMP check lacks of logs, thus, it is quite difficult to troubleshoot.
Adding debug level logs to fix that.
> [snmp] add debug level logs

- checks.d/wmi_check.py
Sinces #1800, `val` variable is unreferenced when WMI metric is null.
Thus, an exception is raised when we try to submit it to Datadog.
Ignore null values, and continue, so it does not raise.
> [wmi] do not raise on null values

- checks.d/couch.py
- ci/couchdb.rb
- conf.d/couch.yaml.example
- tests/checks/integration/test_couch.py
- fail gracefully when one or more individual dbs are not readable by the configured user.
- allow blacklisting of specific databases via db_blacklist in couch.yaml
- append to blacklist at run time if unable to query a given db's stats
> [couchdb] Improve error handling and add Blacklist support.

- checks.d/mesos_master.py
On a non leader node, this is the error one of our customer got:
instance #0 [ERROR]: "'MesosMaster' object has no attribute 'leader'"
This commit should fix this issue.
> [mesos_master] Fix error on non leader nodes

- checks.d/mesos_slave.py
If the cluster doesn't have a name the check shouldn't fail.
> [mesos_slave] Do not fail if no cluster name

- packaging/osx/install.sh
We use to display a prompt when asking for a sudo password which turns
out to be useful if the user's sudo password is cached because recently
used in the same terminal... that's really confusing and in addition, it
leads customers to type their password in clear on a terminal, which
isn't really cool.
This has been removed and we now rely on the system prompt only when the
sudo password is needed :)
We keep on notifying the user he MAY be asked for his sudo password
since OSX just shows `password`, it made sense to precise that it
actually means the SUDO password and not the one on Datadog or whatever.
[skip ci]
> [osx][install_script] Remove confusing sudo prompt

- jmxfetch.py
Replaces #1850 , which was very "hacky".
The collector logs were being duplicated to `jmxfetch.log` because `agent.py` imports `jmxfetch.py`, which causes the `initialize_logging` method to be called twice.
This fixes the issue by only initializing logging in `jmxfetch.py` when it's the main module (and not imported from another module).
> [logging] Fix logs duplication in jmxfetch.log

- checks.d/wmi_check.py
Fix regression with #1800, as 0s were not reported anymore.
Log a warning when the specified WMI property does not exist among the
class, or when the value extracted is not a digit.
Keep the crawler running.
> [wmi] report zeroes :bug:

- checks.d/snmp.py
Fix SNMP check infinite loop when SNMP command returns an
`error_status`. Update `first_oid` reference before `continue`
statements are called.
> [snmp] do not infinite loop on `error_status`

- checks.d/elastic.py
- tests/checks/integration/test_elastic.py
The metrics `heap_used_percent` and `heap_max_in_bytes` have been added
to the elasticsearch integration following up a customer request.
> [elastic] Added common JVM metrics

- CHANGELOG.md
Fail2ban is postponed to 5.6.0 agent release. Remove it from the 5.5.0
CHANGELOG.
[skip ci]
> [changelog] remove Fail2ban :pencil2:

- checks.d/btrfs.py
In other datadog stats (eg. `system.fs.inodes.in_use`, `system.disk.in_use`), 0 means no usage, and 1 means full usage.
This change makes `btrfs.disk.btrfs.usage` report values in the same way: 1 = 100% usage.
> [btrfs] track usage based on used bytes instead of free bytes

- win32/gui.py
The check is working agian since 5.4.0 but it was never re-enabled in
the GUI. Here's the commit that does it :)
> [process] Re-enable check on Windows

- conf.d/directory.yaml.example
The pattern is matched against the files' absolute paths, which was not clearly stated in the docs.
> [directory] Clarify doc on `pattern` config parameter

- checks/collector.py
- utils/debug.py
* Create a decorator that catches any exceptions thrown by the decorated
function and logs them along with a traceback.
* Use it with `Collector.run` method to help troubleshooting.
* Avoid code duplication between Windows and other environments.
> [core] log collector runs's exceptions

- checks/__init__.py
- checks/collector.py
Move Datadog agent developer mode stats logs from `info` to `debug` log level.
Refactor Windows & Unix code paths.
> [dev] stats log level `info`→`debug` & refactoring

- checks.d/pgbouncer.py
Previously it was assuming that python dicts are ordered which is not
the case. So collected metrics were wrong.
We can’t use python OrderedDict as it was only introduced in python 2.7
and we want to support python 2.6
So here is an implementation using lists instead.
> [pgbouncer] Fix check

- win32/gui.py
When the GUI is started:
- It checks for a Pidfile left by a previously running (and potentially still running) GUI
- If such a Pidfile was found and if the Pid inside is file is indeed the Pid of a running instance of `agent-manager.exe`, then let's kill that old process
- Let's write the Pid of the current process to that pidfile
Nothing else was changed :)
> [Windows] Have a single instance of Agent Manager

- checks.d/process.py
- conf.d/process.yaml.example
- tests/checks/integration/test_process.py
See https://github.com/DataDog/dd-agent/issues/1660
Improvements:
- Non-blocking call to `cpu_percent` after the first sample
- After the first sample, retrieves an averaged value since the last call (instead of an averaged value over the fraction of a second defined by `cpu_check_interval`)
The first sample of `cpu.pct` on every process still uses a blocking call so that the check can retrieve a value as soon as it finds new processes. Setting the `cpu_check_interval` to `0` removes that first blocking call.
Also fixed the handling of the cache of AccessDenied PIDs (it was previously refreshed at every run of every instance).
> [process] Improve sampling of cpu.pct

- checks.d/openstack.py
- conf.d/openstack.yaml.example
Hi @talwai, I was talking with @2bethere and @irabinovitch about using the OpenStack integration here at Lithium. I needed to make a few changes to your script in order to get it to work. Here's a PR that will merge my changes into your branch. I'm not sure if that's something you want or not so feel free to reject it. I just wanted to share up my changes. This branch is based on PR #1864 
In addition to the policy changes listed https://gist.github.com/talwai/7445f16c2584b8caffe2 I also modified `compute_extension:v3:os-hypervisors`, `compute_extension:v3:os-server-diagnostics`, `compute_extension:availability_zone:detail`, `compute_extension:v3:os-availability-zone:detail`.
Key changes:
- Can, assuming permissions allow, dynamically get the list of hypervisors and networks to monitor
- …
> OpenStack integration

- checks.d/nginx.py
Use JSON parser to extract Nginx metrics when `content_type` *starts
with* (rather than *equals*) `application/json`.
Also add DEBUG level logs to help troubleshooting.
Thanks @tmichelet for investigating.
> [nginx] Fix 'json' content_type support :bug:

- checks.d/network.py
- tests/checks/fixtures/network/netstat
- tests/checks/fixtures/network/ss_ipv4
- tests/checks/fixtures/network/ss_ipv6
- tests/checks/mock/test_network.py
`netstat` is deprecated on many distributions, `ss` is its replacement and is present by default in the `PATH` on most of the distributions that I've tested (CentOS >= 6, Ubuntu >= 12.04, but not on CentOS 5).
We still fallback to `netstat` if `ss` is not installed.
Addresses https://github.com/DataDog/dd-agent/issues/1156
I've also checked that `subprocess.Popen` doesn't hang with `stdout=PIPE`: as long as we use it with `communicate()` (which we do here) we should be fine.
> [network] Use `ss` instead of `netstat` on linux

- checks.d/haproxy.py
- tests/checks/integration/test_haproxy.py
The count_per_status currently counts both backends and frontends. An
important query is how many backends are available or unavailable
disregarding the big set of tags, which causes the typeaheads in the
datadog ui to never load.
In order to achieve this, a new counter 'haproxy.backend_hosts' is added.
It has two tags: service and available. The latter is either true or
false.
> [haproxy] Count available/unavailable backends

- conf.d/process.yaml.example
PR #1928 improved the sampling of `cpu.pct` but its value
is not accurate for short-lived processes (it was even less
accurate before that PR but it's still worth mentioning).
> [process][doc] Add comment on cpu.pct for short-lived processes

- checks.d/consul.py
At the moment, the consul check will only send the status of the last
service check in `/api/health/state/any`.
This pull request will send the status of all the service checks it can
find.
> [consul] Send more than the last service check

- checks/system/unix.py
On large SunOS systems, the kstat population is often quite large.  Using `kstat -c <class>` requires a full scan of the metric list and can be slow/expensive.  Filtering by `module` allows kstat consumers to use the kstat index (which includes `module`, `name` and `instance`, but not `class`). Using this filter strategy for the `zone_memory_cap` check results in a speedup of 1-2 orders of magnitude.
> [system] Filter SunOS memory_cap kstats by module

- packaging/centos/datadog-agent.init
- packaging/debian/datadog-agent.init
- packaging/debian/datadog-agent.service
- packaging/debian/start_agent.sh
- packaging/supervisor.conf
We don't need to run supervisor as root anymore.
Tested on:
Will launch a `dd-agent-testing` on them.
> [core] run supervisor as dd-agent

- checks.d/mongo.py
This fix attempts to address what is described here: https://github.com/DataDog/dd-agent/issues/1855
Two main things have been done:
- We now collect mongodb dbstats for each DB running on the cluster/host and return them with an associated tag cluster:db:foo where foo would be the database name.
- We now also correctly deal with replica sets. While getting the integration tests to work I found an issue with the way we were attempting to collect replica set stats. These commands can only be made against the 'admin' db (which always exists I believe), so we now issue replicaset commands against it. 
Also, since pymongo.Connection is deprecated, I changed this over to use MongoClient which is the preferred way to do so. Finally, the api_key was causing issues when creating an event when …
> [mongo] Connection DB should be separate from monitored DB(s)

- checks/collector.py
- tests/core/test_config.py
Problem
-------
When running `rake ci:run` we can see `nosetests: error: no such option:
-s` for some specific tests.
It's caused by calls to `get_config` (from config.py) with `parse_args=True`,
which calls `OptionParser`, which tries to parse the `nosetests` command line,
and fails because `dd-agent` doesn't have a `-s` option. (but has a `-A` and
`-v`). Source of the error: https://github.com/DataDog/dd-agent/blob/4907d1178a0eb38558cfa2cc644be769835a7b92/config.py#L88
Solution
--------
One of the concerned tests was directly calling `get_config`, the
`parse_args=False` arg was added.
The others are using a `Collector` which calls `get_hostname` (itself calling
`get_config` with `parse_args=True`) in `_get_hostname_metadata`:
https://github.com/DataDog/dd-agent/blob/4907d1178a0eb38558cfa …
> [tests] remove misleading nosetests error message

- checks.d/network.py
Adds UDP metrics from `/proc/net/snmp` in addition to the existing TCP metrics.
We have some things using UDP and they are having trouble keeping up. Our most reliable indicator of this problem are dropped UDP due to full buffers. This adds that functionality to the agent so that we can see it in charts!
I basically lifted the existing TCP code and made few modifications to have different variables for TCP versus UDP. If you'd prefer this refactored some for lessening code duplication, I'm open to refactoring with guidance.
> Add UDP metrics.

- config.py
- ddagent.py
`use_dd` is deprecated and always set to `True`. Remove it to improve
code readability.
Fix #1856.
> [core] deprecate 'use_dd' flag

- checks.d/http_check.py
- tests/checks/integration/test_http_check.py
With this PR we enable the RSA+RC4+MD5 cipher which is considered weak. We can add further weak ciphers if needed. Disabled by default, the user must specify `weakciphers: true` in their http_check.yaml for this to have any real effect - otherwise weak ciphers are disabled.
Session object has nearly identical request method.
Default value for weakcipher is false.
Adding debug logging for weak ciphers.
Importing datetime differently to urllib3 code.
Added Transport adapter for weak cyphers, requests lib sessions required too.
Session object has nearly identical request method.
Default value for weakcipher is false.
Adding debug logging for weak ciphers.
Importing datetime differently to urllib3 code.
Changing cipherlist for weak ciphers, now it works.
> Enable http_check to function with weak ciphers on SSL/TLS.

- packaging/datadog-agent/source/install_agent.sh
In preparation to serve packages through HTTPS - we need to install `apt-transport-https` so that `apt` can download through HTTPS.
From what I understand, YUM needs no additional packages - this is only for Debian and Ubuntu.
> Install apt-transport-https

- checks.d/network.py
As @olivielpeau [mentioned](https://github.com/DataDog/dd-agent/pull/1974#issuecomment-149275279) on https://github.com/DataDog/dd-agent/pull/1974, some of these can be missing in old Linux versions.
We want to make sure we found them before submitting them.
> [check] [network] Test if UDP metrics exist before trying to report them

- packaging/centos/datadog-agent.init
- packaging/debian/datadog-agent.init
The exit code of the `status` command has to be one of 0, 1, 2, 3, 4,
69 to be correctly understood by Ansible, but was returning `253`
when the agent was not running on linux kernel versions 3.18+
Normalize the exit code to 0 or 1 to avoid the issue.
See https://github.com/ansible/ansible-modules-core/blob/cbbb20b6bf0d82fdc92f064c9e4d18c04f203da6/system/service.py#L590
Fixes #1976
More generally we could try to stick more closely to the [LSB specs](http://refspecs.linuxbase.org/LSB_4.1.0/LSB-Core-generic/LSB-Core-generic/iniscrptact.html) for the exit code of the `status` command.
> [core] Normalize exit code of fallback `status` command

- packaging/datadog-agent/source/install_agent.sh
- packaging/datadog-agent/source/setup_agent.sh
- packaging/osx/install.sh
Unix install scripts now set mode `640` and owner `dd-agent:root` (when applicable) to datadog.conf, as it can contain sensitive data (the api key in particular).
The permissions are set only when the file is not already there.
> [packaging] Tighten permissions on datadog.conf

- checks.d/riak.py
Fix https://github.com/DataDog/dd-agent/issues/1482
Revert https://github.com/DataDog/dd-agent/pull/1527 (backend wasn't able to
deal with custom service checks tags at that time)
> [riak] add custom tags to service checks tags

- checks/collector.py
- checks/system/unix.py
Based on: https://github.com/DataDog/dd-agent/pull/1826 - bringing in @jraede changes and making sure it's only reported if the kernel actually has it in `/proc/meminfo`
> Adding support for MemAvailable

- checks/collector.py
- tests/core/test_transaction.py
- transaction.py
If the server is configured in a local timezone that follows DST, the
forwarder can get stuck if we use .now instead of .utcnow as it will
think that there is already a transaction in progress.
> [core][transaction] Use utcnow instead of now

- CHANGELOG.md
> [changelog] fix `pycurl` dependency issue on win64

- checks.d/sqlserver.py
If we leave database connections open it can cause the SQL Server Agent to hang when attempting to stop.
> [sqlserver] Close database connections

- agent.py
- checks/collector.py
- packaging/centos/datadog-agent.init
- packaging/datadog-agent/source/agent
- packaging/debian/datadog-agent.init
- packaging/osx/datadog-agent
This adds the ability to send a SIGUSR2 signal to the collector and successfully have it reload the `conf.d` integration configs.
Also note, this does not yet work on windows.
> [core] Hot reloading of integration configs

- checks.d/openstack.py
- conf.d/openstack.yaml.example
This PR is a rebased and updated version of @mtougeron's PR #1966 
It also incorporates a few other miscellaneous changes and fixes (apologies to reviewers for shoddy commits)
It adds the following:
- Collection of project-level metrics related to limits and quotas, courtesy @mtougeron
- Caching of host aggregates, which change infrequently, in between check runs. This allows us to query 
for `os-aggregates` only every `CACHE_TTL` seconds, rather than at the standard interval of 15s
- Proper failover of endpoints in the service catalog - we now correctly accept `internal` endpoints for 
Nova and Neutron when `public` endpoints are not present
- **IMPT - a new default** for the metric collection - local-only scoping. This is to handle the tricky case of ensuring that no two agents running …
> [integration] [openstack] Add project limit collection and implement agent scoping

- conf.d/jmx.yaml.example
- jmxfetch.py
Will allow JMXFetch to connect to JMX servers with unusual setups, for instance JBoss applications (which use JMX Remoting instead of the usual RMI protocol) and Tomcat applications that use `JmxRemoteLifecycleListener `.
I'm going to update our docs to specify which JARs to use for these known cases.
> [jmxfetch] Allow adding custom jars to JMXFetch's classpath

- checks.d/mongo.py
- conf.d/mongo.yaml.example
Rebased of #1832 on master, thanks a lot @benmccann !
My two cents: 
Split the metric list in multiple parts:
* `COMMON_METRICS`: default metrics to collect
* `V2_ONLY_METRICS`: metrics available in MongoDB 2.x only
* `TCMALLOC_METRICS`: TCMalloc memory allocator metrics
It's easier to assess the check coverage in our CI, and gives more
control on the level of metric collection.
Create a `collect_tcmalloc_metrics` option (default to False).
> [mongo] add tcmalloc metrics

- checks.d/win32_event_log.py
- conf.d/win32_event_log.yaml.example
Add config option for allowing the user to have events tagged by event_id of the form `event_id:<num>`.
> [win32_event_log] Allow optional tagging by event_id

- tests/core/fixtures/flare/password_uri.yaml
- tests/core/test_flare.py
- utils/flare.py
For lines including passwords in the URI of the form `fooproto://bar_user:somepass@somewhere....` this regex will strip somepass and substitute for asterisks.
> Obfuscates passwords encoded in URI's

- checks.d/disk.py
- checks.d/mysql.py
- checks.d/network.py
- checks.d/postfix.py
- checks.d/varnish.py
- checks/collector.py
- checks/system/unix.py
- config.py
- jmxfetch.py
- resources/processes.py
- tests/checks/mock/test_disk.py
- tests/checks/mock/test_network.py
- util.py
- utils/subprocess_output.py
Issue came up when investigating hostdown issues.
https://datadog.zendesk.com/agent/tickets/30510
It seems as though, periodically, a subprocess call hangs and ultimately causes the watchdog to reset the agent. During this period of time, there is then a host down event, followed by a host recovered event posted to the customers events page. We noticed that it seems as though the hanging happens in various checks (not the same for every host down event). Offending checks have included the customers own custom `iostat` check, as well as our own `postfix` check, and even `resources/processes.py`.
The theory is that this is caused by a hanging call to `subprocess.Popen`. There is a known issue where the use of a `subprocess.PIPE` for stdout (or even stderr) could cause the process to hang …
> [core] Replace subprocess.Popen with safer get_subprocess_output

- checks/datadog.py
Currently dogstream does not print debug logs about events
> [dogstream] Add debug logs

- checks.d/snmp.py
Here is a **5.5.2 candidate**
For an unindentified reason (need more investigation ?), some OIDs do not return when pulled in a batch query. By default, the SNMP AgentCheck attemps to query up to 10 OID at the same time to speed up the crawling runtime. 
```
Running SNMP command nextCmd on OIDS ('1.3.6.1.4.1.39538.3.1.3.1.1.7', '1.3.6.1.4.1.39538.3.1.3.3.1.11') 
Returned vars: [[(ObjectName('1.3.6.1.4.1.39538.3.1.3.1.1.7.0'), Integer(7)), (ObjectName('1.3.6.1.6.3.1.1.6.1.0'), Integer(1694833796))]]
```
*(Note the unrelated '1.3.6.1.6.3.1.1.6.1.0' returned :open_mouth: )*
versus
```
Running SNMP command nextCmd on (CommunityData(communityIndex='s1542604247011267360', communityName=<COMMUNITY>, mpModel=1, contextEngineId=None, contextName='', tag='', securityName='s1542604247011267360'), …
```
> [snmp] customisable `oid_batch_size` batch size

- checks.d/activemq_xml.py
Specifying queue names in config will now correctly limit metrics to
only those queues/topics/subscribers.
If you have lots of queues this is a way to monitor a subset of them.
Also needed if over the 300 max metrics threshold.
> [activemq_xml] limiting queues in config should work

- tests/core/test_transaction.py
Propjoe doesn't support /intake/foo addresses as it's not needed. This is making the test to fail.
> [core] Fix transaction test

- checks.d/wmi_check.py
- checks/libs/wmi/counter_type.py
- checks/libs/wmi/sampler.py
- checks/system/win32.py
- tests/checks/common.py
- tests/checks/fixtures/wmi/win32_perfformatteddata_perfdisk_logicaldisk
- tests/checks/fixtures/wmi/win32_perfformatteddata_perfproc_process
- tests/checks/fixtures/wmi/win32_perfformatteddata_perfproc_process_alt
- tests/checks/fixtures/wmi/win32_perfrawdata_perfos_system_current
- tests/checks/fixtures/wmi/win32_perfrawdata_perfos_system_previous
- tests/checks/fixtures/wmi/win32_perfrawdata_perfos_system_unknown
- tests/checks/fixtures/wmi/win32_process
- tests/checks/mock/test_wmi_check.py
- tests/core/test_wmi.py
- tests/core/test_wmi_calculator.py
Original discussion thread: https://github.com/DataDog/dd-agent/issues/1952
Credits to @TheCloudlessSky (https://github.com/TheCloudlessSky) . Thanks a lot !!!
A lightweight Python WMI module wrapper built on top of `pywin32` and
`win32com` extensions.
**Specifications**
* Based on top of the `pywin32` and `win32com` third party extensions only
* Compatible with `Raw`* and `Formatted` Performance Data classes
* Dynamically resolve properties' counter types
* Hold the previous/current `Raw` samples to compute/format new values*
* Fast and lightweight
* Avoid queries overhead
* Cache connections and qualifiers
* Use `wbemFlagForwardOnly` flag to improve enumeration/memory performance
*\* `Raw` data formatting relies on the avaibility of the corresponding calculator.
Please refer to …
> [core][wmi] new WMI metric collection core

- checks.d/openstack.py
- checks/__init__.py
- conf.d/openstack.yaml.example
- tests/checks/common.py
- tests/checks/mock/test_openstack.py
The OpenStack `AgentCheck` is intended to run besides individual hypervisors. It can be scoped to any set of projects living on that host via instance-level config, 
At the hypervisor-level it collects:
- [Hypervisor Uptime and Statistics](http://developer.openstack.org/api-ref-compute-v2.1.html#os-hypervisors-v2.1) 
At the project-level it collects:
- [Diagnostics for guest servers within that project](http://developer.openstack.org/api-ref-compute-v2.1.html#diagnostics-v2.1)
- [Absolute limits for the project](http://developer.openstack.org/api-ref-compute-v2.1.html#limits-v2.1)
Additionally it sends service checks to register the UP/DOWN state of networks discovered by the agent, 
the locally running hypervisor, and the outward-facing (`public || internal`) API services of Nova, …
> [checks.d][openstack] add monitoring for Openstack Nova and Neutron

- checks.d/kubernetes.py
- checks/__init__.py
- conf.d/kubernetes.yaml.example
- tests/checks/mock/test_kubernetes.py
Also fix service check messages
> [kubernets] Kubelet check failing shouldn't stop metrics collection

- checks.d/mongo.py
Not sure where this came from! 
Spotted this issue - dbstats weren't getting reported due to it.
> [mongo] variable typo.

- setup.py
The module was previously dynamically imported from the [Windows System check](https://github.com/DataDog/dd-agent/blob/5.5.x/checks/system/win32.py#L10-L14) and needs to be manually included now.
> [packaging][windows] force-include 'wmi' module

- checks.d/docker_daemon.py
With 5.6.0, this happens on every cycle:
```
2015-11-05 19:20:27 UTC | WARNING | dd.collector | checks.docker_daemon(__init__.py:649) | Couldn't find pid directory for container: . They'll be missing network metrics
```
> [docker_daemon] Remove spurious proc root container warnings

- jmxfetch.py
Currently, not reading from tempfiles when redirecting std streams, which breaks flare.
> [jmxfetch] Fix std redirect

- packaging/centos/datadog-agent.init
- packaging/debian/datadog-agent.init
By default, Supervisor runs with the given `user` in the `supervisord`
section of the `supervisor.conf` configuration file.
> If supervisord is run as the root user, switch users to this UNIX user
account before doing any meaningful processing. This value has no effect
if supervisord is not run as root.
(c.f
http://supervisord.org/configuration.html#supervisord-section-settings)
Thus, forcing Supervisor to run as `dd-agent` in the init script file is
simply an extra precaution. However, it makes impossible to change UNIX
users running the agent subprocesses via the `supervisor.conf`
configuration file only.
Drop this constraint.
> [core] `supervisor.conf` to select Supervisor user

- win32/agent.py
Otherwise we don't actually log anything that's logged by jmxfetch.py
> [windows][jmxfetch] fix logging initilization from jmxfetch python

- checks.d/consul.py
Add the main_tags to the service_check tags. This will include the consul_datacenter tag in the health checks. This is needed for when you have the same service name in multiple datacenters
> Add the main_tags to the consul service_check tags

- conf.d/openstack.yaml.example
We're using `urljoin` now and this recommendation for omitting trailing slashes is no longer necessary
> [openstack] minor doc update

- checks.d/http_check.py
- tests/checks/integration/test_http_check.py
In the WeakCiphersAdapter we still need to check with getattr for the _tunnel_host attribute, we can't assume it's going to be populated automatically by httplib, requests lib, etc.
> [http_check] fixed check for weak ciphers

- daemon.py
- tests/core/test_utils_process.py
- utils/process.py
Sometimes the agent fails to restart after a "hard" reboot because the pidfile
contains the pid of a non-datadog running process, and the only check the agent
did before this commit was to check if the pid was associated with a running
process.
This commit implements a new function `is_my_process` which verifies on Linux if the
`psutil.Process.cmdline` ("command line this process has been called with") is
the good one (corresponding to the current executable). This function is used
instead of `pid_exists` when `psutil` is installed and checks the pid contained
in the pidfile, thus solving the above-mentioned problem.
-------
I tested it on Mac (both dmg install and source install), and Debian.
> [core] improve detection of agent process from pid

- checks.d/docker_daemon.py
- util.py
Also exclude a few more keys for GCE tags as those can be very spammy.
> [docker/gce] Properly collect pod names for docker daemon check

- tests/core/test_flare.py
- utils/flare.py
- win32/gui.py
Especially useful because the path of the temp dir on Windows where the tar is saved can vary from machine to machine.
> [flare][windows] Mention path to tar file in flare's UI

- .gitignore
These files are generated as a side effect of running tests and do not need to
be checked into the repository.
[skip ci]
> [dev] ignore tests/core/fixtures/flare/dd*

- checks.d/consul.py
- conf.d/consul.yaml.example
This PR is supposed to enable Consul check over SSL, when a client certificate or a specific trusted CA might be needed.
> [check_consul] add SSL support to Consul checks.

- checks.d/go_expvar.py
- ci/resources/go_expvar/test_expvar.go
- conf.d/go_expvar.yaml.example
- tests/checks/mock/test_go_expvar.py
This change adds the ability to configure a custom namespace for your `go_expvar` metrics. By default, the old value (`go_expvar`) is used. The mock tests were updated to confirm that the new behavior works as expected.
In addition to the changes around the check script, the Go utility the tests use was modified as well. A manual GC trigger was added to ensure garbage collection has run at least once.
fixes #2016
> [go_expvar] add configuration option for custom metric namespace

- checks.d/http_check.py
- checks/network_checks.py
- conf.d/http_check.yaml.example
- tests/checks/integration/test_http_check.py
The check will now raise a critical warning if we're within the specified CRITICAL range before a certificate expires.
> [http_check] Adding a days_critical to the SSL certificate expiration feature

- checks.d/http_check.py
- checks/__init__.py
- tests/checks/integration/test_http_check.py
Also - AgentCheck messages could be unicode, so changed it there as well.
> [http_check] content-matching with unicode support

- config.py
- setup.py
- win32/agent.py
- win32/shell.py
py2exe only includes the python files of the python packages in the
`library` zipped file. This causes the `requests` library to be shipped
without CA certs, so all the https requests made with it fail (unless
SSL cert validation is explicitely disabled).
This fixes the issue by:
1. shipping the default certificates of `requests` with the Windows
agent as an extra data file
2. overriding the path to the default CA bundle that `requests` uses
(which is done in quite an ugly way, but I haven't found any better
way)
Notes:
- we already ship CA certs for `tornado`, but to be as close as possible to the agent's behavior on other platforms I've used the default CA certs provided by `requests`/`certifi`
- this doesn't fix SSL cert validation on the `http_check` on Windows, because the check uses …
> [windows][requests] Bundle default CA certs of `requests`

- tests/core/test_flare.py
- utils/flare.py
Also added a message in the output to make credentials removal from `datadog.conf` explicit. The message is similar to what is already displayed for the yaml files in `conf.d`, for instance:
```
2015-09-22 19:05:08,842 | INFO | dd.collector | utils.flare(flare.py:340) |   * /etc/dd-agent/datadog.conf - this file contains credentials which have been removed in the version collected: api_key, proxy credentials
2015-09-22 19:05:08,844 | INFO | dd.collector | utils.flare(flare.py:340) |   * /etc/dd-agent/supervisor.conf
2015-09-22 19:05:08,849 | INFO | dd.collector | utils.flare(flare.py:340) |   * /etc/dd-agent/conf.d/elastic.yaml - this file contains a password which has been removed in the version collected
2015-09-22 19:05:08,851 | INFO | dd.collector | utils.flare(flare.py:340) |   * …
```
> [flare] Remove proxy credentials from collected datadog.conf

- checks/collector.py
- resources/processes.py
They shouldn't make the collector exit when they raise an exception.
Also, raise an exception in the processes resource check instead of
returning False.
> [resources] Catch and log exceptions from the resources checks

- packaging/datadog-agent/source/install_agent.sh
This enables GPG signature check when installing RPM packages from our
one line install script. The key is also downloaded (just the first time
therefore it's rather DNS-spoofing proof).
We'll have to switch all these URLs to HTTPS as soon as it's enabled on
the `yum.datadoghq.com` domain.
[skip ci]
> [packaging][rpm] Check the RPM signature

- packaging/datadog-agent/source/install_agent.sh
yum on RedHat <= 5 doesn't support TLS1.2 so it can't use
our https repo. Use http instead.
See https://github.com/DataDog/chef-datadog/pull/240 for a detailed description of the issue.
> [packaging][rpm] Use HTTP for yum on RedHat <= 5

- checks/collector.py
If the create_dd_check_tags was enabled and if custom tags are passed
in datadog.conf, we have to send the dd_check and host_tags at the same
time.
Otherwise they’ll overwrite each other.
> [core] Fix host tags sending

- checks/system/unix.py
We use the output of ps for the mem usage stats, but the values can
have different units (can be G or M).
We would need to parse the unit and convert the values to the same unit
(probably bytes), otherwise it doesn't make much sense.
The Mac Package is now bundling psutil so let’s use psutil to get these
metrics (and add more!)
> [system-mac os] Fix memory metrics

- checks.d/postgres.py
A customer was having issues with the postgres check, after investigating it became apparent that metrics weren't reported for all specified relations. It looks like [pg8000](https://pypi.python.org/pypi/pg8000) wasn't doing a good job with the parameter substitution when making executing the SQL query. 
The fix consists in having us build the query manually instead.
> [postgres] FIX: pg8000 wasn't doing a good job with multiple relations

- checks.d/consul.py
- conf.d/consul.yaml.example
- tests/checks/mock/test_consul.py
This is a rebased and slightly modified version of #2018 . It queries for cluster status via the `/v1/health/service/<service>` endpoint, which allows us to split the coarse-grained `consul.catalog.nodes_up` and `consul.catalog.services_up` metrics into the following
-  `consul.catalog.nodes_passing` tagged by `consul_service_id`
-  `consul.catalog.nodes_warning` tagged by `consul_service_id`
-  `consul.catalog.nodes_critical` tagged by `consul_service_id`
-  `consul.catalog.services_passing` tagged by `consul_node_id`
-  `consul.catalog.services_warning` tagged by `consul_node_id`
-  `consul.catalog.services_critical` tagged by `consul_node_id`
The `consul.catalog.nodes_up` and `consul.catalog.services_up` metrics are preserved with their original values, but will likely be removed or …
> [consul] more accurate nodes_* and services_* gauges

- checks/collector.py
- ddagent.py
- tests/core/test_utils_logger.py
- utils/debug.py
- utils/logger.py
Create a `utils.logger` module:
* Move `log_exceptions` from `utils.debug`
* `NoAPIKeyLogRecord` is a custom `LogRecord` that obfuscates API keys
logging
> [core] do not log API keys

- packaging/datadog-agent/source/agent
- packaging/osx/datadog-agent
We don't package our own `kill` bin with the osx and source installs, so use the command provided by the OS for these install methods.
The cross-platform compatibility of the HUP signal seems to be good, so we can expect this to work well on most platforms.
Tested on OSX and FreeBSD.
> [packaging] Fix config reload on osx and source install

- checks.d/go_expvar.py
- conf.d/go_expvar.yaml.example
Adds support for counters by way of `increment` to the go_expvar check.
I'm unsure why the existing integration does not support counters and only rate. I feel like maybe I'm missing something here. In our use a rate will often do what I want, but it seems odd to convert to a rate when the full counter value is available. Also someone might want to alert on a raw total instead of a rate?
> Add counter support for go_expvar.

- ci/zookeeper.rb
Update the mirror urls to use Apache.org archives, the previously used cogent mirror only includes the latest release. As such each time apache releases a new version the url we had here previously would begin returning 404 and fail tests.
Also start testing against 3.4.7, rather than 3.4.6.
> Update the mirror urls to use Apache archives for ZK tests

- .travis.yml
- checks.d/zk.py
- ci/resources/zookeeper/zoo.cfg
- ci/zookeeper.rb
- conf.d/zk.yaml.example
- tests/checks/integration/test_zk.py
This is a rebased and slightly modified version of @jpittis #1770 
The addition puts the `zookeeper.instances.*` gauges behind an instance-level configuration flag (defaults to `True`). Users can flag this off if they prefer to rely solely on the `expected_mode` service check to monitor instance status
> Rebased pr #1770: gather stats from zookeeper mntr command

- conf.d/cassandra.yaml.example
Thanks @johnaxel 
**Related PR**
https://github.com/DataDog/chef-datadog/pull/263
> [cassandra] Add YAML for Cassandra version > 2.2

- checks.d/mongo.py
MongoDB v3.2 instances throw the following exception with `pymongo==3.2`
and `db[$cmd].find_one(...)` command:
```
OperationFailure: Invalid collection name: admin.$cmd
```
Comply with `pymongo==3.2`, use `db.command('serverStatus')` instead.
> [mongo] `pymongo==3.2` :heart: MongoDB 3.2

- checks.d/docker_daemon.py
> [docker-daemon] Don't warn if process finishes before measuring

- checks.d/statsd.py
- conf.d/statsd.yaml.example
Adds a StatsD integration for collecting metrics and service checks using [StatsD's admin interface](https://github.com/etsy/statsd/blob/master/docs/admin_interface.md).
Even though Datadog provides DogStatsD some organizations may choose to run StatsD for one reason or another. They may also be migrating from an existing StatsD setup. Or maybe they are monitoring someone else's stuff that uses StatsD.
We're in the second group, migrating from an existing StatsD setup. Having the ability to get service checks and metrics from our existing StatsD gives us both monitoring of current infra until it's gone and a way to measure our progress in moving "legacy" clients when that comes to pass.
* I can imagine this seeming odd since DogStatsD, but I hope I've justified it well.
* I'm running this …
> Add StatsD integration.

- checks.d/zk.py
- tests/checks/integration/test_zk.py
Switch `zookeeper.bytes_received`, `zookeeper.bytes_sent` from `gauge` to `count` type. 
**WARNING**: potential backward incompatibility issues.
Fix #1729.
@remh can you take a pass on it ? I am also wondering if we should use `rate` instead of a `count`, as both are valid.
> [zk] new `zookeeper.bytes_received/sent*` rates 

- checks.d/redisdb.py
- conf.d/redisdb.yaml.example
- tests/checks/integration/test_redisdb.py
The redis [INFO](http://redis.io/commands/INFO) COMMANDSTATS command returns:
* The number of times each command has been called.
* The amount of time spent on calling this command
* The average time per call of each command.
This parses that data into three gauges, tagged by command:
* `redis.command.calls`
* `redis.command.usec`
* `redis.command.usec_per_call`
These metrics are only collected if the `command_stats` flag is set to true for the instance, as there are 3 new metrics for every command run on a redis instance.
> [redis] Optionally collect redis INFO COMMANDSTATS as metrics.

- checks.d/teamcity.py
- conf.d/teamcity.yaml.example
It would be helpful to have the ability to disable SSL validation in the teamcity check, same idea as issue #1782.
I went ahead and added a flag in with the same name as the nginx check. I did not try and write an integration test. Is a test needed for this?
> [teamcity] Add ssl_validation flag to check

- agent.py
- dogstatsd.py
I'm working on FreeBSD port for dd-agent and I notice PID_FILE constant not being used. I also add option to set a path for pid file. I can change PID_DIR to '/tmp' and update to correct dir in FreeBSD port.
> [core] Set agent pid file and path from constant

- dogstatsd.py
- tests/core/test_bucket_aggregator.py
- tests/core/test_dogstatsd.py
- try to skip errors so that we can serialize what we can
- add a metric on serialization status
> [dogstatsd] Recover gracefully from serialization errors

- config.py
I needed to apply this patch so that I could configure a datadog agent install from source that ran alongside the system/ubuntu based install. Without this patch, if a set of configs is found in `/etc/...`, then they override the configs in the local directory tree even when installed from source.
> Enable running multiple datadog agents on the same machine.

- checks/collector.py
- checks/system/unix.py
Adds some new memory metrics:
* Slab:  The total amount of memory, in kilobytes, used by the kernel to cache data structures for its own use.
* PageTables: The total amount of memory, in kilobytes, dedicated to the lowest page table level.
* SwapCached: The amount of swap, in kilobytes, used as cache memory.
This is data we have in our existing munin + graphite setup. It's also stuff we've seen have a production impact during a nasty outage caused by a huge amount of VM pressure from slab allocation due to a weird problem we created by running a `find` across all of `/proc`. :P
I still am not sure how this metric gets turned in to `system.memory.*`. Is this all I need to do? Will do some testing. :smile:
> Add slab, page tables and cached swap.

- checks.d/vsphere.py
- conf.d/vsphere.yaml.example
- requirements.txt
As it stands, the vsphere check does not allow customization of SSL verification procedures in any way. This PR seeks to allow the ability to disable SSL verification, and to specify your own CA certificates.
> [vsphere] Add SSL config options for certs

- win32/gui.py
Looking at the code, there is no reason for it not to work on Windows.
Also it's been confirmed in #1969
Fix #1969
Will need to be tried though.
> [windows][gui] Show directory check in the GUI

- checks.d/process.py
- conf.d/process.yaml.example
- tests/checks/integration/test_process.py
When running the datadog agent as a container, we need to point
psutils at a different procfs to gather metrics on processes
outside the current namespace.
-- 
Based on #2124
> [process] Relocatable procfs for process check

- checks.d/mongo.py
- conf.d/mongo.yaml.example
- tests/checks/integration/test_mongo.py
Rebase of #1906 
**Additional changes**
* Add the corresponding `top` option in `additional_metrics`
* Clean up `top` metric collection code to comply with the current code
state.
Thanks again @scottbessler.
> [mongo] report dbtop metrics 

- checks.d/go_expvar.py
Adds a timeout for requests made to fetch go expvar metrics.
Locally we had a misbehaving app that never answered, causing the entire collector to be blocked and not getting metrics!
Should this be configurable?
r? @antifuchs @remh
> Add timeout for requests to get go expvar metrics.

- checks.d/vsphere.py
Currently, all metrics from vsphere are reported as gauges. We should attempt to read the metric type from the VMware metrics module and call self.gauge or self.rate, etc. accordingly.
First came up in conversation with @LeoCavaille here: https://github.com/DataDog/dd-agent/pull/1824
> [vsphere] Check metric type first to determine how to report

- checks/libs/vmware/basic_metrics.py
The vsphere dashboard is currently attempting to use these two metrics, but they are not included in the basic metrics collected. This should add those metrics, without the need to enable all metrics (read: a TON of metrics).
The vsphere dashboard is also trying to display disk.usage and mem.usage, which are also not basic metrics, but those are not being added at this time, because their compatibility is unknown as shown [here](https://github.com/DataDog/dd-agent/blob/master/checks/libs/vmware/all_metrics.py#L1215) and [here](https://github.com/DataDog/dd-agent/blob/master/checks/libs/vmware/all_metrics.py#L699)
> [vmware] Adding network.received and network.transmitted to basic_metrics.py

- datadog.conf.example
- util.py
Looks like the agent pulls AWS host tags, but doesn't pull `security-groups`. Additionally, it doesn't look like there is a good way to grab security group ids from EC2, however we do have access to the security group names. The fix to apply here is simply to make sure we add that to the tags collected as `security-group-name:<name>`.
> [util] Incorporating security-groups into tags collected from ec2

- checks.d/docker_daemon.py
When a user misconfigures their kubernetes check, it make the docker check fails too. This PR modifies the behavior so that we just log a warning and omit the kubernetes tags.
> [docker_daemon] catch exception when getting k8s labels fails

- checks.d/linux_proc_extras.py
- conf.d/linux_proc_extras.yaml.example
- tests/checks/integration/test_linux_proc_extras.py
I somehow broke #2030 . Oops.
Adds some new system metrics:
* context switch count (for rates!)
* processes created count (for rates!)
* interrupts
* counts of processes by state, with tags
* counts of processes by priority, with tags
These metrics are used in our existing setup and, from what I can tell, are not available today in Datadog agent. We can get them from specific processes via `process.yaml`, but not for the whole system!
I originally tried to add this stuff to `unix.py` but I'm unable to determine how those metrics end up as things like `sys.mem.free` and the like. So I settled on making a check that added the metrics I as after. I expect to add more.
Most of these metrics feel very "core" to Linux and therefore seem suitable to be included in something like `unix.py`. But …
> Add "more unix" plugin with some linux metrics.

- checks.d/wmi_check.py
- checks/libs/wmi/sampler.py
- ci/common.rb
- ci/etcd.rb
- ci/haproxy.rb
- ci/mongo.rb
- ci/resources/cache.rb
- tests/checks/mock/test_wmi_check.py
- tests/core/test_timeout.py
- tests/core/test_wmi.py
- utils/timeout.py
A decorator to timeout a function. Decorated method calls are executed in a separate new thread with a specified timeout.
Also check if a thread for the same function already exists before creating a new one.
Timeout WMI queries after 10seconds with a warning message and no data.
Recover at next iteration retrieving the existing query.
Less thread safety error-prone `WMISampler`: have one active query per connection at a time.
* `_get_connection` → `get_connection`, a context manager that
* returns an existing and available WMI connection, or create one if
needed
* release it, i.e. mark it as available when done
> [core][wmi] gracefully timeout WMI queries

- conf.d/gunicorn.yaml.example
Without the `setproctitle` module, gunicorn cannot set its own master process name to `unicorn master [appname]` and our check can't find the master process.
> [gunicorn] Mention that the `setproctitle` module is required

- checks.d/snmp.py
- tests/checks/common.py
- tests/checks/integration/test_snmp.py
This PR allows checking for multiple SNMP instances in parallel, each running in it's own thread (within the allocated thread-pool). The actual OID/walk is still done serially for each instance, but this PR should help organizations with multiple instances configured with a performance benefit as a factor of the thread pool size.
NOTE: tests involving rates now require three runs because network checks report the results of the nth run on the n+1 run.
> [snmp] convert into network-check to run instances in parallel

- Rakefile
Same as #2220, but for the `rake setup_env` command.
> [dev-env] Fix URL of get-pip script

- checks.d/network.py
- config.py
- utils/subprocess_output.py
It seems like a low/no disk space can cause the TemporaryFile calls made in `subprocess_output` to "fail" - and by fail we mean empty output that can lead to IndexErrors, etc, when parsing the output. In general we have to be ready to expect an empty string as output.
> Low/No Disk space caused the Agent to crash and not recover.

- checks.d/mysql.py
- conf.d/mysql.yaml.example
Allow tags for MySQL custom queries, separate from the global tags applied to the default metrics
> Added tag parameter for custom  MySQL queries

- checks.d/mysql.py
- ci/mysql.rb
- conf.d/mysql.yaml.example
- tests/checks/integration/test_mysql.py
This PR combines multiple efforts by @ovaistariq (huge effort!) @garnermccloud @c960657 @zdannar @polynomial @leucos to greatly improve the catalog of MySQL metrics reported. Metrics have been added to provide additional insight into:
* Performance Schema
* Replication
* Galera Cluster
* Per schema performance and size metrics
Additional work has gone into improving the test and attempt to test the entire catalog. 
This overhaul will now allow us to provide the following new metrics (hang tight):
```
* MySQL name: 'Com_replace' - Datadog metric name: 'mysql.performance.com_replace' - Metric type: RATE
* MySQL name: 'Com_load' - Datadog metric name: 'mysql.performance.com_load' - Metric type: RATE
* MySQL name: 'Aborted_clients' - Datadog metric name: 'mysql.net.aborted_clients' - Metric …
```
> [mysql] enhancing the catalog of metrics reported.

- checks.d/mysql.py
- tests/checks/integration/test_mysql.py
If the check is configured to use `mysql_sock` but the connection fails for whatever reason, the service check will report a `port:0` tag because the `service_check_tags` update happens after the connection.
This PR fixes that.
> [check] [mysql] Fix buggy tagging in service_checks

- packaging/datadog-agent/win32/wix/agent.wxs
Datadog Agent configuration file `datadog.conf` contains sensitive data
such as the API key.
Set the file permission, to allow the following access:
* Users. None
* Administrator & System. Full control
Similar to #76.
**Note**: Permissions are set at first install only. It is unchanged on upgrade.
> [windows] 🔒 permissions on `datadog.conf`

- tests/core/test_flare.py
- utils/flare.py
The flare module should support the use of the proxy settings and
verify_ssl_certs settings in the datadog.conf. Users experiencing issues
with these settings configured are unable to submit the flare bz2 for
diagnosing issues with support.
> [core][flare] should respect ssl and proxy config

- checks.d/mesos.py
- checks.d/mesos_master.py
- checks.d/mesos_slave.py
Requests internally (and irritatingly imho) bundles `chardet`. It uses this library to figure out the encoding for a given response if there are no suitable HTTP headers detailing the character set of the response.
This library is pathologically slow (its loop heavy) on any python implementation _not_ running on top of a VM. There are better implementations of `chardet` for vanilla pythons but the requests library authors wish to avoid bundling C extensions. https://github.com/kennethreitz/requests/issues/2359
Taking a leaf from opentable, we now force the encoding of the mesos response to always be UTF8 which avoids requests pulling large mesos payloads through `chardet` and prevents the datadog agent taking large amounts of CPU time to run the check.
> Mesos: Prevent requests from using chardet

- checks.d/elastic.py
- conf.d/elastic.yaml.example
Put `pending_task` stat collection behind a flag since some hosted ES services don't expose it
> [elastic] optionally collect pending task stats

- checks.d/snmp.py
I was faced with the following situation, my simplified conf:
```
metrics:
- OID: 1.2.3
name: first
- OID: 1.2.3.4.5
name: second
```
As you see OID of `first` is prefix of `second` OID. Without my bug fix both metrics get the value of `first` (since `second` have prefix `1.2.3`).
> [snmp] fix situation when ont requested oid is prefix for another requested oid

- checks.d/snmp.py
- checks/network_checks.py
- conf.d/snmp.yaml.example
- tests/checks/common.py
- tests/checks/integration/test_snmp.py
This is just a minor touch-up to #1331 by @chrissnell - adding tests and raising an exception in the event of a bad `forced_type`.
PR summary by @chrissnell:
Some SNMP-enabled devices return incorrect data types when certain OIDs are queried. The F5 1600LTM load balancer is an example of such a device. This PR allows for the forcing of data types (to 'gauge' or 'counter') in the event of an incorrect response from the remote agent.
It adds a parameter to the metric definition on the YAML, 'forced_type'.
NOTE: The changes in this PR were tested in a back-ported version of this improved snmp check that Datadog provided me. The check patched here is from a newer version of the agent that I don't have any easy way to test right now. The changes are the same between the versions and it should …
> Add support for forced SNMP data types to help w/ buggy devices

- checks.d/mongo.py
This PR adds `mongo_replset_state` as a tag to represent [the various replica states](https://docs.mongodb.org/manual/reference/replica-states/) of mongodb instances.
In some cases, we’d like to look at stats only for replica primaries. This gives us that ability!
> [mongo] tag mongo instances by replset state

- checks.d/hdfs_datanode.py
- conf.d/hdfs_datanode.yaml.example
- conf.d/hdfs_namenode.yaml.example
This is just a quick bugfix that updates bean name being requested from the DataNode's JMX interface.
> [hdfs] Bugfix updated bean name in datanode check

- checks.d/wmi_check.py
- checks/libs/wmi/sampler.py
- checks/system/win32.py
- tests/checks/mock/test_wmi_check.py
- tests/core/test_wmi.py
- tests/core/test_wmi_calculator.py
Use a `list` to cache WMI connections instead of a `set`.
WMI queries can potentially raise a `TimeoutException` on query timeouts. Handle it.
> [system][wmi_check] handle `TimeoutException`

- checks.d/mysql.py
- conf.d/mysql.yaml.example
- tests/checks/integration/test_mysql.py
When we made the MySQL check revamp, this was probably the one point where I had noticed we were lacking a little bit - amongst other things because not all info is available everywhere (ie. the information on a slave node is different to the information available on `master`, and in turn, it'd be different in a system without replication enabled). This attempts to address all use cases.
- Also squeezing in a fix to an issue regarding the hostkey that probably came up as a product of a badly resolved conflict.
- Fix to a bad service_check tag issue when the customers connect to their MySQL instance via a port and experience a connection failure. We were updating the tags _after_ the exception - which was naturally not working in the event of a failed check.
> [mysql] Improving replication status check

- conf.d/cassandra.yaml.example
`ColumnFamily` metrics are available two ways: as global aggregates and per keyspace/column family. This regex from @olivielpeau limits metric collection to those metrics associated with a specific keyspace to omit the global aggregates. This eliminates confusingly similar metric names (e.g. `cassandra.total_disk_space_used` and `cassandra.total_disk_space_used.count`) and prevents the double-counting of certain metrics.
> [cassandra] Exclude aggregated metrics not associated with a specific keyspace

- conf.d/kafka.yaml.example
Collecting MeanRate from Kafka's Meter JMX Mbeans isn't terribly helpful for graphing in DD because the rate is the [mean rate for the entire lifetime of the Kafka broker](http://metrics.dropwizard.io/3.1.0/manual/core/#meters).
Instead of collecting the MeanRate, we could collect the load average style rates or we can simply grab the monotonically increasing counts and calculate our own rate from that raw counters. Since DD captures metrics at smaller time intervals than a minute, calcuating our own rate gives the user the most granular view of cluster activity so that's what the example configuration file will contain.
In addition to fixing the collection of these rate metrics, the example configuration is also updated to collect nearly all the useful metrics [recommended by …
> [kafka] Improve example configuration

- checks.d/hdfs.py
- checks.d/hdfs_namenode.py
- conf.d/hdfs.yaml.example
- tests/checks/mock/test_hdfs_namenode.py
- add a deprecation notice on the old check
- add to the new check a metric (`capacity_in_use`) that was sent by the old check
> [hdfs] Deprecate previous hdfs check

- checks.d/gunicorn.py
This slipped by [when upgrading to psutil 3.3.0](https://github.com/DataDog/dd-agent/pull/2134) . `get_children` is no longer valid.
> [gunicorn] use psutil 3 compatible children func

- datadog.conf.example
- util.py
An IAM role associated with the instance is required to retrieve AWS EC2
custom tags. Log a warning when missing, not an exception.
Fix #1884
> [core] EC2 tags collection requires an IAM role

- checks.d/pgbouncer.py
Fixed an error when there were no results for a query run against a pgbouncer instance. In that case there was a check against a variable `results` that was not yet initialized. I added an initialization before the checks for `results = None`, thus fixing the problem.
> [pgbouncer] fixed UnboundLocalError for results var

- conf.d/go-metro.yaml.example
- config.py
- packaging/centos/datadog-agent.init
- packaging/debian/datadog-agent.init
- packaging/supervisor.conf
- utils/flare.py
Alternatively, we could add a python launcher that will only launch the binary iff `conf.d/dd-tcp-rtt.yaml` exists.
> [go-metro] Adding supervisor entry and sample yaml config.

- datadog.conf.example
The [guide to tagging](http://docs.datadoghq.com/guides/tagging/) recommends that tags are in the key:value syntax. This should be reflected in the example datadog.conf file.
> Use key:value in example tags

- checks/wmi_check.py
- tests/checks/mock/test_wmi_check.py
- tests/core/test_wmi.py
Do not log a warning about non digit property values for the 'Name'
property.
Strengthen unit tests: less race condition error-prone.
> [wmi] no warnings on 'Name' property 🔇

- packaging/osx/supervisor.conf
Now that go-metro is bundled only on Linux, we use a different
`supervisor.conf` file for OSX.
We could go back to a shared supervisor conf once we have go-metro in the OSX pkg and instructions on how to run it unprivileged.
> [packaging][osx] Use osx-specific supervisor.conf

- checks/collector.py
- checks/system/common.py
- checks/system/unix.py
- checks/system/win32.py
Split `system.uptime` metric collection check on Windows and Unix
systems to comply with their respective system metric formats.
> [system] ✂ uptime collection on windows & unix

- checks/system/unix.py
Just comment out unused `proc` var.
We should probably remove all this unused `processes` stuff.
> [flake8] Fix F841 in system unix check

- tests/checks/mock/test_sysstat.py
In a [recent refactory](https://github.com/DataDog/dd-agent/commit/162c3fab358aa3f02c5beec4bd4189c9a70b40fc) we got rid of  `checks.system.common` module, still `test_sysstat.py` was importing it, causing failures on CI.
> [system] fixed import of missing module

- conf.d/go-metro.yaml.example
Fix `libcap` installation instructions for Debian based distributions on `go-metro` YAML configuration file.
> [go-metro] `apt-get ̶u̶p̶d̶a̶t̶e̶`→`install`

- checks.d/haproxy.py
- conf.d/haproxy.yaml.example
*Rebase of @talwai's original work #2256.*
Adds two flags to the HAProxy config:
* `count_status_by_service` instructs the check to tag the status
counts it collects by service in addition to by host. Defaults True
* `collate_status_tags_per_host` instructs the check to collate
backend-level status tags for `haproxy.count_per_status` from (`up`,
`open`, `down`, `maint', `nolb`) to one of (`up`, `down`)
`collate_status_tags_per_host` only applies when `collect_status_metrics_by_host` is `True`.
> [haproxy] options to collapse status count metrics

- checks.d/docker_daemon.py
Events that don't have an `id` field also don't have a `from` field so `event['id']` bits in `_format_events` don't need to be modified.
> [docker] Avoid event collection failure if an event has no ID param

- CHANGELOG.md
- conf.d/go-metro.yaml.example
- packaging/supervisor_32.conf
We use 2 different supervisor confs on x64 and i386. The init script
should be able to handle both w/o problems.
> [packaging][go-metro] Remove go-metro from the i386 packages

- checks.d/zk.py
- tests/checks/integration/test_zk.py
Report `mntr` command's `zk_packets*` information as rate, not gauge.
> [zk] `mntr` command's `zk_packets*` as rate

- checks.d/kubernetes.py
- tests/checks/common.py
- tests/checks/fixtures/kubernetes/pods_list.json
- tests/checks/mock/test_kubernetes.py
- utils/kubeutil.py
Using the kubelet api, query the number of pods and group them by the Replication Controller that spawned them.
Report the number of pods spawned by each RC, tagging with `kube_replication_controller` and `node_name` thus allowing sums.
> [kubernetes] add kubernetes.pods.running metric

- packaging/datadog-agent/source/setup_agent.sh
Applies the changes of #1504 to the `setup_agent.sh` file, and sets the default agent version to `5.7.0`.
Should be merged right after 5.7.0 is released (i.e. once the the repo has the `5.7.0` tag)
Supersedes #1504 when combined with #2198.
> [source] Revamp our source install script (part 2)

- utils/http.py
Add a timeout to avoid hanging requests that get the collector killed.
> [utils] Add a default timeout parameter to retrieve_json

- requirements-opt.txt
- requirements.txt
We get bitten fairly often by differences in the deps/versions of deps
defined in the requirement files and in omnibus. Adding a comment to
make clear that updating only the requirement files is not enough.
> [requirements] Add reminder to update omnibus-software too

- packaging/centos/datadog-agent.init
Without this fix, the `stop` command (-> `killproc`) would only wait for
0.1 second before `kill -9`ing supervisord, so if the collector for
instance took more than that to stop, a subsequent `start` would
fail because we'd try to start a collector before the old one had died.
This fix uses an option of `killproc` so that it waits for 30 seconds
(similar to our init script on debian) before `kill -9`ing
supervisord (which is plenty of time since supervisord `kill -9`s
the processes that haven't stopped after 10 seconds, by default).
Without the fix, here is what can happen when we restart the agent (`supervisord.log`, I removed the log lines about jmxfetch and go-metro since they're not relevant):
```
2016-03-11 21:50:28,437 WARN received SIGTERM indicating exit request
2016-03-11 …
```
> [centos][init] Wait for supervisord to stop before `kill -9`ing it

- checks/libs/wmi/sampler.py
- tests/checks/mock/test_wmi_check.py
- tests/core/test_wmi.py
Disable WMI timeouts, cache and re-use connections.
Fix #2364
> [wmi] disable timeout and re-use connections

- conf.d/cassandra.yaml.example
Cassandra added a new `system_schema` keyspace in version 3.0. If not excluded from the JMX check, this keyspace reports ~130 additional JMX metrics to Datadog. Tested on Cassandra 3.0.4.
> [cassandra] exclude new system_schema keyspace

- ddagent.py
Watchdog constructor takes `duration` parameter in seconds, not
milliseconds. Initialize the forwarder accordingly.
> [core] set watchdog duration in seconds

- conf.d/kafka_consumer.yaml.example
changed the default Kafka broker port listed in the configuration to the _actual_ default port
[skip ci]
> [kafka] changed default Kafka broker port

- packaging/datadog-agent/source/install_agent.sh
This is to add support for installing dd-agent package on Arista EOS. This have
been tested to work correctly at Fastly but with a caveat that user `dd-agent`
on Arista EOS does not persist between reboot so one must take care of adding
that back in by using event-handle system in `running-config` for the Arista.
In addition, Fastly package dd-agent into it's own virtualenv and run on Arista
which isolate the Python environment from the rest of EOS.
> Adding detection of Arista EOS.

- checks/collector.py
tzname has an encoding issue with Japanese versions of windows.
See https://trello.com/c/cEhSEKpW/1231-windows-agent-is-not-reporting-metrics-and-strange-character-shows-in-time-zone-part
> [collector.py] ugly fix for the tzname encoding issue

- packaging/datadog-agent/source/install_agent.sh
- We don't really care whether `apt-get update` succeeds or not when
installing `apt-transport-https`, but we do want to avoid having the
whole install script fail when that fails.
- switch the apt repo to https
> [install script] Ignore `apt-get update` failures + use https for apt repo

- checks.d/consul.py
The consul API may return `null` instead of `[]` when there are no
peers in the cluster.
Fixes #2336
> [consul] Enforce that get_peers_in_cluster returns a list

- checks.d/iis.py
- tests/checks/mock/test_iis.py
- tests/core/test_wmi.py
Before 5.7.0, for `sitename == '_Total'`, we used to send a service check.
5.7.0 to 5.7.2 were always  sending a critical service check for this site name.
Go back to the previous behavior, and add a test case.
Should fix #2354
> [iis] Fix service check on the `_Total` site

- checks/libs/wmi/sampler.py
- tests/checks/mock/test_wmi_check.py
- tests/core/test_win32.py
- tests/core/test_wmi.py
Re-enable the timeout feature (that was reverted in #2366), after some tests.
Sharing COM objects between threads leads to handle/memory
leaks. Because of this, take the safe approach of having one connection
COM object per thread, and never keep reference to the connection once
the thread is terminated.
This could probably be improved on by having a pool of long-lived
threads that would have their own COM objects.
Also, add a test to check that no handle leaks happen on the core check.
> [wmi] enable timeout and remove connection caching

- checks.d/docker_daemon.py
- tests/checks/integration/test_docker_daemon.py
In cases where the docker volume is not mounted the disk check can't collect metrics about the volume usage. It happens in the ECS optimized AMI for example: https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-optimized_AMI.html
Collecting these metrics using `docker info` makes sense in this case and is also useful in others.
> [docker] add optional disk metrics

- .travis.yml
- checks.d/elastic.py
- tests/checks/integration/test_elastic.py
Some of the stats I introduced for 1.x are removed in 2.x. :cry: 
Resolves #2186
> [elasticsearch] Restricts 1.x specific stats to v1.x

- checks/check_status.py
- utils/platform.py
- win32/gui.py
- win32/status.html
The header on the Python interpreter will now include the Python Interpreter Architecture as well as the version. It will look like this:
```
Status date: 2016-04-12 15:49:45 (2s ago)
Pid: 31865
Platform: Linux-3.13.0-32-generic-x86_64-with-debian-wheezy-sid
Python Version: 2.7.11, 64bit
Logs: <stderr>, /tmp/collector.log
```
> Adds Python Interpreter Arch to Info Cmd

- checks.d/tokumx.py
- conf.d/tokumx.yaml.example
Ran into a situation where some data points coming from mongo are of type int64 (ie `0L`, or `2L`). We should take these into account and then coerce them to floats.
Additionally, the integration panel for TokuMX mentions specifying a full MongoDB URI, but the yaml shows no examples.
> [tokumx] Handle int64 and replica connections

- .pylintrc
- .travis.yml
- README.md
- checks.d/cacti.py
- checks.d/mongo.py
- checks.d/vsphere.py
- checks.d/zk.py
- checks/datadog.py
- checks/libs/wmi/sampler.py
- ci/default.rb
- dogstream/cassandra.py
- requirements-test.txt
- tests/checks/common.py
- tests/checks/integration/test_redisdb.py
- tests/checks/integration/test_zk.py
- tests/core/test_timeout.py
- tests/core/test_win32_agent.py
- tests/core/test_wmi.py
- util.py
- win32/gui.py
- Stop testing agent on python 2.6
- Remove code used to handle python < 2.6
- Remove unused code
- Reenable pylint
> [core] Remove support of python 2.6 + Cleanup + pylint

- requirements.txt
There is a bug in boto 2.36.0 that is fixed in the 2.39.0 release: https://github.com/boto/boto/pull/3399
> [dependencies] Upgrade boto 2.36.0 -> 2.39.0

- checks/collector.py
Otherwise they will just leak. No need to store them or send them in the agent payload though (they are empty).
> [core] Make sure to flush service metadata

- checks.d/mongo.py
- conf.d/mongo.yaml.example
- tests/checks/integration/test_mongo.py
**[mongo] more default metrics ↗**
The following metric topics are now collected by default:
* `durability` - journaling-related operations and performance report.
* `locks` - serverstatus locks report.
* `wiredtiger` - wiredtiger storage option.
Log a warning to inform the user when any of these metric topics is
listed in the configuration file 🔊 .
**[mongo] additional `wiredtiger` cache metrics**
Collect additional WiredTiger metrics, i.e.
* `wiredTiger.cache.modified_pages_evicted`,
* `wiredTiger.cache.unmodified_pages_evicted`
Number of pages evicted from the cache
* `wiredTiger.cache.tracked_dirty_bytes_in_cache`
Amount of space taken by dirty data in the cache (bytes).
> [mongo] more default metrics ↗

- checks.d/mongo.py
Rebase of @rhwlo's #2237 changes.
**Added my 2 cents**
Rename `ReplicationInfo` metric names to match `db.getReplicationInfo`
command return, i.e.
* `oplog.totalSizeMB` → `oplog.logSizeMB`
* `oplog.timeDiffSeconds` → `oplog.timeDiff`
Thanks again @rhwlo
> [mongo] oplog replicationInfo metrics 

- checks.d/mongo.py
- tests/checks/integration/test_mongo.py
Rebase of #2409.
**Added**
* Restore `SERVICE_CHECK_NAME` class variable 
* Initialize the check in `TestMongoUnit:test_state_translation`
Thanks again @antifuchs
> [mongo] Improve messaging&tags on MongoDB replset member state events

- checks/check_status.py
- ddagent.py
- transaction.py
- win32/status.html
When propjoe responds with a 413 error (payload too big), the agent used to retry the request. It shouldn't. The request shouldn't ever succeed.
This stops it from resubmitting the request. It logs a warning, saying what happened. It also adds a warning to the info page that a request was rejected.
> better 413 response handling

- packaging/datadog-agent/source/setup_agent.sh
Fixes the following error when installing the agent with the source install script:
```
* Setting up setuptools
It looks like you hit an issue when trying to install the Datadog agent.
###
File "/usr/lib64/python2.7/zipfile.py", line 811, in _RealGetContents
raise BadZipfile, "File is not a zip file"
zipfile.BadZipfile: File is not a zip file
###
```
Cause: the latest versions of setuptools (`20.10.0` and `20.10.1`) can't be downloaded by
`ez_setup.py`, so make ez_setup download a version that is actually
available.
See also https://github.com/pypa/setuptools/issues/557
> [source] Pin setuptools version

- checks.d/disk.py
- conf.d/disk.yaml.default
- tests/checks/mock/test_disk.py
This changeset adds an `exclude_mountpoint_re` option the disk integration configuration and corrects a small typo in the disk integration configuration template.
Nagios’s `check_disk` plugin has a `-i` option to ignore paths or partitions based off of regular expressions, and this will add the same functionality to Datadog.
I’ve added tests to `mock/test_disk.py` alongside the other disk tests to verify that the regexes exclude what we want and nothing else.
> [disk] add a regex option to exclude disks based on mountpoint

- utils/dockerutil.py
On Ubuntu 16.04, both `/run/lxcfs/controllers`- and `/sys/fs`-style mount points are present. Only the latter are accessible by the **dd-agent** user, but `find_cgroup()` returns the former.
With this PR, `find_cgroup()` checks that the mount point is accessible by the current user.
> [docker] Ignore mountpoints not accessible by current user

- ddagent.py
- tests/core/test_watchdog.py
- util.py
**[util] watchdog high activity detection :fire:**
New option to the Watchdog to detect suspiciously high activity:
restarts the process when too many resets were made for a given
timeframe.
**[core] detect forwarder pathological activity**
On some specific system date and scheduled transaction flush time, the
Datadog Agent forwarder's schedule breaks and enters in a frenetic loop.
It gets unreachable, flushes (no transaction) at a very high rate
(several ~100 flushes/second). At this point, only a restart fixes the
situation.
Under the hood, the issue is related to `tornado==3.2.2`. More
information is available here:
https://github.com/tornadoweb/tornado/issues/947
Before considering any upgrade, a simple fix is to use the Watchdog to
detect this pathological high activity.
> [core] detect forwarder pathological activity

- checks/system/win32.py
Our Windows pagefile statistics are not very robust. We've had a few requests to add more, better. This PR adds such metrics.
Now we're capturing the total size of the pagefile, how much is used, how much is available and the percent that's still free.
I've tested it on Windows, it seems to work fine, and the metrics come out looking pretty nice.
> [core] adds swap (pagefile) to windows stats

- conf.d/http_check.yaml.example
These parameters are not used anymore in the http_check.py code.
Since the introduction of status_check based monitors, users can control from the app UI after how many CRITICAL statuses they want to be alerted etc.
The presence of these 2 parameters is confusing.
> [http_check] Removes deprecated parameters 'threshold' and 'window' from the yaml

- checks.d/marathon.py
This metric is not really useful (nor used) but it’s really costly to collect.
Let’s remove it.
Fix #1861
> [marathon] Remove versions metric

- checks.d/win32_event_log.py
- conf.d/win32_event_log.yaml.example
- tests/core/test_wmi.py
The (optional) `event_format` parameter will instruct the check to
generate
Datadog's event bodies with the specified list of event properties.
If unspecified, the EventLog's `Message` or `InsertionStrings` are used
by default.
Available properties are:
- Logfile
- SourceName
- EventCode
- Message
- InsertionStrings
- TimeGenerated
- Type
> [win32_event_log] `event_format` option 🎨

- checks.d/activemq_xml.py
- conf.d/activemq_xml.yaml.example
ActiveMQ standby hosts (for HA) are running but do not allow connections
until they are failed over to. When a failover occurs we need to start
capturing metrics, but until then we should silently wait.
This adds a new config parameter which if used will treat a offline host
as 0 successful metrics rather than logging exceptions and presenting an
"agent error" in the datadog console interface.
----
Rebase from #2023
Thanks to @joelvanvelden
> [activemq_xml] add monitoring for standby hosts

- checks.d/mongo.py
Link MongoDB events to the integration, i.e. set events' `source_type_name`. Ignore `event_type`, as constant (i.e. useless).
> [mongodb] set `event_type` & `source_type_name`

- tests/checks/common.py
Modules will normally live in `integrations-core/foo` or `integrations-extra/bar` and a file typically called (by convention) `check.py`...
These changes would allow us to use the AgentCheckTest facilities with CircleCI and the SDK. We might have to fine-grain a little bit how we load the checks if `is_sdk=True`.
Should be backward compatible.
> [SDK] Minor changes to allow testing of the SDK check modules

- checks.d/docker_daemon.py
Fixes
```
2016-05-04 05:24:24 UTC | ERROR | dd.collector | checks.docker_daemon(__init__.py:763) | Check 'docker_daemon' instance #0 failed
File "/opt/datadog-agent/agent/checks/__init__.py", line 746, in run
self.check(copy.deepcopy(instance))
File "/opt/datadog-agent/agent/checks.d/docker_daemon.py", line 222, in check
containers_by_id = self._get_and_count_containers()
File "/opt/datadog-agent/agent/checks.d/docker_daemon.py", line 273, in _get_and_count_containers
self._filter_containers(containers)
File "/opt/datadog-agent/agent/checks.d/docker_daemon.py", line 412, in _filter_containers
self.log.debug("Container {0} is filtered".format(container["Names"][0]))
IndexError: list index out of range
```
when trying to exclude containers from monitoring
> Use local var for container_name

- checks.d/docker_daemon.py
fixes https://github.com/DataDog/dd-agent/issues/2454
Lines in `/proc/$PID/cgroup` don't have the same format for all system.
- In CoreOS they look like: `3:cpu,cpuacct:/system.slice/docker-$CONTAINER_ID.scope`
- In RancherOS: `5:cpu,cpuacct:/docker/$USER_DOCKER_CID/docker/$CONTAINER_ID`
- In Ubuntu: `4:cpuacct:/docker/$CONTAINER_ID`
To avoid picking the first (wrong) container ID, let's switch from `search` to `re.findall`.
> [docker] fix container ID extraction for RancherOS

- checks/libs/wmi/sampler.py
- conf.d/wmi_check.yaml.example
> [wmi][docs] Document that `%` is the only accepted wildcard in filters

- aggregator.py
- tests/core/test_dogstatsd.py
On service checks, tags which keys finished with `m:` were mistaken for
the beginning of a message metadata field.
Fix the behavior, and add a test.
Fixes #2373
> [dogstatsd][sc] Fix parsing of tag key ending with `m`

- checks.d/mysql.py
See #2406.
- `ROUND((SUM(sum_timer_wait) / SUM(count_star)) / 1000000)`: represents the real average `timer_wait` per query for a given schema. Here, `sum_timer_wait` represents the sum of all `timer_wait` times for a certain query, and `count_star` is the number of times a certain query was run. 
- formerly `ROUND(AVG(avg_timer_wait)/1000000)` actually represented the average of averages.
The discrepancy between the two computations may be considerable.
> [mysql] improving accuracy for query exec time. Fixes issue #2406.

- packaging/datadog-agent/source/setup_agent.sh
Setuptools has moved to github from bitbucket. As per the github readme the new preferred location is:
https://bootstrap.pypa.io/ez_setup.py
> [source_install] updating setuptools ez_setup.py to new recommended location.

- .travis.yml
- appveyor.yml
- tests/README.md
- tests/checks/common.py
- tests/checks/integration/test_mysql.py
- tests/checks/integration/test_process.py
- tests/checks/integration/test_supervisord.py
- tests/checks/mock/test_directory.py
Currently, coverage reports only fail through an opt in system. You have to set `COVERAGE=true`. While it's a good idea not to always have the very verbose output or failures when you're testing something, it can be annoying, it should be opt out instead of opt in. That way, it's easier for people (both community and Datadog) to ensure they have proper coverage in their tests.
> [core] changes coverage failure to opt out, instead of opt in

- checks.d/disk.py
- tests/checks/mock/test_disk.py
#2359 introduced a regression under the following circumstances:
* device name is `''`
* `excluded_disk_re` is not specified in the config file.
In that case, the default pattern for `excluded_disk_re` was `^$` thus making `_exclude_disk` return before evaluating `excluded_mountpoint_re`.
Also added a specific test for this issue and fixed the logic with a more verbose but easier to read pattern.
> [disk] Fix disk check exclusion

- checks.d/http_check.py
- conf.d/http_check.yaml.example
If a `no_proxy` environment variable is set we should honor it when making requests. This PR addresses the issue by adding the environment variable to the `proxies` dict used by `requests` to make the request.
- Should we allow overriding of `no_proxy` in the yaml configuration file?
- Should we "inherit" `http` and `https` system-wide environment variables as well if they're not set in the configuration file?
- I have allowed to override any proxy settings with a per instance `no_proxy` flag.
- If no `datadog.conf` proxy is enabled, but environment variables are found for https or http proxies, these will be enforced.
Unfortunately this is now a little more convoluted then I would've liked. Passing the `self.proxies` dict with `http` and/or `https` and a `no_proxy` key (or `no` key …
> [http_check] add support for no_proxy environment variable

- setup.py
A client contacted us telling us that the agent had stopped working on Windows Server 2008. There were a few things obscuring what was going on, I won't go into detail about how I figured it out. But, after digging through their logs for a while, the root of it was the following error: `WindowsError: [Error -2146893795] Provider DLL failed to initialize correctly`.
This is a known py2exe issue in Windows. [Amazon had the same issue last year](https://github.com/aws/aws-cli/issues/1226) with their AWS cli not working on Windows Server 2008 and earlier, if it had been built on a later system. 
What's happening is that py2exe is bundling all the necessary .dll's into the installer. However, in this case, the .dll is an Operating System .dll. It's not appropriate to bundle the OS specific …
> [core] [windows] Fixes windows agent for windows server 2008 and earlier

- util.py
Right now `get_hostname` never resolves to an EC2 instance id for windows host because the condition to look for it didn't include empty hostnames. This PR fixes that.
> [util] Fix get_hostname for windows ec2 instances

- checks.d/mongo.py
**[mongodb] `replset_name` tag 🏷**
Add replication set name tag, `replset_name` <U+1F3F7>  to MongoDB metrics.
**[mongodb] `cluster:db:$dbname`→`db:$dbname` 🏷**
MongoDB metrics are tagged with two key sets for the database name, i.e.
* `cluster:db:$dbname` for `dbStats` metrics.
* `db:$dbname` for `top` metrics.
For consistency, add a `db:$dbname` tag to `dbStats` metrics. Do not
remove the legacy `cluster:db:$dbname` to avoid backward
incompatibilities.
> [mongodb] better metric tagging

- checks.d/mongo.py
Adds an additional tag `action:mongo_replset_member_status_change` to events generated for mongo replset status changes.
I don't like relying on full text search for events. I find tag filtering to be a more precise and ergonomic way of asking for a specific type of event. This tag lets us filter *just* for status change events easily.
cc @rhwlo @antifuchs
> [mongo] Add additional tag on status change to make searching more precise.

- checks.d/mesos_master.py
Fixes a case where a missing metric can cause the mesos_master integration to report only a subset of metric values.
Our version of Mesos — 0.21.0 — was missing a key `master/tasks_error` and getting a `KeyError`. This caused it to only report 20 of the possible 60 metrics it should've been collecting!
I didn't add any sort of logging for missing keys. Happy to do so if desired.
cc @rhwlo @antifuchs
> [mesos_master] Fix key error when a metric is missing.

- utils/checkfiles.py
- utils/dockerutil.py
- utils/kubeutil.py
get_hostname tries calling DockerUtil in some cases which can lead to irrelevant error logs like
```
2016-05-11 20:23:09,243 | ERROR | dd.collector | utils.checkfiles(checkfiles.py:29) | Couldn't find any configuration file for the docker_daemon check.
2016-05-11 20:23:09,243 | ERROR | dd.collector | utils.dockerutil(dockerutil.py:79) | No instance was found in the docker check configuration. Docker related collection will not work.
```
This PR makes `get_conf_path` raise an IOError instead of logging, and manage this exception more precisely downstream.
> Fix bad logging in case a check config file is missing

- utils/service_discovery/sd_docker_backend.py
source, init_config and instance were not assigned correctly, leading to useless debugging output
> Fix configcheck command

- checks.d/mapreduce.py
- conf.d/mapreduce.yaml.example
- tests/checks/mock/test_mapreduce.py
With the following exceptions:
- `mapreduce.job.elapsed_time`
- `mapreduce.job.map.task.elapsed_time` (made non-default in config)
- `mapreduce.job.reduce.task.elapsed_time` (made non-default in config)
Also, removed `mapreduce.job.map.task.progress` and
`mapreduce.job.reduce.task.progress`.
We have to ping @kky once this PR is merged and part of a nightly/pre-release package so that he can update the default screenboard accordingly.
> [mapreduce] Switch most metrics to counters

- checks.d/process.py
- tests/checks/integration/test_process.py
Process pagefault stats aren't very good as a gauge. In most processes they're a roughly monotonically increasing count. But, they're pretty good as a rate. It gives you a baseline that you can then measure changes against.
> [check][process] changes pagefaults stats from gauge to rate

- checks.d/vsphere.py
- conf.d/vsphere.yaml.example
This adds the ability to set a custom field from the vSphere PowerCLI which acts as a marker for which VMs you would like to have monitored by the agent. In order to add this custom field, a user can use this command: `Get-VM <MyVMName> | Set-CustomField -Name "DatadogMonitored" -Value "DatadogMonitored"`
The ideal would have been to use the new tagging feature brought in vSphere 6.0 (usable also through the vSphere Web Client), but the vSphere API (at least in vCenter 5.5) does not expose these tags. There is an attribute on the managed object for VirtualMachine, called tag. Unfortunately, this is actually not the same tag set as the ones set in the vSphere Web Client (at least in vCenter 5.5). The tags set in the web client are instead stored in the Inventory Service.
Additionally, …
> [integration][vsphere] Add optional vm include parameter

- checks.d/mcache.py
- conf.d/mcache.yaml.example
- tests/checks/integration/test_mcache.py
This PR adds support for memcached "items" statistics as reported by `stats items`. It also attempts to simplify the inclusion of additional optional metrics. To do so, it introduces a map of `stats` arguments (ie. items) to a list  of rate metrics, gauge metrics, and if needed a raw stat output handler.
In the particular case of the items statistics, we need an output handler because we need to parse the raw key value (with form "items:<slab_id>:<metric_name>" to extract the `<slab_id>` and actual metric name. The actual value remains untouched - no need to operate over it. We can then use the `slab_id` to tag the relevant metrics. All handlers are expected to return a tuple of metric_name, tags, and actual value. 
Enabling optional metrics requires configuring the `optional_metrics` …
> [memcached] Additional stats metrics

- config.py
- tests/core/fixtures/checks/invalid_check_1.py
- tests/core/fixtures/checks/invalid_check_2.py
- tests/core/fixtures/checks/invalid_conf.yaml
- tests/core/fixtures/checks/valid_check_1.py
- tests/core/fixtures/checks/valid_check_2.py
- tests/core/fixtures/checks/valid_conf.yaml
- tests/core/fixtures/checks/valid_conf_2.yaml
- tests/core/fixtures/checks/valid_sub_check.py
- tests/core/test_config.py
- utils/checkfiles.py
Based on @tmichelet's work in #2273, rebased on top of master (i.e. it now handles configs from the service discovery).
When we load the checks, we take into account the configs from files (`.yaml` and `.default.yaml`) first, and then the configs from service discovery for the checks that haven't been loaded yet.
Also, this changes the logic of `get_check_class` in `utils.checkfiles` to take into account checks from 3rd-party dirs.
cc @hkaj 
Original PR message:
```
- Add tests on config's logic
- Refactor logic
- Update logic to look for checks in 3rd-party directory
```
> [Config] Update config logic to look for checks in 3rd-party directory (rebased)

- jmxfetch.py
Otherwise jmxfetch won't be able to send metrics
> [jmxfetch] If statsd is bound to all interfaces, use localhost

- requirements-opt.txt
- requirements.txt
Scandir requires both the python development headers and GCC in order to be built. So, it should be in requirements-opt rather than the main requirements file. If you want to install it from source, we should allow you to be able to do that without Python.h or gcc.
> adds scandir to requirements-opt

- checks.d/tokumx.py
Tokumx has a bug where a key should be more differentiated than it is, as it is, it 4 different values share this key, so it's updated any time any of them update, sending false data back to the server. This PR fixes it.
> [checks][tokumx] fixes the div by zero error in tokumx

- packaging/datadog-agent/source/setup_agent.sh
Installing the Datadog Agent from source leaves a `setuptools-X.Y.Z.zip`
left over file. Archive it.
Fix #2533
Thanks @paulmenzel.
[skip ci]
> [source] archive setuptools

- README.md
If you're a doofus and don't know that bundler is a Ruby gem, then you won't know how to install it unless someone tells you.
> Added a note on how to get bundler installed

- checks/system/win32.py
When timing out, the memory check illegitimately returns `None` instead
of an empty list, causing an error in the collector 💀..
```
2016-05-17 15:19:23 Pacific Daylight Time | WARNING |
checks.collector(win32.pyc:148) | Timeout while querying
Win32_PerfRawData_PerfOS_Memory WMI class. Memory metrics will be
returned at next iteration.
2016-05-17 15:19:23 Pacific Daylight Time | ERROR |
checks.collector(collector.pyc:293) | Unable to fetch Windows system
metrics.
File "checks\collector.pyc", line 286, in run
TypeError: 'NoneType' object is not iterable
```
Fix it.
> [win32] plays well memory check timeouts

- checks.d/sqlserver.py
And not just at the beginning.
This also deletes the useless cache_failure feature.
> [sqlserver] send service checks at every run

- agent.py
- checks.d/agent_metrics.py
- checks.d/btrfs.py
- checks.d/disk.py
- checks.d/gunicorn.py
- checks.d/linux_proc_extras.py
- checks.d/mysql.py
- checks.d/network.py
- checks.d/process.py
- checks.d/system_core.py
- checks.d/system_swap.py
- checks/__init__.py
- checks/collector.py
- checks/system/unix.py
- config.py
- datadog.conf.example
- utils/kubeutil.py
Allows overriding of `/proc` by defining `procfs_path` in `datadog.conf` - should be enforcable by using `self.agentConfig.get("procfs_path")` from any of the checks. I believe we enforce that pretty much everywhere relevant with this PR.
Places where we haven't overriden it just yet: 
- https://github.com/DataDog/dd-agent/blob/jaime/config_proc/daemon.py: because we haven't read the configuration yet.
- https://github.com/DataDog/dd-agent/blob/jaime/config_proc/utils/process.py: because when those functions are called, we haven't read the configuration either.
> [linux] make /proc configurable.

- checks.d/postgres.py
- conf.d/postgres.yaml.example
Counting the number of tables to provide the `postgresql.table.count` metric can be very expensive, especially on large clusters.
This PR contains two changes to mitigate the impact of a slow count:
1) Put an hard limit on the count, not user-configurable
2) Suggest to disable the metric in the `postgres.yaml` file
For backward compatibility, the metric is still collected by default
**Notice**: couldn't provide an integration test for the hard limit feature because the strings containing the SQL code are class fields evaluated at import time.
> [Postgres] hard limit on pg count metric

- packaging/osx/install.sh
For those with GNU utilities installed (`sed` in particular), the OS X "vanilla" `sed` command to set the API key into the configuration breaks. The proposed changes in this PR will check whether the vanilla or GNU version of `sed` is installed and use the appropriate command depending on the `sed` version.
> GNU-Friendly sed

- Rakefile
Enforces the use of ``python2`` while creating the ``venv/`` virtualenv, during the execution of ``rake setup_env``.
Without the ``-p`` option, virtualenv uses the ``python`` system executable. Unfortunately I'm running a system (ArchLinux) that uses Python 3 as a default and because of that, the virtualenv is not properly created.
> [dev] locating the system python2 to create the virtualenv

- agent.py
- utils/configcheck.py
- utils/flare.py
Right now the flare command doesn't collect service discovery configcheck command, we need to run `/etc/init.d/datadog-agent configcheck` explicitely. It's a very useful command for investigating config issues so let's add it.
> [flare] Add sd_configcheck output to flare command

- checks.d/win32_event_log.py
When the windows event `Message` evaluates to a "false" value, do not
select its value as the event's `msg_text`.
Same behavior for the `InsertionStrings`.
Fixes the integration test. This small regression was introduced in #2136.
> [win32_event_log] Fix small regression on `msg_text` selection

- checks.d/vsphere.py
When the vSphere check fails on an instance, its metadata -stored in the
class- may have not been populated.
Thus, the collector fails and raises a `KeyError` exception when
attempting to collect vSphere external host tags for the given instance,
i.e.
```
2016-05-23 10:10:13 Central Daylight Time | ERROR |
checks.collector(logger.pyc:19) | Uncaught exception while running run
File "utils\logger.pyc", line 16, in wrapper
File "checks\collector.pyc", line 486, in run
File "checks\collector.pyc", line 699, in _populate_payload_metadata
File "C:\Program Files (x86)\Datadog\Datadog
Agent\files\..\checks.d\vsphere.py", line 511, in get_external_host_tags
KeyError: 'foobar'
```
Do not raise, but log a warning instead.
> [vsphere] skip host tags for broken instances

- checks.d/mongo.py
Fix #2520
If you connect to mongo through mongos, there won’t be a `local`
database. But we shouldn’t fail the check if this happens as other
metrics would still be available.
> [mongo] Only try to connect ReplicationInfo metrics when we can

- ddagent.py
On older `tornado` versions (including the `dd-agent` default) the `allow_ipv6` option would default to `True` when using the `curl_httpclient` (expected), but would actually default to `False` when using the `simple_httpclient`. Since our default http client is the simple one, this implies that by default our ipv6 support requires enabling the curl client. This PR should address this.
Note: on newer tornado's the weird behavior was corrected, but doing this explicitly will hurt no one.
> [core] always default to ipv6, then fallback to ipv4.

- checks.d/mysql.py
The service check wasn't doing the right thing when running on the master. Should address issue #2596.
Couple things:
- We now default to collecting the number of slaves by looking at `SELECT * FROM INFORMATION_SCHEMA.PROCESSLIST WHERE COMMAND LIKE '%Binlog dump%'` because looking at the worker threads could be inaccurate (it's blocking though, but we should be fine).
- `Slave_running` will also be available on the master node, so we have to also check the number of slaves is 0 (or None). That should guarantee being on a slave, and not falling through that logic branch on a master (and thus report CRITICAL, when we're fine).
For now we're keeping the replication check on the master in case a customer would like to run the `dd-agent` just on that node and still get replication insights.
> [mysql] fix replication service check.

- tests/checks/mock/test_docker.py
- utils/dockerutil.py
Due to a bug on docker-py, whenever the Docker api fails at returning a stream of events, the library returns a plain string instead of a Json as expected, thus raising warnings on collector's logs.
Waiting for https://github.com/docker/docker-py/pull/1082 to be merged, this PR increases agent resilience to this problem.
The fix was tested by couple of customers.
> [docker] be resilient to dockerpy buggy api calls

- checks.d/iis.py
- checks.d/wmi_check.py
- checks/libs/wmi/sampler.py
- conf.d/iis.yaml.example
- conf.d/wmi_check.yaml.example
- tests/core/test_wmi.py
**[wmi] set a `provider` to request data**
`WMISampler` class has a new `provider` attribute to specify a WMI
provider to request data from.
Available options are:
* (Default) `ProviderArchitecture.DEFAULT`
Request from the provider corresponding to the version of the Datadog
Agent version installed, i.e. 32-bit on Datadog Agent 32-bit or
64-bit otherwise.
* `ProviderArchitecture._32BIT`
Request from the 32-bit provider.
* `ProviderArchitecture._64BIT`
Request from the 64-bit provider.
**[wmi_check] support `provider` option**
Add a `provider` option to the WMI check's YAML configuration file.
Instructs the check to request WMI data from the specified provider.
Available options are: `32` or `64`.
**[iis] support `provider` option**
Add a `provider` option to the WMI check's YAML …
> [wmi] set a `provider` to request data

- checks.d/haproxy.py
- conf.d/haproxy.yaml.example
- tests/checks/mock/test_haproxy.py
Fixes #2315
- Refactored the aggregation method by implementing a counter by context
- Added a few mock tests
- Fixed a bug on aggregates when `count_status_by_service` is disabled
> [haproxy] Add `collate_status_tags_per_host` option

- conf.d/sqlserver.yaml.example
The '%' character must be escaped as '%%' for adodbapi to make a
correct connection_string. Adding a comment to warn users in the
sqlserver.yaml.example file.
Only a comment, so [skip ci] is appropriate.
> [sqlserver] [skip ci] warn users about % char in yaml

- checks.d/mysql.py
When a MySQL 5.7 is a slave _and_ has a running binlog with no
downstream slaves attached, this check assumed that the instance was a
master with no running slaves.
Fix it so that it checks for Slave_IO_Running and Slave_SQL_Running
before checking for Binlog_enabled and Slaves_connected.
This PR should supersede #2493 - it is essentially no more than a rebase of it. We first look at the slave variables available in most 5.7+ versions, and if we don't yet have concluded on a status, we then look at possible master, slave combinations.
> [mysql] Fix slave_running for mysql 5.7 with slave binlog

- checks.d/kubernetes.py
- tests/checks/mock/test_kubernetes.py
- utils/dockerutil.py
- utils/kubeutil.py
Using the default route works fine in most cases, but if the user has a virtual network set up (like Calico) it won't point to the real host.
The docker host name is more reliable.
`_get_default_router` is not used anywhere else, so I killed it.
> Use docker hostname instead of default route to query cadvisor & kubelet

- requirements.txt
Docker recently introduced networks, docker-py 1.3.1 doesn't support them, let's upgrade to the most recent version.
tested successfully
related: https://github.com/DataDog/omnibus-software/pull/55
> Bump docker-py to 1.8.1 for network features

- config.py
- tests/core/test_service_discovery.py
- utils/service_discovery/abstract_config_store.py
- utils/service_discovery/abstract_sd_backend.py
- utils/service_discovery/sd_docker_backend.py
- improve test coverage for service discovery and logging
- support ip address collection from networks when available (for docker > 1.9)
- make template variable interpolation more resilient
- add the ability to specify keys on top of indexes for template variables (eg: `host_bridge` will return the IP address of the host on its bridge network)
- kill some dead code
> [service discovery] Improve logging, test coverage and template variable interpolation

- tests/core/test_service_discovery.py
- utils/kubeutil.py
- utils/service_discovery/abstract_config_store.py
- utils/service_discovery/sd_docker_backend.py
To make it possible to associate explicitly a configuration template with a container, and fix the image name extraction.
- This PR makes it possible to assign a `datadog_id` label to containers that specify the config store key associated with the configuration template for said container. If such label is not applied, falls back to image name matching.
- The image name matching has also been fixed, it didn't play well with private image repositories serving on a custom port. To avoid breaking backward compatibility we still fall back to the old format. The new resolution order is: `configuration file --> container label --> full image name --> legacy image name --> auto-config`
- supersedes #2583 
- fixes #2576
> [service discovery] Replace buggy image name extraction with get_identifier.

- appveyor.yml
- checks/check_status.py
- ci/default.rb
- ci/windows.rb
- config.py
- tests/core/test_autorestart.py
- tests/core/test_bucket_aggregator.py
- tests/core/test_check_status.py
- tests/core/test_common.py
- tests/core/test_datadog.py
- tests/core/test_dogstatsd.py
- tests/core/test_ec2.py
- tests/core/test_flare.py
- tests/core/test_modules.py
- tests/core/test_run_files.py
- tests/core/test_service_discovery.py
- tests/core/test_tail.py
- tests/core/test_transaction.py
- tests/core/test_watchdog.py
- tests/core/test_win32_agent.py
- tests/core/test_wmi.py
- transaction.py
- utils/flare.py
- utils/jmx.py
Allows the CI to pass (on AppVeyor) for the `default`, `core_integration` and `windows` test suites.
The tests that run only on unix are tagged with `@attr('unix')`. A few tests have been disabled on Windows for specific reasons that are documented in comments.
All the tests pass except for `test_parallelism` and `test_no_parallelism` of `tests.core.test_transaction` that are extremely flaky. They have been disabled on Windows for now.
cc @yannmh, @degemer
> [win32] Fix core unit and integration tests

- agent.py
- checks/collector.py
- checks/datadog.py
- checks/libs/wmi/sampler.py
- config.py
This commit:
- removes the creation of a Ganglia object when not enabled
- "       "   "        "  " Dogstreams "   "    "   "
- removes the `Sample: ...` debug logs for WMI
> [core] clean debug logs and kill Dogstream-based DdForwarder

- checks/collector.py
- Only send a processes payload when gohai actually returns data
- Remove the `format_description` and `format_version` fields
> [gohai][processes] Simplify payload

- utils/dockerutil.py
Followup to https://github.com/DataDog/dd-agent/pull/2608, added comments to keep memory of the workaround.
> [docker] added comments to temporary workaround

- checks.d/iis.py
- tests/checks/mock/test_iis.py
Do not log a warning about non digit property values for the 'Name'
property.
Test that the check completes with no warnings.
> [iis] no warnings on 'Name' property 🔇

- checks/check_status.py
- win32/status.html
Reading the proxy settings is a bit costly as it reparse the whole
config file and we do it every time we persist the forwarder status.
This information is not that valuable as it will be collected by a
flare anyway. Let’s just remove it
> [status page] Remove proxy info from it

- packaging/debian/datadog-agent.init
On Kernel 3.18+ on some distributions that also use overlayfs, certain commands will fail. However, they'll work fine if they're not using overlayfs.
This is a stopgap solution, so that the commands will work on our docker testing environments.
> kernel 4+ won't error out on status now

- checks.d/docker_daemon.py
Docker Status rounds the disk metrics, which means something like this
can happen:
```
[u'Data Space Used', u'5.238 GB']
[u'Data Space Available', u'18.12 GB']
[u'Data Space Total', u'23.35 GB']
```
So:
```
used = 5238000000
free = 18120000000
total = 23350000000
```
With `used + free > total` because of the rounding error.
In this case, this commits changes the default behavior to taking
`total` as `used + free` and calculating the disk percentage based on
that. (There should only be a small difference between `total` and `free + used`)
> [docker_daemon] fix disk metrics rounding issue

- checks.d/http_check.py
This option was removed by mistake a while back, let's add it back.
> [http_check] Bring back include_content option

- checks.d/dns_check.py
- conf.d/dns_check.yaml.example
- tests/checks/mock/test_dns_check.py
New `record_type` optional parameter in the configuration.
Along with tests: runs of the check in `test_invalid_config` now reload
the config correctly and test that the expected exception is raised.
> [dns_check] Allow querying a custom record type

- checks.d/redisdb.py
The `command` field can be empty with the current version of redis-py
querying a custom "Garantia Data" Redis version.
In this case, and until redis-py adds support for it, we just send the
histogram without the `command` tag, which is better than nothing.
Fixes #2629 
Thanks @fotinakis for reporting this issue!
> [redisdb] Avoid exception when slowlog query returns empty `command`

- requirements.txt
Supervisor 1.3.1 has a bug in it: https://github.com/Supervisor/supervisor/issues/562
This will upgrade it to fix the bug.
> [core] upgrades supervisor to avoid supervisor bug

- agent.py
It's cleaner and it prevents the thread pool from growing with no limit after each configuration reload if a network check is enabled.
> Stop checks before reloading them

- checks.d/iis.py
- tests/checks/mock/test_iis.py
- tests/core/test_wmi.py
Before this commit, the check would tag metrics from sites of the same instance with multiple `site:` tags on each metric.
Fix this behavior and improve existing tests to catch the issue.
> [iis] Fix metrics tagging when multiple sites are specified on instance

- dogstatsd.py
The dogstatsd server error message does not currently include enough information. It should include the serveraddr as well, especially because, when it errors out, the message comes directly after the message `2016-07-12 19:34:47 UTC | INFO | dd.dogstatsd | dogstatsd(dogstatsd.py:165) | Reporting to http://localhost:17123 every 10s` this can easily be confusing.
> [core] better dogstatsd server error message

- checks.d/openstack.py
Sometimes the check doesn't find the Neutron/Nova endpoint because the name is
not what is expected. This commit extends the current search by adding
one possible name for each component: 'Compute' for Nova and
'Networking' for Neuron.
> [openstack] nova/neutron extend name search

- datadog.conf.example
Fix format and remove trailing whitespace in **datadog.conf.example**
> Fix format and remove trailing whitespace

- checks.d/docker_daemon.py
- conf.d/docker.yaml.example
- utils/dockerutil.py
Containers may be run with custom cgroups, not necessarily falling under the default docker one. Typically I think we should expect these to be subgroups of the docker cgroup, although I'm not sure if that can be guaranteed (maybe we can make that a requirement - amongst other things because the docker group should probably have read privileges to the cgroup files - more testing in order). When customers decide to run the containers like this, we were unable to pick up on the cgroup stats and the check fails.
If we are aware of the container <pids>, which we are (at least when running the agent on the host), we can quickly grab the cgroup file locations by parsing /proc/<pid>/cgroup. We can then iterate over the mountpoints, searching for these files in the particular subsystems of …
> [docker_daemon] resolve hierarchy by looking at procfs <pid>/cgroup 

- checks.d/jenkins.py
- conf.d/jenkins.yaml.example
Its replacement is ready now, so we can go ahead and deprecate it.
(See #1918 which reverted the deprecation because the replacement wasn't deemed ready at the time)
> [jenkins] Deprecate check

- tests/core/test_ec2.py
- util.py
Docker info sometimes returns default EC2 hostnames and `get_hostname`
wasn't checking whether it was possible to use the instance id.
This commits change this behavior by allowing `get_hostname` to check
the docker proposed hostname before using it.
> [core] don't use docker hostname if it's a EC2 one

- checks.d/win32_event_log.py
Otherwise the check can fail with
```
File "checks\__init__.pyc", line 750, in run
File "C:\Program Files (x86)\Datadog\Datadog Agent\files\..\checks.d\win32_event_log.py", line 147, in check
File "C:\Program Files (x86)\Datadog\Datadog Agent\files\..\checks.d\win32_event_log.py", line 240, in to_event_dict
File "C:\Program Files (x86)\Datadog\Datadog Agent\files\..\checks.d\win32_event_log.py", line 210, in _msg_text
UnicodeEncodeError: 'ascii' codec can't encode character u'\u200e' in position 31: ordinal not in range(128)
```
> [Event log] Unicode everything

- checks.d/http_check.py
- checks.d/openstack.py
- checks/__init__.py
- conf.d/openstack.yaml.example
Customers often have boxes that must route http/https traffic through a proxy. Their keystone server, and openstack API calls might have to use the proxy. The openstack check should be proxy aware, this check aims to provide that functionality.
Also, in case the keystone/openstack servers happen to be in the LAN and not require the proxy (even though the agent might), we also introduce a `use_agent_proxy` flag to the openstack config to override the behavior at will.
Also improving support for openstack Mitaka. On mitaka (despite being v2.1) the nova endpoints don't match the `novav21` pattern, instead they match directly to nova. The small changes to how we deal with nova endpoint versions should allow us to get the endpoints if the right `nova_api_version` is overridden in the YAML. …
> [openstack] openstack should pick-up on proxy settings set on agent

- checks.d/elastic.py
- ci/elasticsearch.rb
- ci/resources/elasticsearch/elasticsearch.yml
- tests/checks/integration/test_elastic.py
When the `cluster_stats` parameter is enabled in the user configuration,
the Datadog Agent's Elasticsearch check attempts to resolve and
attach with the corresponding metrics, the hostname of the different
nodes.
On Amazon Elasticsearch v1.5.2, the node objects
returned by the `_cluster/nodes/stats?all=true` endpoint returns the
following keys:
```
root@xxxx:~# cat node_stats.json| jq '.nodes[] | select(.name ==
"${hostname}") | keys
[
"breakers",
"fs",
"indices",
"jvm",
"name",
"os",
"process",
"thread_pool",
"timestamp"
]
```
where `name` contains the hostname.
> [elastic] improve hostname resolution

- dogstatsd.py
- tests/core/test_dogstatsd.py
We used to pass an empty string `''` meaning `any available interface` when `non_local_traffic` is present in the config file.
This doesn't play well with the new code since we now use a unique, fullstack socket so we explicitly set the IPv4 meta address `0.0.0.0` for retro compat.
This leaves an open issue: it's not possible to start the agent with `non_local_traffic` on an IPv6 only environment. For standalone Dogstatsd instances this is not a real issue, one can pass `::` as `bind_host`.
> [dogstatsd] fix server address when non_local_traffic is passed

- checks/network_checks.py
When the HTTP check is misconfigured, the thread pool used for network
checks woud restart over and over without providing any usefull
information, i.e.
```
Running check http_check
Stopping Thread Pool
Starting Thread Pool
Stopping Thread Pool
Starting Thread Pool
received 0 payloads since last flush
```
Instead, exceptions should be logged so it is easier to troubleshoot.
> [http_check] log exceptions 🔊

- config.py
- tests/checks/common.py
- tests/core/test_config.py
`AgentCheckTest.load_check()` and `load_check()` in `tests.checks.common` are both needed, one by integration tests, the other by unit tests (respectively). We could maybe get rid of the former but it would involve too many changes at the moment. The proposed changes will allow both unit tests (if added in the SDK) and integration tests to correctly load the checks in the testing infrastructure.
Also, because integrations-core would've been dropped into `3rd-party`, and that is misleading, renaming to `dd-integrations`.
> [sdk] minor tweaks - sdk env detection, check location

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
This PR adds templates for new issues and PRs so that formatting and pre-reqs are pre-populated. 
In order to speed up responses to issues and PRs, we want to ensure key information is included.
1. Create a new issue or PR via the Issue link in this repo.
1. Validate that the new issue or PR contains the template text.
N/A
> add issue and pr templates

- checks.d/marathon.py
…properly built when the base url included a path.
As tested in the REPL, the fix will properly join base url's and paths:
```
>>> urljoin("http://marathon.mesos", "v2/apps")
'http://marathon.mesos/v2/apps'
>>> urljoin("http://marathon.mesos/service/marathon/", "v2/apps")
'http://marathon.mesos/service/marathon/v2/apps'
>>> urljoin("http://marathon.mesos", "v2/apps")
'http://marathon.mesos/v2/apps'
>>> urljoin("http://marathon.mesos/", "v2/apps")
'http://marathon.mesos/v2/apps'
>>> urljoin("http://marathon.mesos:8080", "v2/apps")
'http://marathon.mesos:8080/v2/apps'
>>> urljoin("http://marathon.mesos:8080/", "v2/apps")
'http://marathon.mesos:8080/v2/apps'
```
Care needs to be taken to include a trailing slash in the base URL when there is a path included.
```
>>> …
```
> Fix a small problem that prevented marathon full path from being properly built 

- checks.d/ssh_check.py
If the ssh check has trouble loading a private key file, we log a generic error message so that it's impossible to determine the cause.
Catch specific exceptions and log different warning messages.
> [ssh] Be more specific when logging ssh errors

- ci/default.rb
Adds the `-P` option to `xargs` to run more than one `pylint` process in parallel. The `--jobs` options offered by `pylint` was the first choice but it's buggy, so the fallback to `xargs`.
The execution is sequential so on Travis one core is sitting during the checks. Moreover, `pylint` has a huge overhead at startup that in our case is multiplied by the number of files to process, ~270. 
The first problem is addressed by the `-P` option passed to `xargs`, the second one is addressed by letting each `pylint` instance inspect 100 files per run (`-n 100` passed to `xargs`).
> [CI] run multiple instances of pylint

- agent.py
- daemon.py
- dogstatsd.py
- utils/proxy.py
Remove noisy logs.
Not see them anymore.
:fire:
> [core] remove noisy logs

- checks.d/gearmand.py
- conf.d/gearmand.yaml.example
* Add metrics to collect data on each individual task. This lets you see how many of each task is queued to catch problems with each individual queue's processing.
* Each new metric is tagged by task:<task_name>
* List of tags: gearman.queued_by_task, gearman.running_by_task, gearman.workers_by_task
* Here is an example in metrics explorer with this new data:
> Add per-task gearman metrics

- checks.d/process.py
Uses the configured proc path (`psutil.PROCFS_PATH` which is set during the check's initialization) when getting pagefault stats instead of `/proc`. 
I found https://github.com/DataDog/dd-agent/pull/2482 (makes proc path configurable) after wanting to run the process integration in docker with, and noticed the page fault stats still used '/proc' which means the integration wouldn't be able to get accurate stats if proc path was something else.
> [process] Use configured proc path when getting pagefault stats

- checks.d/kubernetes.py
This might have saved me a lot of time debugging issues, making it more obvious that I was trying to access "localhost:10255" from within the dd-agent container.
> Log URL in kubelet check failures

- checks.d/mysql.py
- conf.d/mysql.yaml.example
Allow a connection timeout to be used on when connecting to MySQL instances.
When monitoring more than one instance of MySQL, if the host becomes unavailable, it'll block all the other MySQL instance checks. This block can be longer than the polling period, and you get false alerts and service checks.
Use case: Monitoring many RDS instances from a single host. A failover event occurs, causing connection issues to a single box temporarily. This connection hang (while the Master is being rotated), also blocks all the other monitored instances. 
Unsure how to a reasonable test case. Other than pull a remote host down, or disable networking.
Defaults to the original no-timeout '[None](https://github.com/PyMySQL/PyMySQL/blob/pymysql-0.6.6/pymysql/connections.py#L822)' behaviour. When the …
> Allow `connection_timeout` to be set for MySQL checks

- checks.d/disk.py
- tests/checks/fixtures/disk/centos-df-Tk
- tests/checks/mock/test_disk.py
remove missing method `_is_number` in `disk` check.
Fix https://github.com/DataDog/dd-agent/issues/2732
The previous method was:
```python
try:
float(my_var)
except:
return False
return True
```
> [disk] handle multilines df output

- checks/wmi_check.py
- tests/checks/integration/test_wmi_check.py
Fix flaky `tag_queries` test in wmi check integration test.
`CommandLine` is generally empty for the `svchost` processes, which
makes the check fail when used as a target property of `tag_queries`
(for good reasons IMO). Let's use a property that we're sure exists
and is not empty.
Also, make the error message clearer when the target property exists
but is empty.
Fix a flaky test, and have a better error message for missing/empty target properties
> [wmi_check][test] Fix flaky `tag_queries` test

- .gitignore
- checks.d/http_check.py
- conf.d/http_check.yaml.example
- tests/checks/integration/test_http_check.py
Hi, I add allow_redirects parameter http_check. Because I want to check http status only 301 or 302.
Regards,
> [http_check] Add allow_redirects parameter

- checks.d/haproxy.py
- checks.d/hdfs_datanode.py
- checks.d/hdfs_namenode.py
- checks.d/mapreduce.py
- checks.d/nginx.py
- checks.d/rabbitmq.py
- checks.d/yarn.py
- checks/__init__.py
- datadog.conf.example
Adds a timeout to many integration's HTTP request methods.
We recently a problem with a cluster that caused the HTTP response to not return for awhile. It ended up repeatedly being killed by the watchdog and at one point even did this somehow:
```
2016-07-08 15:06:28 UTC | INFO | dd.collector | checks.collector(collector.py:539) | Finished run #1. Collection time: 146.23s. Emit time: 0.04s
```
This could've been easily avoided with a timeout!
O_o
I picked 9 because it's < 10. Adding this an instance variable on the class — as is done in some other integrations — seemed Hard because i'd have to thread it through all the various functions that are called. Open to suggestions on this.
I came along in 2nd commit and added this to every place I found it missing that we used. I'd love to see …
> Add an HTTP timeout to many integrations.

- checks/__init__.py
- tests/core/test_common.py
If the `min_collection_interval` > 300 (the default expiration time) then metrics would be expired before running the next interval. This would affect rates, post expiration messages on the log file, and remove metric contexts when it probably shouldn't.
Make the expiration time be `X + min_collection_time` where X would typically be the default expiration time.
> [core] expiration should adjust to longer collection intervals (>300s).

- checks.d/rabbitmq.py
- tests/checks/integration/test_rabbitmq.py
- tests/checks/mock/test_rabbitmq.py
A new status check was added, `rabbitmq.status` that reflects the status of the RabbitMQ service (up/down), which is different from the outcome of the `aliveness` strategy that is still implemented by the existing `rabbitmq.aliveness` status check.
The aliveness check is misleading when the RabbitMQ service is down - an exception is raised and the check simply provides _no data_ whilst the _info_ command, along with the UI correctly report an issue for the integration.
> [RabbitMQ] new health check

- checks.d/kafka_consumer.py
- requirements.txt
Bumps the version of the kafka-python package.
Improve support for newer kafka's.
(none)
> [kafka] bumping kafka-python package version to 1.2.5.

- packaging/centos/datadog-agent.init
- packaging/debian/datadog-agent.init
Completely silence configcheck when starting.
Seeing useless DEBUG logs when restarting: 
```
Stopping Datadog Agent (stopping supervisord): datadog-agent.
2016-08-02 19:14:37,645 | DEBUG | dd.collector | utils.proxy(proxy.py:68) | No proxy configured
2016-08-02 19:14:37,653 | DEBUG | dd.collector | utils.dockerutil(dockerutil.py:67) | Couldn't find any configuration file for the docker_daemon check.
2016-08-02 19:14:37,657 | DEBUG | dd.collector | docker.auth.auth(auth.py:189) | File doesn't exist
2016-08-02 19:14:37,678 | DEBUG | dd.collector | utils.subprocess_output(subprocess_output.py:63) | Popen(['/bin/hostname', '-f'], close_fds = True, shell = False, stdout = <open file '<fdopen>', mode 'w+b' at 0x7f33765079c0>, stderr = <open file '<fdopen>', mode 'w+b' at 0x7f3376507a50>, stdin …
```
> [packaging] silence configcheck when starting

- utils/dockerutil.py
In case, the agent cannot resolve the docker host hostname, we fall back on the default gateway.
Customer ticket on kubernetes where the agent was unable to resolve the docker host hostname.
> [docker] Fall back to default route if docker hostname is not resolvable

- checks/network_checks.py
When looking over the Network Check class, I noticed a few issues in the constructor for the class. This PR enables the duplication check and stops overwriting another method parameter.
> Network check corrections

- checks.d/mongo.py
- ci/mongo.rb
- conf.d/mongo.yaml.example
- tests/checks/integration/test_mongo.py
This PR adds some additional metrics from collections. It will now collect the following metrics from each collection (from the database that you're collecting from):
```
mongodb.collection.indexSizes
mongodb.collection.size
mongodb.collection.avgObjSize
mongodb.collection.count
mongodb.collection.capped
mongodb.collection.max
mongodb.collection.maxSize
mongodb.collection.storageSize
mongodb.collection.nindexes
```
Collection level metrics, like the amount of space that a collection is taking up, or the average object size, scoped to a specific collection, can be very important. If a certain collection is too large, maybe it should be split up. If the indexes on a collection are getting much, much larger than the others, maybe you want to split the collection. There are a lot of these …
> [mongo] Adds metrics for collections

- aggregator.py
- dogstatsd.py
Copy/paste from the two commits:
Previously, if `dogstatsd` received a packet with an incorrect metadata (empty
for example), it would fail and raise an exception without explanation.
This commits changes this behaviour: if something is wrong with the metadata,
it is logged at warning level but does not fail.
Previously dogstasd was only logging
```
except Exception:
log.exception('Error receiving datagram')
```
whereas the `parse_*` functions were trying to raise useful errors.
This shouldn't happen anymore, as the parse exception are now handled and
logged in the aggregator.
It has another benefit: if there are incorrect packets in the "datagram",
the correct ones will be processed correctly (it was not the case before,
`dogstatsd` was failing at the first incorrect packet).
> [dogstatsd] improve logging of incorrect packet

- ci/mongo.rb
If Mongo installation gets dirty for any reason, the CI enters a persistent failing state
I was sick of seeing the failing badge on the README
> [CI] cleanup mongo installation before running tests

- checks/collector.py
Lower log level of the `Running check xxxx` message after the first run of the collector.
Since we removed the LaconicFilter (see #2605) the collector is filled
with `Running check xxxx` messages that get logged for every check
at every run. It fills up the logs too quickly for an info-level logging.
`rake run` on my dev env, looked at the collector logs: it works
> [collector][logging] Log check starts with info level on first run only

- agent.py
- checks.d/docker_daemon.py
- config.py
- tests/core/test_service_discovery.py
- util.py
- utils/dockerutil.py
- utils/platform.py
- utils/service_discovery/abstract_config_store.py
- utils/service_discovery/abstract_sd_backend.py
- utils/service_discovery/config_stores.py
- utils/service_discovery/consul_config_store.py
- utils/service_discovery/etcd_config_store.py
- utils/service_discovery/sd_docker_backend.py
It makes configuration reload smarter.
The gist of it is that the agent now maintains a mapping `container_identifier <--> checks` and only reloads checks for which a docker event associated with an identifier in this mapping happened since the last collector run.
In environments where a lot of docker events happen, full config reload on any container event is not a good design. We noticed several cases where the agent triggered a reload at each run, making rate collection impossible (calculating rates requires values from several runs, and these are forgotten on each check reload).
Individual reload is a better option.
In more details:
- the `identifier_to_checks` cache is built based on the content of the config store and the `auto_conf` folder. This cache is invalidated and refreshed …
> Improve service discovery to only reload checks that need it

- checks.d/mongo.py
Connection to database going in db.command function, but the call of this function happens outside of exception block. The check can't catch unreachable instances and integration check mongodb.can_connect doesn't work properly
> [mongo] repairing of mongodb.can_connect check

- checks.d/php_fpm.py
- conf.d/php_fpm.yaml.example
- util.py
This PR allows you to override the Host HTTP header sent during requests to the fpm status and ping URLs.
In load-balanced configurations it's possible an FPM pool is only mapped to http://production.url/status and not http://localhost. But production.url points to some load balancer which distributes load across many different servers.
To be able to test local servers you need to be able to say "Connect to localhost, but tell it you're after production.url"
This change adds the Host HTTP header if defined, otherwise the check works as is. The check has integration tests, and from them I was unable to figure out how to make a check that demonstrates a failing and a working check based on differing Host headers.
> [php5_fpm] allow Host header override

- checks.d/kubernetes.py
- conf.d/kubernetes.yaml.example
- tests/checks/fixtures/kubernetes/events.json
- tests/checks/fixtures/kubernetes/metrics_1.2.json
- tests/checks/fixtures/kubernetes/pods_list_1.2.json
- tests/checks/fixtures/kubernetes/proc_net_route.txt
- tests/checks/mock/test_kubernetes.py
- utils/kubeutil.py
* Fetch events from the Kubernetes API and feed them to Datadog.
* Add new `limits` and `requests` metrics.
Logic recap:
* ~~Each agent fetches the whole list of available events and discards those not regarding pods running on the same node.~~
* If the `collect_events` config param is set to `True`, the agent fetches the whole list of available events
* ~~The strategy above could be replaced with delegating~~ Users should delegate one and only one agent pod to collect and send all the events - that agent possibly being the one running on k8s master. This unfortunately doesn't work on GCE where the master is not part of the cluster but it's provided by the platform as an external service instead. How to achieve this part is left to the users.
* To avoid duplicates, the timestamp of the …
> [kubernetes] Ingest k8s events + limits and requests metrics

- .travis.yml
- ci/common.rb
This PR tries to avoid running a integration test for an agent check (and
only this, core integration tests, linter and core mocked tests are
always run) when it is not required.
To do this, we first lists all modified files, and then
- check if a check file was modified (in `checks.d`)
- check if a check test file was modified
- ignore fixtures and configuration
If any file other than the one listed above are modified, all tests will
be run. Otherwise, a list of modfied checks is built, and only these
tests will be run (with the core tests).
Faster Travis.
> [ci] do not run integration tests if not relevant

- checks.d/postgres.py
- conf.d/postgres.yaml.example
- tests/checks/integration/test_postgres.py
This PR adds a flag in the postgres check to use psycopg2 instead of pg8000
See discussion at #2755 
Added a test that enables this flag. Also modified existing test to make sure it keeps using pg8000 by default.
Some other approaches more "global" could be tempting, but they wouldn't let the possibility to do it on a per instance basis.
> [postgres] Allow to use psycopg2

- checks.d/mysql.py
Work around an issue in mysql where if the unit is not specified by the user in the config file for `key_buffer_size` (eg. 4 instead of 4G) the value will be `0` in `GLOBAL VARIABLES`.
fix #2777 
Of course the config should be corrected on the user side but we can avoid failing on that rather easily so let's do it.
> [mysql] Check for null key_buffer_size before dividing by it

- checks.d/process.py
- tests/checks/integration/test_process.py
Adds `system.processes.mem.pct `metric to the agent process check
Requested here: https://trello.com/c/H1Tz2Ksd/2103-process-check-metric-for-memory-usage-as-percentage
> add system.processes.mem.pct metric to process check

- checks.d/docker_daemon.py
- utils/dockerutil.py
This adds a `docker.cpu.throttled` metric to the metrics generated by `docker_daemon.py`.
This metric is easily obtained from `docker stats` but missing from DataDog, and can be useful in determining if a container is getting CPU throttled.
> Add CPU throttling stats to Docker metrics.

- checks.d/docker_daemon.py
- util.py
- utils/dockerutil.py
Dogstatsd calls util.get_hostname that in turn was making calls to service discovery related code. This PR remove this behavior.
Although it was just calling the constructor of the config store class as a side effect, it's better to keep things separated.
We should make sure the hostname is still resolved the same way to avoid breaking things. This was tested locally with and without docker and the results are satisfying.
🙈
> [core] avoid calls to service discovery from dogstatsd

- checks.d/docker_daemon.py
- utils/dockerutil.py
ECS agent container no longer has the IP address or ports available when we inspect its container to infer the introspection point. The docker gateway, typically at `172.17.0.1` is fine for constructing the url to query the API. We can set it as a parameter in the config file, or we can extract it from the agent's own information.
Also, although rare, if the agent is not run dockerized, we can grab it `@localhost`
Our ECS task reporting broke due to our inability to query the endpoint. …
> [docker_daemon] [ecs] introspection resilience

- checks/libs/wmi/sampler.py
- utils/debug.py
**[wmi] set provider architecture when necessary**
On Windows 2008, setting a WMI provider would cause an exception.
To prevent this from unecessarily happening, only proceed when the
provided value is not set to the default one.
**[debug] improve `run_check` compatibility**
Datadog Agent checks do not necessarily inherit directly from the
`AgentCheck` class. When it is the case, the `run_check` DEBUG method
would fail loading the check.
This happens with WMI checks for instance.
Allow the `run_check` DEBUG method to load any agent check that inherits
from the `AgentCheck`.
> [wmi] set provider architecture when necessary

- checks.d/disk.py
- tests/checks/mock/test_disk.py
Timeout disk usage queries after 5 seconds with a warning and no data.
Recover at next iteration retrieving the existing query.
> [disk] timeout on disk usage

- checks.d/mongo.py
To authenticate using a X.509 certificate, one must use the `db.auth()`
method specifying `MONGODB-X509` for the `mechanism` field, and the user
that corresponds to the client certificate for the user field.
More information:
https://api.mongodb.com/python/current/examples/authentication.html
https://docs.mongodb.com/manual/tutorial/configure-x509-client-authentication/
> [mongodb] authenticate with X.509

- checks.d/network.py
- tests/checks/mock/test_network.py
- win32/gui.py
* Added a `psutil`-based check method
* Make Windows use the above
* Enable the check in the Windows GUI
> [Network] Implement the check using psutil on Windows

- checks.d/win32_event_log.py
- checks/libs/wmi/sampler.py
What does this PR do?
PR fixes a customer problem whereby the CPU consumed by the Win32 event log check would increase linearly with time.
Motivation
Customer request
Testing Guidelines
An overview on testing
Additional Notes
Reset WMI query filters before each run. Otherwise, all checks are done relative to when the agent was started, resulting in an ever-growing list of events to be parsed.
The WMI filter was attached to the (cached) sampler object. So, even though the filter was recomputed each time with a new "TimeGenerated >= " string, that was never actually used by the WMI query. So, each successive query returned any new entries, PLUS any entries that had already been retrieved. Processing the list then had a linearly increasing time …
> Make sure the filter gets updated with the last timestamp on each

- checks.d/elastic.py
- tests/checks/integration/test_elastic.py
This adds a bunch of metrics that are missing. I've tracked down the versions of Elasticsearch that each new metric was added, so this should be useful regardless of what version of ES you run.
It's worth noting that there are definitely more metrics missing (primary shard level metrics in particular). If we end up needing these metrics I'll create another pull request.
We need these metrics to accurately see what's happening inside our production clusters. DataDog support advised me that there was no specific timeline to getting these metrics added so I decided to fix it myself and contribute so others can benefit.
I wasn't able to get the tests to pass locally. I've set up a single Elasticsearch node locally running on the correct port and tests fail (with or without my changes). There …
> elastic - add missing metrics

- conf.d/cassandra.yaml.example
Read and Write latency are not only a way to figure out how long it takes to run the specified operation against the given columnfamily, the count metric is also the only way to figure out how often we're reading from and writing to a column family.
cc @johnaxel
> [cassandra] Add read and write latency ColumnFamily metrics

- checks.d/mesos_master.py
- checks.d/mesos_slave.py
- conf.d/mesos_master.yaml.example
- conf.d/mesos_slave.yaml.example
Allow disabling the ssl verification in mesos master and slave checks. This is mostly useful for self-signed certificates. This new option is disabled by default. When it's enabled the agent raises a warning in the collector.
It was requested by a user.
🙈 
👯
> [mesos] make ssl check optional

- tests/checks/integration/test_elastic.py
`cluster_name` tag was removed from service checks in
https://github.com/DataDog/dd-agent/commit/d4c3d76d4ca20414d219957bbb8edfdf1ca46211
> [elastic][tests]❌ `cluster_name` service check tag

- checks.d/process.py
While testing for #2119, I found a few problems. `pids` should be a set as that's what is expected by `get_process_state()`. It also expects a set of integers, not `psutil.Process`es. This short PR addresses the two.
Found the bug while testing for the feature.
> [proc] fix to search by pid.

- utils/dockerutil.py
If we attempt to grab metrics from the `cpu` subsystem as is the case with the `throttled` metric introduced here #2724, we will currently fail to identify the correct `cpu.stat` file because the `cpu` subsystem will be mistaken for the `cpuacct` subsystem or similar. This PR attempts to address the issue for this and future metrics.
Also fixes badly indented function.
Found the bug while testing #2724.
> [dockerutil] cpu subsys will be mistaken for cpuacct, this fixes that.

- checks.d/disk.py
- tests/checks/mock/test_disk.py
In #2714, we solved a problem with disk usage where nfs mounts would hang. In some cases, we're still seeing them hanging, because `os.statvfs` is being called in another place as well.
This adds a timeout wrapper to that second call, as well.
> [disk] another timeout on disk usage
