config.py
ddagent.py

Forwarder drops payloads when it receives empty endpoints.
This was the previous behaviour, let's do the same. See https://github.com/DataDog/dd-agent/pull/2564.

[forwarder] drop payloads when no valid endpoint

---

checks.d/docker_daemon.py
conf.d/docker.yaml.example
conf.d/docker_daemon.yaml.example

We used to have `custom_cgroups` be a setting that would apply both at the `init_conf` and `instance` levels. This PR makes it only apply per instance. It also updates the documentation.
It's confusing to have it configurable on both levels. Also, there was a small bug. So let's just do this instead.

[docker_daemon] custom cgroups are per instance only. YAML updates.

---

checks.d/docker_daemon.py

On kubernetes a cgroup file will look like
```
root@dd-agent-nightly-rc-jnexb:/host/proc/17916# cat cgroup
10:net_prio:/5e5f675ab3dbd1353837e46d158a6401abe0673324568b204a3a183ea6a
42772
9:perf_event:/5e5f675ab3dbd1353837e46d158a6401abe0673324568b204a3a183ea6
a42772
8:blkio:/5e5f675ab3dbd1353837e46d158a6401abe0673324568b204a3a183ea6a4277
2
7:net_cls:/5e5f675ab3dbd1353837e46d158a6401abe0673324568b204a3a183ea6a42
772
freezer:/5e5f675ab3dbd1353837e46d158a6401abe0673324568b204a3a183ea6a4277
2
5:devices:/5e5f675ab3dbd1353837e46d158a6401abe0673324568b204a3a183ea6a42
772
4:memory:/5e5f675ab3dbd1353837e46d158a6401abe0673324568b204a3a183ea6a427
72
3:cpuacct:/5e5f675ab3dbd1353837e46d158a6401abe0673324568b204a3a183ea6a42
772
2:cpu:/5e5f675ab3dbd1353837e46d158a6401abe0673324568b204a3a183ea6a42772 …
```

[docker] Fix pid retrieval

---

checks.d/ceph.py
tests/checks/fixtures/ceph/ceph_10.2.2_mon_health.json
tests/checks/mock/test_ceph.py

Avoid check failure when the `detail` key of `health detail` contains info on non-osd components. The bug was introduced in https://github.com/DataDog/dd-agent/pull/2805
Improve check resilience.
PR includes a test case that reproduces the issue.
The `detail` key of `health detail` can contain info on the health of
non-osd units, for example:
```
mon.vagrant-ubuntu-trusty-64 low disk space -- 18% avail
```
In that case the check would previously fail with an IndexError because
the regex we use wouldn't match this string.
Ignore the entry instead.
cc @vagelim

[ceph] Fix check failure when health detail contains non-osd info

---

checks.d/ceph.py
tests/checks/mock/test_ceph.py

* Catch `KeyError` on `osd_pool_stats`
* Improve health metrics: the `ceph.num_full_osds` and `ceph.num_near_full_osds` metrics report values that make more sense and add `ceph.osd.pct_used` metric (see explanation below).
* Check resilience
* Improved usability of the health metrics
Updated the existing mock tests, and made them more detailed
Previous behavior: the `ceph.num_near_full_osds` and
`ceph.num_full_osds` would either:
* take the value `0` and be tagged with no `osd` tag if no osd is
reporting health issues
* take a value representing the usage percentage, tagged by `osd`
This doesn't really make sense with respect to the name of the metrics
(`num_*`). To solve this, replace these metrics with the following:
* `ceph.num_near_full_ods` and `ceph.num_full_osds` report the total …

[ceph] Improve health metrics

---

tests/core/test_service_discovery.py
utils/service_discovery/sd_docker_backend.py

When no key (network name or id) was passed to the `host` variable, we used to skip the `_get_fallback_ip` method and only try using the `Config.NetworkSettings.IPAddress` address (which is empty more often than not now). With this PR, `_get_fallback_ip` applies every time, using the `bridge` network address or the last network (sorted) address.
More and more often `Config.NetworkSettings.IPAddress` is empty, relying on it makes the agent fail in cases where it could infer the config automatically.
Updated the relevant mocks in unit tests
- Fix #2845 
- Also limit the `split('_')` to 1 to avoid splitting the specifier if it …

[service discovery] fix fallback IP address extraction

---

utils/dockerutil.py
utils/service_discovery/sd_docker_backend.py

dockerutil needs a reference to config_store to enable config reload. In some cases this reference was missing. This PR fixes that.

[service discovery] pass missing config_store reference to dockerutil

---

checks.d/docker_daemon.py
ci/docker_daemon.rb
tests/core/test_service_discovery.py
utils/dockerutil.py
utils/service_discovery/abstract_config_store.py
utils/service_discovery/abstract_sd_backend.py
utils/service_discovery/sd_docker_backend.py

This change makes the docker service discovery read the kubernetes annotations
to discover how to monitor a pod. This behavior is only triggered when a
service discovery backend isn't set. The 3 annotations looked for are:
- `com.datadoghq.sd/check_names`
- `com.datadoghq.sd/init_configs`
- `com.datadoghq.sd/instances`
The semantics are exactly the same as that of a KV store.
Fixes #2794
#2794 has more motivation. This allows not running a KV store and having multiple versions of monitoring configuration rolled out via standard deployment mechanisms.
Added a unit test.
I don't think there are any integration tests for service discovery, especially on kube. Either way, I'll be running this on my own kube cluster until this is upstreamed.

[kubernetes] Add ability to specify service discovery via kubernetes annotations

---

aggregator.py
config.py
tests/core/test_histogram.py

Support for a new histogram aggregate type, sum, which records the sum of all
values seen during the sampling period. Matches up with the [timing](https://github.com/etsy/statsd/blob/master/docs/metric_types.md#timing) option of the same name in the original statsd. 
Heavy users of statsd and have used `sum` there and went to enable it here and noticed it wasn't an option. 
/cc @jnunemaker

Add support for sum histogram_aggregates type

---

packaging/datadog-agent/source/setup_agent.sh

Bumps default version to the latest agent release - `5.9.0`.
New agent has been released.

[source] bumping to version 5.9.0.

---

checks.d/kubernetes.py

This a pull request proposal for issue #2872.
We simply replace time.mktime by calendar.gmtime which takes as input struct time in UTC like the ones used in Kubernetes events.

Fix incorrect time conversion for Kubernetes events

---

CHANGELOG.md

Updates the changelog with the 5.9.1 changes.
Issue with the 5.9.0 packaging due to building against the wrong dd-agent-omnibus.

[changelog][skip ci] 5.9.1 bugfix release changelog updates.

---

checks.d/docker_daemon.py

This PR sets the event `alert_type` (Status in app) to `error` if a container reports `die` or `oom`.
Currently all Docker events are set to the default `alert_type: info`, this change will allow for additional filtering in the event stream and event monitoring for event types that may not be expected.

[docker] set alert_type to error when for oom and kill events

---

packaging/datadog-agent/source/setup_agent.sh

Bumping source install to 5.9.1.
New release available.

[packaging][skip ci] bumping agent to 5.9.1.

---

packaging/datadog-agent/source/install_agent.sh

Fixes the install script when the `initscripts` package is not installed.
Tested the resulting install script on CentOS 5/6/7
The yum package of `datadog-agent` has a dependency on `initscripts`.
If we disable all the repos when installing `datadog-agent` _and_ if
`initscripts` is not installed `yum` won't be able to find the dep,
and the install will fail.
To fix this we fall back to installing the agent with all the repos enabled when
the install without them fails.

[install_script][yum] Enable all the repos when installing `datadog-agent`

---

checks.d/redisdb.py
conf.d/redisdb.yaml.example

Pass through ssl_* values from redisdb.yaml on to the redis constructor.
Hosted redis providers (e.g. redislabs.com) use SSL to protect the redis connections.  Passing through the ssl_* params enables monitoring of such providers.

enable monitoring of SSL-ified redis servers

---

checks.d/consul.py
conf.d/consul.yaml.example
tests/checks/mock/test_consul.py

This PR adds a new option to the consul check to include calculated network latencies based on https://www.consul.io/docs/internals/coordinates.html. Both inter and intra dc metrics are included. The dc to dc metrics are under `consul.net.dc-latency`, include `source_datacenter`/`dest_datacenter` tags, and are host-less. The node to node metrics are under `consul.net.latency`, are emitted per-host, and include a `consul_datacenter` tag.
Previously had access to this data in graphite and found it interesting/useful at times. It's nice to be able to see network latencies between hosts, racks, availability-zones, roles, etc using the host-level tags. 
This PR is a follow on to https://github.com/DataDog/dd-agent/pull/2647 which should be merged prior to merging this.

Consul net latency

---

checks.d/consul.py
conf.d/consul.yaml.example
tests/checks/mock/test_consul.py

A mechanism for detecting leadership changes that can be enabled on all server nodes in a cluster. It will emit a single event from the new leader. This avoids the need to designate a single agent as the watcher for leadership changes, all agents can watch themselves.

Implement consul self_leader_check

---

win32/agent.py

Datadog Agent on Windows can potentially hit "random" `WindowsError`
exceptions while restarting a process. The Windows agent's supervisor
(`win32/agent`) crashes and processes are not monitored, or restarted
anymore.
Catch `WindowsError` exceptions and retry later.
References:
http://stackoverflow.com/questions/17076679/windowserror-access-is-denied-on-calling-process-terminate?answertab=votes#tab-top

[win32] retry on process restart failures

---

ci/kong.rb
ci/resources/kong/setup_uuid.sh

Takes care of having a working Cassandra
don't ask, don't tell
Had to update Cassandra version, the old archive was giving a 404
I'm using rsync instead of curl to grab `utils-linux` b/c the curl shipped with Travis is quite old and doesn't support recent SSL implementations

[CI][Kong] if cassandra isn't there, kong env is broken

---

ci/kong.rb

move `make && make install` instructions for kong to the install stage
kong tests are slow

[CI][kong] compile kong in the install stage

---

checks.d/mesos_slave.py

Fixes a bug in the mesos-slave.py check. This check queries both the localhost and the master node. The bug is that even if you specify SSL for communicating with the localhost (slave), the master is always queried with plain HTTP. This is definitely a bug because it is impossible to configure a mesos cluster where master and slave are using different protocols.
I've got SSL enabled on my mesos cluster and this check just plain doesn't work with SSL enabled.
Anything else we should know when …

[mesos_slave] Connect to master with same protocol as slave

---

ci/resources/apache/httpd.conf

Apache won't start if we have a dangling pidfile

[CI][Apache] store pidfile in the volatile dir

---

checks.d/mongo.py

When sending MongoDB events back to DataDog, the agent parses the MongoDB connection string URI and attempts to extract the hostname (in the `hostname_for_event` function).
However, if the URI contains username/password auth (`mongodb://username:password@hostname:port`), the existing code will incorrectly extract the username and report that as the hostname.
This PR fixes that and should correctly extract the hostname, whether or not auth is used. It has been tested in production.
I didn't like seeing incorrect **datadog is PRIMARY** messages in my event stream.

[mongo] fixing hostname detection when username/password auth are part of the uri

---

utils/kubeutil.py

In the kubernetes check, use the env var KUBERNTES_SERVICE_HOST to specify the API endpoint, if present.
See https://github.com/DataDog/dd-agent/pull/2551#issuecomment-246413595 . When using dd-agent in namespaces such as `kube-system`, the kube-dns service might not be running, so the `kubernetes` host might not be present.

Use the env var KUBERNETES_SERVICE_HOST if present

---

checks.d/kubernetes.py

This fixes parsing of resource quantities in Kubernetes resources and limits. Right now suffixes like G, M, m, etc. get simply ignored, leading to wrong numbers (unless you manage to always end up with absolute bytes/CPU numbers without any units).
It's based on the second part of #2766, but with some optimizations (precomputing stuff once at the module level).

Fix parsing of units in Kubernetes resource quantities

---

checks.d/kubernetes.py
conf.d/kubernetes.yaml.example
tests/checks/mock/test_kubernetes.py
utils/kubeutil.py

- add a few tags to k8s events
- also expose the `namespace` parameter in the check configuration file
Events are more useful with context.
The namespace parameter is interesting and deserves to be explicitly exposed.
Added a unit test for `KubeUtil.extract_event_tags`.

[kubernetes] add some tags to events

---

agent.py
utils/profile.py

If dumping pstats in the current dir fails, fall back to /tmp.
User noticed that they didn't get the dumps because the agent was trying to write to `/` as the default path is relative and they were probably running it with supervisor.
This was just a minor bug as the agent should not run in dev mode in production (it ruins its perf) and usually runs in the foreground from a directory where it has write access.

[dev mode] fallback to /tmp to dump pstats

---

tests/core/test_flare.py

This was really annoying when running the tests locally. Now the fixture
is not deleted anymore.

[tests] do not delete flare fixture

---

checks/check_status.py
ddagent.py
transaction.py
win32/status.html

Not all requests should be replayed. We already do not replay requests that are too large (#2418), this extends the logic to 400 responses and makes the list of bad response types into a constant (`RESPONSES_TO_REJECT`), so that it can easily be added to or pruned.
It was causing some issues in certain setups that these were being requeued. Also, it's wasteful to requeue responses that we know will be rejected. And, it's confusing to pollute the logs with re-rejections of validly rejected requests.
Rather than having a blacklist of responses, we might want to have a whitelist of responses: Only requeue responses that were rejected for network errors or server errors.

[Core] Do not requeue all responses

---

packaging/suse/datadog-agent.init

The current init files do not work for suse, they all have various errors. I took the Ubuntu one, added in the missing functions that were throwing up the errors (I had to include the copyright text as well).
This is not the best and I fully admit that there are problems with this approach, but it's better than any of the other solutions I considered: rewriting the init file would be a time consuming and error prone task--I am certain that these functions work and that our current init file works.
The Red Hat file has similar issues. I just picked the debian one because it was easy to fix.
The systemd file works fine, so no such replacement is needed.

Adds an init file for SUSE

---

checks.d/consul.py
conf.d/consul.yaml.example
tests/checks/mock/test_consul.py

Support multiple instances of the `consul` check
Customer request: the Agent needs to support multiple instances of the check when an Agent monitors multiple containers running consul servers.
Updated the mock tests.
Also adds support of yaml-configured tags on each instance to
distinguish data from different instances running on the same Agent

[consul] Support multiple instances

---

checks.d/http_check.py

Fixes an issue with the http_check module where using a HTTPS URL would fail to parse the 'notAfter' date due to improper import of _strptime
I have 30 endpoints all using https that I needed to monitor and was disappointed to find out that there was a blocking error when trying to monitor them. I'm new to doing pull requests and contributing on github, but I'm interested in helping out where I can!
I'm not sure this is the best fix, but I was able to fix the issue on Ubuntu 14.04 with this …

[http_check] SSL certificate strptime fix

---

checks/collector.py

We add one service check per check, to see whether the check is broken
or not. The info command then shows a misleading number service checks.
Let's fix it and not count the additional service check.
Misleading service check count.
Run info.
Backward compatibility issue: unlikely, this only issue would be custom scripts depending on the info output.

[core] display expected service check count

---

checks.d/redisdb.py
tests/checks/integration/test_redisdb.py

Adjusts the `redis.can_connect` tags to include the those specified in the config file.
At present the `redis.can_connect` service check does not include the tags specified in the config file. I don't see why this is the case, so I figured I'd send a PR as a way of asking. That way if it's an oversight we've already got a fix lined up. :)
Added a test assertion for the tag.
Let me know if the tag is intended to be left out!

[redis] Fix tags on redis connect check.

---

checks/collector.py
tests/core/test_metadata.py

Fix encodings of timezone metadata on Windows systems on which `time.tzname` returns non-`ascii` characters. I've been able to confirm on a Korean and on a Japanese system that `locale.getpreferredencoding` returns the correct encoding.
- Non-ascii characters make the emitter crash (at least until #2941)
- the timezone is useless when it's not decoded
Added some tests that give example inputs/outputs
This has also been tested successfully on customers' machines.

[win32] Handle tzname encodings

---

checks.d/apache.py
conf.d/apache.yaml.example

Adds a timeout for connecting to the Apache status server, and fails the service check if the connection can't be established or the status isn't supplied in a timely manner.
Customer report that a hung Apache caused the dd-agent to hang as well.  Therefore, not only did it not report the Apache failure but prevented other metrics from being reported too.
If the apache process is hung, then the service check will hang
indefinitely, too.  With this change, the service check will time out,
and (correctly) report that the service is down.

[Apache] service check could hang entire collector process if the connection to the apache status URL hangs.

---

emitter.py
tests/core/test_emitter.py

On Japanese and Korean versions of Windows, We've seen cases where
the json encoding would fail on a UnicodeDecodeError because of
non-utf8-decodable characters in strings, which causes the whole emitter to fail.
This fixes the issue by making another pass on the
whole payload to remove all the non-decodable characters and log the
affected strings.
Added a mock test on the function that removes non-decodable chars.

[collector][emitter] Ignore all non-unicode-decodable characters

---

checks.d/marathon.py
conf.d/marathon.yaml.example
tests/checks/common.py
tests/checks/fixtures/marathon/apps.json
tests/checks/fixtures/marathon/deployments.json
tests/checks/mock/test_marathon.py

Adds a new metric for to Marathon checks to count the number of deployments that are pending.
Basically, we'd like to track when that number stays high (e.g. > 1) so that we can alert on stuck deployments.
~~An overview on [testing](https://github.com/DataDog/dd-agent/blob/master/tests/README.md)
is available in our contribution guidelines.~~
Added some tests, there was no real coverage for this guy.
I added a new helper method for loading a JSON fixture. I'm happy to pull that out, though, as it feels like it's extending this a little much.

[marathon] Count running/pending deployments

---

checks.d/varnish.py
utils/subprocess_output.py

Do not set close_fds=True
This was introduced by
https://github.com/DataDog/dd-agent/commit/24cf7823c254925ab061baf6aff712678a4c793f
But it’s not needed anymore and as a result the collector is looping
over thousand of file descriptors, trying to close all file descriptors between 3 and the max number of open files descriptors (most of the
time it cannot) and use a lot of CPU to do so.
See: https://github.com/python/cpython/blob/2.7/Lib/subprocess.py#L1185-L1197 for implementation
This commit change that
and revert to the default `close_fds=False`
Also I’m removing a bunch of options that are not used anywhere.
Thanks a lot to @ross for pointing that out.

[core][subprocess output] Do not set close_fds=True

---

checks.d/consul.py

As long as the number of polled services is lower than the limit, let's
just log that no whitelist has been defined. We should only add a
warning when there's an actual issue.
Fixes #2954, removes a spurious warning from the info page of the Agent and from the infra list of the webapp.
None for this trivial change, but we have mock and integration tests on this check.

[consul] Remove warning when no whitelist is defined

---

conf.d/kafka_consumer.yaml.example

Documents how to specify multiple Kafka/ZK nodes. 
In a production environment, it's often useful to specify multiple Kafka / Zookeper nodes for a single check instance. This way you only generate a single check process, but if one host goes down, KafkaClient / KazooClient will try contacting the next host. Generating multiple check processes is a bad solution because then you're doing redundant reads against Kafka (not a big deal) and Zookeeper (can be a bottleneck).
Modify config to see if it works.
Fixes #2943

[Kafka] Document specifying multiple Kafka / ZK nodes

---

checks.d/disk.py
checks/system/win32.py
requirements-opt.txt
tests/checks/integration/test_process.py

Upgrades psutil to the latest version (`4.4.1`), and related changes on `dd-agent` (see details in commit messages):
- [disk] Use `in_use` percentage provided by psutil
- [win32][system] Use `psutil` to sample `cpu.interrupt`: tested on my local windows VM: `psutil` and `WMI` send the same values for `cpu.interrupt`
The upgrade was requested by a customer so that we ship a version that includes this fix: https://github.com/giampaolo/psutil/issues/761
More generally it's good to keep an up-to-date version.
Went through the changelog of `psutil` and through the occurences of `psutil` in `dd-agent` to find things that could be affected. Not sure I've spotted everything but I'll closely monitor the deploy of the updated Agent on our staging infrastructure (especially for the `gunicorn` check …

[psutil] Upgrade to 4.4.1

---

requirements-opt.txt
requirements.txt

Upgrade `kazoo` dep to latest `2.2.1`
Customer request: the upgrade fixes a leak handle in Kazoo (see https://github.com/python-zk/kazoo/issues/169)
\+ it's always good to have up-to-date deps
Tested manually on an Agent running the `kafka_consumer` check. Nothing to report.
This moves the req to `requirements.txt` since this version doesn't have a
dependency on `zope.interface` anymore, so it doesn't need a compiler
(see https://github.com/python-zk/kazoo/blob/2.2.1/CHANGES.rst#20b1-2014-04-24)
Related `omnibus-software` PR: https://github.com/DataDog/omnibus-software/pull/84

[kafka_consumer] Upgrade `kazoo` dep to `2.2.1`

---

checks.d/pgbouncer.py
conf.d/pgbouncer.yaml.example

Rather than reconstructing the postgres connection string from its constituent parts (username, password, host, port), pass through connection strings authored by the user to psycopg2. This lets us use all of psycopg2's features, including SSL encryption.
pgbouncer v1.7 added SSL support, which is currently missing from the pgbouncer check.

Allow SSL connects to pgbouncer

---

checks.d/docker_daemon.py

Set exec events priority to low.
Docker health checks create tons of these, let's make them discreet 
Hopefully nobody is relying on their priority for important stuff.
Failing health checks will be caught by service checks by #2859 anyway

[docker] set exec events' priority to low

---

checks.d/postgres.py
conf.d/postgres.yaml.example

The PostgreSQL check has been changed to try to connect to the PostgreSQL database via a UNIX socket if the hostname provided in the configuration begins with a forward-slash ('/').
This behaviour is similar to the 'psql' command-line utility. From `psql(1)`:
```
--host=hostname
Specifies the host name of the machine on which the server is
running. If the value begins with a slash, it is used as the
directory for the Unix-domain socket.
```
With the difference being that we interpret it as an exact path, whereas psql interprets it as a directory to look for a socket with a particularly formatted name.
This addresses issue #2361. Arguably, a new configuration parameter, `unix_sock` or similar, should be added. I chose to do it this way as it touches less code, and is, as mentioned above, …

[postgres] Allow 'host' config value be UNIX socket path

---

checks.d/postgres.py
conf.d/postgres.yaml.example

Fix the postgres check to make it handle `psycopg2` nicely with the support of UNIX sockets
Fixing the postgres check that I completely broke by merging #2734
Ran the updated check on a local postgres DB, with and without a UNIX socket as `host`, and with `use_psycopg2` enabled and disabled
:confounded:

[postgres] Fix unix socket connection with psycopg2

---

checks.d/mysql.py

Superseding #2741 
Fail gracefully when issuing the query for `SHOW ENGINE INNODB STATUS`: An empty set _can_ be returned, and produces an ERROR.
When monitoring RDS Aurora read instances, although the InnoDB engine is certainly enabled (passing the relevant checks), the engine status query returns an empty set. Presumably only the current Write instance maintains this data. 
The existing code path, issues & attempts to use the result set in the same `try` block. `fetchone()` produces an error on an empty set:
```
- instance #13 [ERROR]: "'NoneType' object has no attribute '__getitem__'"
File "/opt/datadog-agent/agent/checks/__init__.py", line 750, in run
self.check(copy.deepcopy(instance))
File "/etc/dd-agent/checks.d/mysql.py", line 323, in check
raise …
```

[mysql] Robust innodb engine status check

---

checks/check_status.py

catch EOFError when loading status
It can happen when disk is full.

[core] catch EOFError when loading status

---

checks.d/mongo.py
ci/common.rb
tests/checks/integration/test_mongo.py

Supersedes https://github.com/DataDog/dd-agent/pull/2952. Thanks @ebroder 🙇 
**Additional changes**
* Move MongoDB `fsyncLock` metric test to the `AgentCheckTest` class suite.

[mongodb] Add metrics for fsyncLocked-ness, replset votes and vote fraction

---

checks.d/consul.py

When there is only 1 node in a consul cluster, network latency metric collection will cause the check to fail. This fix will skip network latency metric collection in this case.
Found when testing changes with https://github.com/DataDog/dd-agent/pull/2757

[consul] skip network latency metric collection if only 1 node in cluster

---

checks.d/kubernetes.py
tests/checks/mock/test_kubernetes.py

_Note: Please remember to review the Datadog [Contribution Guidelines](https://github.com/DataDog/dd-agent/blob/master/CONTRIBUTING.md)
if you have not yet done so._
Add the `kube_namespace` tag to `kubernetes.pods.running`.
User request, it makes aggregation easier and more useful.
Relevant tests have been update.
We should update the `kube_replication_controller` tag name (must be done carefully as it will break things for users relying on it). It used to be accurate but now pods can be created by daemon sets, jobs, deployments, and replica sets too.

[kubernetes] add namespace tag to kubernetes.pods.running

---

checks/collector.py

Catch exceptions raised by system checks and log them
There's no reason to let the Agent crash when system checks fail
We already do this for Windows system checks so it should
be safe to do it for unix checks.

[collector][system] Catch exception raised by system checks

---

checks.d/kubernetes_state.py

some code call the constructor using keywords, fixed the name of the params, got completely unnoticed in the tests

[kubernetes_state] fixed init param names

---

checks.d/elastic.py

- Add support of ES 5.x (based on #2958, see complete explanation there), the check would fail without these changes.
- Handle RC versions of ES (see #2958)
Also, remove an unused var (`nodes_url`).
No integration tests on this specific version of ES for now, but I've tested the check against a test ES cluster and it collects metrics w/o errors (haven't looked into which metrics were potentially missing though)
Supersedes #2958 and #2980, thanks @ptinsley and @alexef!

[elasticsearch] ES 5.x support

---

conf.d/kubernetes_state.yaml.example

Add a note for RHEL users about Protobuf client performances

[kubernetes_state] added note for RHEL users

---

checks.d/mysql.py

Password casted to string in mysql.py
Pure number password without  quotes causes an error in pymysql. 
If password only contains number, it must be surrounded by quotes, otherwise the pymysql will raise an error. So I cast it to a string to avoid misunderstanding. Or leave it alone to let the user to determine when to use a string? Just my personal opinion.

password cast to string

---

conf.d/auto_conf/kubernetes_state.yaml

Add automatic configuration for the kubernetes_state integration.
Leading up to 5.10.x we've added a new kube-state-metrics integration.  Since one deploys kube-state-metrics as a pod/service on their kubernetes cluster the IP/PORT/etc needed in the kubernetes_state.yaml file will likely be as dynamic as any other service deployed on kubernetes. This seems like the most reasonable way to deploy/configure the integration such that it's picked up, configured and enabled automatically if a user has kube-state-metrics deployed.
Deploy dd-agent to a k8s cluster with kube-state-metrics deployed. Confim the kubernetes_state integration is picked up automatically by service discovery/auto_conf.

Setup auto config for kube-state-metrics

---

packaging/datadog-agent/win32/wix/agent.wxs
win32/gui.py

Modifies the installer so that if agent-manager.exe is running, it is automatically terminated during uninstall and/or upgrade.  This prevents requiring a reboot after upgrade.
Multiple failed installs due to agent-manager.exe running in the background.
Modifies install script to terminate agent-manager during uninstall or
upgrade.  Otherwise, agent-manager is running in the background and can't
be upgraded, leading to an unstable install

[Win32] Terminate agent-manager.exe on uninstall/upgrade.

---

conf.d/process.yaml.example

The process.yaml.example file has some examples in it. They should be commented out so that they aren't erroring out or accidentally submitting metrics that the user doesn't want when they copy it over. 
I found this error and thought it was a good thing to fix.

comments out examples in process.yaml.example

---

checks.d/marathon.py
conf.d/marathon.yaml.example
tests/checks/mock/test_marathon.py

Deployments monitoring was behind a flag, let's enable it by default instead.
- it's an interesting metric to monitor
- low perf impact (small check, only one more http request)
- the marathon check is usually used in a container, which means enabling this flag requires mounting a custom yaml file for the customer or providing yet another env var for us
Updated unit tests

[marathon] enable deployments monitoring by default

---

utils/dockerutil.py

This fixes a bug that was caused by the wrong tag being used.
The bug was resulting in the feature not working (pause containers were not ignored) and 
this warning being shown:
```
Warning: container_image isn't a supported tag
```
Inspiration
Tested on kubernetes 1.4.5

[docker] Use proper tag when filtering pause containers

---

tests/checks/mock/test_kubernetes_state.py
tests/core/test_kubernetes.py
utils/kubernetes/kube_state_processor.py

This renames a metric name to make it less ambiguous. Otherwise we could end with 
`kubernetes_state.nodes.unschedulable {status:available}` which is quite confusing

[kubernetes state] Use a less ambiguous metric name and tags

---

conf.d/postgres.yaml.example

Adds a line of comment
I was confused by how pg8000 behaves when using unix sockets

[postgres] explicit that the drivers behave differently when using unix sockets

---

Gemfile
ci/common.rb

And add some debug logging.
Using `TRAVIS_COMMIT` on the `git diff` command sometimes fail because
git can't find the object reference for some reason (see https://travis-ci.org/DataDog/dd-agent/jobs/173291117#L240-L242 for instance). Instead use the
latest commit of the PR branch and use a difference comparison to only
take into account the changes brought by the PR branch since the latest
common commit with the base branch.
Also, pin the version of a gem dependency since later versions are
incompatible with the provided ruby on Travis (1.9.3).

[ci] Fix Travis test skipping

---

checks.d/rabbitmq.py
conf.d/rabbitmq.yaml.example

[rabbitmq] Fixes #2905 by adding ssl_verify instance config option, which can be used to skip ssl verification for API calls.
We use a vendor app that bundles RabbitMQ using self-signed certificates, and we'd like to monitor it using Datadog.
I didn't add/change any tests for this, but I'd be willing to add some if I can get some guidance on it.

[rabbitmq] Fixed #2905 - add ssl_verify option

---

utils/service_discovery/abstract_config_store.py
utils/service_discovery/sd_docker_backend.py

Fix 2 issues:
- auto_conf templates use the canonical image name (without the repository nor the tag) so individual config reload was failing for them
- containers that were running and are deleted quickly couldn't be inspected so their check wasn't disabled after they were removed

[service discovery] fix single check reload

---

packaging/datadog-agent/source/install_agent.sh

This makes a few small changes that add SUSE to the install script. I use the same logic to detect that it's SLES here that I do everywhere else.
While OpenSUSE can use the RH build, SLES cannot, so I just use an else if where SLES comes after OpenSUSE.

[core][packaging] Adds SUSE to install script

---

checks/check_status.py

This changes the API key validation check to use the proxy settings as exposed by `utils/proxy.py`.
When we upgraded to 5.10 our info page broke. We found out this was the cause. See #3011 
Follow the instructions in the linked issue for reproducing, then apply this diff to see the issue be resolved.
I didn't write any tests since the original change didn't have any tests and I didn't really know what to do. I'm more than happy to write tests with some guidance.
Fixes #3011

Use proxy for API key check in info page

---

ci/common.rb

[ci] fix bad citizens detection
Ternary operation has a high priority in Ruby.
Also add a short comment about the meaning of the bad citizens.

[ci] fix bad citizens detection

---

checks.d/mongo.py

MongoDB 3.2 introduced a new find command, which standard query
operations in pymongo will use if it's available. That command doesn't
support the legacy `$cmd.sys.inprog` pseudo-collection, which is
replaced by a `currentOp` command.
Fortunately there's a built-in API to handle this. Use it.
Based on https://github.com/DataDog/dd-agent/commit/f6b074248f463552a0f640b95f6ba5246ea7d61d#commitcomment-19773690, this is currently broken under newer versions of MongoDB.

[mongo] Use db.current_op instead of manually querying

---

.travis.yml
ci/apache.rb
ci/fluentd.rb
ci/postgres.rb
ci/rabbitmq.rb

Fixes:
- Travis jobs that were timing out by re-enabling the cleanup phase (for some reason some jobs on Travis wouldn't exit unless the processes that are spawned are all killed)
- Postgres setup phase (`psql`'s default user works fine for the first connection, and for some reason the `USER` env var wasn't set correctly on the Travis env)

[ci] Fix Travis jobs timing out

---

checks/collector.py

Isolate system check failures.
If one system check fails, it shouldn't fail the others.
This commits adds a try/except for each of them individually.
Follow up of https://github.com/DataDog/dd-agent/pull/2973/files

[collector] isolate system checks

---

utils/subprocess_output.py

https://docs.python.org/2/library/tempfile.html#tempfile.SpooledTemporaryFile
Use SpooledTemporaryFile for subprocess output.
SpooledTemporaryFile stores data in memory (up to max_size, 1 MB)
instead of on disk, it should stop the agent from completely crashing when disk is
full.
Running the agent should be enough.

[core] SpooledTemporaryFile for subprocess output

---

ci/rabbitmq.rb

Rabbitmq can take a long time to start up on the Travis environment
(can take from 1sec to more than 30sec from what I've found), and
unfortunately I went through rabbitmq's logs and haven't found any
obvious explanation for that.
Let's just increase the timeout instead of having the test fail every
other build.

[ci][rabbitmq] Increase wait timeout

---

checks.d/btrfs.py
checks.d/disk.py
checks.d/gunicorn.py
checks.d/mysql.py
checks.d/process.py
checks.d/system_core.py
checks.d/system_swap.py
checks/__init__.py
checks/collector.py
conf.d/process.yaml.example

Fixes the `procfs_path` customization in the `process` check.  Previously the `procfs_path` specified in `process.yaml` wouldn't be taken into account because `psutil.PROCFS_PATH` would get overwritten in the `__init__` method of other checks (in particular the `disk` check since it runs by default)
Also, since `PROCFS_PATH` is a global setting of the `psutil` lib it makes sense to set it once for the whole collector and only allow its customization from `datadog.conf`, so let's deprecate the setting in `process.yaml`.
🐮

[psutil] Only set `psutil.PROCFS_PATH` once in the collector

---

checks.d/postfix.py

This PR accomplishes two related goals: primarily, it increases the robustness by which subprocess_output.py determines if the output is empty. Secondly, it updates postfix.py so that it does not raise an error when it examines empty postfix queues.
[This recent PR](https://github.com/DataDog/dd-agent/pull/2950) refactored and cleaned up subprocess_output.py. At the same time, the conditional used to validate the emptiness (or non-emptiness) of the output was subtly changed. Specifically, emptiness was previously checked via
if output is None:
and after the refactor was checked via
if not output:
This was an important change, since the output from `subprocess.Popen` is always non-None, and therefore the condition `is None` would never evaluate to **True**. Conversely, `if not output` …

[core][subprocess output] Fix unintended empty output errors

---

checks.d/etcd.py
tests/checks/integration/test_etcd.py

This PR makes the `etcd` check send a `CRITICAL` status if it encouters _any_ errors
when talking to etcd.
When creating some forced failure scenarios in our infrastructure, but stopping `etcd` processes,
I noticed that the agent was not reporting the 'Connection refused' error to Datadog.

[etcd] Report errors connecting to etcd endpoint

---

packaging/datadog-agent/source/install_agent.sh

Cloudfront is having an issue resulting in the following error ```Error gnutls_handshake() failed```
See https://github.com/nodesource/distributions/issues/388 for details
As our APT repositories and RPM packages are signed with the public key C7A7DA52, this won't have a too high security impact.

Disable https in installation script

---

checks.d/haproxy.py
ci/haproxy.rb
ci/resources/haproxy/haproxy.cfg
conf.d/haproxy.yaml.example
requirements.txt
tests/checks/integration/test_haproxy.py

Support unix sockets for haproxy stats collection.
Running a separate stats socket with tight permissions instead of over a tcp port provides greater security.
Sorry, I have no idea how to get the tests actually working in a local environment. It has been a world of pain. I'm hoping travis does a better job at running them and providing some useful feedback.
I'm on macOS 10.12, using homebrew, ruby 2.3.1, python 2.7.12. `rake` aborts on rubocop errors. So does `rake ci:run`. `rake ci:run[haproxy]` tries to compile haproxy which can't find openssl, even if I supply correct CFLAGS and LDFLAGS to my homebrew'd openssl install as env. Subsequent `rake ci:run[haproxy]` runs don't try to recompile haproxy, they fail with `Errno::ENOENT No such file or directory - …

[haproxy] unix socket stats urls

---

checks.d/kubernetes.py
conf.d/kubernetes.yaml.example
tests/checks/fixtures/kubernetes/events.json
tests/checks/fixtures/kubernetes/namespaces.json
tests/checks/mock/test_kubernetes.py
utils/kubernetes/kubeutil.py

This PR allows the agent to collect events from multiple Kubernetes namespaces by using a list of names and/or a regexp.
Two new configuration keys are added:
'namespaces': a list of names
'namespace_name_regexp': a regexp to match any namespace
The old configuration value 'namespace' is still handled by the agent: if present it is added to the 'namespaces' list.

Updating Kubernetes check to handle multiple namespaces fix #2838

---

checks.d/docker_daemon.py
conf.d/docker_daemon.yaml.example
tests/checks/integration/test_docker_daemon.py

This PR allows us to send service checks according to the healthcheck reported by docker for containers. This is a new feature introduced with Docker `1.12`, and not all containers will implement it. Currently we will send an `UNKNOWN` status in that case. Maybe we should only submit the service check when available.
Because grabbing the health status requires inspecting the containers, and that's a potentially expensive call, for now this feature will be hid behind a feature flag `health_service_checks`.
Also added a simple test. More work could be done on this front.
Provides yet another point of view regarding a container's health, as intended by the container's maintainers. 
I have also noticed a couple CI/tooling issues - we can sneak them in here. Or address them in a separate PR …

[docker_deamon] docker healthcheck as service checks.

---

checks.d/iis.py
tests/checks/mock/test_iis.py
tests/core/test_wmi.py

[iis] fix is_2008 option

---

tests/core/fixtures/flare/whitespace_apikeys.conf
tests/core/test_flare.py
utils/flare.py

Fixes the case when there was whitespace before the `api_key` in datadog.conf causing a pattern match failure.
Support case.

[flare] ignore whitespace before api_key

---

conf.d/kubernetes.yaml.example

Move the `tags` param to instance. It wasn't picked up in `init_config` but is expected and correctly handled in `instance`.

[kubernetes] move tags param to instance where it belongs

---

conf.d/haproxy.yaml.example

To reduce the number of contexts created
[skip ci]

[haproxy] Enable collate_status_tags_per_host on new installs

---

checks.d/docker_daemon.py

Initialize `whitelist_patterns` to `None`
If no whitelist pattern is defined, `health_service_checks = True if self.whitelist_patterns else False` in `check` will fail.
This didn't impact anyone as it wasn't released yet.

[docker] fix missing attribute

---

config.py
tests/core/test_service_discovery.py
utils/service_discovery/abstract_config_store.py
utils/service_discovery/sd_docker_backend.py

Currently the kube annotations are used for service discovery once per docker container. This causes "duplicate" checks to be instantiated if you have sidecar containers in your kubernetes pod.
This PR changes the annotations to annotate a specific container to monitor (by name).
Seeing dup checks in my cluster :X.
Unit tests. I will also be deploying this to my internal cluster and monitoring.
The various tuples flying around between config & backend are getting a bit old. AFAICT there are 4 distinct sets:
- Config->Backend: `[(source, (check_name, init_config, instance_tpl))]`
- `_get_config_templates` -> `_get_check_configs`: `[(source, (check_name, init_config, instance_tpl, variables))]`
- `_get_check_configs` -> `get_configs`: `[(source, (check_name, init_config, instance))]`
It's …

[kubernetes] Only use kube annotations for sd once per pod

---

checks.d/sqlserver.py

Remove a `log.warning` call outputting a string containing connection password in case of errors. The log operation was redundant anyways since the exception is correctly and safely propagated.

[sqlserver] remove warning message leaking password strings

---

checks/system/unix.py

The pull request moves the removal of the process table header into the try block above to prevent an IndexError from crashing the process. The general standard error will catch the IndexError and not require an additional error class
We had a system that filled its disk so the output of the process table returned was empty and cause the process to fail. Other errors are caught when running the `ps` command so I figured why not catch this one at the same time if `ps` command succeeds but nothing is returned.
I looked at the testing but I couldn't any tests that test this file. If I could get a pointer of where to look then …

Fixes IndexError from killing agent when no process table returned

---

checks.d/postgres.py
conf.d/postgres.yaml.example
tests/checks/integration/test_postgres.py

Makes the collection of PostgreSQL database size metrics optional, defaulting to enabled.
For large databases with many relations the calculation of this metric can be very slow and expensive. See #3034.
I'm not a Python programmer so feedback is very welcome!

[postgres] Allow disabling postgresql.database_size metrics

---

packaging/datadog-agent/source/install_agent.sh

Now that all our linux packages create a `dd-agent` group

[install_script] Make `dd-agent` group of `datadog.conf`

---

.gitignore
.rubocop.yml
agent.py
config.py
datadog.conf.example
jmxfetch.py
tests/core/test_service_discovery.py
util.py
utils/service_discovery/abstract_config_store.py
utils/service_discovery/config.py
utils/service_discovery/config_stores.py

Enables service discovery for JMX integrations. 
Once a service discovery index config is detected, we parse the config from JSON (as stored in etcd/consul) to YAML and the relayed over to JMXfetch over a named pipe `dd-service_discovery` that lives in `/tmp` by default.
If multiple changes are detected, these are all submitted to JMXfetch by a single write operation to avoid race conditions. The pipe should take care of locking from the reading and writing ends, and by dropping all relevant configs in a single write operation we can guarantee all configs will be read on the JMXfetch in a single iteration and thus help avoid having multiple versions of the same config in the pipe at any given time.
Enabling Service Discovery for JMXfetch integrations.
An overview on …

[service_discovery][jmx] trying to pick-up JMX changes with SD.

---

tests/checks/common.py

What does this PR do?
A one-line change that allows tests to optionally access the 'additional_checksd' parameter from the appConfig when using 'load_check()'
Motivation
This is mandatory if you want to have a set of Checks that you will not be submitting back to Datadog. And wish to use the 'additional_checksd' feature to access them. And you also want to be able to reuse Datadog's excellent AgentCheckTest and supporting code.
Testing Guidelines
N/A (it is a part of the test infrastructure)
Additional Notes
None.
It is a one-liner.
It is innocuous if you do not define 'additional_checksd' in your test's appConfig.
But without it, you must resort to dropping your code into a checkout of dd-agent's checks.d.

[tests] allow tests to use the additional_checksd parameter

---

conf.d/kubernetes.yaml.example
utils/kubernetes/kubeutil.py

dd-agent assumes that the kubelet API is available at the default gateway of the container. This PR allows overriding of the kubelet host if the KUBERNETES_KUBELET_HOST environment variable is found. As an example, the kubernetes downward API in 1.4+ can be used to specify the node name:
```
- name: KUBERNETES_KUBELET_HOST
valueFrom:
fieldRef:
fieldPath: spec.nodeName
```
There are implementations of kubernetes where the kubelet API is not available at the default gateway. An example of this would be when Calico is used: projectcalico/calico-containers#1099
We're testing Calico …

allow override of kubelet host with KUBERNETES_KUBELET_HOST env var

---

tests/core/fixtures/flare/proxy.conf
tests/core/fixtures/flare/whitespace_proxy.conf
tests/core/test_flare.py
utils/flare.py

Fixes the case when there was whitespace before proxy user/pass causing our regex match to fail.
Raised in support ticket.
Added unit test for cases with and without whitespace.

[flare] ignore whitespace before proxy credentials

---

checks.d/process.py
tests/checks/integration/test_process.py

Send the tags configured on the `instance` with the process checks. Given the tests around the old behavior I imagine there might be some reason why this isn't the case now, but just in case there isn't I think it would be useful if the checks had the same tags that were configured for the metrics.
This fixes #2974, FYI.

Send all configured tags with process checks.

---

config.py

Avoid raising exception when passed argument to `_is_affirmative` is `None`. 
Return `False` in that case instead of raising an exception.
For instance https://github.com/DataDog/dd-agent/pull/3010 introduced a case where the passed argument is `None`, which would make the whole collector fail. **#3010 should not be released without this fix**
Fix stuff
It works.
Returning `False` doesn't break backwards compatibility because that made the code blow up before.
🤖

[config] Fix `_is_affirmative` when passed argument is `None`

---

conf.d/jmx.yaml.example

Adds `refresh_beans` as a configuration option.
Multiple support ticket requests.

Alex poe/update jmx with refresh beans

---

checks.d/yarn.py
conf.d/yarn.yaml.example
tests/checks/mock/test_yarn.py

Rebased https://github.com/DataDog/dd-agent/pull/2489 (and fixed typo).
Added application tags in the configuration file,
allowing set extra tags for app metrics like queue,
user, etc.
Also, added the tags functionality merged in
https://github.com/DataDog/dd-agent/pull/2473
on tests

[yarn] Add configurable application tags

---

aggregator.py

We seem to have a bug where we would not parse the tags if a bad rate was reported, we wouldn't even attempt to parse them. This fix will simply correct the bad rate like we were doing earlier without raising an assert that would stop us from grabbing the tags.
Behavior was identified by customer.

[aggregator] if sample rate is bad, fix it but still parse tags.

---

utils/service_discovery/config_stores.py
utils/service_discovery/zookeeper_config_store.py

Adds support for using Apache Zookeeper as the backend for Service Discovery features when running DataDog agents in a cluster.
Zookeeper is widely deployed and used as the default for a DC/OS Mesos cluster. Instead of using resources for a Console or Etcd cluster just for DataDog configs, it makes sense to use the existing Zookeeper instance. And many other systems still use Zookeeper as a key value store.
NA
Works similar to the other stores, just has to iterate each time, unfortunately, to fetch all of the children. One way to bypass that would be to just change the "datadog/config_checks" mtime on each update but users …

[service_discovery] Add a Zookeeper service discovery implementation.

---

tests/checks/common.py

Allows us to override fixtures location. Helpful for the SDK.
Ran into this while porting the `ceph` check to the SDK.

[test][sdk] override fixture dir for SDK.

---

requirements.txt

Another take on #2863 because I deleted the original branch
What does this PR do?
Bumps kafka-python 1.3.1.
Motivation
There's a number of bug fixes and issues since the 1.2.5 release. Similar to #2709, if you're bumping the version in the newest release of the agent, might as well bump it up to 1.3 series.

[kafka] Bump kafka-python to 1.3.1

---

requirements.txt

To stay in sync with omnibus-software (`pyro4` was bumped in https://github.com/DataDog/omnibus-software/pull/81)

[packaging] Update pyro4 dep to 4.36

---

checks.d/http_check.py
tests/checks/integration/test_http_check.py

Fix `content_match` option when non-ascii characters are specified
As stated in pyyaml's docs (http://pyyaml.org/wiki/PyYAMLDocumentation#StringconversionPython2only) yaml strings are converted to `unicode` python objects when they contain non-ascii characters. The existing test would use the type `str` for `content_match` instead so it passed but the check actually didn't work  with non-ascii chars in `content_match`
The reason it didn't work is that it'd compare a `unicode` object with the undecoded `content` of the response.
To fix this, change the test to use a `unicode` object instead, and make the check use the response's `text` (i.e. the decoded `content`, see http://docs.python-requests.org/en/master/user/quickstart/#response-content) when `content_match` is a `unicode` object. …

[http_check] Fix content matching for non-ascii characters

---

conf.d/disk.yaml.default

Makes a small change in `disk.yaml.default`.
A client is using the disk integration's `tag_by_filesystem` option and expecting tags like `#filesystem:nfs` as the example states in disk.yaml.default. 
Tags are being generated without the `filesystem:` prefix.

Update on tag_by_filesystem section of disk.yaml.default

---

tests/checks/mock/test_kubernetes_state.py
utils/kubernetes/kube_state_processor.py

It adds more kubernetes state metrics:
* Add mem/cpu requests and limits
* Add container restarts
* Add pod phase: Pending|Running|Succeeded|Failed|Unknown
It fixes part of #3045
We'd like to know things such as which containers are restarting, which pods are in pending or failed states, container requests/limits, etc.
Tests might fail because the prometheus protobuf.bin blob lacks the
resource limits added in https://github.com/kubernetes/kube-state-metrics/pull/49
I can comment those out in the tests or in the code. Or maybe someone can add an updated protobuf dump.

[Kubernetes] Add state metrics for pods and containers

---

utils/cloud_metadata.py

Adds `shutdown-script`, `configure-sh`, and `google-container-manifest` to the list of excluded GCE metadata keys.
The `google-container-manifest` metadata likely contains sensitive info, and is a kubernetes config file so it doesn't make any sense to use as a datadog tag in any case. It's similar to what can be stored in the `user-data` key (which is already excluded) but is specifically used for configuring the older container-vm images on GCE. The `configure-sh` metadata is a big kubernetes bash script that should also be excluded.
Excluding `shutdown-script` is equivalent to the current exclusion for `startup-script`.

Exclude shutdown-script and google-container-manifest metadata.

---

requirements.txt

Bump version of the docker lib
Use a more recent version of docker. This is needed to match the version in the integration-core repo. We need 1.10.+ to use docker-compose in version 2. This should not impact anything for the dd-agent code.
ref: https://github.com/DataDog/omnibus-software/pull/97

Upgrade docker-py version to 1.10.6

---

config.py
utils/flare.py

Make the `flare` command bundle the `trace-agent.log` file if it exists

flare: add trace-agent log file

---

checks.d/process.py

This emits a warning when no process is found in the process check
#3088

[process] Emit a warning when no process was found

---

packaging/centos/datadog-agent.init
packaging/debian/datadog-agent.init
packaging/supervisor.conf
packaging/suse/datadog-agent.init

In a future release, the `datadog-agent` package will bundle the [datadog-trace-agent](https://github.com/DataDog/datadog-trace-agent)
This change will add a process definition for the trace-agent to the bundled supervisor config. It will also add this proc to the `datadog-agent` process group so that existing install methods will start it up along with existing processes.
Should be merged after https://github.com/DataDog/dd-agent-omnibus/pull/107

pkg: add trace-agent to supervisor

---

win32/gui.py

Ignore "access denied" errors when accessing the old process by PID.
Also, switch to psutil for simplicity. I think we didn't use psutil
before because it still had some bugs on Windows, but it looks like
these bugs have been fixed since then.
The agent manager would crash on startup if the stored PID was
referring to a process that the user couldn't access or terminate (usually
when the process is a system process).
Example stack trace in `agent-manager.exe.log`:
```
File "gui.py", line 847, in <module>
File "gui.py", line 822, in kill_old_process
pywintypes.error: (5, 'OpenProcess', 'Access is denied.')
```
Tested manually on a custom build of the agent, by playing a little bit with the
PID stored in the PID file.

[win32][gui] Fix old process detection and termination

---

conf.d/auto_conf/elastic.yaml

Fix elasticsearch auto config when cluster-mode port is exposed.
fix #3128 
- Run agent in auto_conf mode with the previous version --> ConnectionError.
- Run it again with new settings and the check succeeds.

[auto_conf] [elastic] fix elasticsearch autoconf

---

config.py
tests/checks/common.py

From the SDK, whenever `load_class` or `load_check` were invoked we were actually loading from the sources in the `dd-agent` repo. The aim of this PR is to ensure that when running from SDK-land (both locally or on the CI environments: Travis, CircleCI) we can guarantee the "common" test logic (shared by `dd-agent` and `integrations-core`, `integrations-extra`) actually loads the corresponding modules/classes. 
We need consistent testing, and preferably having a single source for all testing facilities (at least as long as we have commonalities between `dd-agent` and the SDK repos).  We still have checks/logic that store state (docker, kubernetes, etc) and will remain in `dd-agent` for some time, these checks rely largely on the same testing code. Similarly, `integrations-core` and …

[sdk][tests][common] load actual SDK checks (classes/modules) not dd-agent's 

---

checks.d/docker_daemon.py
utils/dockerutil.py

If one cgroup stat file is missing, still try to report the metrics
from the other files. This allows collecting most cgroup metrics on
vanilla Debian 8 systems (where by default the `memory` cgroup metrics
are not available).
Also, remove the retry logic as it seems to have been made at a time
when `find_cgroup_filename_pattern` was used. Since we're trying
all the stat files now it is as if we were retrying `len(CGROUP_METRICS)`
times.
Tested this with a containerized agent running on a debian 8 (jessie) VM.
Addresses https://github.com/DataDog/dd-agent/issues/2251#issuecomment-239122829

[docker_daemon] Report as many cgroup metrics as possible

---

checks.d/marathon.py
conf.d/marathon.yaml.example
tests/checks/mock/test_marathon.py

Add support to marathon for:
disable_ssl_validation: to bypass bad or self-signed certs
group: to get a subset of apps running in marathon (https://mesosphere.github.io/marathon/docs/application-groups.html)
Optional features to support different usecases
Tests already exist for check_marathon
none that I know of

[check_marathon] Add marathon disable_ssl_validation and group support

---

config.py
tests/core/test_service_discovery.py

YAML parsing for JMX-service discovery was broken after merging #2901 
This small change fixes this bug.

[service_discovery][jmx] fix yaml parsing

---

checks.d/http_check.py
conf.d/http_check.yaml.example
tests/checks/integration/test_http_check.py

Adds a feature to the Http_check : allows users to look for a certain content in the URL and shows the check as DOWN if that content is found. 
User will need to set the `reverse_content_match` to `true` in order to do so. 
Several Customer Requests 
Added some test to the `tests/checks/integration/test_http_check.py` file to test the new feature independantly while checking there was no retro compatibility issue.
Ran the rake ci:run[system] and the behavior was expected
Option to Enable is reverse_content_match, defaults to False

[HTTP CHECK] Add an Option to mark check as DOWN if a content is found

---

agent.py
checks.d/docker_daemon.py
config.py
tests/core/test_service_discovery.py
utils/checkfiles.py
utils/configcheck.py
utils/service_discovery/abstract_config_store.py
utils/service_discovery/consul_config_store.py
utils/service_discovery/etcd_config_store.py
utils/service_discovery/sd_docker_backend.py

**Create a cache for configuration templates**
- it keeps auto_configuration templates and templates coming from the KV store
- it invalides the KV templates when the agent detects an update in the config store
- to reload auto_conf or JMX templates we still need to restart the collector or send it a `SIGHUP`.
**Minor clean ups and test updates**
Using this cache avoids querying the config store at every container update.
Tests were updated accordingly. A custom docker image using this build is also available at the `TODO` tag.

[Service Discovery] create a template cache to reduce calls to the KV store

---

checks.d/kubernetes.py
conf.d/kubernetes.yaml.example
tests/checks/mock/test_kubernetes.py
utils/kubernetes/kubeutil.py

Authentication against the apiserver was limited to bearer token. This PR adds support for X509 cert auth.
#3142 adds the feature for authenticating against kubelet, apiserver deserves some love too.
Also, it was requested by existing users ( 👋 @netvisao )
Tests were updated accordingly.

[kubernetes] support cert auth against apiserver

---

checks.d/network.py

Adds one more udp related metric.
InCsumErrors is not available. Here is good explanation of different fields from `/proc/net/snmp`: https://blog.packagecloud.io/eng/2016/06/22/monitoring-tuning-linux-networking-stack-receiving-data/#procnetsnmp
> `InCsumErrors`: Incremented when a UDP checksum failure is detected. Note that in all cases I could find, `InCsumErrors` is incrememnted at the same time as `InErrors`. Thus, `InErrors` - `InCsumErros` should yield the count of memory related errors.

Add udp metric InCsumErrors for checksum errors

---

agent.py
config.py
datadog.conf.example
jmxfetch.py
utils/checkfiles.py
utils/service_discovery/abstract_config_store.py

- Enables configuration of JMX yaml files with any name when they have the `is_jmx: true` flag  in the `init_config` section. This mirrors the same functionality for JMX yaml files in `/conf.d`.
- Adds validation for file names in the `/auto_conf` directory to only configure files with `.yaml` extension. This mirrors the same functionality as in `/conf.d`. For example, `foo.yaml.example` will be ignored.
Support case that found the `is_jmx` limitation.

[Service Discovery][jmx] is_jmx flag in auto_conf

---

.github/PULL_REQUEST_TEMPLATE.md

This is the new PR template:
A brief description of the change being made with this pull request.

adds the sdk message to the pr

---

checks.d/spark.py
conf.d/spark.yaml.example
tests/checks/fixtures/spark/spark_apps_pre20
tests/checks/mock/test_spark.py

Spark integration, at least against Spark 1.5, was using the wrong value of 'id'.  It appears there are two values, the generic job id name from 8080/json:
"activeapps" : [ {
"starttime" : 1483727736675,
"id" : "app-20170106103536-0024",
"name" : "PythonPi",
"user" : "db",
"memoryperslave" : 1024,
"submitdate" : "Fri Jan 06 10:35:36 PST 2017",
"state" : "RUNNING",
"duration" : 5357
} ],
However, when you chase down individual job URL, in this case 4040/api/v1/applications/, you get
[ {
"id" : "PythonPi",
"name" : "PythonPi",
"attempts" : [ {
"startTime" : "2017-01-06T18:35:34.758GMT",
"endTime" : "1969-12-31T23:59:59.999GMT",
"sparkUser" : "",
"completed" : false
} ]
} ]
When creating the URLs to retrieve the individual job statistics, the api appears to want the id from the 2nd, not the …

[Spark]  Fix check to enumerate job IDs

---

checks.d/zk.py

The manner in which tags are applied to service checks and metric checks depends on 2 separate variables. This change modifies the variable that encapsulates tags relevant to service checks (`sc_tags`). Currently for service checks, this variable applies only the host and port information provided in the instance configuration. This change will allow user-defined tags to similarly be applied to service checks (as is the case with metric checks). 
Several of the core integrations handle tags differently for the purposes of metric checks vs. service checks. It's unclear what motivated the inconsistent handling of tags in these contexts. When users are using tags to template alerts, this presents an unnecessary limitation that impacts the ability to template service check-based alerts.
While …

[zk] Modified sc_tags in zk.py to include user-specified tags.

---

requirements.txt

So that it's consistent with the version in integrations-core

[redis] Bump python lib bugfix version

---

checks.d/kubernetes.py
conf.d/kubernetes.yaml.example
tests/checks/mock/test_kubernetes.py
utils/kubernetes/kubeutil.py

To verify the identity of the Kubernetes API server we use the CA cert passed in the agent pod service account by default. This PR makes it possible to pass a custom ca cert instead.
User request
Test updated accordingly

[kubernetes] make apiserver cacert configurable

---

checks.d/redisdb.py

Adds a couple metrics exposed in the output of the Redis info command.
Feature request from customer.

[redis] additional Stats metrics

---

checks.d/haproxy.py

[haproxy] added support for `haproxy.backend.uptime` metric

---

checks.d/php_fpm.py
tests/checks/integration/test_php_fpm.py

Include custom tags in service check
Inside a Docker scheduler, using the `ping_url` is bad, since each restart of the process will assign a new unique port to the process, thus marking the old service as gone, even though its in fact running somewhere else successfully.
Including own tags to the service, a cluster alert can be created to mitigate this issue :)

[php_fpm] Include custom tags in service check

---

checks.d/dns_check.py
conf.d/dns_check.yaml.example
tests/checks/integration/test_dns_check.py

Adds support to `dns_check` for a new `record_type`: `NXDOMAIN`. If specified, an NXDOMAIN result is required from the query to return "success", and response time data is reported.
In many DNS systems, NXDOMAIN results are uncached. Further, a query for a unqualified domain name that one expects to return an NXDOMAIN result can result in many dns queries, depending on the resolver's configured search domain. For these reasons, queries that are expected to return NXDOMAIN are a good candidate for simulating the worst-case performance of a DNS lookup on any given instance. The worst-case performance of a DNS lookup is something we'd like to monitor, and this change provides a way to do so with Datadog.
Tests have been added for two cases:
- Confirming that a check instance configured with …

[dns_check] support monitoring the performance of NXDOMAIN queries

---

checks.d/marathon.py

If you use marathon.can_connect to check for marathon service availability and health, it won't fail if the check can't connect (if marathon is down) 
The check should raise a critical event if marathon can't connect. Otherwise if marathon is down you may only get an alert if you have enabled "Alert on no data" which can be a high timeframe as well.
I'm not a python dev by anymeans, but perhaps other "can_connect" alerts should be updated to send critical alert on "Can't connect" rather than rely on no data found.

[marathon] catch can't connect instead of failing on nodata found

---

checks.d/tcp_check.py
tests/checks/integration/test_tcp_check.py

Before this commit, adding instance tags in the tcp_check configuration
only applied the tags to the (deprecated) service_check but not the
response_time metric sent to datadog.
With this improvement, the custom instance tags are also applied to the
response_time metric, as I would expect.

[tcp_check] Set instance tags in response_time metric

---

packaging/datadog-agent/source/install_agent.sh

Automatic repo add + install on openSUSE was failing. Fixed in lines 85 through 88 for both current and future releases.
Adds in openSUSE support, which was broken on openSUSE Leap 42.2
Pending DataDog deployment on OpenStack system which uses mix of SUSE / openSUSE.

[install_agent.sh] Fixed openSUSE autoinstallation failures

---

requirements-opt.txt

We updated this in [omnibus software](https://github.com/DataDog/omnibus-software/pull/106) and removed it from the not windows branch in [dd-agent-omnibus](https://github.com/DataDog/dd-agent-omnibus/pull/121).
We did this because 2.6.2 has wheels built for windows!!

updates psycopg2 to 2.6.2

---

tests/checks/integration/test_docker_daemon.py
utils/dockerutil.py

Fix `image_tag_extractor` in the case where `RepoTags` is empty.
Also add support for image name extraction from `RepoDigests`.
Working on an other PR I realized we were getting a warning:
```Failed to count Docker images. Exception: 'NoneType' object is not iterable```
Fix `test_tags_options`.

[docker] fix image tag extraction

---

.travis.yml
checks.d/docker_daemon.py
conf.d/docker_daemon.yaml.example
tests/checks/integration/test_docker_daemon.py

Based on the great work of @parkr in https://github.com/DataDog/dd-agent/pull/2740
and 
- fix tests & conflicts
- change how we name and tag the metrics a little
- kill some dead code

[docker] container & volume metrics (wraps #2740)

---

checks.d/mongo.py

We want to see number of mongodb databases because our databases can grow dynamically. I was thinking about this code. The best solution which I see it's usage of GAUGE link to AgentCheck.gauge function with static metric's name.
Please correct me if I am wrong
Would like to see this metric in the oficial repository
Thanks

[mongo] add metric with number of databases

---

config.py

Because of the release, we're bumping the config.py to the new version.

bumps config.py version to 5.12

---

requirements-opt.txt

Pins pysnmp subdependency `pyasn1`
Regression in 5.11.0

[snmp] pinning subdependency to avoid breakage.

---

conf.d/docker_daemon.yaml.example

With `container_image`, I see the following in the collector logs (v 5.10.1)
WARNING | dd.collector | checks.docker_daemon(__init__.py:675) | container_image isn't a supported tag
Change docker_daemon example docs.
The existing example seems incorrect and leads to warnings in the logs.
I haven't fully confirmed using `image_name` actually works as I expect.

[docker_daemon] change container_image to image_name in example

---

checks.d/docker_daemon.py
utils/dockerutil.py
utils/platform.py
utils/service_discovery/sd_docker_backend.py

This is a first step towards a Docker Swarm integration.
With this PR, all metrics coming from service discovery as well as container metrics will be tagged with the swarm service.
That's a low hanging fruits regarding container monitoring.

[swarm] tag container metrics with swarm service if available

---

packaging/datadog-agent/source/setup_agent.sh

Bumps the default agent version for the source install.
5.11.1 bugfix release.

[source install] bump default version to 5.11.1

---

config.py

Bad release, bumping to 5.11.2.
Bad release for 5.11.1

[config] version bump to 5.11.2.

---

checks.d/tokumx.py

The datadog user may only have access to the databases which the customer
wishes to monitor. Without this patch, a failure to invoke dbstats on _any_
database would raise an exception and prevent monitoring for _all_ databases.
With this patch, databases that cannot be accessed are ignored with a warning.

Skip dbname's we can't access

---

packaging/datadog-agent/source/setup_agent.sh

Bumps source install to `5.11.2`.
New release.

[source] bumping version for source install to 5.11.2.

---

checks.d/spark.py

Set Spark events source type name to `spark` so it gets properly resolved by the backend.

[spark] fix event source type name

---

checks.d/spark.py

Spark commonly runs hundreds of jobs, stages per minute. Sending events
on status changes brings little value but potentially flood the event stream.
Do not send events for Spark job/stage status changes. Instead
`spark.job.*`/`spark.stage.*` metrics should be used.
⚠️  **Backward compatibility change** ⚠️ 
Invite users to update their Spark event monitors before merging.

[spark] no events on job/stage status changes

---

utils/dockerutil.py

There was an infinite instantiation loop for DockerUtil(). Since it implements the singleton pattern and `fetch_swarm_state()` is in the constructor, if `fetch_swarm_state()` calls DockerUtil() again, it will call the constructor again (and so forth) and the class instance will never make it to the Singleton class map.
Found the issue while testing another PR branched off `master` that included the `swarm` changes. 

[dockerutil] break singleton instantiation loop.

---

checks.d/kubernetes.py

A PodSpec with containers with no explicit [ResourceRequirements](https://kubernetes.io/docs/resources-reference/v1.5/#resourcerequirements-v1) results in error logs from the collector:
Unable to retrieve container requests for $container: 'requests'
Unable to retrieve container requests for $container: 'requests'
Unable to retrieve container requests for $container: 'requests'
...
Reduce a noisy log from ERROR to DEBUG level.
This is a normal config; no reason to fill the log.

[kubernetes] reduce log message from error to debug

---

checks.d/tcp_check.py
tests/checks/integration/test_tcp_check.py

Add the instance name to the tags of the network.tcp.response_time metric.
It will also be merged to integration-core once approved.

Add instance name to tags on response_time metric

---

checks.d/marathon.py
conf.d/marathon.yaml.example
tests/checks/mock/test_marathon.py

- Add tasksHealthy and tasksUnhealthy to metrics sent do datadog for all marathon apps
- Add ability to use ACS token to authenticate with the marathon api for marathon running in DC/OS platform 1.8
In order to alert on unhealthy marathon apps, we required the ability to compare unhealthy instances vs healthy instances for an app running in marathon, and alert based on a threshold. This required the tasksHealthy and tasksUnhealthy metrics provided by the marathon api
Marathon running in DC/OS 1.8 requires an ACS token for authentication. Added the ability to optionally configure the base url for the ACS auth endpoint. If …

Add token auth marathon

---

utils/kubernetes/kubeutil.py

Kubeutil has the wrong path for finding service account token & cert (see https://kubernetes.io/docs/user-guide/accessing-the-cluster/#accessing-the-api-from-a-pod). This PR updates the path.
Was getting an error when using the dd-agent with KUBERNETS=true and KUBERNETES_COLLECT_EVENTS=true

[kubernetes] Update service account path in kubeutil.py

---

tests/core/test_transaction.py

Fixes endpoint test.
A changed was rolled on intake that would 400 if the API request contained no api series.

[core][test] fix test on endpoints, we're not sending 400 if series missing.

---

packaging/datadog-agent/source/install_agent.sh

This will ensure that all sles 11 sp4's can install it.
On a more updated zypper (which is default on sles 12), it allows you to disable the repo gpg check. Our repos aren't signed anyway, so the gpg check is just accepting that the repo isn't signed.
However, on sles 11, the zypper that's on the base image doesn't have this option. So you have to use `--no-gpg-check`.

fixes install script for sles 11

---

checks/collector.py

As it is misbehaving (eating way more CPU than needed/expected). 
See https://github.com/DataDog/gohai/issues/41

[mac] disable gohai

---

requirements.txt

The version of requests we're on now causes some bugs, bumping it should (hopefully) resolve more than it creates

Updates requests to 2.13.0

---

checks/system/win32.py

This PR fixes the naming of pagefile memory on windows, it also fixes where we're pulling it from in psutil. Previously, we were reporting the physical memory, rather than the pagefile.

adds proper pagefile memory on windows

---

utils/cloud_metadata.py
utils/hostname.py

If the hostname is None, we should try to get the EC2 instance-id.
This was reported by a customer, and they proposed this fix.
The hostname can be None when `/bin/hostname -f` returns an error, which
can happen at AMI creation when the hosts file is not ready.`

[utils/hostname] better EC2 detection

---

requirements.txt

Reflects change in omnibus-software, see https://github.com/DataDog/omnibus-software/pull/122

[requirements] Downgrade `requests` to 2.11.1

---

utils/dockerutil.py
utils/kubernetes/kubeutil.py

When the agent is containerized it makes sense to use
docker info's Name as the hostname even if it doesn't resolve.
Because otherwise the agent falls back to the container short ID
which is not really helpful.
This PR drops the resolvability check for the name.
Fixing https://github.com/DataDog/docker-dd-agent/issues/139

[docker/hostname] improve get_hostname for containers

---

config.py
tests/core/test_config.py
utils/windows_configuration.py

On Windows, the integrations installer will allow them to place an integration anywhere they want, and it will write that location in the registry.
This forces our sdk loader to act a differently than otherwise, it grabs the key from the registry, then it loads the check from it.

[core] adds logic for windows sdk check loading

---

.gitignore

For local dev you sometimes use it and it pollutes your Git.
It won't affect files already in git (jmx.yaml.example).

[gitignore] add conf.d

---

ddagent.py
tests/core/test_transaction.py
tests/core/test_utils_net.py
utils/net.py

This PR adds a DNS cache to the agent, if disabled the agent just skips any local DNS resolution. Otherwise we've implemented a very simple cache that should allow us to reduce the number of DNS queries made.
A customer was complaining about too many DNS queries. We suggested some local caching like `dnsmasq`, apparently that was not an option for them. Unfortunately there was no way to do this using `requests`, which was the preferred approach.

[core] add a DNS cache

---

utils/dockerutil.py

Simply adds a bogus PID exception. Used by `docker_daemon`, has potential to be useful elsewhere so dockerutil seems to be a nice place for it.
https://github.com/DataDog/integrations-core/pull/237

[dockerutil] adding bogus PID exception.

---

config.py
tests/core/fixtures/checks/manifest.json
tests/core/test_config.py
utils/checkfiles.py
utils/windows_configuration.py

Let's validate the SDK checks to ensure we can detect checks with the wrong manifests.
We might need this to warn/default to core checks if the core agent is updated from under an SDK installed check. Otherwise checks might break and we wouldn't have anything meaningful to debug in that aspect.

[core][sdk] ensure manifest validation when running checks.

---

datadog.conf.example

Adds `consul_token` parameter to datadog.conf.example. This didn't exist although [our docs](http://docs.datadoghq.com/guides/servicediscovery/#configuring-etcd-or-consul-in-datadogconf) lists it in the example. When configuring the docker agent with the env var `SD_CONSUL_TOKEN` our [`sed` command](https://github.com/DataDog/docker-dd-agent/blob/master/entrypoint.sh#L110-L111) was failing.
Customer support ticket.

[service_discovery] add consul_token to datadog.conf

---

emitter.py

In some scenarios: only for windows system metrics using the old check
interface, hostname was not passed. In that case we should use the
internalHostname one.

[emitter][payload split] make sure to have a hostname

---

utils/windows_configuration.py

full path (not the root of the installation directory).  Make associated
change here so SDK checks will load
Companion PR https://github.com/DataDog/dd-agent-omnibus/pull/150

[Windows]  Changed the registry value in the installer to point to the

---

.travis.yml
Rakefile
appveyor.yml
checks/__init__.py
checks/check_status.py
checks/collector.py
config.py
tests/checks/mock/test_no_profiling.py
tests/core/test_common.py
tests/core/test_config.py
tests/core/test_service_discovery.py
utils/flare.py
utils/sdk.py
utils/windows_configuration.py
win32/status.html

This PR adds certain SDK-related facilities/improvements to the `flare` and `CheckStatus`, and as a result to the `info` page.
It also fixes several issues encountered with the testing infrastructure including build issues on `travis` and `appveyor` (also local).
I have also snuck in a fix to the SNMP flare. In particular, the `community_string` should be considered a credential and as such should be redacted.
With the advent of the SDK we need to be able to track what integration versions users have installed. This will allow them and us to understand what code actually got loaded, and what versions of the checks they're running at a glance.
Anything else …

[info+flare] include SDK-relevant information if available

---

checks/system/unix.py

Original submission moved the deletion of list index zero inside the 'try'
block, with the net effect that it would be skipped on any exception.  The
exception that's actually occurring is SubprocessOutputEmptyError.  So,
catch all exceptions and return a failure, rather than attempting to parse
potentially malformed data returned in an exceptoin case.
Original PR https://github.com/DataDog/dd-agent/pull/3043
Updates a submission intended to stop an uncaught exception when 'ps' fails (in the user's case, due to a full filesystem)
Regression testing and review indicated fix was potentially incomplete.

Create more general fix to original problem.

---

config.py

Removes a dump of a jmx check yaml config in the logs
Could potentially contain sensitive information that shouldn't be
logged

[auto_config][jmxfetch] Remove yaml dump in log

---

requirements-opt.txt

Don't know if we should keep these check deps in the requirements files of dd-agent, but right now any discrepancy makes the integrations-core CI build fail (https://github.com/DataDog/integrations-core/pull/262 upgraded the dep in `integrations-core`)

[requirements][scandir] Sync dep version with integrations-core

---

win32/gui.py

The PgBouncer Datadog Agent check depends on `psycopg2` third party,
which is currrently  not shipped with the Windows agent.
Disable PgBouncer check on Windows.

[win32] disable pgbouncer check

---

checks/__init__.py
config.py

Fixes a small bug where the check version was not properly being reported in the info page for WMI checks.
It also addresses another small issue, when we hit an issue when validating the YAML, we actually fail before attempting to load the check, so the check version is unknown at that point. We were reporting the check version as `None` in that case, this will now report it as `unknown` (as we have not yet loaded the check). Is `unknown` better than `None`? I went for it because it would be more consistent with other error messages when the version cannot be determined (ie. a bad manifest, etc).
Found the bug while testing the RC.

[core][sdk][info] fix version detection for WMI Checks

---

config.py
tests/core/test_config.py

Fixes the version comparison in `validate_sdk_check` (added in #3251)
Added a test case covering what this fixes.
We have to use tuples of integers if we want the comparison
to work as expected

[core][sdk][version_manifest] Fix version comparison

---

checks/check_status.py

Instead of hardcoding the url, politely use the one from the config.

[fowarder] validate api_key against any endpoint

---

agent.py

This PR attempts to add to the relevant locations to `sys.path` before the checks are loaded in the collector solving potential library dependency issues in integrations-extras. It does not affect `core` integrations as these already bundle their deps with the `dd-agent` core package. It does not affect `unix` systems either because in those cases we **_do_** enfore the target location for the packages so we can drop the preferable `pth` files instead.  
On windows, integrations can be installed to an arbitrary location, meaning we don't know at build time what the `pth` files we'd drop in `site-packages` should look like. 

[core][sdk][win] add paths to sys.path if bundled with libs.

---

utils/flare.py

Creates the `sdk_manifests.json` file in the same directory as the other files of the tar.
Without this change it would get added as a `<main_dir>\sdk_manifests.json` file one level above all the other files when extracted on a unix env.
Built a windows agent against this branch and checked that a flare tar doesn't have the issue anymore.
The change is done by python in `TarFile.add` (see https://github.com/python/cpython/blob/v2.7.13/Lib/tarfile.py#L1863-L1869), but not in `Tarfile.addfile`

[flare] Use "/" path separator in TarInfo name

---

packaging/datadog-agent/source/install_agent.sh

As otherwise if another repository is configured and failing it will
fail the install for nothing.

[install script] only refresh datadog repo on SUSE

---

packaging/datadog-agent/source/setup_agent.sh

This fixes the source install after https://github.com/DataDog/dd-agent/pull/3114 is merged.
I tested the new logic on dash, bash and zsh.

[packaging] fixes source install for sdk

---

CHANGELOG.md

Update the ChangeLog for upcoming 5.12.0
Keep in sync with https://github.com/DataDog/datadog-trace-agent/
Links are valid, info makes sense.
My first dd-agent ChangeLog update, so, feel free to edit.

[trace-agent] updated trace agent ChangeLog for 5.12.0

---

utils/dockerutil.py

related to #2466
Lines in `/proc/$PID/cgroup` don't have the same format for all systems.
- In CoreOS they look like: `3:cpu,cpuacct:/system.slice/docker-$CONTAINER_ID.scope`
- In RancherOS: `5:cpu,cpuacct:/docker/$USER_DOCKER_CID/docker/$CONTAINER_ID`
- In Ubuntu: `4:cpuacct:/docker/$CONTAINER_ID`
For RancherOS we were parsing the `$USER_DOCKER_CID` not the `$CONTAINER_ID`.

[docker] parse subsystem

---

packaging/datadog-agent/source/setup_agent.sh

The source install script should have the agent at version 5.12.0!

[source install] bumps agent version

---

config.py

After the release the agent version should be 5.13.0

bumps agent version in config.py to 5.13.0

---

emitter.py

This PR forces source type to "system" for the payload split in the emitter
Otherwise this will churn contexts as they'll have a different source type name. This can also lead to transient double counting.

[core][emitter] Force source type to system for legacy payload

---

packaging/datadog-agent/source/setup_agent.sh

Fixes the source install, which failed when we removed all the checks from the agent. It was partially integrated, but did not entirely work.

Fix the 5.12.0 Source Install

---

transaction.py

Fixes a case where the removal of a transaction from the TransactionManager would raise `ValueError: list.remove(x): x not in list` and crash the forwarding ioloop.
This would happen when:
1. the endpoint is not available
2. the transaction queue is full
3. a flush is "timed out" (when flush time > 10 seconds), and
4. the endpoint becomes available again
In that scenario a transaction could be removed first by the code handling the size of the queue (see https://github.com/DataDog/dd-agent/blob/5.12.1/transaction.py#L137, which can run while the transaction is being sent) and then from the `on_success` callback once the transaction has been successfully sent.
The fix has 2 parts (see related 2 commit descriptions): the first should fix the issue in most cases, the second should ensure …

[forwarder] Fix error on removal of transactions

---

utils/cloud_metadata.py

We get the following log when we start the dd-agent on an instance in GCE. 
`dd.collector | utils.cloud_metadata(cloud_metadata.py:45) | Collecting GCE Metadata failed Header value True must be of type str or bytes, not <type 'bool'>`
It looks like the header in the request sent to GCE to get the metadata is in the wrong format. Also I think this is now deprecated in favour of `Metadata-Flavor: Google` (see https://cloud.google.com/compute/docs/metadata#transitioning)
This PR uses the new `Metadata-Flavor: Google`
We're relying on GCE tags to identify important groups of instances and none of these tags are coming through.

[core][cloud_metadata] Use Metadata-Flavor header to avoid request exception for GCE tags

---

packaging/supervisor.conf

This patch restarts the trace agent if it exits with an error code
that is different from 0. Else, it would restart in some cases but
would consider as 'expected' the return code 2 which is what Go
returns for builtin runtime errors.
Currently, some of our trace agents are dead and not restarted.
I tested it by replacing the trace agent by a dummy program that
would exit with code error 2 after some time (don't return it too
fast otherwise program is not considered as started).
* test it actually restarts the program when exiting on code 2
* test it still restarts the program when receiving a signal
Example testing session log:
```
2017-03-30 09:13:53,580 INFO success: trace-agent entered RUNNING state, process has stayed up for > than 5 seconds (startsecs)
2017-03-30 09:14:48,213 INFO …
```

[trace-agent] restart on unexpected error code

---

utils/subprocess_output.py

Reverts DataDog/dd-agent#3002
Unfortunately, SpooledTemporaryFile and TemporaryFile behave the same in this case, because subprocess.Popen needs actual files.
Let's revert to avoid confusing people.

Revert "[core] SpooledTemporaryFile for subprocess output"

---

tests/core/test_dockerutil.py
utils/dockerutil.py

cgroup parsing doesn't work if `docker` is not in the string
Regression in 5.12.2
Now with unit test.

[docker] fix cgroup parsing

---

checks/collector.py
checks/system/win32.py

checks.d/network. This check is redundant, and causing confusing returns
as the same metric is being reported from two different places.
Removes the Network check from the system checks.
While debugging/testing a separate code change, found that two different checks were reporting the same metric, and this was causing confusing data.

[Windows] Remove system network check.  Network check was added as

---

CHANGELOG.md

[changelog] Add link to 5.12.3 trace-agent changes

---

utils/kubernetes/kube_state_processor.py

- removes some of the duplicated code for gauges
- fixes the `container.restarts` metric type
- introduces a type check for prometheus metrics
container.restarts is always `0` because we use the gauge value instead of counter value.
See https://github.com/DataDog/integrations-core/pull/317

[kubernetes_state] refactor gauge submission, fix container.restarts

---

jmxfetch.py

Passes `--sd-enabled` option when JMXFetch-SD is enabled
See https://github.com/DataDog/jmxfetch/pull/135 for details
The new option replaces the `sd-standby` option that wasn't used anywhere on JMXFetch
side.

[jmxfetch] Pass `--sd-enabled` option when JMXFetch-SD is enabled

---

utils/hostname.py
utils/service_discovery/sd_docker_backend.py

Kubeutil raises an exception if it can't reach the kubelet. We should catch it.
Ugly collector logs
Run the agent on a non-k8s node, see that the exception is now caught.
sister PR: https://github.com/DataDog/integrations-core/pull/345

[kubernetes] catch errors from kubeutil init

---

jmxfetch.py

When SD uses `auto_conf` to init JMX-fetch related checks, it verifies that the check name is listed in the list `JMX_CHECKS`. Kafka was missing, making impossible to use SD with JMX an the autoconf config storage.

Add kafka to the list of jmx checks

---

utils/dockerutil.py

If a container is in host mode we shouldn't call `socket.inet_aton` on its network gateway because it's empty and will fail, resulting in a warning in the integration. We can't not report the metrics either because existing behavior reports network metrics even in host mode (so network metrics are actually for the whole host). So let's keep the same behavior but avoid the buggy call to inet_aton.
Getting rid of a warning.
Run the agent in host mode (or any other container on the same machine), see that the warning disappeared compared to the RC, replaced with a debug log.

[docker] fix net metrics in host mode

---

config.py
packaging/datadog-agent/source/setup_agent.sh

Bumps the config.py minor for the nightlies, and the source install.
5.13.0 release.

[agent][release] version bumps after 5.13.0 release.

---

requirements.txt

AWS az "us-east-2" has been added in boto 2.43. We currently ship 2.39.
This bump boto to the latest version (2.46.1 right now)
Customers in us-east-2 could not get EC2 tags from the agent.

Bump boto version to 2.46.1

---

packaging/osx/supervisor.conf
packaging/supervisor.conf

Remove `/opt/datadog-agent/agent/checks` from the `PYTHONPATH` set up by supervisor.
Seems to have been there forever, but I don't think we need it in the
python path for any (good) reason. From what I've checked we always
import with `import checks.abc` instead of `import abc`.
Having it in the python path pollutes the module root namespace. For
instance it prevents importing the `datadog` module (i.e. module from
`datadogpy`) correctly (its name collides with `checks/datadog.py`).
Haven't tested this in depth but I applied the changes on an installed agent and haven't seen any import error.
The only use case that this change would break is if custom checks
are doing direct imports (e.g. `import wmi_check` to import
`checks/wmi_check.py`). The fix is trivial so it doesn't sound
blocking …

[packaging] Remove agent/checks from PYTHONPATH

---

utils/cloud_metadata.py

bosh_settings frequently includes passwords. This will blacklist it.

adds bosh_settings to excluded tags, as it frequently includes passwords

---

tests/core/test_dockerutil.py
utils/dockerutil.py
utils/service_discovery/sd_docker_backend.py

Some orchestrators init containers with the image sha256 instead of the
image name, and docker inspect returns this. If it's the case, make
a docker image inspect call to get the image name and cache the result
No cache invalidation is coded as image deletion don't trigger events and obsolete image count should be significant on a typical host
Compatibility with k8s 1.6 & Nomad
Added unit test for the three cases we support

[docker] fix image name when using sha256 for specs

---

utils/kubernetes/kube_state_processor.py

Record the fact that we a pod is in a certain phase.
We like to monitor the amount of pending pods, the service check does not give the amount of control we like.

[kubernetes_state] Record pod phase

---

tests/core/test_dockerutil.py
utils/dockerutil.py

Some systems still use the systemd slice hierarchy for Docker. Let's support them.
Customer request
Updated the relevant unit test

[docker] support systemd slices in cgroup paths

---

utils/dockerutil.py

DockerUtil.image_name_extractor() can return None if no name is found (invalid container or image), but image_tag_extractor didn't handle the None case. This fixes the CI break

fix exception when image name is None

---

utils/flare.py

Add auto discovery templates under `etc/confd/auto_conf` in flare.
A lot of support tickets are actually misconfigurations in the templates. This change will make it easier to debug such issues.

[flare] add auto_conf templates

---

dogstatsd.py

In dogstatsd, logs hostname on initialization
When running the agent as a dogstatsd server only (see for instance the dogstatsd-only docker image), it's useful to know which hostname the dogstatsd server will apply to metrics that have no explicit host tag attached.

[dogstatsd] Log hostname on initialization

---

tests/core/test_service_discovery.py
utils/configcheck.py
utils/service_discovery/sd_docker_backend.py

- In https://github.com/DataDog/dd-agent/pull/3326, one SD code path was not fixed and still used get('Image'). This PR fixes it to use image_name_extractor too
- Updated configcheck.py to use it too

[docker]  use DockerUtil.image_name_extractor for all code paths

---

packaging/datadog-agent/source/agent
packaging/datadog-agent/source/supervisor.conf

The default supervisor socket is named `datadog-supervisor.sock` and
most other `supervisor.conf` configs use the default name. This change
keeps the socket filename in sync with the default, otherwise
it breaks service discovery.
Service discovery was breaking because it could not communicate with supervisor.
```
2017-05-08 20:57:25,609 | ERROR | dd.collector | collector(agent.py:604) | Uncaught error running the Agent
File "agent/agent.py", line 600, in <module>
sys.exit(main())
File "agent/agent.py", line 543, in main
agent.start(foreground=True)
File "/opt/datadog-agent/agent/daemon.py", line 174, in start
self.run()
File "agent/agent.py", line 284, in run
self._submit_jmx_service_discovery(jmx_sd_configs)
File "agent/agent.py", line 433, in …
```

[config] Make supervisor socket consistent with default

---

checks/__init__.py
tests/core/test_check_status.py

If a check has multiple instances, and the first instance adds a
warning and then raises an exception, the next instance of the check
would actually have that warning in its status (even if this second
instance ran fine).
Fix this by always discarding remaining warnings at the end of each
instance run.
Also, add a test reproducing the issue.
Reported on a support case.
Adds a test reproducing the issue
"Warnings" are one of the info that gets printed on the info page and sent as a service check, e.g.:
```
elastic (5.13.0)
----------------
- instance #0 [WARNING]
Warning: full warning message
- instance #1 [ERROR]: FooException
Traceback: [...]
- instance #3 [OK]
- Collected 189 metrics, 0 events & 3 service checks
```

[check] Fix misattribution of check instance warning

---

config.py
tests/core/test_nomadutil.py
utils/dockerutil.py
utils/orchestrator/__init__.py
utils/orchestrator/nomadutil.py
utils/platform.py
utils/service_discovery/sd_docker_backend.py

Detects the Nomad orchestrator and:
- adds job/group/task names as tags
- tags caching and cache invalidation
Auto-detection works via the NOMAD_ALLOC_ID envvar, so the dd-agent must run in a container started via Nomad (we need to write an example specfile)
- docker_deamon intergration PR is https://github.com/DataDog/integrations-core/pull/305

[docker] Support Nomad for SD and tags

---

tests/core/fixtures/kubeutil/service_cache_events1.json
tests/core/fixtures/kubeutil/service_cache_events2.json
tests/core/fixtures/kubeutil/service_cache_services1.json
tests/core/fixtures/kubeutil/service_cache_services2.json
tests/core/test_kube_event_retriever.py
tests/core/test_kube_pod_service_mapper.py
tests/core/test_kubeutil.py
utils/kubernetes/__init__.py
utils/kubernetes/kube_event_retriever.py
utils/kubernetes/kubeutil.py
utils/kubernetes/pod_service_mapper.py
utils/service_discovery/sd_docker_backend.py

Add deployment and service k8s tags to service discovery tags. 
Logic is in separate kube_event_retriever and pod_service_mapper classes
The deployment name is inferred from the replicaset name, as this is hardcoded in the k8s source. Matching selectors would be costly, especially if we need to support matchExpressions set selectors
The pod->service is implemented by matching every pod to every service's label selectors. The services are kept in memory cache and cache is checked every time service discovery is triggered. If the pod satisfies matches several services, multiple kube_service tags are added.
The cache is invalidated on kubernetes events pushed by the kubernetes check, mirroring how docker_daemon/dockerutils work. These events allow to trigger SD updates on service events.
It …

[k8s] KubeUtil + SD service and creator tags

---

utils/kubernetes/kubeutil.py

Adds support for custom kubernetes label prefixes. Fixes #3321. 
The motivation is that we (Confluent) would like to remove the "kube_" prefix.
Thanks

Support custom kubernetes label prefixes

---

tests/core/test_dockerutil.py
tests/core/test_service_discovery.py
utils/dockerutil.py
utils/service_discovery/sd_docker_backend.py

- move SD docker tags extraction to dockerutil.extract_container_tags with error handling
- only inspect the container once in a shared c_inspect var
- update sd unit test fixtures
- extend test_dockerutil to test new method

[SD] better docker tag extraction logic + tests

---

utils/kubernetes/kubeutil.py

transform kubeutil.get_kube_labels into get_kube_pod_tags to add kube_{creator} and kube_service tags to the dictionnary. This allows docker.* and kubernetes.* metrics to get these tags
Test docker image is dev-dd-agent:xvello_docker_k8s_extend_tags , works on a k8s 1.6.1 cluster, these tags are now consistent between:
- service discovery
- kubernetes.pods.running
- kubernetes.* cadvisor metrics
- docker.* cgroup metrics

kube_{creator} and kube_service for more metrics

---

utils/service_discovery/abstract_config_store.py

Allows configuring multiple instances of the same check with `auto_conf`.
In some cases (and for some checks), it makes sense to have multiple
instances of the same check running against a container. Example:
`php_fpm` check when the user wants to run the check against multiple `status_url`s.
I did some basic manual testing. Haven't written unit tests but if needed I can add some.
Opening this PR after discussing with @sdwr98 on a use case for #3259 (the use case being: having the ability to define multiple instances of the same check with `auto_conf`, which is useful for `php_fpm` for example)

[auto_conf] Allow multiple instances per check

---

checks/check_status.py

Tell the underlying `requests` library to only validate the SSL key when `ssl_skip_validation` is `False`.
Tested and working with `skip_ssl_validation` omitted/`True`/`False`.
Fix #3303

Respect `ssl_skip_validation` when checking API key

---

checks/__init__.py

The flag to enable/disable the proxy checks is `no_proxy` not `skip_proxy`. This fixes it.
Bug identified during testing.

[checks][proxy] fix helper function flag is `no_proxy`

---

config.py

Upgrade jmxfetch to 0.14.0, see [release notes](https://github.com/DataDog/jmxfetch/releases/tag/0.14.0)
Should be merged with https://github.com/DataDog/omnibus-software/pull/146

[jmxfetch] Upgrade to 0.14.0

---

datadog.conf.example
requirements.txt
utils/service_discovery/etcd_config_store.py

Add `sd_backend_username` & `sd_backend_password` options to enable authentication when connecting to the etcd datastore.
Depends on https://github.com/DataDog/omnibus-software/pull/145 for dependency bump.
Allows for fine-grained access control for clients that need it
Debian package built with both PR available on request.

[AD] add support for etcd auth

---

utils/dockerutil.py

TLS settings were confusing. Setting tls_verify to true and tls_cacert to a path would request TLS verification but not pass the ca cert path, causing errors. The solution was to set tls_cacert and omit tls_verify but that's hard to guess.
Support tickets.

[docker] Make TLS settings more intuitive

---

checks/network_checks.py

Fix typo in the network exception log, the right key in configuration are lowercase.
see: #3354

Fix typo in the network exception log

---

tests/core/test_dockerutil.py

Add a test fixture for the new k8s qos cgroup format, to avoid regression, document where each format is encountered.

add k8s 1.6 to cgroup parsing dockerutil test

---

tests/core/test_orchestrator.py
utils/orchestrator/__init__.py
utils/orchestrator/baseutil.py
utils/orchestrator/mesosutil.py
utils/orchestrator/metadata_collector.py
utils/orchestrator/tagger.py
utils/platform.py
utils/service_discovery/sd_docker_backend.py

Introduces a generic container tagger mechanism to support all orchestrators through a common interface instead of expanding `SDDockerBackend.get_tags` and `DockerDaemon._get_tags` once again.
This introduces three classes:
- `Orchestrator.BaseUtil`: provides the common interface and the caching and container inspect logic
- `Orchestrator.MesosUtil`: inherits BaseUtil and just implements `_get_cacheable_tags` and `is_detected`
- `Orchestrator.Tagger`: triggers orchestrator detection and proxies calls to relevant BaseUtil classes
ECSUtil and NomadUtil will be moved to BaseUtil if this PR is approved.
unit tests in the test_orchestrator.py file

Mesos tagging and generic container tagger

---

checks/__init__.py

Adds a `warning` message when the `set` method is used.
`AgentCheck.set` will be removed in Agent 6.0. Any custom check that currently uses it should be modified.
2 core checks currently use `AgentCheck.set`:
- `zk`: see https://github.com/DataDog/integrations-core/pull/473
- `docker`: check that's been deprecated since agent [`5.5.0`](https://github.com/DataDog/dd-agent/blob/master/CHANGELOG.md#550--09-17-2015), so we should probably remove it from the `integrations-core` altogether when Agent 6.0 is released

[checks] Deprecate `AgentCheck.set`

---

tests/core/test_service_discovery.py
utils/service_discovery/sd_docker_backend.py

Fixes: #3340
As explained in  #3340, having multiple instances for the same check in the annotations don't work well.
This brings the few adjustments to make it work.
The doc will need to be updated to say that if you want several instances of the same check in the annotations, you'll need to have an array for then inside the annotations array.

Fix multi-instance service discovery

---

tests/core/test_kube_event_retriever.py
tests/core/test_kube_pod_service_mapper.py
utils/kubernetes/kube_event_retriever.py
utils/kubernetes/kubeutil.py
utils/kubernetes/pod_service_mapper.py
utils/service_discovery/sd_docker_backend.py

https://github.com/DataDog/dd-agent/issues/3381 reported a high apiserver traffic since 5.14 and the introduction of kubernetes.pod_service_mapper. This couple of PR changes the logic to only pools events every 5 minutes (configurable) instead of every run.
- add collect_service_tags to disable collection completely
- add a delay parameter to throttle requests to the apiserver
- remove check_services_cache_freshness and use process_events only for cache invalidation
- disable podmapper freshness check from SD, rely on event from the kubernetes check
Needs changes in integration-core: https://github.com/DataDog/integrations-core/pull/476

[kube] Reduce apiserver request count for pod_service_mapper

---

checks/collector.py
tests/core/test_watchdog.py
util.py
utils/timer.py

Move `Timer` to its own `utils.timer` module
`util.py` is deprecated, and `Timer` was still used in a check
(vsphere). Move to `utils`, and still import it in `util` so that
custom checks importing it from `util` still work (until we finally
remove it in Agent 6.0)
No specific manual testing done, relying on CI.

[util] Move `Timer` to its own `utils.timer` module

---

packaging/osx/datadog-agent

This PR modified the restart command of the Mac OSX packaged Agent. The restart command now checks to see if the supervisor process is still running, and waits up to 10 seconds before calling the start command.
Running the `stop` then `start` commands on Mac leads to this error quite often: `Error: Another program is already listening on a port that one of our HTTP servers is configured to use.  Shut this program down first before starting supervisord.`
This seems to be due to the supervisor process taking too long to fully exit and free up ports, so we wait up to 10 seconds for this to be done. 
Thanks @cmatteri For writing …

Update Mac restart command

---

README.md

This PR clarifies that the trace agent is not part of this repository and will not be installed with the installation from source.
https://github.com/DataDog/dd-agent/issues/3382

Mention trace agent in README

---

checks/collector.py
config.py
datadog.conf.example
tests/core/test_common.py
tests/core/test_dockerutil.py
tests/core/test_mesosutil.py
tests/core/test_orchestrator.py
utils/dockerutil.py
utils/orchestrator/baseutil.py
utils/orchestrator/mesosutil.py
utils/orchestrator/metadata_collector.py

- add orchestrator.MetadataCollector.get_host_tags() and method in Mesosutil
- add DockerUtil.get_host_tags() for docker_version
- detect mesos and dcos agents via http/https tests
- retrieve docker_version, docker_swarm, mesos_version and dcos_version host tags
- add new collect_orchestrator_tags conf option (default True)
Allows easier troubleshooting for version-specific orchestrator issues
Unit tests in the CI

[docker] add docker/mesos version host tags

---

config.py
tests/core/test_ecsutil.py
tests/core/test_nomadutil.py
utils/kubernetes/kubeutil.py
utils/orchestrator/baseutil.py
utils/orchestrator/dockerutilproxy.py
utils/orchestrator/ecsutil.py
utils/orchestrator/kubeutilproxy.py
utils/orchestrator/metadata_collector.py
utils/orchestrator/nomadutil.py
utils/platform.py
utils/service_discovery/sd_docker_backend.py

**Warning: the need to merge https://github.com/DataDog/dd-agent/pull/3383 and rebase on master first**
This PR:
- ports ECSUtil and NomadUtil to BaseUtil and MetadataCollector for container tags (see https://github.com/DataDog/dd-agent/pull/3383)
- adds host tags for:
- ECS: `ecs_version`
- Nomad: `nomad_version`, `nomad_region`, `nomad_datacenter`
- Kube: `kube_master_version` and `kubelet_version` through a KubeUtilProxy class
- gets Docker host tags through a DockerUtilProxy class in orchestrator package for consistency
- adds unit tests for detection and tags extraction
What's more to do:
- remove references to ECSUtil and NomadUtil in docker_daemon (sister PR to come)
- decide whether is_* methods should stay in utils.Platform or be removed (as we abstract the orchestrator via …

[docker] Add kube/ecs/nomad host tags + port to BaseUtil

---

checks/collector.py
checks/system/unix.py

Adds a metric for the percent of allocated and used file handlers over the system's max. Uses `/proc/sys/fs/file-nr` as noted here - https://www.kernel.org/doc/Documentation/sysctl/fs.txt
This metric will be displayed as a fraction between 0 and 1, and is named: `system.fs.file_handles_in_use` to keep syntactically similar to `system.disk_in_use` which has similar units. 
This would look like this in app: https://cl.ly/3u2E2S3l2j0K
Users would like to be able to be alerted if the number of handlers being used was approaching the limit available. 

[core] Adds fraction of file handles in use over system limit

---

checks/libs/wmi/counter_type.py

process the data requested in this support card
https://trello.com/c/y9KrekoF/170-how-to-get-usable-avgdisksecperread-from-win32perfrawdataperfdiskphysicaldisk
Adds two new calculator types for computing values returned by WMI
Customer request.

[Windows] add additional calculator types.  New calculators needed to

---

checks/prometheus_check.py

Allows checks to define a `self.ignore_metrics` array that PrometheusCheck will ignore. This is used in the revamped kubernetes_state check from https://github.com/DataDog/integrations-core/pull/492
- Reduce log spam
- Improve performance
- While defining the array, check authors can comment why some metrics are left out on purpose (not relevant / high card / ...) and not just forgotten

[PrometheusCheck] add ignore_metrics array

---

config.py
packaging/centos/datadog-agent.init
packaging/debian/datadog-agent.init
packaging/supervisor.conf
packaging/suse/datadog-agent.init
utils/flare.py

Adds the [datadog-process-agent](https://github.com/DataDog/datadog-process-agent) to the supervisor file so it will run as part of the Agent. As with the trace-agent, you must enable a flag in the config for the Agent to actually run without immediately stoppign.
The omnibus change is https://github.com/DataDog/dd-agent-omnibus/pull/181
Once both this and omnibus build are in place we will be able to validate it's running. If you run the omnibus build on this and the omnibus branch you will get a pkg that installs things correctly.
cc @shang-wang

pkg: Add process-agent to supervisor and flares

---

tests/checks/common.py

Moves the ` wait_for_async` function to the Agent instead of duplicated in each Network Integration test
The Network based Integrations were using the same function. Due to how fast the localhost test was returning, there seemed to be some flakiness in the network based checks. 
A previous PR added a solution to catching the quickly returned localhost service check for the TCP check. This PR takes that modified function out of the Integrations repo, places it into the Agent so that it can be used for all Network based checks. 
is …

Moves common wait_for_async network function out to the Agent

---

tests/core/test_mesosutil.py
utils/orchestrator/mesosutil.py

These tags have a container cardinality.
- Kept them commented out with a message to explain why
- Updated unit tests
- Only `marathon_app` remains (similar to a kube_deployment)
After 5.15 settles in, and if requested, we could patch BaseUtil to support two cardinality tiers for tags and only use the high card for docker metrics.

[docker] disable mesos_task and chronos_job tags because of high cardinality

---

tests/core/test_mesosutil.py
utils/orchestrator/mesosutil.py

Following up on this comment https://github.com/DataDog/dd-agent/pull/3414#issuecomment-313382842, re-enable `chronos_job` and extract `chronos_job_owner` if not empty.
Unit tests updated accordingly

[mesos] extract chronos_job and chronos_job_owner if not empty

---

tests/core/test_kube_event_retriever.py
utils/dockerutil.py
utils/kubernetes/__init__.py
utils/kubernetes/kubeutil.py
utils/orchestrator/kubeutilproxy.py
utils/platform.py

- Allows the user to set bearer token path and api_server hostname and credentials manually, to allow running directly on the node.
- If `kubernetes.yaml` is present and valid, enable k8s tagging for Docker and SD metrics
- If both client certs are configured, skip token lookup to remove the error
Sister PR for configuration: https://github.com/DataDog/integrations-core/pull/508
Tested on container (datadog/dev-dd-agent:xvello_kube_on_host image) and deb package on ubuntu host.
fixes #3221

[kube] Allow to run agent on the node

---

checks/collector.py
utils/orchestrator/metadata_collector.py

Enable orchestrator.MetadataCollector even when not containerised, in case the agent is installed on the host.
To reduce boot time on non-docker hosts, orchestrator detection is passed if docker is not found, as we only support docker as a runtime for now.

try collecting docker+orchestrator host tags even if not containerised

---

tests/core/test_kube_pod_service_mapper.py
utils/kubernetes/pod_service_mapper.py

- Move from log.exception to log.warning (less scary)
- On 8th 403 error, print log.error on configuration change then disable class to avoid spamming apiserver
- Add unit test for backoff mechanism

[kube] disable kube_service tagging on 4 403 errors from apiserver

---

tests/core/test_service_discovery.py
utils/service_discovery/sd_docker_backend.py

This PR adds two new template variables to the service-discovery check configs:
* `pid` the host PID namespace PID of a container processes' PID 0
* `id` the docker container id hash
We have a few custom integrations that collect information from `/proc`. When we were running only one instance of a process per-host (pre-containers), it was easy to determine the correct `pid` to interrogate. Now that we're using Kubernetes and Docker, there is often many such processes per machine. These variables help us find the process we want.
This PR Is actually authored by @jnewland - I'm submitting it upstream because I've been working on our dd-agent packaging setup.

Add support for %%id%% and %%pid%% template variables

---

checks/collector.py
datadog.conf.example
utils/cloud_metadata.py

I added a few ways to get the proper host alias for cloud foundry, including some undocumented options in the config file and environment variables. I can use or remove any that people think is a good idea. But, basically it will detect if it's cloud foundry and then grab the proper host alias from a few places.
I want the firehose nozzle metrics to be associated with their respective host, this will make that easier to do.

Get real host aliases for Cloud Foundry

---

utils/service_discovery/sd_docker_backend.py

Rework #3365 to move back to a different template variable name.
This is something we actually don't want included by default in `%%tags%%`. It should be used with care as it could flood the tag auto complete menu with a useless tag if used carelessly (typically: in a highly volatile environment where containers churn often and have different names each time).
Sorry for the back and forth @subuk, your first version was actually the good one!

Add container name tag in auto discovery

---

tests/core/fixtures/flare/auth_token.yaml
tests/core/fixtures/flare/password.yaml
tests/core/test_flare.py
utils/flare.py

- Add regex for auth tokens
- Use `re.search()` instead of `re.match()`. `re.match()` only matches at the beginning of the line.
That would prevent the replacement of password or token if it was the first option of an instance (i.e. there would be a dash `-` before the parameter). Noticed this while writing the tests.
Added functionality to auth via token in the consul check: https://github.com/DataDog/integrations-core/pull/521
Need to sanitize config file
Anything else we should know when …

[flare] Add regex for auth tokens

---

utils/kubernetes/kubeutil.py

If `api_server_url` is not set and the envvar `KUBERNETES_SERVICE_PORT` is set, `master_port` will be a str instead of the intended int type, making the `%d` formatter sad. Moving to a `%s` formatter as it can handle both int and str types.

fix string formatting in kube_api_root_url init

---

tests/core/test_dockerutil.py
utils/dockerutil.py

https://github.com/DataDog/dd-agent/pull/3383 introduced the `docker_swarm` host tag, setting it to `active` or `inactive`. This would be added to every docker host instead of only swarm clusters (like other orchestrator tags).
This PR disables the tag when inactive, and only keeps the `docker_swarm:active` tag, when swarm is actively detected.

remove docker_swarm:inactive host tag, only keep it when detected

---

config.py
jmxfetch.py

It bumps the version to 0.15.0 and explicitly passes the pipe name as the `dd-service_discovery` pipe name is the legacy pipe.
Required with the latest jmxfetch release.

[jmxfetch] bump to 0.15.0.

---

agent.py

We need to submit the config terminator to acknowledge we've piped everything out. Done in it's own `write()` to ensure atomicity of the write. The jmxfetch will continue to greedily `read()` until the configuration terminator is received.
Feedback in the sister PR: https://github.com/DataDog/jmxfetch/pull/145
The local FIFO nature of the named pipes should make this process safe, a `write()` should not be lost and the configuration on the other end should be received in full. Additionally, the delivery of the config terminator - which marks the end of the "piping" procedure, should be guaranteed so there should be no real possibility of having the jmxfetch side fall in a busy-loop waiting for a terminator that will never be delivered.

[auto-discovery][jmx] send terminator after configs + fix execption handling

---

utils/kubernetes/kubeutil.py

Strips spaces and new lines around the bearer token.
The token is extracted from a file, which more often than not ends with a new line. This makes the token end with `\n`. Let's remove that.
Tested it on a cluster, it works fine.

[kubernetes] strip spaces around bearer token

---

utils/kubernetes/kube_state_processor.py

Add a deprecation warning in preparation for the removal of KubeStateProcessor in 5.16.
Don't wanna be to quick with code 🔥 in case users rely on it for custom checks.
Note the PR is against 5.15.x. There is #3440 against master for the actual removal.

Add deprecation warning for KubeStateProcessor

---

tests/core/test_service_discovery.py
utils/service_discovery/sd_docker_backend.py

Tags could be dicts.
Also, I believe `kube_state_processor` has been deprecated after the migration to prometheus checks.
Encountered this issue testing.

[auto-discovery] tags could be a dict of KV pairs

---

tests/core/test_kubeutil.py
utils/kubernetes/kubeutil.py

This will tag pod metadata with `kube_stateful_set:<name>` if they are members of a stateful set.
I ultimately want to be able to create timeboards and monitors on the diff between the `desired` and `current` number of pods for a given `StatefulSet`.  I am currently doing something similar with the diff between `desired` and `available` pods for a deployment.  It is unclear to me if these changes are needed for the kube_state integration or not. 

kubernetes/kubeutil.py: Tag pods that are created by StatefulSets

---

agent.py
jmxfetch.py

If JMXFetch happens to go down, use the `atime` stat date on the JMX launch file to decide if the auto-discovery configurations should be re-piped to JMX. JMXFetch will touch that file when coming up so we should have a relatively good idea of when JMXFetch started - alternatively, we could look at the process table to figure this stuff out (but that would be computationally more expensive).
Customer bug.
Sister PR: https://github.com/DataDog/jmxfetch/pull/143

[auto-discovery] re-pipe configurations after JMXFetch restart

---

checks/collector.py
tests/core/fixtures/azure/metadata_instance.json
tests/core/test_azure.py
utils/cloud_metadata.py

Detect an Azure host using the metadata instance service and use the VM ID as hostname.

Add hostname detection for azure cloud provider

---

datadog.conf.example
dogstatsd.py
tests/core/test_dogstatsd.py

Adds a config variable that allows the SO_RCVBUF socket option to be set on dogstatsd's UDP socket.
Tons of `RcvbufErrors` on hosts running a highly-trafficked `dogstatsd` and [this blog post](https://blog.packagecloud.io/eng/2016/06/22/monitoring-tuning-linux-networking-stack-receiving-data/#udpqueuercvskb), especially this bit:
> You can also set the sk->sk_rcvbuf size by calling setsockopt from your application and passing SO_RCVBUF. The maximum you can set with setsockopt is net.core.rmem_max.
This change is in production and seems to be performing well.
> Anything else we should know when reviewing?
I'm a python noob, and am totally open to adjusting this PR given your feedback!

[dogstatsd] Add statsd_so_rcvbuf config variable

---

utils/kubernetes/kubeutil.py

Add an option to import k8s node labels as host tags
Why not
Tied to https://github.com/DataDog/integrations-core/pull/614

[kubernetes] add option for node labels --> host tags

---

requirements.txt

Bumps kazoo to `2.4.0`
@jeffwidman wants to upgrade kazoo for kafka_consumer, apparently there are several improvements and bugfixes in the latest versions. Unfortunately most of the affected elements have mocked tests, so we maybe wouldn't know of any fallout until QA time comes along. 
Sister PRs:
- https://github.com/DataDog/omnibus-software/pull/154 
- https://github.com/DataDog/integrations-core/pull/623

[kazoo] bumping to 2.4.0

---

aggregator.py
tests/core/test_aggregator.py

Parses `distribution` metrics and ignores them.
`distribution` is a new dogstatsd metric type that this implementation doesn't
support.
Instead of failing on known but unsupported metric types, ignore these
metrics and continue parsing the rest of the packet.
Without this, sending a new "distribution" type metric in a datagram
makes dogstatsd drop the whole datagram.
This change has virtually no impact on the performance of the dogstatsd
parser.

[dogstatsd] Parse distribution metrics and ignore them

---

agent.py

This PR wraps the jmx_state get line that pulls in the information about the JMXFetch process from supervisor in a try/except block. 
There have been a few cases where this line throws an exception due to a broken pipe, which causes the Agent to crash since its uncaught. Example stacktrace:
```
dd.collector | collector(agent.py:604) | Uncaught error running the Agent 
Traceback (most recent call last): 
File "/opt/datadog-agent/agent/agent.py", line 600, in <module> 
sys.exit(main()) 
File "/opt/datadog-agent/agent/agent.py", line 543, in main 
agent.start(foreground=True) 
File "/opt/datadog-agent/agent/daemon.py", line 174, …
```

[JMX SD] Wraps the jmx_state get call in try catch

---

dogstatsd.py
emitter.py

key from appearing in the log.
Skims off everything after "api_key=" in the URL when logging, so that the API key doesn't get logged in the clear.
customer request.
Intentionally didn't use the code for replacing the key with "****".  As this will be executed each time, whether the agent is logging in debug or not, didn't want to incur the additional overhead.

Truncate the URL at the API key when logging to prevent the clear API

---

Rakefile

Integrations core does not use a proper venv when testing, meaning that when you call the rake task, it doesn't download jmx fetch. This will allow it to download JMX fetch
I was working on a JMX Check

allows integrations core to download jmx fetch from rakefile

---

tests/core/test_service_discovery.py
utils/service_discovery/abstract_config_store.py
utils/service_discovery/sd_docker_backend.py

Mirroring the kubernetes annotation autodiscovery source, lookup autoconf template in container labels. These templates are expected in the JSON format.
If k8s annotation are present, they take precedence. Else, if valid json is found in the following labels:
- com.datadoghq.ad.check_names
- com.datadoghq.ad.init_configs
- com.datadoghq.ad.instances
**Warning**: the label names changed from the original PR, to reflect the s/ServiceDiscovery/AutoDiscovery/ transition
a template is rendered from them, bypassing the auto_conf files lookup.
If a K/V store backend is configured, this feature is disabled, like k8s annotations.
- Added the `test_get_check_tpls_labels` test method. We could go further with integration testing.
- For manual testing, one can use the workbench recipe …

Allow autoconf templates in docker labels

---

checks/prometheus_check.py

Allows to override metric type if the provided type is invalid or absent via the `type_overrides` class member. Overrides have effect both on protobuf and text formats. If the type name is invalid, the override is ignored.
Some prometheus source don't specify type information in the text format. We can't reliably report on `untyped` metrics, so we'll need to force a type in the checks. See https://gitlab.com/gitlab-org/gitlab-ce/issues/35028

Add type_overrides member to PrometheusCheck class

---

tests/core/test_utils_process.py
utils/process.py

Was excluded on windows
Enabled the command line check to make sure the pid in the pidfile references a datadog process
Customer request

[windows]  Enable check to see if the pid is a running copy of itself.

---

checks/libs/wmi/sampler.py

because python doesn't have the concept of unsigned integers. So, it
just converts to a negative number.
If the type returned is supposed to be UINT32, convert it accordingly.
Customer report.

[windows wmi]  When the WMI type returned is a UINT32, python struggles

---

checks/__init__.py
utils/debug.py

Removes the `run_check` method.
`run_check` dates back from pre-5.12 windows agents, when we weren't
shipping a full python interpreter and needed this specific method
to allow users to run custom checks from `shell.exe`.
This doesn't make sense anymore now that we ship a full python
interpreter that the agent processes use. That interpreter has the
necessary modules to run checks. The correct way to run checks
(shipped by default or custom) is now similar to Linux/macOS, i.e.:
```
> ..\embedded\python.exe agent.py check <check_name>
```
`shell.exe` should only be used to troubleshoot the python environment
that the windows service and the windows GUI use.

[win32] Remove `run_check`

---

utils/service_discovery/sd_docker_backend.py

Bug fix of https://github.com/DataDog/dd-agent/pull/3341
Annotations with multi instances configuration leads to check level tags be added to the container level tags array.
While adding container tags with this [method](https://github.com/DataDog/dd-agent/blob/master/utils/service_discovery/sd_docker_backend.py#L490), performs a shallow copy of the container tag array to avoid adding tags from the previous instance ( which would come from [this for loop](https://github.com/DataDog/dd-agent/blob/master/utils/service_discovery/sd_docker_backend.py#L438)), contains its check tags.
Issue encountered by a customer.
Instantiate a pod with annotations containing several instances (along the lines of [this example](https://gist.github.com/CharlyF/c1220097e45ce9caf77bde567a066723))
The agent will …

[autodiscovery] annotations with multi instances bug

---

agent.py
utils/configcheck.py

Utilizes the sys.exit() function in the `configcheck` command utility. This allows the exit code to be determined based on whether or not the yaml configs are good/bad. 
Customer Request. Now when running the one off config check script/command, you can utilize `$?` to determine if there are any bad yaml files. 
Previously, if the configcheck finished and printed that there were errors in the yaml files, the following command:
```
echo $?
```
would output `0. Now this outputs 1, indicating there was a failure. 
is available in our …

[Core] Utilize sys.exit in configcheck

---

config.py

Upgrades jmxfetch to 0.16.0, see https://github.com/DataDog/jmxfetch/blob/master/CHANGELOG.md#0160--08-21-2017
Sister PR: https://github.com/DataDog/omnibus-software/pull/158

[jmxfetch] Upgrade to 0.16.0

---

jmxfetch.py
utils/jmx.py

New `list_jvms` command.
> List available Java virtual machines on the system using the Attach
>   API.
See https://github.com/DataDog/jmxfetch/pull/112

[jmxfetch] add `list_jvms` command

---

packaging/centos/datadog-agent.init
packaging/debian/datadog-agent.init

Only has a real impact on the debian init script, but let's fix that
everywhere.
Introduced in #3301.
The bug would only affect Debian by:
- making the `DATADOG_ENABLED` var not work as expected
- always printing a pretty ugly error message

[packaging] Fix bashism in init script

---

dogstatsd.py
tests/core/test_dogstatsd.py

Makes logic more consistent: one function determines if dogstatsd6
should be used, based on the config param and on the presence of the
binary. Both have to be valid to enable dogstatsd6.
The current logic wouldn't work properly when the option is enabled but the binary
is not present.
Updated the tests.

[dogstatsd6] Fix fallback logic to dogstatsd5

---

tests/core/test_kube_event_retriever.py
tests/core/test_kube_pod_service_mapper.py
tests/core/test_kubeutil.py
tests/core/test_leader_elector.py
utils/kubernetes/__init__.py
utils/kubernetes/kube_event_retriever.py
utils/kubernetes/kubeutil.py
utils/kubernetes/leader_elector.py
utils/kubernetes/pod_service_mapper.py

Implement a leader election mechanism among agents on kubernetes to collect events automatically.
It's a pain to create a single deployment for the one agent responsible to collect events. It's also not recommended to have all agents report events due to the load this puts on the apiserver (and the redundant data sent by all agents).
This feature will allow having event collection enabled only once, without needed a snowflake agent deployment. All agents can be started with the `leader_candidate: true` option and take part in this election. Only the leading agent will report events.
Unit tests were added, integration tests …

[kubernetes] implement leader election among agent for event collection

---

ddagent.py
transaction.py

Makes payload rejection log entry more explicit.
We drop some payloads for other reasons than the payload being too
large, so make the log message more generic too.

[forwarder] Make payload rejection log entry more explicit

---

checks/__init__.py
tests/core/test_common.py

Avoids `null` values on service check fields.
The `api/v1/check_run` endpoint doesn't accept payloads with a `message` value of `null`, so avoid that. #3446 was not working because of this.
Do the same thing on the `tags` and `hostname` fields as it makes sense to be consistent.
cc @remh

[collector] Only add service check fields if non-null

---

checks/__init__.py
checks/collector.py
config.py

Fixes a couple of issues with the info page:
- if a module fails to load - `unknown` version + show exception in info page.
- if a custom check is used - report `custom` as the version.
https://github.com/DataDog/integrations-core/issues/669

[info] `unknown` ver if failed module load, `custom` if custom check.

---

packaging/datadog-agent/source/install_agent.sh

The install script should install dirmngr as well, as debian 9 doesn't come with it.
Only install it if it exists in the cach

adds dirmngr to debian install script

---

CHANGELOG.md
config.py
packaging/datadog-agent/source/setup_agent.sh

* Source install version
* Changelog date
* Bump `AGENT_VERSION` in `config.py` for nightlies' versioning

[packaging] Release 5.17.0

---

tests/core/test_dockerutil.py
tests/core/test_orchestrator.py
utils/dockerutil.py
utils/kubernetes/kubeutil.py
utils/platform.py
utils/service_discovery/sd_docker_backend.py

Until now AD would fail if docker wasn't reachable.
This change make AD retry 5 times with a 15s interval
before failing to give docker a chance to start. Same for the kubelet.
user request
Updated related tests.
linked PR: https://github.com/DataDog/integrations-core/pull/722

[AD] make Auto Discovery wait on docker/kubelet

---

utils/dockerutil.py
utils/kubernetes/kubeutil.py

Refactor code from `dockerutil.image_name_extractor` into generic `dockerutil.image_name_resolver` and expose `kubeutil.image_name_resolver` wrapper to handle errors and null case.
Allow the kubernetes check to resolve image sha to image names

[k8] add image_name_resolver to kubeutil wrapping dockerutil

---

tests/core/test_leader_elector.py
utils/kubernetes/kubeutil.py
utils/kubernetes/leader_elector.py

- fix the lease duration param name
- use the node name instead of the pod name as the lock creator
node name as the lock creator allows to take over the lease in case an agent is killed an a new one is scheduled on the same node.

[k8s] Fix leader election's lease parameter and node name

---

checks/datadog.py
tests/core/test_datadog.py

It resets the dogstream tail generator when an exception occurs. This allows the generator to be recreated on the next check.
Previously, once the generator failed, it would never be re-created. This would mean that if a file did not exist when the generator was created, it would never be checked.
Fixes #2261

Reset generator if dogstreams can't read a file

---

checks/__init__.py

Deprecates `AgentCheck.read_config`.
It's only used in one check (kafka_consumer) and its usefulness in
AgentCheck is dubious IMO.
Related to https://github.com/DataDog/integrations-core/pull/733 (which removes the use of this method from the `kafka_consumer` check)

[AgentCheck] Deprecate `read_config`

---

utils/dockerutil.py

Inspecting non existant images raise a NotFound error that spams the collector logs. This PR catches it and return None. If the image doesn't exist the process stops here.
Sometimes a container is stopped, and its image is forcibly removed. In this case when we try and extract the image info from the container, we hit a NotFound error that was not expected. Customers using Nomad seem to hit this issue often. Not sure if it's Nomad that force removes images, or users' scripts, but we can and should handle it.
is available in our …

[docker] catch docker.errors.NotFound for nonexisting images

---

utils/flare.py

multiple types of API input in datadog.conf
Modified the regex used when checking for the API Key in datadog.conf or other locations. Currently we only support the syntax `api_key: <KEY>` However, this doesn't allow for a space before the `:` or using `api_key = <KEY>`
Currently the API key isn't being fully redacted in the flare if it doesn't use the aforementioned format. It seems like K8s Agents use the `=` syntax by default.
Performed a series of manual tests locally based on the above …

[Core] Update the Main Credential regex to support

---

tests/core/test_service_discovery.py
utils/service_discovery/abstract_config_store.py

swarm can use org/image:tag@sha256:xxxxxxxx format, that throws off
the parser. reworking it to handle all known formats and unit test it
Added `test_get_image_ident` unit test

rework AD image name extractor to support new swarm format

---

utils/kubernetes/kubeutil.py

get_node_hostname can fail and return None, we used to revert to
the docker hostname but removed that
Built docker image `datadog/dev-dd-agent:backport_3523` with it for impacted users

[k8s] partially revert _locate_kubelet from #3497 to fix regression

---

utils/orchestrator/mesosutil.py
utils/orchestrator/nomadutil.py

If envvar is NoneType, we want to return the tags directly instead of crashing.
Support case brought up by the community.
Set up a DCOS cluster v 1.9.2, deployed the agent running 5.17.2 and witnessed the successful auto discovery of a redis container along with the collection of Mesos/Marathon specific tags.

do not crash if ENV in CONF is None

---

utils/configcheck.py
utils/flare.py

Redact sensitive infos in config dumps performed by the SD config check
Using `json.dumps` makes a pretty printing of the configs, which puts each configuration parameter on a new line, thus making it easy to redact using the existing mechanism of the flare. Only a small modification of the regexes was needed to account for the double quote signs that the dump prints around each parameter

Redact sensitive infos in config dumps

---

tests/core/test_ecsutil.py
tests/core/test_service_discovery.py
utils/orchestrator/ecsutil.py
utils/service_discovery/sd_docker_backend.py

This PR removes access to deprecated top-level bridge NetworkSettings from Docker and update test fixtures
Top-level bridge NetworkSettings were deprecated by Docker since 1.13 and will be removed in future versions (see https://github.com/moby/moby/pull/28437)

Remove access to deprecated top-level bridge NetworkSettings

---

checks/collector.py
dogstatsd.py
emitter.py

Fix potential leak of API key in `collector.log` and `dogstatsd.log`. The `requests` module logs the url in its exception message, so the API key could appear.

Fix potential leak of API key in collector.log and dogstatsd.log

---

checks/system/unix.py

Reverts the code introduced in #3472. 
The change does not cause the metric to be submitted. It doesn't get included in the payload in the collector. And even then as it's submitted as a system metric in the payload, and not via a regular gauge, the backend is not prepared to handle it. 
On top of it, it's probably a less helpful metric than physPctUsable which takes into account the page caching, etc... which is in fact usable memory. So I feel like we don't lose value by reverting.
Found issue while testing.

Revert "Added Percentage Free Memory Stats (#3472)"

---

packaging/datadog-agent/source/setup_agent.sh

Bumps the source install to `5.18.0`.
New release.

[setup-script] bump default version to 5.18.0

---

CHANGELOG.md
config.py

Bumps the version on config.py to the next minor: `5.19.0`.
Also snuck in an amendment to the changelog.
Minor release ✅

[config] bump to `5.19.0`

---

checks/check_status.py
config.py
dogstatsd.py
tests/core/fixtures/config/bad.conf
tests/core/fixtures/config/invalid.conf
tests/core/fixtures/config/multiple_apikeys.conf
tests/core/fixtures/config/multiple_endpoints.conf
tests/core/fixtures/config/multiple_endpoints_bad.conf
tests/core/fixtures/config/one_endpoint.conf
tests/core/test_config.py
tests/core/test_dogstatsd.py

Performs a sanity check before starting the agent to avoid collecting anything if the api key is obviously wrong.
Enhance the message on the status page when an api key is invalid
The agent might start collecting metrics but never flush if users paste a wrong api key

Avoid starting the agent if the api key is too short

---

checks/__init__.py
tests/core/test_common.py

Some device names can have the `@` symbol in them. This PR converts that symbol to a `_` using the standard normalize method.
Since some deice names can have this symbol, and we aren't currently sanitizing, it can cause undesired behaviour in the UI, since its not one of our supported tag chars. 
This is to go along with an integrations core PR for the disk check so that can use this updated normalize method.

[Core] Update the normalize to also convert @ symbol to _

---

utils/kubernetes/kubeutil.py

Per a customer request we are adding extra tags to the kubernetes events.
Those tags will help to investigate and better identify what created the events.
Deployed an agent on a pod, created a few events and checked that the tags were properly added to the events in Datadog.
Updated unit test in a sister PR:
https://github.com/DataDog/integrations-core/pull/810
```
rake ci:run[kubernetes]
[...]
Ran 29 tests in 5.061s
OK
```
Event example:
```
{u'count': 1, u'firstTimestamp': u'2017-10-16T11:23:53Z', u'lastTimestamp': u'2017-10-16T11:23:53Z', u'source': {u'host': u'minikube', u'component': u'kubelet'}, u'reason': u'Killing', u'involvedObject': {u'kind': u'Pod', u'name': u'nginx-4217019353-1fv4v', u'namespace': u'default', u'apiVersion': u'v1', u'fieldPath': u'spec.containers{nginx}', …
```

adding source components and object name tag to kubernetes events

---

agent.py
config.py
dogstatsd.py
tests/core/test_config.py
win32/service.py

Check to validate API key occurs before the agent updates the
config from the registry (if the API key is provided on the MSI install
command line).  This causes the agent to fail to run even when a valid
API key has been provided.
Allow the configuration to be processed without a valid api key (by introducing
an override parameter), so that the Windows service can start successfully.
The Windows service must start or (as currently configured) the installation will fail.
Introduced with https://github.com/DataDog/dd-agent/pull/3546

[Windows]  Fix startup option when API key provided to installer.

---

tests/core/test_kube_event_retriever.py
utils/kubernetes/kube_event_retriever.py

Event collection was based on the resversion of each event.
Per Kubernetes' doc:
`Clients should not assume that the resource version has meaning across namespaces, different kinds of resources, or different servers.`
This is just a modification of the evaluation.
Proactive correction to avoid issues in the future.
Modified the nosetest core test to comply with the new timestamp based collection.
```
nosetests tests/core/test_kube_event_retriever.py
......
----------------------------------------------------------------------
Ran 6 tests in 0.230s
OK
```
and
```
rake ci:run[kubernetes]
[...]
----------------------------------------------------------------------
Ran 29 tests in 5.144s
OK
```

[kubernetes] Filter kubernetes events on timestamp instead of resversion

---

checks/system/unix.py

On a centos 7.3 system with dd agent running in alpine-latest we get flooded with errors like 'Unable to get file_handles metrics'. After some debugging I found out that file.read only returns the first number of the file content from /proc/sys/fs/file-nr
The code then expects to have 3 numbers after calling split which fails. 
I don't know why read only returns the first number here (it should return the complete file content), maybe some magic or based on the fact that it's a pseudo file, but readline actually returns the correct line. read(256) does it too, but since the content is in one line readline makes more sense to …

Fix 'Unable to get file_handles metrics' in FileHandles handles unix check

---

datadog.conf.example

Comment out all Trace sections from the datadog.conf.example
There have been numerous cases where users are using a config management tool to append config options to the dd_conf_example file. However, this is going below the `[trace ignore]` section instead of the `[Main]` section so it wasn't working as expected.

Comment out all of Trace examples

---

config.py
win32/service.py

Checks datadog.conf. If `apm_enabled` is set to true, then it starts the trace agent service.  Trace agent service will be installed by parallel checkin

Enable the apm service based on the configuration file

---

tests/core/test_kubeutil.py
utils/kubernetes/kubeutil.py

Kubernetes 1.8 changed the generation of ReplicaSet names, they’re no longer digits only, and this broke the agent’s metric collection code, see https://github.com/kubernetes/kubernetes/pull/51538/files and https://github.com/DataDog/integrations-core/issues/837
Updated unit test cases to cover valid and invalid cases for this new format.

[kube] restore kube_deployment tag on k8s 1.8+ clusters

---

datadog.conf.example
tests/core/test_dockerutil.py
utils/dockerutil.py
utils/service_discovery/sd_docker_backend.py

Add docker labels as tags for auto discovery.
User request.
Added unit tests for it.

[AD] Add docker labels as tags in AD

---

CHANGELOG.md

Only the windows release is declared as released for now
[skip ci]

[changelog] 5.19.0

---

checks/collector.py
tests/core/test_dockerutil.py
tests/core/test_ecsutil.py
tests/core/test_mesosutil.py
tests/core/test_nomadutil.py
utils/dockerutil.py
utils/kubernetes/kubeutil.py
utils/orchestrator/baseutil.py
utils/orchestrator/dockerutilproxy.py
utils/orchestrator/ecsutil.py
utils/orchestrator/kubeutilproxy.py
utils/orchestrator/mesosutil.py
utils/orchestrator/metadata_collector.py
utils/orchestrator/nomadutil.py

Move all host tags coming from docker and orchestrators to host metadata with the exception of node labels in k8s because they're legit.
This metadata is not really useful as tags and it's mostly for analysis purpose. Therefore metadata is a better fit that tags - especially because host metadata doesn't churn contexts when updated.
This will require some work in the app to display it. Still figuring that out.

Switch most of container host tags to host metadata

---

checks/collector.py
config.py
datadog.conf.example

Sometimes customers want to disable gohai metadata collection, but it's currently not possible without removing the binary. It should be possible through a configuration option. This adds a config option, `disable_gohai`, which disables the collection of metadata by the gohai binary.

adds option to disable gohai metadata collection

---

tests/core/test_kubeutil.py
utils/kubernetes/kubeutil.py

Allows the default pod name to be set by an environment variable named `KUBERNETES_POD_NAME`.
Currently in Kubernetes, when a pod is created, its hostname is the Pod's `metadata.name` value. As a result, the Kubernetes check assumes that the pod's hostname is the same as the pod's name when locating pod metadata information.
But that's not necessarily always the case as the hostname can be set to any other value using a Pod annotation. If that's the case, the Kubernetes check is not able to locate pod _and_ node information as it expects the hostname to be the same as the pod name.
This is especially problematic when a pod uses host networking, where the pod's hostname is the same as the host's hostname.

[kubernetes] Allow overriding the pod name

---

packaging/datadog-agent/source/setup_agent.sh

This fixes the sed command that adds the log files paths to
`datadog.conf`. It was giving the error 
`sed: 1: "/^api_key/a\collector ...": extra characters after \ at the end of a command` on macOS. This is because sed expects a new line after the command `a`. It works on linux because there is a GNU extension that allows skipping the newline.
This fixes it and should keep working on the other distributions.
Encountered this while trying a source install on my mac.
Tested on macOS and on an ubuntu VM.

[source_install] Fix sed command in source install for macOS

---

utils/checkfiles.py

Agent6 will still support docker_images in AD templates but will
print a warning asking to move to the docker-agnostic ad_identifiers
field. integrations-core templates will be updated accordingly. This
ensures we can use the new default AD templates.
If both are present, the new name takes precedence, like in agent6.

add forward-compatibility to ad_identifiers superseeding docker_images

---

daemon.py
utils/windows_configuration.py

SCM protects against multiple instances running; causes more harm than good.
Change logging output for registry entries that aren't found.  Mostly,
they're not expected to be present and they create confusion

Remove check for pidfile on windows.

---

win32/gui.py

Changes gui implementation to deal with the fact that the datadog-agent service now may have dependent services.  Stop them all, and then restart (or just stop them all when stopping).

change restart to stop/start with deps

---

datadog.conf.example

Component: `trace-agent` configuration example
Updating the config example for ignored resource.

Fix `trace.ignore` configuration example

---

tests/core/test_kubeutil.py
utils/kubernetes/kubeutil.py

my bad, RS new names' lenght is not constant. Let's try to validate every suffix more than 2 runes long
See https://github.com/DataDog/integrations-core/issues/837#issuecomment-344911890

[kube] fix deployment tagging for 1.8+

---

utils/service_discovery/sd_docker_backend.py

auto conf should be enabled when there is **not** a config kv backend. Fix that.
fixing auto conf from labels and annotations.

fix auto-conf enabling condition

---

checks/libs/win/__init__.py
checks/libs/win/pdhbasecheck.py
checks/libs/win/winpdh.py

Updates the PDH library.  Provide a generic PDHBaseCheck to build PDH based system checks.

[Windows] Update pdh library to support generic pdh based checks

---

win32/gui.py

documented way to add the api key

[Windows] allow the gui to start w/o an API key.  Otherwise, there's no

---

packaging/datadog-agent/source/setup_agent.sh

Has the user enter an email address if they choose to send an install failure report to Datadog Support. 
Ensures Support can reach back out with any help on resolving their install issue. Will provide a smoother experience. 

[Source Support] Let the user enter email

---

packaging/datadog-agent/source/setup_agent.sh

- Bump source install agent version to `5.20.0`
- Fix win lib to pass flake8 test

Bump source install agent version

---

appveyor.yml

Avoid conflict when installing bundler
'--conservative' will prevent gem to upgrade bundler if it already meet version requirement.
Appveyor jobs would fail when install bundler due to a conflict with appveyor cache.

Avoid conflict when installing bundler

---

packaging/datadog-agent/source/setup_agent.sh

updated the default version to 5.20.1 in the source installer script
Released 5.20.1

[source] update default version to 5.20.1

---

datadog.conf.example

This commit switches the use of = to : in the tracing section of the
example configuration file. Just a cosmetic change for better
consistency.
I was reading the example config and noticed a style inconsistency between the sections. Decided to submit a PR just in case it bothered anyone else.
No code change. The configurations I'm currently using uses `:` everywhere.

[config] Use : instead of = in APM config

---

config.py
datadog.conf.example
ddagent.py

By default, the Tornado HTTP Client (either the simple client or the curl client) in the forwarder will use IPv6 if it is available. Sometimes users wish to force the agent to use IPv4. This PR adds a config option that allows users to force the forwarder's HTTP client to use IPv4.
This feature has been requested by several customers.
Test strategy:
On a network that support IPv6:
- Set the agent's log level to debug
- Verify that the forwarder is using IPv6 addresses
- Set `allow_ipv6: no` in the agent config
- Verify that the forwarder is using IPv4 addresses
- Set `use_curl_http_client: yes` in the agent config
- Repeat the previous tests
The curl client persists connections after each request, so I could see which IP version it was using with `lsof -i -a -p $(pgrep -f ddagent.py)` (it …

Adds an option to disable IPv6.

---

checks/prometheus_check.py
tests/core/test_prometheus.py

Only relevant in Agent >= 6, patch applied also here for consistency.

[PrometheusCheck] change name of method shadowing one in the base class in v6

---

config.py
datadog.conf.example
tests/core/test_ec2.py
utils/cloud_metadata.py

- Collects the OpenStack instance's `uuid` and `name` for `host_aliases` from `meta_data.json`
- Collects the OpenStack instance's `meta` key/value pairs as agent `tags` from `meta_data.json`
- Allows you to use the OpenStack instance's `uuid` instead of its `instance-id`
- We need the OpenStack instance's metadata tagging to work similar to the AWS EC2 tag collection.
- We want the `uuid` and `name` to appear in the "also known as" part of the UI.
- OpenStack nova recycles the `instance-id` so it isn't guaranteed to be unique where the `uuid` is. The `uuid` value is also what you use when calling the nova api.
Created a config option called `openstack_use_metadata_tags` (defaults to true) in case someone doesn't want those tags to be agent tags.

[core] Collect OpenStack metadata and tags

---

tests/core/test_service_discovery.py
utils/service_discovery/sd_docker_backend.py

Extract the tag `kube_container_name` in `sd_docker_backend` and `kubeutil`.
Also improves the coverage of these two packages.

Add kube container name in service discovery

---

checks/libs/win/pdhbasecheck.py
checks/libs/win/winpdh.py

so that failure to log into remote machine doesn't skip initialization

[Windows] [Pdh] Fix initialization of the metrics list

---

checks/system/unix.py

This change emits more file handler metrics that weren't previously available: num allocated, num allocated but unused, used (an alias for allocated - allocated and unused), and max num of file handles.
The "% of max file handlers used" metric introduced by https://github.com/DataDog/dd-agent/pull/3395 helps us detect changes in file handler usage, but sometimes I want to know the absolute values (ex: when comparing different hosts with different limits).
I verified this by running the agent on my host and seeing the new metrics in the Datadog web UI.

[filehandles] Include allocated, allocated but unused, used, and max filehandler metrics

---

datadog.conf.example

Move to colon notation and example as default value.
Make the example clean for the trace-agent aprt.
No-op change.

Unify doc example for trace section

---

tests/core/test_kubeutil.py
utils/kubernetes/kubeutil.py

Improve the way we are setting the nodeIP / nodeName in kubeutil.
If the agent doesn't run inside a kubernetes Pod, we cannot [get](https://github.com/DataDog/integrations-core/blob/bf7c8aa7dea0af631572f31e84c4fdabd80ccf15/kubernetes/check.py#L517) the hostname for the [events](https://github.com/DataDog/integrations-core/blob/bf7c8aa7dea0af631572f31e84c4fdabd80ccf15/kubernetes/check.py#L554).
All events will have **None** as `node_name` value.
All Pods inside the PodList are running on the same node/kubelet so in theory we could pick any of them and get the `spec.nodeName` for the `node_name` / hostname.
Sadly the static Pods don't have the associated `status.hostIP` so we need to manage that.

kubeutil: get nodeName and nodeIP even if the agent isn't inside a Pod

---

config.py
setup.py
setup_tk.py
tests/checks/common.py
utils/checkfiles.py

The goal of this PR is to allow running checks packages as pip wheels just like any other check. These checks would typically packaged as follows such that they will be installed to `./datadog/<integration>/` site in `site-packages`. 
It should remain completely backward compatible as far as previous functionality goes.
Improved packaging of checks, improved developer experience.

[wheels] allow running checks packaged as wheels

---

packaging/datadog-agent/source/install_agent.sh

Adds the ability to add host tags via the `curl | sh` installation script
Quickly deploy the datadog agent to public cloud instances via cloud-init while also being able to add host tags (e.g. to indicate what application the instance runs)
I exported the `DD_API_KEY` and `DD_HOST_TAGS` variables and ran the script on a host without the agent installed. The agent was properly installed and also had the host tags set appropriately.
I looked into adding capability to specify package version but it looked
pretty involved and I really just wanted host tagging.

Fixed #3550 - Add host tagging to install_agent.sh

---

checks/winwmi_check.py

Adds a condition in `_extract_metrics` to skip properties that haven't been included as part of the query in `wmi_check.yaml`. `SWbemServices.ExecQuery` is expected to [always return key properties of a WMI class](https://msdn.microsoft.com/en-us/library/aa393866(v=vs.85).aspx).
Returning the key properties can cause a `ValueError` in the [WMI check](https://github.com/DataDog/dd-agent/blob/f42cefe214192d2f58720ac774b5effc7021028c/checks/wmi_check.py#L200), logging a warning each time the check runs.
is available in our contribution …

[WINWMI check] Skip properties in WMI query results if not in arguments

---

aggregator.py
tests/core/test_aggregator.py

Ignore all dist metrics (i.e. metric types starting with 'd')
Avoid dropping packets, just ignore these metrics.
unit test + no noticeable impact on performance (used benchmark in `benchmark_aggregator`)

[aggregator] Ignore all dist metrics (metric type starting with 'd')

---

config.py

Avoids spamming logs with exceptions when checks aren't wheels.
We always try to load the checks as wheel-installed checks, but it's
not an error if the checks are installed differently, so avoid logging with
exception level.
Without this, we get this error in the logs for every check that's enabled, on agent startup:
```
2017-12-29 13:12:34 UTC | ERROR | dd.collector | config(config.py:872) | Unable to import check module process from site-packages
File "/opt/datadog-agent/agent/config.py", line 869, in _get_check_module
check_module = import_module("datadog_checks.{}".format(check_name))
File "/opt/datadog-agent/embedded/lib/python2.7/importlib/__init__.py", line 37, in import_module
__import__(name)
ImportError: No module named datadog_checks.process …
```

[wheel] Don't spam logs with exceptions when checks aren't wheels

---

checks/collector.py

When debugging some support case, having the metadata payload in the logs
can be very useful.

Log metadata payload as debug to be added to flares

---

checks/prometheus_check.py
tests/core/fixtures/prometheus/ksm.txt
tests/core/test_prometheus.py

This PR adds 2 generic mechanisms to the prometheus check:
- A `label_to_hostname` setting that allows a specified label to override hostname if present
- A `label_joins` setting that allows to join 1:1 labels 🏷 from one metric to another
Sometimes some metrics come from a different node and the node is usually specified in an associated label, hence the utility of the `label_to_hostname` setting.
For the `label_joins`: in prometheus it's common to have some placeholder metric holding all the labels because it's possible to do some label joins in the prometheus query language, that's why we need a mechanism to do joins some labels during processing, so the metric can be sent with all labels/tags wanted.

Generic label joins + node to hostname for the Prometheus Check

---

utils/checkfiles.py

Fixes issue with auto-discovery and wheels. More precisely, if a wheel-check was installed but the bundled check was missing (perfectly plausible scenario as soon as we release standalone wheel checks) the check validation would fail.
Issue discovered in 5.21.0 testing (does not affect 5.21.0, but would affect subsequent releases)

[wheels][auto-discovery] utils.checkfiles support for wheels

---

checks/libs/win/pdhbasecheck.py

Fixes an issue when pulling tags from a yaml config file with any integration that uses the `PDHBaseCheck` class
A customer reached out with a report of the IIS check, which now collects metric via PDH, failing after upgrading to 5.21

Fix issue with creating tags from conf in IIS

---

checks/prometheus_check.py

Just a minor documentation change so that we refer to the prometheus check here provided as the **_parent_** class instead of the _mother_ class - just for clarity (`base` and `parent` are more common).

[prometheus][skip ci] change comments to refer to parent class

---

checks/prometheus_check.py

Add SSL/TLS support for the prometheus check and closes #3639 
As reported in #3639 some prometheus endpoint (such as a secured etcd) could be behind https an the prometheus check need to support these
This was manually tested on a secure etcd cluster

[Prometheus Check] add SSL support

---

checks/system/unix.py

Adds collection of the total system memory for Mac OS X.
I was looking at my default host dashboard and noticed that the memory breakdown was completely negative since there is no `system.mem.total` metric being submitted - https://cl.ly/3F002J2x1Q0u

Collect total system memory for Mac OS X

---

tests/core/test_proxy.py
utils/proxy.py

This makes `requests` correctly ignore environment-declared proxies.
I encountered the bug

fix proxy skipping

---

checks/__init__.py

This allows one to set default proxies. If the uri doesn't match the env var `no_proxy` and the user hasn't enabled the config flag, you can now pass `proxies={}` to have `requests` preserve environment-declared proxies.
Customer uses `HTTP_PROXY`/`HTTPS_PROXY` https://github.com/DataDog/integrations-core/pull/1051

allow default proxies

---

datadog.conf.example
jmxfetch.py

This enables users to load a custom jar at jmxfetch start,
to allow using them reliably in AD templates
Only supporting a single string in agent5 to enable the use of
the DD_CONF_JMX_CUSTOM_JARS envvar binding, agent6 will support
a string array
`datadog/dev-dd-agent:backport_3648` allows to test it

add jmx_custom_jars option to datadog.yaml

---

aggregator.py
checks/__init__.py

De-duplicate tags before pushing to the backend. This avoid pushing hundred of tags if a check is buggy.

Deduplicate tags on metrics, events and service_checks for check and dogstatsd

---

win32/service.py

APM service.  APM service will be installed automatic start, and then it
will stop itself if not enabled.
Changes startup logic.  Main service will no longer start APM service; the APM service will be started automatically by the Service Control Manager
https://github.com/DataDog/dd-agent-omnibus/pull/217
Request to add process agent; make process agent and APM work the same
Should test that APM service stops itself when configured to be not running.

[Windows] The agent service is no longer responsible for starting the

---

packaging/datadog-agent/source/setup_agent.sh

Fixes bashism in source install script. Fixes #3656
Part of the changes in #3650 broke the alpine image build.
Our source install needs to be compatible with ~POSIX shell, so replace
bashisms.
I've double-checked this fixes the alpine image build.

[source install] Fix pushd/popd bashism

---

config.py

Bumps JMXFetch to 0.18.1
Released new version.
Sister omnibus PR: https://github.com/DataDog/omnibus-software/pull/170

[jmxfetch] bumping to 0.18.1

---

config.py

bundled `checks.d` is now a deprecated location as checks are shipped as wheels. 
Noticed we would bail out if path was non-existent while testing windows.

[config] wheel bundling deprecates checksd

---

config.py

Catch a wider array of errors that can occur when loading wheels based checks.
When trying to load a buggy check, this would crash the Agent with an `uncaught error`. This can occur for any issue in a custom check as well as our own packaged check, assuming they are wheels. 
The Agent shouldn't stop running due to one check's issue

[Core] Catch more general errors when loading wheels checks

---

packaging/datadog-agent/source/install_agent.sh

SUSE's protections make it so that you need to explicitly import the GPG key with `rpm --import...`

[install script] import the gpg key for suse explicitly

---

config.py
win32/service.py

service start.  They're installed as auto-start services, however, if
the user restarts the agent (especially via the gui) they won't be
restarted on their own.
Services aren't correctly started when reconfiguring.

[Windows] Start subservices (trace/process) if they're configured on

---

utils/dockerutil.py

Fix a crash if the image is not defined
```
"/opt/datadog-agent/agent/utils/dockerutil.py", line 587, in image_name_extractor return image.split('/')[-1] AttributeError: 'NoneType' object has no attribute 'split'
```

Fix split on NoneType

---

tests/core/test_dockerutil.py
utils/dockerutil.py

This PR update the list of the excluded pause containers.
See the PR of the [agent6](https://github.com/DataDog/datadog-agent/pull/1233) for more details.

pause-container: update the list of the pause containers

---

packaging/datadog-agent/source/setup_agent.sh

Python 2.6 support was dropped some time ago. This removes it from the error message.

remove python 2.6 from the error message of source install

---

tests/core/test_dockerutil.py
utils/dockerutil.py

Extend the support of the pause container regex.
This will catch regional pause containers like:
`asia.gcr.io/google_containers/pause-amd64:3.0`

pause-container: extend the regex to catch region based.

---

CHANGELOG.md
utils/dockerutil.py

Logs an INFO message instead of an ERROR when the host is deemed as Dockerless. 
Basically, if there was no docker_daemon.yaml file detected, assume that a running Docker instance will use a default socket file /var/run/docker.sock. If both the yaml file and the socket file do not exist, then the host is Dockerless; raise an INFO instead of an ERROR so as not to alarm customers.
A question often asked by (new) support engineers and customers.

[dockerutil] logs info if Dockerless

---

tests/core/test_kubeutil.py
utils/kubernetes/kubeutil.py

The previous code was looking the pod's creator in the annotations, while [kubernetes/kubernetes#54445](https://github.com/kubernetes/kubernetes/pull/54445) removed the pod annotation that the agent code is looking for, from version 1.9.
It now uses the stabilized metadata.ownerReferences field instead, and falls back on the annotations if they are missing.
This issue came up in https://github.com/DataDog/dd-agent/issues/3642 
Changed tests relatively to the new way to get ownerreferences
- Tested on GKE cluster with k8 1.9.2
- Tested on minikube with k8 1.7.3

[kubernetes] fix logic to collect ownerreference for k8 1.9

---

packaging/datadog-agent/source/setup_agent.sh

This is needed to build the dogstatsd docker image and can always be
useful when only the base agent is needed.

Adding an option to skip installing integrations

---

tox.ini

Bumped flake8 version to 3.5.0 because of `integrations-core`, requirements have to be in sync but we now need more exceptions for the test to pass.

Add more exceptions to flake8

---

datadog.conf.example

Update `datadog.conf.example` to exhaustively document the supported configuration options for the trace-agent.
The config example was outdated, not suggesting the the user the right options.
No-op change.

Clean trace-agent ini config options

---

CHANGELOG.md
README.md

Adds a mention to A6 release notes in the Changelog and link to prepackaged binaries for A5 and A6 in the README
Keeps docs up to date with A6 release

Update Agent 5 github docs to mention A6

---

tests/core/test_dockerutil.py
utils/dockerutil.py

Fixes the parsing of swarm images such as `datadog/docker-dd-agent:latest@sha256:769418c18c3e9e0b6ab2c18147c3599d6e27f40fb3dee56418bf897147ff84d0` when gathering tags in dockerutil. The issue here was with the `@sha256`
A user was missing his tags on his hosts.
Added a test case
Similar to the [maching agent 6 code](https://github.com/DataDog/datadog-agent/blob/c0d3dc9bdd3ce0dbc379c01b010487e927464095/pkg/util/docker/util_common.go#L90-L93)

Add case for swarm image name with @sha256

---

packaging/datadog-agent/source/install_agent.sh

Stop installing old APT key in installation script. It's been fully replaced by the new key (that the script already installs)

[install_agent] Remove old APT key

---

checks/__init__.py

No need to re-call `set()` on the list and build a new one. We already sort and construct the set for the tag list in the aggregator. This code is called from there, passing forth a tag list that has already been sanitized. This is a redundant call/allocation.
While debugging testing issues found in `integrations-core` as collateral from https://github.com/DataDog/dd-agent/pull/3641 - the unneeded call was identified.

[formtter] tag list already sorted, set

---

checks/libs/win/pdhbasecheck.py
checks/libs/win/winpdh.py
checks/libs/win/winpdh_stub.py

loses fidelity, especially with values between 0 and 1.
change default pdh counter precision to float from int.
Allows configuration to set specific counter types
customer request

[windows] change default datatype for pdh queries to double. Integer

---

packaging/osx/install.sh

It's v5.11.3 and will remain at that version. The latest URL points
to Agent 6 now.

[macos][install script] Update URL of latest Agent 5

---

checks/collector.py

Removes API key if included as part of the `processes` field in the metadata payload when log level is set to `DEBUG`
Noticed an API key, as part of the processes field, could be sent if `DEBUG` mode is enabled

Remove API key if included in processes metadata payload

---

README.md

Makes more clear that the reference repo for the Agent development should be https://github.com/DataDog/datadog-agent
Avoid confusion, see https://github.com/DataDog/datadog-agent/issues/1405

Slim down the README and redirect to datadog-agent

---

packaging/datadog-agent/source/setup_agent.sh

The migration to wheels added hashes in the integrations `requirements.txt`s. The source install was not made to handle theses hashes. As a quick fix, this PR uses `requirements.in` instead.
This also allows wheel installations to fail.
Install from source was broken.

Fix source install

---

utils/subprocess_output.py

Small refactor to add a `subprocess_output` method that can be imported and called by `datadog_checks_base`.
Needed to fix https://github.com/DataDog/integrations-core/pull/1397, but doesn't break things for checks that still import and use `utils.subprocess_output.get_subprocess_output` directly.
Had to remove a debug log entry, since we don't have access to `log` anymore from the new method.

[subprocess_output] Add compatibility layer with datadog_checks_base

---

checks/system/unix.py

There is bug in iostat where the values for %util will sometimes be excessively greater than 100%. We will log the invalid metric value and report to value as 0. 
[Here](https://bugzilla.redhat.com/show_bug.cgi?id=445676) is the redhat won't fix bug report

Cap `system.io.util` to 100%

---

packaging/datadog-agent/source/setup_agent.sh

* Fixes the source install script to handle this change in `integrations-core` `5.24.0`: https://github.com/DataDog/integrations-core/pull/1384 (renaming of base check package)
* (nice-to-have) fix a couple of bashisms
Fix source install for 5.24.0.
Manually ran builds of the alpine image build with these changes (for both 5.23.0 and 5.24.0 agent/integrations-core tags)

Fix source install for integrations base pkg name change

---

jmxfetch.py

TL;DR Linux uses a colon (:) and Windows a semicolon (;). os.pathsep knows
this.
When using the jmx agent on Windows in combination with a custom_jar_paths and or tools_jar_path the agent will fail because the classpath seperator is a colon. On Windows a path seperator has to be a semicolon. The python function os.pathsep return the correct seperator.

Make the classpath seperator in jmxfetch adjust to the os

---

checks/system/unix.py
tests/checks/mock/test_sysstat.py

Fixes https://github.com/DataDog/dd-agent/issues/3731 , i.e. fixes core `IO` check on newer versions of `iostat`.
In the process of fixing this issue, I found tests for this part of the code that had been wrongly removed in https://github.com/DataDog/dd-agent/pull/3114 (migration of checks to `integrations-core`). So I've:
1. brought these tests back
2. by running them, found a bug introduced in this recent PR: https://github.com/DataDog/dd-agent/pull/3727, and fixed that bug.
We have tests again :)
And I've added a test case for the newer iostat output format.
See individual commit descriptions for the full story 📖 
cc @ChristineTChen: could you add more tests on the code you added in https://github.com/DataDog/dd-agent/pull/3727? I've only changed the minimum amount of code to fix 
the …

[IO] Fix on newer versions of iostat + tests + misc fix

---

tests/core/test_dockerutil.py
utils/dockerutil.py
utils/orchestrator/dockerutilproxy.py

This adds a host tag to docker swarm nodes containing the node role (manager or worker). 
To determine if the node is a manager/worker this checks the `ControlAvailable` flag in the response from `docker info` the same it is done by the [docker cli](https://github.com/docker/cli/blob/c889ea1bca95f78d10e9e8f7869d5cfd755850eb/cli/command/system/info.go#L259).

[docker] Add host tag for docker swarm node role.

---

tests/checks/mock/test_sysstat.py

The test_sysstat.py file was wrongly removed during migrating checks to integrations-core. This PR adds tests for capped io `%util` metric on linux, sunos5, and freebsd platforms.

[unix] add tests for capped iostat util logic

---

requirements.txt

See title
`pip install -r requirements.txt` is currently broken, see https://ci.appveyor.com/project/Datadog/integrations-core/build/master.5840
`python-etcd` lists urllib requirement as `urllib3>=1.7.1` which clashes with the one from `requests==2.18.4` that is `urllib3<1.23,>=1.21.1`

Explicilty pin urllib to avoid python-etcd to pull latest

---

config.py

file)
Sets the default state for APM to be enabled if not set in the config file
Make behavior consistent between agent5 and agent6
Windows agent uses this value to determine whether to start the apm service on main service startup (the service will not be started automatically by the service control manager).

Sets apm enabled by default (if there's no indication in the config

---

CHANGELOG.md
config.py
packaging/datadog-agent/source/setup_agent.sh

- updates the `master` to 5.26.0 (nightly releases)
- source install: pull 5.25.0
5.25.0 has been released.

5.25.0 release - final touches

---

CHANGELOG.md

Adding a note to the version 5.25 of the agent explaining that we changed the embedded python interpreter to USC4.
Some clients updated to the last version and their custom integration were broken.
[Agent 5.25](https://cl.ly/2G3o293Z0d2v)
[Agent 5.24](https://cl.ly/301l3X2t2U3Q)
Just an update on the changelog, no test has been performed.

Adding unicode interpreter UCS4 note

---

config.py

Bumping JMXFetch to 0.20.1 after agent release.
New JMXFetch version available.

[config] bumping jmxfetch to 0.20.1

---

packaging/datadog-agent/source/setup_agent.sh

Bumps the source install to 5.25.1
5.25.1 release

[source_install] bump to 5.25.1

---

checks/check_status.py
util.py
utils/jmx.py

PyYAML 'load()' method could execute arbitrary code. We now use
'safe_load' everywhere to avoid it.
Vuln: CVE-2017-18342

Use "safe_load" instead of "load" from PyYaml

---

packaging/datadog-agent/source/setup_agent.sh

Fixes the paths of each integrations' data files when installing from source.
To make integrations work.
An overview on [testing](https://github.com/DataDog/dd-agent/blob/master/tests/README.md) is available in our contribution guidelines.

Fix copying integrations' data files for source install

---

packaging/datadog-agent/source/setup_agent.sh

Updates Agent version in source install. This version is propagated to `INTEGRATIONS_VERSION`.
To fix the source install.

Update default agent version in source install

---

checks/collector.py

This reverts commit 78e9ad46749b319fa4aff57bea0b232136ef0e6d,
which introduced a significant file descriptor leak when dogstreams is enabled.

Revert "Fixes issue #3700"

---

CHANGELOG.md

Updates the changelog
Incomplete changelog for `5.27.0` and `5.27.1`. Add known issues regarding the #3701 file descriptor leak.

[changelog] update with dogstreams PRs + add known issues

---

requirements.txt
tests/core/test_timeout.py
utils/timeout.py

Fix import of `_thread_by_func` from base check utils. It is only used in this test, so this should be safe.
Failed build

Fix import of _thread_by_func and pin urllib3==1.23

---

checks/datadog.py
datadog.conf.example

Declares `dogstreams` deprecated.
Dogstreams is deprecated (see docs page: https://docs.datadoghq.com/agent/faq/dogstream/)
Manually enabled dogstreams, the warning is logged, and only once.
🔥 🔥 🔥
(also, added mention that Ganglia integration is deprecated in the example conf, it's been deprecated for **4 years**)

[dogstreams] Declare the feature deprecated

---

config.py
requirements.txt

amazon linux is not reported corrrectly with the builtin `platform` module. We use the `distro` module which is the recommended replacement since `platform.dist` and `platform.linux_distribution` are deprecated and will be removed in python 3.8: https://docs.python.org/3.7/library/platform.html#platform.linux_distribution.
We change `amzn` to `amazon` to match what `gopsutil` reports in agent 6: https://github.com/shirou/gopsutil/blob/0f70a4a06f7a1039305ec9b3ba9c2800f8929fba/host/host_linux.go#L403.

Report amazon linux in metadata using the distro module

---

checks/system/win32.py

to pdh based counter
Get data from windows performance counters; begin moving all of the system checks to windows performance counters; match agent6 implementation

[windows] change calculation of % interrupt time from NT kernel function

---

tests/core/test_common.py

We only need that the expected_proxies are among the environ_proxies so a set inclusion is enough
travis uses the TRAVIS_APT_PROXY variable breaking the test with assertEqual.

Fix test_no_proxy

---

Rakefile
config.py
packaging/datadog-agent/source/setup_agent.sh

Updates JMXFetch to 0.23.0 on dd-agent
New JMXFetch release.
Why didn't we ever upgrade to `0.22.0`? Oversight?
Sister PR: https://github.com/DataDog/omnibus-software/pull/275

[config] bumping jmxfetch to 0.23.0

---

requirements.txt
tests/core/test_proxy.py

Bump requests version to 2.20.1
related PR: https://github.com/DataDog/omnibus-software/pull/276

Bump requests version to 2.20.1

---

checks/__init__.py
config.py
datadog.conf.example

Fix status page cleaning up warning message after the first run
This also add a feature flag to disable the linter feature if needed.
New status page is now much less verbose when checks have multiple instances. We also only log Python3 error once for all instance.
```
Checks
======
test (custom)
-------------
- instance #0 [WARNING]
Warning: check is not compatible with Python3 (see log for more information)
- instance #1 [WARNING]
Warning: check is not compatible with Python3 (see log for more information)
- instance #2 [WARNING]
Warning: check is not compatible with Python3 (see log for more information)
- instance #3 [WARNING]
Warning: check is not compatible with Python3 (see log for more information)
- instance #4 [WARNING]
Warning: check is not compatible with Python3 (see log for …
```

Fix status page cleaning up warning message after the first run

---

requirements.txt

Fix building alpine docker image

Pin pylint to last python2-compatible version

---

requirements.txt

Bump datadog-a7 to the latest version

Bump datadog-a7 to the latest version

---

config.py

This allows us to execute the linter on windows no matter the install path of the agent

Directly import A7 instead of executing the binary

---

checks/system/win32.py

Fixes regression caused in previous release; conversion of computation of `% Interrupt time`to using windows performance counter wasn't done correctly
regression; customer feedback
Install on windows; verify metric `system.cpu.interrupt`

[windows] fix core cpu check; didn't specify counter instance name

---

.rubocop.yml
agent.py
checks/__init__.py
config.py
jmxfetch.py
tests/core/test_utils_yaml.py
util.py
utils/ddyaml.py
utils/jmx.py
win32/gui.py

Given the state of `pyyaml` package and the [CVE-2017-18342](https://nvd.nist.gov/vuln/detail/CVE-2017-18342) (which does not affect us), let's just make things a little safer for users who may be using `pyyaml` in their custom checks. This PR monkey patches unsafe operations, and points to the safe counterparts.
Make custom checks safer if they use `pyyaml`.
We should make this very clear in the changelog.

[pyyaml] allow patching of unsafe pyyaml operations

---

checks/collector.py

Add bug fix version to the `datadog.agent.check_ready` metrics

Add bug fix version to the datadog.agent.check_ready metrics

---

config.py
datadog.conf.example
jmxfetch.py

Bumps JMXFetch to version 0.26.0. Adding support for new JMXFetch options in the agent configuration.
New JMXFetch release and new options supported.

[jmxfetch] 0.26.0 released

---

requirements-opt.txt

Upgrades psutil to 5.5.0.
Reflects https://github.com/DataDog/omnibus-software/pull/291
Keep source install deps in sync with Agent
Will have to be QA'ed well on Windows, since we use `psutil` in the windows system checks of Agent 5.

[psutil] Upgrade to 5.5.0

---

packaging/datadog-agent/source/setup_agent.sh

Fixes the source install. After a new release of `isort` (pulled in by pylint) an issue with the dependency resolution of the old pip we used to use was uncovered with transitive dependencies. This PR bumps the pip version to a more current release.
On a different note, it's debatable the `pylint` dependency belongs in the `requirements`, but let's address the root cause here - the outdated pip.
Broken alpine build, source installs.
Change fixes the source install.

[alpine] fix source install dep resolution: bump pip

---

config.py
packaging/datadog-agent/source/setup_agent.sh

Bumps the default config version: 5.33.0
Updates the source install to the latest stable: 5.32.0
`5.32.0` release.

[config][source_install] bump respective versions after 5.32.0 

---

CHANGELOG.md

Adds the trace agent changes to the changelog 😊
The trace-agent is now co-located with Agent6 code in the same repository, so we can no longer use the old reference, and a diff of the `datadog-agent` repo would be confusing and misleading.

[changelog] update 6.10.0 entry with trace info

---

requirements-opt.txt
requirements.txt

Reverts DataDog/dd-agent#3829, since the `master` branch of `dd-agent` now needs to be in-sync with the `agent-v5` branch of integrations-core, which doesn't include (and doesn't need) these changes.

Revert "Upgrade requests & protobuf"

---

requirements.txt

Upgrades urlllib3 to 1.24.2
Not reflected on `omnibus-software` since urllib3 is not pinned there (which is not great btw). I checked urllib3 is already upgraded to 1.24.2 in the latest Agent 5 nightly build.

[urllib3] Upgrade to 1.24.2

---

Gemfile
requirements.txt

Bumps PyYaml to the latest 5.1.
Enable new `full_load()` option for customers perhaps wanting to use that after `load_all()` was patched for security reasons.

[requirements] bumping pyyaml to 5.1

---

CHANGELOG.md

Mentions that 5.32.3 is not released yet so that there's no misunderstanding. We'll have to change this to the actual release date when we do release :)

[changelog] Mention that 5.32.3 is not released yet

---

packaging/datadog-agent/source/install_agent.sh

Adds `/etc/os-release` to the files scanned to determine the distribution.
On SLES 15, the distribution info is located in `/etc/os-release`, which isn't scanned by the Agent 5 script (contrary to the Agent 6 script).

[packaging] Fix install script on SUSE 15

---

checks/collector.py
config.py

Makes the Agent call pylint directly in a subprocess instead of using a7.
Checked this worked on local dev env and custom check.
This will have to be QA'ed on Windows as well.
Also renamed the constants since they're actually related to python 3.
Requires https://github.com/DataDog/dd-agent-omnibus/pull/383

Call pylint directly instead of using a7

---

requirements.txt

Follow-up to https://github.com/DataDog/dd-agent/pull/3856
The Agent calls pylint directly now. No need for a7, and we don't include it in packaged agents anymore.

Remove a7 from requirements.txt

---

requirements.txt

Fixes the alpine/source build by pinning `lazy-object-proxy`. Newer versions of the python package result in a broken alpine build.
Broken alpine builds.
To be consistent, let's pin it across the board. Omnibus PR here: https://github.com/DataDog/dd-agent-omnibus/pull/385

[requirements] pin lazy-object-proxy for successful alpine build

---

CHANGELOG.md
packaging/datadog-agent/source/setup_agent.sh

Just sets the release date for 5.32.6 and updates the source install default tag.
5.32.6 release.

changelog: set release date + bump source install default tag

---

requirements-opt.txt
requirements.txt

Updates a couple deps.
Deps must be updated to address outdated/removed deps.
(none)

[requirements] bumps psutil to 5.6.7 and ntplib to 0.3.4

---

config.py

Bumps JMXFetch to version 0.26.4.
Just a new bugfix release for JMXFetch that requires being updated here.
(none)

[config] bumping JMXFetch version to 0.26.4

---

config.py

Bumps the config version to 5.32.7
New release.
Will just ship cert changes.

[config] bumping to 5.32.7

---

packaging/datadog-agent/source/setup_agent.sh

Bumping source install to 5.32.7
`5.32.7` release.
Nope.

[source] bumping to 5.32.7

---

agent.py

The `allow_profiling` configuration field isn't properly converted to a boolean (and is then a string), + is default value is True when not set. 
It means that when tested again the `developer_mode` boolean, only the `developer_mode` value matters because `allow_profiling` is always True either because it is a non-empty string, or because it has the default value `True`. The only way of setting it to false is to set it to an empty string in the configuration (`allow_profiling: ""`).
In other words:
```
allow_profiling = 'false'
developer_mode = True
if allow_profiling and developer_mode
→ this returns True
allow_profiling = 'false'
developer_mode = False
if allow_profiling and developer_mode
→ this returns False
```
It is only an issue when the `developer_mode` is enabled.

[agent] do not always start the Agent profile dumps when the developer_mode is enabled.

---

config.py

Bumps the agent version to `5.32.8` as we prepeare that release + bumps JMXFetch to the latest A5-version. 
related PR: https://github.com/DataDog/omnibus-software/pull/368
Release prep.

[config] setting the right agent and jmxfetch versions

---

config.py

Bumps JMXFetch version to 0.26.6 - latest.
Need to add back support for Java7 that was lost with newer log4j2 releases.
None

[config] bumping jmxfetch to latest 0.26.6 version 

---

config.py

Bumps JMXFetch
Re-introduce Java6 compatibility.

[config] bumping jmxfetch to latest relase

---

config.py

Bumps the expected JMXFetch version to 0.26.8.
JMXFetch 0.26.7 had a Java 1.6 incompatibility, that was since fixed in 0.26.8.

[config] bump jmxfetch to java1.6 compatible 0.26.8

---

packaging/datadog-agent/source/setup_agent.sh

This PR fixes the URL used to download get-pip.py, that points to a now incompatible script with Python 2.7.
Installing datadog-agent from source was broken with the following error:
```
File "/home/pi/.datadog-agent/get-pip.py", line 24226, in <module>
main()
File "/home/pi/.datadog-agent/get-pip.py", line 199, in main
bootstrap(tmpdir=tmpdir)
File "/home/pi/.datadog-agent/get-pip.py", line 82, in bootstrap
from pip._internal.cli.main import main as pip_entry_point
File "/tmp/tmpJ2mYwm/pip.zip/pip/_internal/cli/main.py", line 60
sys.stderr.write(f"ERROR: {exc}")
SyntaxError: invalid syntax
```

Change get-pip.py URL to 2.7

---

packaging/datadog-agent/source/setup_agent.sh

Updates the link to install pip from https://bootstrap.pypa.io/2.7/get-pip.py to https://bootstrap.pypa.io/pip/2.7/get-pip.py. 
When installing from source using the setup_agent.sh script:
`DD_API_KEY=<YOUR-API-KEY> sh -c "$(curl -L https://raw.githubusercontent.com/DataDog/dd-agent/master/packaging/datadog-agent/source/setup_agent.sh)"`
The script contains a link to install pip: https://bootstrap.pypa.io/2.7/get-pip.py
This causes the install script to fail as it links to a page with the following message:
> The URL you are using to fetch this script has changed, and this one will no
> longer work. Please use get-pip.py from the following URL instead:
> 
>     https://bootstrap.pypa.io/pip/2.7/get-pip.py
> 
> Sorry if this change causes any inconvenience for you!

[core] update deprecated pip install url

---

.circleci/config.yml
Rakefile

Old code was fetching and using the latest pip which no longer supports
Python2. This change ensures that we only use Python v2-compatible
version for our CI/CD. while this doesn't fix all the issues with the pipeline,
it fixes the problems with pip and gets most of the CircleCI builds passing
CI/CD failures

[build] Ensure pip version is Python2 compatible

---

packaging/datadog-agent/source/install_agent.sh

On Ubuntu/Debian systems, there is an `_apt` user which reads the APT keyrings to verify signatures. Our APT keyrings are owned by root and so if they're not world-readable, the `_apt` user fails to read them and thus can't verify the signatures.

[install_agent] Fix APT keyring permissions

---

packaging/datadog-agent/source/install_agent.sh

Adds datadog-signing-keys package to be installed along with the agent in the `install_agent.sh` script.

 [install_agent] Install datadog-signing-keys package along with the agent

---

packaging/datadog-agent/source/install_agent.sh

This PR is quite simple, it simply aims to allow making the pkg_list configurable. This might be required for some testing repositories. 
Failed `dd-agent` QA pipeline due to missing artifact.

[install-script] make pkg_list optional for testing purposes

---

tests/core/test_watchdog.py

There is a small typo in tests/core/test_watchdog.py.
Should read `suspiciously` rather than `suspicously`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md

docs: fix simple typo, suspicously -> suspiciously

---

packaging/datadog-agent/source/install_agent.sh

Add the next APT future GPG key.
Note: we don't need to add the next RPM future GPG key because we aren't signing RPM repodata

add the next future APT key following 2024 gpg key rotation

---

packaging/datadog-agent/source/install_agent.sh

Reverts DataDog/dd-agent#3936
#incident-28254
The "" in this line https://github.com/DataDog/dd-agent/blob/fb2dbb70b42cc70962cc2e7c5e8ba3570dbd4669/packaging/datadog-agent/source/install_agent.sh#L99 is what’s causing https://github.com/DataDog/dd-agent/blob/fb2dbb70b42cc70962cc2e7c5e8ba3570dbd4669/packaging/datadog-agent/source/install_agent.sh#L206 to fail (since key is empty, it tries to overwrite a folder when writing curl

Revert "add the next future APT key following 2024 gpg key rotation"

---

packaging/datadog-agent/source/install_agent.sh

Revert "Revert "add the next future APT key following 2024 gpg key rotation"" and fix breaking typo

Revert "Revert "add the next future APT key following 2024 gpg key rotation"" and fix typo
